BEGIN;

-- ============================================
-- ACTUALIZAR IMPRESORAS CON DATOS REALES
-- ============================================

-- Eliminar impresoras de ejemplo si existen
DELETE FROM public.impresoras WHERE nombre IN ('Impresora 1', 'Impresora 2', 'Impresora 3');

-- Insertar las impresoras reales
INSERT INTO public.impresoras (nombre, modelo, estado, capacidad_maxima_horas_dia, activa)
VALUES
  ('Mimaki 130', 'Plotter de Corte', 'Disponible', 24.00, true),
  ('JV100-160', 'OARA Impresión', 'Disponible', 24.00, true),
  ('Charger 320', 'Impresión de Gran Formato', 'Disponible', 24.00, true),
  ('UVR180', 'Impresora UV Híbrida de Gran Formato', 'Disponible', 24.00, true),
  ('Inkami 3200', 'Impresión', 'Disponible', 24.00, true)
ON CONFLICT (nombre) DO UPDATE SET
  modelo = EXCLUDED.modelo,
  estado = EXCLUDED.estado,
  capacidad_maxima_horas_dia = EXCLUDED.capacidad_maxima_horas_dia,
  activa = EXCLUDED.activa,
  updated_at = now();

-- ============================================
-- CREAR TABLA DE HISTORIAL DE CAMBIOS DE ESTADO
-- ============================================

CREATE TABLE IF NOT EXISTS public.impresora_historial_estado (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_impresora integer NOT NULL REFERENCES public.impresoras(id) ON DELETE CASCADE,
  estado_anterior varchar(50),
  estado_nuevo varchar(50) NOT NULL,
  motivo text,
  usuario_id integer,
  usuario_nombre varchar(100),
  created_at timestamptz DEFAULT now()
);

-- Índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_impresora_historial_impresora ON public.impresora_historial_estado(id_impresora);
CREATE INDEX IF NOT EXISTS idx_impresora_historial_fecha ON public.impresora_historial_estado(created_at DESC);

-- ============================================
-- FUNCIÓN PARA REGISTRAR CAMBIOS DE ESTADO AUTOMÁTICAMENTE
-- ============================================

CREATE OR REPLACE FUNCTION public.registrar_cambio_estado_impresora()
RETURNS TRIGGER AS $$
BEGIN
  -- Solo registrar si el estado cambió
  IF OLD.estado IS DISTINCT FROM NEW.estado THEN
    INSERT INTO public.impresora_historial_estado (
      id_impresora,
      estado_anterior,
      estado_nuevo,
      motivo,
      usuario_id,
      usuario_nombre
    ) VALUES (
      NEW.id,
      OLD.estado,
      NEW.estado,
      NULL, -- Se puede agregar desde la aplicación
      NULL, -- Se puede obtener desde el contexto de autenticación
      NULL  -- Se puede obtener desde el contexto de autenticación
    );
  END IF;
  
  -- Actualizar updated_at
  NEW.updated_at = now();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear trigger para registrar cambios automáticamente
DROP TRIGGER IF EXISTS trigger_registrar_cambio_estado_impresora ON public.impresoras;

CREATE TRIGGER trigger_registrar_cambio_estado_impresora
AFTER UPDATE OF estado ON public.impresoras
FOR EACH ROW
EXECUTE FUNCTION public.registrar_cambio_estado_impresora();

-- ============================================
-- VISTA PARA TRABAJOS ACTIVOS POR IMPRESORA
-- ============================================

CREATE OR REPLACE VIEW public.v_impresora_trabajos_activos AS
SELECT 
  iu.id as uso_id,
  iu.id_impresora,
  iu.id_orden,
  iu.fecha_inicio,
  iu.fecha_fin,
  iu.horas_usadas,
  iu.estado as estado_uso,
  iu.operario,
  iu.created_at,
  i.nombre as nombre_impresora,
  i.modelo as modelo_impresora,
  i.estado as estado_impresora,
  ot.numero_op,
  ot.cliente,
  ot.descripcion,
  ot.sector,
  ot.estado as estado_orden
FROM public.impresora_uso iu
INNER JOIN public.impresoras i ON iu.id_impresora = i.id
LEFT JOIN public.ordenes_trabajo ot ON iu.id_orden = ot.id
WHERE iu.estado = 'En Proceso'
ORDER BY iu.fecha_inicio DESC;

-- ============================================
-- PERMISOS
-- ============================================

-- Permisos de lectura para todos los usuarios autenticados
GRANT SELECT ON public.impresoras TO anon, authenticated;
GRANT SELECT ON public.impresora_uso TO anon, authenticated;
GRANT SELECT ON public.v_impresoras_ocupacion TO anon, authenticated;
GRANT SELECT ON public.impresora_historial_estado TO anon, authenticated;
GRANT SELECT ON public.v_impresora_trabajos_activos TO anon, authenticated;

-- Permisos de escritura solo para usuarios autenticados (se controlará por rol en la aplicación)
GRANT INSERT, UPDATE ON public.impresora_uso TO authenticated;
GRANT INSERT, UPDATE ON public.impresoras TO authenticated;
GRANT INSERT ON public.impresora_historial_estado TO authenticated;

-- Nota: El control de acceso por rol (taller-grafico) se manejará en la aplicación frontend
-- ya que Supabase Auth no tiene roles personalizados integrados directamente en RLS

COMMIT;

