-- Script completo para implementar sistema de etapas de Taller de Imprenta
-- Ejecutar este archivo completo en Supabase SQL Editor

BEGIN;

-- ============================================
-- 1. Agregar campo etapa_taller_imprenta
-- ============================================
ALTER TABLE public.ordenes_trabajo
ADD COLUMN IF NOT EXISTS etapa_taller_imprenta varchar(100);

CREATE INDEX IF NOT EXISTS idx_ordenes_etapa_taller_imprenta 
ON public.ordenes_trabajo(etapa_taller_imprenta);

-- ============================================
-- 2. Crear tabla de historial
-- ============================================
CREATE TABLE IF NOT EXISTS public.historial_etapas_taller_imprenta (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  etapa_anterior varchar(100),
  etapa_nueva varchar(100) NOT NULL,
  id_usuario integer REFERENCES public.usuarios(id),
  nombre_usuario varchar(255),
  comentario text,
  fecha_cambio timestamptz NOT NULL DEFAULT now(),
  fecha_inicio_etapa timestamptz NOT NULL DEFAULT now(),
  fecha_fin_etapa timestamptz,
  tiempo_en_etapa_seg integer
);

CREATE INDEX IF NOT EXISTS idx_historial_etapas_taller_imprenta_orden 
ON public.historial_etapas_taller_imprenta(id_orden);

CREATE INDEX IF NOT EXISTS idx_historial_etapas_taller_imprenta_fecha 
ON public.historial_etapas_taller_imprenta(fecha_cambio DESC);

CREATE INDEX IF NOT EXISTS idx_historial_etapas_taller_imprenta_etapa 
ON public.historial_etapas_taller_imprenta(etapa_nueva);

ALTER TABLE public.ordenes_trabajo
ADD COLUMN IF NOT EXISTS etapa_taller_imprenta_fecha_inicio timestamptz;

-- ============================================
-- 3. Función para obtener historial
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_historial_etapas_taller_imprenta(p_id_orden integer)
RETURNS TABLE (
  id bigint,
  etapa_anterior varchar,
  etapa_nueva varchar,
  nombre_usuario varchar,
  comentario text,
  fecha_cambio timestamptz,
  fecha_inicio_etapa timestamptz,
  fecha_fin_etapa timestamptz,
  tiempo_en_etapa_seg integer,
  tiempo_formateado text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    h.id,
    h.etapa_anterior,
    h.etapa_nueva,
    h.nombre_usuario,
    h.comentario,
    h.fecha_cambio,
    h.fecha_inicio_etapa,
    h.fecha_fin_etapa,
    h.tiempo_en_etapa_seg,
    CASE 
      WHEN h.tiempo_en_etapa_seg IS NULL THEN 'En curso'
      WHEN h.tiempo_en_etapa_seg < 60 THEN h.tiempo_en_etapa_seg::text || ' seg'
      WHEN h.tiempo_en_etapa_seg < 3600 THEN (h.tiempo_en_etapa_seg / 60)::text || ' min'
      ELSE (h.tiempo_en_etapa_seg / 3600)::text || ' horas'
    END as tiempo_formateado
  FROM public.historial_etapas_taller_imprenta h
  WHERE h.id_orden = p_id_orden
  ORDER BY h.fecha_cambio DESC;
END;
$$;

-- ============================================
-- 4. Función RPC para actualizar etapa
-- ============================================
CREATE OR REPLACE FUNCTION public.actualizar_etapa_taller_imprenta(
  p_id_orden integer,
  p_nueva_etapa varchar(100),
  p_nombre_usuario varchar(255)
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  etapa_anterior_val varchar(100);
  fecha_inicio_anterior timestamptz;
  tiempo_segundos integer;
  usuario_actual_id integer;
BEGIN
  -- Obtener etapa anterior
  SELECT etapa_taller_imprenta INTO etapa_anterior_val
  FROM public.ordenes_trabajo
  WHERE id = p_id_orden;

  -- Obtener ID del usuario
  SELECT id INTO usuario_actual_id
  FROM public.usuarios
  WHERE nombre = p_nombre_usuario
  LIMIT 1;

  -- Si hay una etapa anterior, cerrar su registro y calcular tiempo
  IF etapa_anterior_val IS NOT NULL AND etapa_anterior_val != '' THEN
    -- Obtener fecha de inicio de la etapa anterior
    SELECT fecha_inicio_etapa INTO fecha_inicio_anterior
    FROM public.historial_etapas_taller_imprenta
    WHERE id_orden = p_id_orden
      AND etapa_nueva = etapa_anterior_val
      AND fecha_fin_etapa IS NULL
    ORDER BY fecha_cambio DESC
    LIMIT 1;
    
    -- Si no se encontró fecha_inicio, usar la fecha de cambio más reciente
    IF fecha_inicio_anterior IS NULL THEN
      SELECT etapa_taller_imprenta_fecha_inicio INTO fecha_inicio_anterior
      FROM public.ordenes_trabajo
      WHERE id = p_id_orden;
      
      IF fecha_inicio_anterior IS NULL THEN
        fecha_inicio_anterior := now();
      END IF;
    END IF;
    
    -- Calcular tiempo en segundos
    tiempo_segundos := EXTRACT(EPOCH FROM (now() - fecha_inicio_anterior))::integer;
    
    -- Cerrar el registro de la etapa anterior
    UPDATE public.historial_etapas_taller_imprenta
    SET fecha_fin_etapa = now(),
        tiempo_en_etapa_seg = tiempo_segundos
    WHERE id_orden = p_id_orden
      AND etapa_nueva = etapa_anterior_val
      AND fecha_fin_etapa IS NULL;
  END IF;
  
  -- Actualizar la orden
  UPDATE public.ordenes_trabajo
  SET etapa_taller_imprenta = p_nueva_etapa,
      etapa_taller_imprenta_fecha_inicio = now()
  WHERE id = p_id_orden;
  
  -- Registrar el nuevo cambio de etapa
  INSERT INTO public.historial_etapas_taller_imprenta (
    id_orden,
    etapa_anterior,
    etapa_nueva,
    id_usuario,
    nombre_usuario,
    fecha_cambio,
    fecha_inicio_etapa
  ) VALUES (
    p_id_orden,
    etapa_anterior_val,
    p_nueva_etapa,
    usuario_actual_id,
    p_nombre_usuario,
    now(),
    now()
  );
END;
$$;

-- ============================================
-- 5. Función de notificaciones
-- ============================================
CREATE OR REPLACE FUNCTION public.notify_cambio_etapa_taller_imprenta()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  operario_id integer;
  operario_nombre varchar(255);
  admin_ids integer[];
  usuario_cambio_nombre varchar(255);
BEGIN
  -- Solo procesar si cambió la etapa
  IF OLD.etapa_taller_imprenta IS DISTINCT FROM NEW.etapa_taller_imprenta THEN
    
    -- Obtener nombre del usuario que hizo el cambio
    BEGIN
      usuario_cambio_nombre := COALESCE(
        current_setting('app.current_user_name', true),
        NULLIF(trim(NEW.operario_asignado), ''),
        NULLIF(trim(NEW.usuario_trabajando_nombre), ''),
        NULLIF(trim(NEW.nombre_creador), ''),
        'Sistema'
      );
    EXCEPTION WHEN undefined_column THEN
      usuario_cambio_nombre := COALESCE(
        current_setting('app.current_user_name', true),
        NULLIF(trim(NEW.usuario_trabajando_nombre), ''),
        NULLIF(trim(NEW.nombre_creador), ''),
        'Sistema'
      );
    END;
    
    -- Obtener ID del operario asignado (si existe)
    IF NEW.operario_asignado IS NOT NULL AND trim(NEW.operario_asignado) != '' THEN
      SELECT id INTO operario_id
      FROM public.usuarios
      WHERE nombre = trim(NEW.operario_asignado)
      LIMIT 1;
      
      operario_nombre := trim(NEW.operario_asignado);
    ELSIF NEW.usuario_trabajando_nombre IS NOT NULL AND trim(NEW.usuario_trabajando_nombre) != '' THEN
      SELECT id INTO operario_id
      FROM public.usuarios
      WHERE nombre = trim(NEW.usuario_trabajando_nombre)
      LIMIT 1;
      
      operario_nombre := trim(NEW.usuario_trabajando_nombre);
    END IF;
    
    -- Obtener IDs de administradores y gerencia
    SELECT ARRAY_AGG(id) INTO admin_ids
    FROM public.usuarios
    WHERE rol IN ('administracion', 'gerencia');
    
    -- Crear notificación para el operario asignado (si existe y no es quien hizo el cambio)
    IF operario_id IS NOT NULL AND operario_nombre != usuario_cambio_nombre THEN
      INSERT INTO public.notificaciones (
        id_usuario,
        tipo,
        titulo,
        mensaje,
        id_orden,
        leida,
        created_at
      ) VALUES (
        operario_id,
        'cambio_etapa_taller_imprenta',
        'Cambio de etapa en Taller de Imprenta',
        format('La OP #%s cambió a la etapa "%s" en Taller de Imprenta', 
               NEW.numero_op, 
               COALESCE(NEW.etapa_taller_imprenta, 'Sin etapa')),
        NEW.id,
        false,
        now()
      );
    END IF;
    
    -- Crear notificaciones para administradores y gerencia
    IF admin_ids IS NOT NULL AND array_length(admin_ids, 1) > 0 THEN
      INSERT INTO public.notificaciones (
        id_usuario,
        tipo,
        titulo,
        mensaje,
        id_orden,
        leida,
        created_at
      )
      SELECT 
        unnest(admin_ids),
        'cambio_etapa_taller_imprenta',
        'Cambio de etapa en Taller de Imprenta',
        format('La OP #%s cambió a la etapa "%s" en Taller de Imprenta (por %s)', 
               NEW.numero_op, 
               COALESCE(NEW.etapa_taller_imprenta, 'Sin etapa'),
               usuario_cambio_nombre),
        NEW.id,
        false,
        now();
    END IF;
    
  END IF;
  
  RETURN NEW;
END;
$$;

-- ============================================
-- 6. Crear triggers
-- ============================================
DROP TRIGGER IF EXISTS trigger_notify_cambio_etapa_taller_imprenta ON public.ordenes_trabajo;
CREATE TRIGGER trigger_notify_cambio_etapa_taller_imprenta
  AFTER UPDATE ON public.ordenes_trabajo
  FOR EACH ROW
  WHEN (OLD.etapa_taller_imprenta IS DISTINCT FROM NEW.etapa_taller_imprenta)
  EXECUTE FUNCTION public.notify_cambio_etapa_taller_imprenta();

COMMIT;

