-- Crear tablas para gestión de proveedores

BEGIN;

-- Tabla principal de proveedores
CREATE TABLE IF NOT EXISTS public.proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(255) NOT NULL,
  razon_social varchar(255),
  cuit varchar(50) UNIQUE,
  contacto_nombre varchar(255),
  telefono varchar(50),
  email varchar(255),
  direccion text,
  ciudad varchar(100),
  provincia varchar(100),
  codigo_postal varchar(20),
  sitio_web varchar(255),
  notas text,
  activo boolean DEFAULT true,
  calificacion numeric(3,2) DEFAULT 0 CHECK (calificacion >= 0 AND calificacion <= 5),
  total_compras integer DEFAULT 0,
  monto_total_compras numeric(15,2) DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de productos de proveedores (catálogo de productos que ofrece cada proveedor)
CREATE TABLE IF NOT EXISTS public.proveedores_productos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proveedor integer NOT NULL REFERENCES public.proveedores(id) ON DELETE CASCADE,
  codigo_producto varchar(100),
  descripcion text NOT NULL,
  unidad varchar(50) DEFAULT 'unidad',
  precio_unitario numeric(10,2),
  moneda varchar(10) DEFAULT 'ARS',
  stock_disponible numeric(10,3),
  tiempo_entrega_dias integer,
  observaciones text,
  activo boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(id_proveedor, codigo_producto, descripcion)
);

-- Tabla de presupuestos/cotizaciones
CREATE TABLE IF NOT EXISTS public.presupuestos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_presupuesto varchar(50) NOT NULL UNIQUE,
  id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL,
  id_proveedor integer NOT NULL REFERENCES public.proveedores(id) ON DELETE CASCADE,
  estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
    estado IN ('Pendiente', 'Enviado', 'Recibido', 'Aceptado', 'Rechazado', 'Vencido')
  ),
  fecha_solicitud timestamptz NOT NULL DEFAULT now(),
  fecha_envio timestamptz,
  fecha_recepcion timestamptz,
  fecha_vencimiento date,
  fecha_aceptacion timestamptz,
  monto_total numeric(15,2),
  moneda varchar(10) DEFAULT 'ARS',
  condiciones_pago text,
  tiempo_entrega_dias integer,
  observaciones text,
  archivo_adjunto_url text,
  id_usuario_solicitante integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  nombre_usuario_solicitante varchar(100),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de items de presupuestos
CREATE TABLE IF NOT EXISTS public.presupuestos_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_presupuesto integer NOT NULL REFERENCES public.presupuestos(id) ON DELETE CASCADE,
  id_item_pedido integer REFERENCES public.pedidos_compras_items(id) ON DELETE SET NULL,
  codigo_producto varchar(100),
  descripcion text NOT NULL,
  cantidad numeric(10,3) NOT NULL,
  unidad varchar(50) DEFAULT 'unidad',
  precio_unitario numeric(10,2) NOT NULL,
  precio_total numeric(10,2) NOT NULL,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de historial de precios (para tracking de cambios de precios)
CREATE TABLE IF NOT EXISTS public.precios_historial (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proveedor_producto integer REFERENCES public.proveedores_productos(id) ON DELETE CASCADE,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE CASCADE,
  codigo_producto varchar(100),
  descripcion text NOT NULL,
  precio_anterior numeric(10,2),
  precio_nuevo numeric(10,2) NOT NULL,
  fecha_cambio timestamptz NOT NULL DEFAULT now(),
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  motivo text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de comparación de presupuestos (para comparar múltiples ofertas)
CREATE TABLE IF NOT EXISTS public.comparacion_presupuestos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido_compra integer NOT NULL REFERENCES public.pedidos_compras(id) ON DELETE CASCADE,
  id_presupuesto_seleccionado integer REFERENCES public.presupuestos(id) ON DELETE SET NULL,
  notas_comparacion text,
  criterio_seleccion text,
  id_usuario_comparador integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  fecha_comparacion timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_proveedores_activo ON public.proveedores(activo);
CREATE INDEX IF NOT EXISTS idx_proveedores_nombre ON public.proveedores(nombre);
CREATE INDEX IF NOT EXISTS idx_proveedores_cuit ON public.proveedores(cuit);

CREATE INDEX IF NOT EXISTS idx_proveedores_productos_proveedor ON public.proveedores_productos(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_proveedores_productos_codigo ON public.proveedores_productos(codigo_producto);
CREATE INDEX IF NOT EXISTS idx_proveedores_productos_activo ON public.proveedores_productos(activo);

CREATE INDEX IF NOT EXISTS idx_presupuestos_pedido ON public.presupuestos(id_pedido_compra);
CREATE INDEX IF NOT EXISTS idx_presupuestos_proveedor ON public.presupuestos(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_presupuestos_estado ON public.presupuestos(estado);
CREATE INDEX IF NOT EXISTS idx_presupuestos_fecha_vencimiento ON public.presupuestos(fecha_vencimiento);

CREATE INDEX IF NOT EXISTS idx_presupuestos_items_presupuesto ON public.presupuestos_items(id_presupuesto);
CREATE INDEX IF NOT EXISTS idx_presupuestos_items_pedido ON public.presupuestos_items(id_item_pedido);

CREATE INDEX IF NOT EXISTS idx_precios_historial_producto ON public.precios_historial(id_proveedor_producto);
CREATE INDEX IF NOT EXISTS idx_precios_historial_proveedor ON public.precios_historial(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_precios_historial_fecha ON public.precios_historial(fecha_cambio DESC);

CREATE INDEX IF NOT EXISTS idx_comparacion_presupuestos_pedido ON public.comparacion_presupuestos(id_pedido_compra);

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION public.update_proveedor_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_proveedor_updated_at
  BEFORE UPDATE ON public.proveedores
  FOR EACH ROW
  EXECUTE FUNCTION public.update_proveedor_updated_at();

CREATE TRIGGER trigger_update_proveedor_producto_updated_at
  BEFORE UPDATE ON public.proveedores_productos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_proveedor_updated_at();

CREATE TRIGGER trigger_update_presupuesto_updated_at
  BEFORE UPDATE ON public.presupuestos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_proveedor_updated_at();

-- Función para actualizar estadísticas del proveedor cuando se acepta un presupuesto
CREATE OR REPLACE FUNCTION public.actualizar_estadisticas_proveedor()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.estado = 'Aceptado' AND (OLD.estado IS NULL OR OLD.estado != 'Aceptado') THEN
    UPDATE public.proveedores
    SET 
      total_compras = total_compras + 1,
      monto_total_compras = monto_total_compras + COALESCE(NEW.monto_total, 0)
    WHERE id = NEW.id_proveedor;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_actualizar_estadisticas_proveedor
  AFTER UPDATE ON public.presupuestos
  FOR EACH ROW
  EXECUTE FUNCTION public.actualizar_estadisticas_proveedor();

-- Función para registrar cambios de precios
CREATE OR REPLACE FUNCTION public.registrar_cambio_precio()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.precio_unitario IS NOT NULL AND NEW.precio_unitario IS NOT NULL AND OLD.precio_unitario != NEW.precio_unitario THEN
    INSERT INTO public.precios_historial (
      id_proveedor_producto,
      id_proveedor,
      codigo_producto,
      descripcion,
      precio_anterior,
      precio_nuevo
    ) VALUES (
      NEW.id,
      NEW.id_proveedor,
      NEW.codigo_producto,
      NEW.descripcion,
      OLD.precio_unitario,
      NEW.precio_unitario
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_registrar_cambio_precio
  AFTER UPDATE ON public.proveedores_productos
  FOR EACH ROW
  EXECUTE FUNCTION public.registrar_cambio_precio();

COMMIT;

