-- ============================================
-- Sistema de Libro de Actas por Sector
-- Cada sector puede tener su propio libro de actas
-- para registrar novedades, problemas, mejoras, etc.
-- ============================================

BEGIN;

-- ============================================
-- 1. CREAR TABLA libro_actas_sectores
-- ============================================
CREATE TABLE IF NOT EXISTS public.libro_actas_sectores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sector integer REFERENCES public.sectores(id) ON DELETE CASCADE,
  sector_nombre text NOT NULL, -- Para búsqueda rápida sin JOIN
  fecha timestamptz NOT NULL DEFAULT now(),
  usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  usuario_nombre text NOT NULL, -- Para búsqueda rápida sin JOIN
  titulo text NOT NULL,
  contenido text NOT NULL,
  tipo_novedad text DEFAULT 'general' CHECK (tipo_novedad IN ('general', 'problema', 'mejora', 'incidente', 'reunion', 'capacitacion', 'otro')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Índices para búsqueda rápida
CREATE INDEX IF NOT EXISTS idx_libro_actas_sector ON public.libro_actas_sectores(id_sector);
CREATE INDEX IF NOT EXISTS idx_libro_actas_sector_nombre ON public.libro_actas_sectores(sector_nombre);
CREATE INDEX IF NOT EXISTS idx_libro_actas_fecha ON public.libro_actas_sectores(fecha DESC);
CREATE INDEX IF NOT EXISTS idx_libro_actas_usuario ON public.libro_actas_sectores(usuario_id);

-- Comentarios
COMMENT ON TABLE public.libro_actas_sectores IS 'Libro de actas para registrar novedades por sector';
COMMENT ON COLUMN public.libro_actas_sectores.id_sector IS 'ID del sector (FK a sectores)';
COMMENT ON COLUMN public.libro_actas_sectores.sector_nombre IS 'Nombre del sector (para búsqueda rápida)';
COMMENT ON COLUMN public.libro_actas_sectores.tipo_novedad IS 'Tipo de novedad: general, problema, mejora, incidente, reunion, capacitacion, otro';

-- ============================================
-- 2. FUNCIÓN: crear_acta_sector
-- ============================================
CREATE OR REPLACE FUNCTION public.crear_acta_sector(
  p_id_sector integer,
  p_usuario_id integer,
  p_usuario_nombre text,
  p_titulo text,
  p_contenido text,
  p_tipo_novedad text DEFAULT 'general',
  p_fecha timestamptz DEFAULT now()
)
RETURNS TABLE (
  id integer,
  mensaje text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  nueva_acta_id integer;
  sector_nombre_text text;
BEGIN
  -- Validar que el sector existe
  SELECT nombre INTO sector_nombre_text
  FROM public.sectores
  WHERE id = p_id_sector AND activo = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Sector no encontrado o inactivo';
  END IF;

  -- Validar campos requeridos
  IF trim(p_titulo) = '' THEN
    RAISE EXCEPTION 'El título no puede estar vacío';
  END IF;

  IF trim(p_contenido) = '' THEN
    RAISE EXCEPTION 'El contenido no puede estar vacío';
  END IF;

  -- Validar tipo de novedad
  IF p_tipo_novedad NOT IN ('general', 'problema', 'mejora', 'incidente', 'reunion', 'capacitacion', 'otro') THEN
    p_tipo_novedad := 'general';
  END IF;

  -- Insertar acta
  INSERT INTO public.libro_actas_sectores (
    id_sector,
    sector_nombre,
    fecha,
    usuario_id,
    usuario_nombre,
    titulo,
    contenido,
    tipo_novedad
  ) VALUES (
    p_id_sector,
    sector_nombre_text,
    COALESCE(p_fecha, now()),
    p_usuario_id,
    p_usuario_nombre,
    trim(p_titulo),
    trim(p_contenido),
    p_tipo_novedad
  )
  RETURNING id INTO nueva_acta_id;

  RETURN QUERY
  SELECT nueva_acta_id, 'Acta creada exitosamente';
END;
$$;

COMMENT ON FUNCTION public.crear_acta_sector IS 'Crea una nueva acta en el libro de actas de un sector';

-- ============================================
-- 3. FUNCIÓN: listar_actas_sector
-- ============================================
CREATE OR REPLACE FUNCTION public.listar_actas_sector(
  p_id_sector integer DEFAULT NULL,
  p_sector_nombre text DEFAULT NULL,
  p_fecha_desde timestamptz DEFAULT NULL,
  p_fecha_hasta timestamptz DEFAULT NULL,
  p_tipo_novedad text DEFAULT NULL,
  p_limit integer DEFAULT 100,
  p_offset integer DEFAULT 0
)
RETURNS TABLE (
  id integer,
  id_sector integer,
  sector_nombre text,
  fecha timestamptz,
  usuario_id integer,
  usuario_nombre text,
  titulo text,
  contenido text,
  tipo_novedad text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    a.id,
    a.id_sector,
    a.sector_nombre,
    a.fecha,
    a.usuario_id,
    a.usuario_nombre,
    a.titulo,
    a.contenido,
    a.tipo_novedad,
    a.created_at,
    a.updated_at
  FROM public.libro_actas_sectores a
  WHERE 
    (p_id_sector IS NULL OR a.id_sector = p_id_sector)
    AND (p_sector_nombre IS NULL OR a.sector_nombre ILIKE '%' || p_sector_nombre || '%')
    AND (p_fecha_desde IS NULL OR a.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR a.fecha <= p_fecha_hasta)
    AND (p_tipo_novedad IS NULL OR a.tipo_novedad = p_tipo_novedad)
  ORDER BY a.fecha DESC, a.created_at DESC
  LIMIT p_limit
  OFFSET p_offset;
END;
$$;

COMMENT ON FUNCTION public.listar_actas_sector IS 'Lista las actas de un sector con filtros opcionales';

-- ============================================
-- 4. FUNCIÓN: obtener_acta_sector
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_acta_sector(
  p_id_acta integer
)
RETURNS TABLE (
  id integer,
  id_sector integer,
  sector_nombre text,
  fecha timestamptz,
  usuario_id integer,
  usuario_nombre text,
  titulo text,
  contenido text,
  tipo_novedad text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    a.id,
    a.id_sector,
    a.sector_nombre,
    a.fecha,
    a.usuario_id,
    a.usuario_nombre,
    a.titulo,
    a.contenido,
    a.tipo_novedad,
    a.created_at,
    a.updated_at
  FROM public.libro_actas_sectores a
  WHERE a.id = p_id_acta;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Acta no encontrada';
  END IF;
END;
$$;

COMMENT ON FUNCTION public.obtener_acta_sector IS 'Obtiene una acta específica por ID';

-- ============================================
-- 5. FUNCIÓN: actualizar_acta_sector
-- ============================================
CREATE OR REPLACE FUNCTION public.actualizar_acta_sector(
  p_id_acta integer,
  p_titulo text DEFAULT NULL,
  p_contenido text DEFAULT NULL,
  p_tipo_novedad text DEFAULT NULL,
  p_fecha timestamptz DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  mensaje text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  acta_existe boolean;
BEGIN
  -- Verificar que la acta existe
  SELECT EXISTS(SELECT 1 FROM public.libro_actas_sectores WHERE id = p_id_acta) INTO acta_existe;
  
  IF NOT acta_existe THEN
    RAISE EXCEPTION 'Acta no encontrada';
  END IF;

  -- Validar tipo de novedad si se proporciona
  IF p_tipo_novedad IS NOT NULL AND p_tipo_novedad NOT IN ('general', 'problema', 'mejora', 'incidente', 'reunion', 'capacitacion', 'otro') THEN
    RAISE EXCEPTION 'Tipo de novedad inválido';
  END IF;

  -- Actualizar solo los campos proporcionados
  UPDATE public.libro_actas_sectores
  SET 
    titulo = COALESCE(trim(p_titulo), titulo),
    contenido = COALESCE(trim(p_contenido), contenido),
    tipo_novedad = COALESCE(p_tipo_novedad, tipo_novedad),
    fecha = COALESCE(p_fecha, fecha),
    updated_at = now()
  WHERE id = p_id_acta;

  RETURN QUERY
  SELECT p_id_acta, 'Acta actualizada exitosamente';
END;
$$;

COMMENT ON FUNCTION public.actualizar_acta_sector IS 'Actualiza una acta existente';

-- ============================================
-- 6. FUNCIÓN: eliminar_acta_sector
-- ============================================
CREATE OR REPLACE FUNCTION public.eliminar_acta_sector(
  p_id_acta integer
)
RETURNS TABLE (
  id integer,
  mensaje text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  acta_existe boolean;
BEGIN
  -- Verificar que la acta existe
  SELECT EXISTS(SELECT 1 FROM public.libro_actas_sectores WHERE id = p_id_acta) INTO acta_existe;
  
  IF NOT acta_existe THEN
    RAISE EXCEPTION 'Acta no encontrada';
  END IF;

  -- Eliminar acta
  DELETE FROM public.libro_actas_sectores
  WHERE id = p_id_acta;

  RETURN QUERY
  SELECT p_id_acta, 'Acta eliminada exitosamente';
END;
$$;

COMMENT ON FUNCTION public.eliminar_acta_sector IS 'Elimina una acta del libro';

-- ============================================
-- 7. TRIGGER: actualizar updated_at automáticamente
-- ============================================
CREATE OR REPLACE FUNCTION public.update_libro_actas_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_update_libro_actas_updated_at ON public.libro_actas_sectores;
CREATE TRIGGER trigger_update_libro_actas_updated_at
  BEFORE UPDATE ON public.libro_actas_sectores
  FOR EACH ROW
  EXECUTE FUNCTION public.update_libro_actas_updated_at();

-- ============================================
-- 8. POLÍTICAS RLS (Row Level Security)
-- ============================================
ALTER TABLE public.libro_actas_sectores ENABLE ROW LEVEL SECURITY;

-- Política: Todos los usuarios autenticados pueden leer actas
DROP POLICY IF EXISTS "Permitir lectura de actas a usuarios autenticados" ON public.libro_actas_sectores;
CREATE POLICY "Permitir lectura de actas a usuarios autenticados"
  ON public.libro_actas_sectores
  FOR SELECT
  USING (true);

-- Política: Todos los usuarios autenticados pueden crear actas
DROP POLICY IF EXISTS "Permitir creación de actas a usuarios autenticados" ON public.libro_actas_sectores;
CREATE POLICY "Permitir creación de actas a usuarios autenticados"
  ON public.libro_actas_sectores
  FOR INSERT
  WITH CHECK (true);

-- Política: Solo el creador o administradores pueden actualizar/eliminar
DROP POLICY IF EXISTS "Permitir actualización de actas propias o por admin" ON public.libro_actas_sectores;
CREATE POLICY "Permitir actualización de actas propias o por admin"
  ON public.libro_actas_sectores
  FOR UPDATE
  USING (
    -- El usuario es el creador (se verifica por usuario_id en el contexto)
    -- O es administrador (se verifica en el frontend)
    true
  );

DROP POLICY IF EXISTS "Permitir eliminación de actas propias o por admin" ON public.libro_actas_sectores;
CREATE POLICY "Permitir eliminación de actas propias o por admin"
  ON public.libro_actas_sectores
  FOR DELETE
  USING (true);

COMMIT;

