-- ============================================
-- SISTEMA DE PRESUPUESTOS DE CLIENTES WEB
-- Los clientes pueden crear presupuestos, guardarlos como borrador y enviarlos a la empresa
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE PRESUPUESTOS DE CLIENTES
-- ============================================
CREATE TABLE IF NOT EXISTS public.presupuestos_clientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  numero_presupuesto varchar(50) NOT NULL UNIQUE,
  estado varchar(50) NOT NULL DEFAULT 'borrador' CHECK (
    estado IN ('borrador', 'enviado', 'aceptado', 'rechazado', 'cancelado', 'convertido')
  ),
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_envio timestamptz,
  fecha_respuesta timestamptz,
  fecha_vencimiento date,
  observaciones_cliente text,
  observaciones_internas text,
  precio_total numeric(10,2) DEFAULT 0,
  id_pedido_asociado integer REFERENCES public.pedidos_clientes(id) ON DELETE SET NULL,
  id_op_asociada integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_presupuestos_cliente ON public.presupuestos_clientes(id_cliente);
CREATE INDEX IF NOT EXISTS idx_presupuestos_numero ON public.presupuestos_clientes(numero_presupuesto);
CREATE INDEX IF NOT EXISTS idx_presupuestos_estado ON public.presupuestos_clientes(estado);
CREATE INDEX IF NOT EXISTS idx_presupuestos_fecha ON public.presupuestos_clientes(fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS idx_presupuestos_pedido ON public.presupuestos_clientes(id_pedido_asociado);
CREATE INDEX IF NOT EXISTS idx_presupuestos_op ON public.presupuestos_clientes(id_op_asociada);

-- ============================================
-- 2. TABLA DE ITEMS DEL PRESUPUESTO
-- ============================================
CREATE TABLE IF NOT EXISTS public.presupuestos_clientes_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_presupuesto integer NOT NULL REFERENCES public.presupuestos_clientes(id) ON DELETE CASCADE,
  id_articulo integer NOT NULL REFERENCES public.articulos_empresa(id) ON DELETE RESTRICT,
  cantidad integer NOT NULL DEFAULT 1,
  precio_unitario numeric(10,2) NOT NULL,
  precio_total numeric(10,2) NOT NULL,
  descripcion_personalizada text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_presupuesto ON public.presupuestos_clientes_items(id_presupuesto);
CREATE INDEX IF NOT EXISTS idx_items_articulo_presupuesto ON public.presupuestos_clientes_items(id_articulo);

-- ============================================
-- 3. FUNCIÓN PARA GENERAR NÚMERO ÚNICO DE PRESUPUESTO
-- ============================================
CREATE OR REPLACE FUNCTION public.generar_numero_presupuesto_cliente()
RETURNS varchar(50)
LANGUAGE plpgsql
AS $$
DECLARE
  nuevo_numero varchar(50);
  contador integer;
  año_mes varchar(6);
BEGIN
  -- Formato: PCL-YYYYMM-0001 (reinicia cada mes)
  año_mes := TO_CHAR(CURRENT_DATE, 'YYYYMM');
  
  -- Buscar el último número del mes actual
  SELECT COALESCE(MAX(CAST(SUBSTRING(numero_presupuesto FROM '[0-9]+$') AS INTEGER)), 0) + 1
  INTO contador
  FROM public.presupuestos_clientes
  WHERE numero_presupuesto LIKE 'PCL-' || año_mes || '-%';
  
  nuevo_numero := 'PCL-' || año_mes || '-' || LPAD(contador::text, 4, '0');
  
  -- Verificar que no exista (por si acaso)
  WHILE EXISTS (SELECT 1 FROM public.presupuestos_clientes WHERE numero_presupuesto = nuevo_numero) LOOP
    contador := contador + 1;
    nuevo_numero := 'PCL-' || año_mes || '-' || LPAD(contador::text, 4, '0');
  END LOOP;
  
  RETURN nuevo_numero;
END;
$$;

-- ============================================
-- 4. FUNCIÓN PARA CREAR PRESUPUESTO DE CLIENTE
-- ============================================
CREATE OR REPLACE FUNCTION public.crear_presupuesto_cliente(
  p_id_cliente integer,
  p_items jsonb DEFAULT '[]'::jsonb,
  p_fecha_vencimiento date DEFAULT NULL,
  p_observaciones_cliente text DEFAULT NULL,
  p_estado varchar(50) DEFAULT 'borrador'
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  estado varchar,
  precio_total numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  nuevo_presupuesto_id integer;
  numero_presupuesto_generado varchar(50);
  item_record jsonb;
  precio_total_calculado numeric(10,2) := 0;
BEGIN
  -- Validar que el cliente existe, es cliente web y está activo
  IF NOT EXISTS (
    SELECT 1 FROM public.clientes 
    WHERE id = p_id_cliente 
      AND es_cliente_web = true 
      AND activo = true
  ) THEN
    RAISE EXCEPTION 'Cliente no encontrado o inactivo';
  END IF;

  -- Validar estado
  IF p_estado NOT IN ('borrador', 'enviado', 'aceptado', 'rechazado', 'cancelado', 'convertido') THEN
    RAISE EXCEPTION 'Estado inválido: %', p_estado;
  END IF;

  -- Generar número de presupuesto
  numero_presupuesto_generado := public.generar_numero_presupuesto_cliente();

  -- Crear presupuesto
  INSERT INTO public.presupuestos_clientes (
    id_cliente,
    numero_presupuesto,
    estado,
    fecha_vencimiento,
    observaciones_cliente,
    fecha_envio
  ) VALUES (
    p_id_cliente,
    numero_presupuesto_generado,
    p_estado,
    p_fecha_vencimiento,
    p_observaciones_cliente,
    CASE WHEN p_estado = 'enviado' THEN NOW() ELSE NULL END
  )
  RETURNING id INTO nuevo_presupuesto_id;

  -- Procesar items
  FOR item_record IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.presupuestos_clientes_items (
      id_presupuesto,
      id_articulo,
      cantidad,
      precio_unitario,
      precio_total,
      descripcion_personalizada
    ) VALUES (
      nuevo_presupuesto_id,
      (item_record->>'id_articulo')::integer,
      COALESCE((item_record->>'cantidad')::integer, 1),
      (item_record->>'precio_unitario')::numeric,
      (item_record->>'precio_total')::numeric,
      item_record->>'descripcion_personalizada'
    );

    precio_total_calculado := precio_total_calculado + ((item_record->>'precio_total')::numeric);
  END LOOP;

  -- Actualizar precio total del presupuesto
  UPDATE public.presupuestos_clientes
  SET precio_total = precio_total_calculado
  WHERE id = nuevo_presupuesto_id;

  RETURN QUERY
  SELECT p.id, p.numero_presupuesto, p.estado, p.precio_total
  FROM public.presupuestos_clientes p
  WHERE p.id = nuevo_presupuesto_id;
END;
$$;

-- ============================================
-- 5. FUNCIÓN PARA ACTUALIZAR PRESUPUESTO DE CLIENTE
-- ============================================
CREATE OR REPLACE FUNCTION public.actualizar_presupuesto_cliente(
  p_id_presupuesto integer,
  p_items jsonb DEFAULT NULL,
  p_fecha_vencimiento date DEFAULT NULL,
  p_observaciones_cliente text DEFAULT NULL,
  p_estado varchar(50) DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  estado varchar,
  precio_total numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  item_record jsonb;
  precio_total_calculado numeric(10,2);
  presupuesto_existe boolean;
BEGIN
  -- Verificar que el presupuesto existe
  SELECT EXISTS(SELECT 1 FROM public.presupuestos_clientes WHERE id = p_id_presupuesto)
  INTO presupuesto_existe;
  
  IF NOT presupuesto_existe THEN
    RAISE EXCEPTION 'Presupuesto no encontrado';
  END IF;

  -- Si se proporcionan items, actualizar items
  IF p_items IS NOT NULL THEN
    -- Eliminar items existentes
    DELETE FROM public.presupuestos_clientes_items WHERE id_presupuesto = p_id_presupuesto;
    
    -- Insertar nuevos items
    precio_total_calculado := 0;
    FOR item_record IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
      INSERT INTO public.presupuestos_clientes_items (
        id_presupuesto,
        id_articulo,
        cantidad,
        precio_unitario,
        precio_total,
        descripcion_personalizada
      ) VALUES (
        p_id_presupuesto,
        (item_record->>'id_articulo')::integer,
        COALESCE((item_record->>'cantidad')::integer, 1),
        (item_record->>'precio_unitario')::numeric,
        (item_record->>'precio_total')::numeric,
        item_record->>'descripcion_personalizada'
      );

      precio_total_calculado := precio_total_calculado + ((item_record->>'precio_total')::numeric);
    END LOOP;
  ELSE
    -- Calcular precio total de items existentes
    SELECT COALESCE(SUM(precio_total), 0)
    INTO precio_total_calculado
    FROM public.presupuestos_clientes_items
    WHERE id_presupuesto = p_id_presupuesto;
  END IF;

  -- Actualizar presupuesto
  UPDATE public.presupuestos_clientes
  SET
    fecha_vencimiento = COALESCE(p_fecha_vencimiento, fecha_vencimiento),
    observaciones_cliente = COALESCE(p_observaciones_cliente, observaciones_cliente),
    precio_total = precio_total_calculado,
    estado = COALESCE(p_estado, estado),
    fecha_envio = CASE 
      WHEN p_estado = 'enviado' AND estado != 'enviado' THEN NOW()
      WHEN p_estado != 'enviado' THEN fecha_envio
      ELSE fecha_envio
    END,
    fecha_respuesta = CASE 
      WHEN p_estado IN ('aceptado', 'rechazado') AND estado NOT IN ('aceptado', 'rechazado') THEN NOW()
      ELSE fecha_respuesta
    END,
    updated_at = NOW()
  WHERE id = p_id_presupuesto;

  RETURN QUERY
  SELECT p.id, p.numero_presupuesto, p.estado, p.precio_total
  FROM public.presupuestos_clientes p
  WHERE p.id = p_id_presupuesto;
END;
$$;

-- ============================================
-- 6. FUNCIÓN PARA ENVIAR PRESUPUESTO (cambiar estado a enviado)
-- ============================================
CREATE OR REPLACE FUNCTION public.enviar_presupuesto_cliente(
  p_id_presupuesto integer
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  estado varchar,
  fecha_envio timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.presupuestos_clientes
  SET
    estado = 'enviado',
    fecha_envio = NOW(),
    updated_at = NOW()
  WHERE id = p_id_presupuesto
    AND estado = 'borrador';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Presupuesto no encontrado o no está en estado borrador';
  END IF;

  RETURN QUERY
  SELECT p.id, p.numero_presupuesto, p.estado, p.fecha_envio
  FROM public.presupuestos_clientes p
  WHERE p.id = p_id_presupuesto;
END;
$$;

-- ============================================
-- 7. FUNCIÓN PARA OBTENER PRESUPUESTOS DE UN CLIENTE
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_presupuestos_cliente(
  p_id_cliente integer
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  estado varchar,
  fecha_creacion timestamptz,
  fecha_envio timestamptz,
  fecha_vencimiento date,
  precio_total numeric,
  id_pedido_asociado integer,
  id_op_asociada integer
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.numero_presupuesto,
    p.estado,
    p.fecha_creacion,
    p.fecha_envio,
    p.fecha_vencimiento,
    p.precio_total,
    p.id_pedido_asociado,
    p.id_op_asociada
  FROM public.presupuestos_clientes p
  WHERE p.id_cliente = p_id_cliente
  ORDER BY p.fecha_creacion DESC;
END;
$$;

-- ============================================
-- 8. FUNCIÓN PARA OBTENER DETALLE DE PRESUPUESTO
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_detalle_presupuesto_cliente(
  p_id_presupuesto integer
)
RETURNS TABLE (
  presupuesto jsonb,
  items jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  presupuesto_data jsonb;
  items_data jsonb;
BEGIN
  -- Obtener datos del presupuesto
  SELECT jsonb_build_object(
    'id', p.id,
    'numero_presupuesto', p.numero_presupuesto,
    'estado', p.estado,
    'fecha_creacion', p.fecha_creacion,
    'fecha_envio', p.fecha_envio,
    'fecha_respuesta', p.fecha_respuesta,
    'fecha_vencimiento', p.fecha_vencimiento,
    'precio_total', p.precio_total,
    'observaciones_cliente', p.observaciones_cliente,
    'observaciones_internas', p.observaciones_internas,
    'id_pedido_asociado', p.id_pedido_asociado,
    'id_op_asociada', p.id_op_asociada,
    'cliente', jsonb_build_object(
      'id', c.id,
      'nombre', c.nombre,
      'apellido', c.apellido,
      'empresa', c.empresa,
      'email', c.email,
      'telefono', c.telefono
    )
  )
  INTO presupuesto_data
  FROM public.presupuestos_clientes p
  JOIN public.clientes c ON c.id = p.id_cliente
  WHERE p.id = p_id_presupuesto;

  -- Obtener items del presupuesto
  SELECT jsonb_agg(
    jsonb_build_object(
      'id', i.id,
      'id_articulo', i.id_articulo,
      'articulo', jsonb_build_object(
        'codigo', a.codigo,
        'nombre', a.nombre,
        'descripcion', a.descripcion
      ),
      'cantidad', i.cantidad,
      'precio_unitario', i.precio_unitario,
      'precio_total', i.precio_total,
      'descripcion_personalizada', i.descripcion_personalizada
    )
  )
  INTO items_data
  FROM public.presupuestos_clientes_items i
  JOIN public.articulos_empresa a ON a.id = i.id_articulo
  WHERE i.id_presupuesto = p_id_presupuesto;

  RETURN QUERY
  SELECT
    COALESCE(presupuesto_data, '{}'::jsonb),
    COALESCE(items_data, '[]'::jsonb);
END;
$$;

-- ============================================
-- 9. FUNCIÓN PARA LISTAR PRESUPUESTOS (ADMINISTRACIÓN)
-- ============================================
CREATE OR REPLACE FUNCTION public.listar_presupuestos_clientes_admin(
  p_estado varchar DEFAULT NULL,
  p_id_cliente integer DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  id_cliente integer,
  cliente_nombre varchar,
  cliente_empresa varchar,
  cliente_email varchar,
  estado varchar,
  fecha_creacion timestamptz,
  fecha_envio timestamptz,
  fecha_vencimiento date,
  precio_total numeric,
  id_pedido_asociado integer,
  id_op_asociada integer
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.numero_presupuesto,
    p.id_cliente,
    c.nombre as cliente_nombre,
    c.empresa as cliente_empresa,
    c.email as cliente_email,
    p.estado,
    p.fecha_creacion,
    p.fecha_envio,
    p.fecha_vencimiento,
    p.precio_total,
    p.id_pedido_asociado,
    p.id_op_asociada
  FROM public.presupuestos_clientes p
  JOIN public.clientes c ON c.id = p.id_cliente
  WHERE 
    (p_estado IS NULL OR p.estado = p_estado)
    AND (p_id_cliente IS NULL OR p.id_cliente = p_id_cliente)
    AND (p_fecha_desde IS NULL OR p.fecha_creacion::date >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR p.fecha_creacion::date <= p_fecha_hasta)
  ORDER BY p.fecha_creacion DESC;
END;
$$;

-- ============================================
-- 10. FUNCIÓN PARA CONVERTIR PRESUPUESTO A PEDIDO
-- ============================================
CREATE OR REPLACE FUNCTION public.convertir_presupuesto_a_pedido_cliente(
  p_id_presupuesto integer,
  p_observaciones_internas text DEFAULT NULL
)
RETURNS TABLE (
  id_pedido integer,
  numero_pedido varchar,
  mensaje text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  presupuesto_record RECORD;
  nuevo_pedido_id integer;
  numero_pedido_generado varchar(50);
  item_record RECORD;
BEGIN
  -- Obtener datos del presupuesto
  SELECT * INTO presupuesto_record
  FROM public.presupuestos_clientes
  WHERE id = p_id_presupuesto;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Presupuesto no encontrado';
  END IF;

  IF presupuesto_record.estado NOT IN ('enviado', 'aceptado') THEN
    RAISE EXCEPTION 'Solo se pueden convertir presupuestos enviados o aceptados';
  END IF;

  -- Generar número de pedido
  numero_pedido_generado := public.generar_numero_pedido_cliente();

  -- Crear pedido basado en el presupuesto
  INSERT INTO public.pedidos_clientes (
    id_cliente,
    numero_pedido,
    fecha_limite_deseada,
    observaciones_cliente,
    observaciones_internas,
    estado
  ) VALUES (
    presupuesto_record.id_cliente,
    numero_pedido_generado,
    presupuesto_record.fecha_vencimiento,
    presupuesto_record.observaciones_cliente,
    COALESCE(p_observaciones_internas, '') || E'\nConvertido desde presupuesto ' || presupuesto_record.numero_presupuesto,
    'pendiente'
  )
  RETURNING id INTO nuevo_pedido_id;

  -- Copiar items del presupuesto al pedido
  FOR item_record IN
    SELECT * FROM public.presupuestos_clientes_items
    WHERE id_presupuesto = p_id_presupuesto
  LOOP
    INSERT INTO public.pedidos_clientes_items (
      id_pedido,
      id_articulo,
      cantidad,
      precio_unitario,
      precio_total,
      descripcion_personalizada
    ) VALUES (
      nuevo_pedido_id,
      item_record.id_articulo,
      item_record.cantidad,
      item_record.precio_unitario,
      item_record.precio_total,
      item_record.descripcion_personalizada
    );
  END LOOP;

  -- Actualizar precio total del pedido
  UPDATE public.pedidos_clientes
  SET precio_total = presupuesto_record.precio_total
  WHERE id = nuevo_pedido_id;

  -- Actualizar presupuesto para asociarlo con el pedido
  UPDATE public.presupuestos_clientes
  SET
    id_pedido_asociado = nuevo_pedido_id,
    estado = 'convertido',
    updated_at = NOW()
  WHERE id = p_id_presupuesto;

  RETURN QUERY
  SELECT nuevo_pedido_id, numero_pedido_generado, 'Presupuesto convertido exitosamente a pedido ' || numero_pedido_generado;
END;
$$;

-- ============================================
-- 11. COMENTARIOS
-- ============================================
COMMENT ON TABLE public.presupuestos_clientes IS 'Presupuestos creados por clientes web';
COMMENT ON COLUMN public.presupuestos_clientes.numero_presupuesto IS 'Número único automático formato PCL-YYYYMM-0001';
COMMENT ON COLUMN public.presupuestos_clientes.estado IS 'borrador: cliente lo está armando, enviado: cliente lo envió, aceptado/rechazado: respuesta empresa, convertido: convertido a pedido';
COMMENT ON FUNCTION public.generar_numero_presupuesto_cliente IS 'Genera número único de presupuesto formato PCL-YYYYMM-0001';
COMMENT ON FUNCTION public.crear_presupuesto_cliente IS 'Crea un nuevo presupuesto de cliente con items';
COMMENT ON FUNCTION public.enviar_presupuesto_cliente IS 'Cambia el estado de borrador a enviado y registra fecha de envío';
COMMENT ON FUNCTION public.convertir_presupuesto_a_pedido_cliente IS 'Convierte un presupuesto aceptado/enviado en un pedido de cliente';

COMMIT;

