-- ============================================
-- SCRIPT COMPLETO PARA FIX DEL CRM DE VENTAS
-- Ejecutar este script completo en Supabase SQL Editor
-- ============================================

BEGIN;

-- ============================================
-- 1. Asegurar que las tablas existan
-- ============================================

-- Tabla de items de venta (si no existe)
CREATE TABLE IF NOT EXISTS public.ventas_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta integer NOT NULL REFERENCES public.ventas(id) ON DELETE CASCADE,
  id_articulo_stock integer,
  codigo_articulo varchar(100),
  descripcion text NOT NULL,
  cantidad numeric(10,3) NOT NULL DEFAULT 1.000,
  precio_unitario numeric(10,2) NOT NULL,
  precio_total numeric(10,2) NOT NULL,
  descuento numeric(10,2) DEFAULT 0,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ventas_items_venta ON public.ventas_items(id_venta);
CREATE INDEX IF NOT EXISTS idx_ventas_items_articulo ON public.ventas_items(id_articulo_stock);

-- ============================================
-- 2. Asegurar que id_op y numero_op sean opcionales en ventas
-- ============================================

DO $$
BEGIN
  -- Hacer id_op opcional si no lo es
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'ventas' 
    AND column_name = 'id_op'
    AND is_nullable = 'NO'
  ) THEN
    ALTER TABLE public.ventas ALTER COLUMN id_op DROP NOT NULL;
  END IF;

  -- Hacer numero_op opcional si no lo es
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'ventas' 
    AND column_name = 'numero_op'
    AND is_nullable = 'NO'
  ) THEN
    ALTER TABLE public.ventas ALTER COLUMN numero_op DROP NOT NULL;
  END IF;
END $$;

-- ============================================
-- 3. CREAR/RECREAR función agregar_item_venta
-- ============================================

DROP FUNCTION IF EXISTS public.agregar_item_venta(integer, integer, varchar, text, numeric, numeric, numeric, text);

CREATE OR REPLACE FUNCTION public.agregar_item_venta(
  p_id_venta integer,
  p_id_articulo_stock integer DEFAULT NULL,
  p_codigo_articulo varchar(100) DEFAULT NULL,
  p_descripcion text,
  p_cantidad numeric(10,3) DEFAULT 1.000,
  p_precio_unitario numeric(10,2),
  p_descuento numeric(10,2) DEFAULT 0,
  p_observaciones text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
  v_precio_total numeric(10,2);
  v_result json;
BEGIN
  -- Validar que la venta existe
  IF NOT EXISTS (SELECT 1 FROM public.ventas WHERE id = p_id_venta) THEN
    SELECT json_build_object(
      'success', false,
      'error', 'Venta no encontrada'
    ) INTO v_result;
    RETURN v_result;
  END IF;

  -- Calcular precio total
  v_precio_total := (p_precio_unitario * p_cantidad) - COALESCE(p_descuento, 0);

  -- Insertar item
  INSERT INTO public.ventas_items (
    id_venta,
    id_articulo_stock,
    codigo_articulo,
    descripcion,
    cantidad,
    precio_unitario,
    precio_total,
    descuento,
    observaciones
  ) VALUES (
    p_id_venta,
    p_id_articulo_stock,
    p_codigo_articulo,
    p_descripcion,
    p_cantidad,
    p_precio_unitario,
    v_precio_total,
    p_descuento,
    p_observaciones
  ) RETURNING id INTO v_id;

  -- Actualizar valor total de la venta
  UPDATE public.ventas
  SET valor_total = (
    SELECT COALESCE(SUM(precio_total), 0)
    FROM public.ventas_items
    WHERE id_venta = p_id_venta
  ),
  updated_at = now()
  WHERE id = p_id_venta;

  SELECT json_build_object(
    'success', true,
    'data', json_build_object('id', v_id)
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ============================================
-- 4. CREAR/RECREAR función crear_venta_directa
-- ============================================

DROP FUNCTION IF EXISTS public.crear_venta_directa(varchar, numeric, integer, varchar, varchar, varchar, varchar, varchar, text, varchar, varchar, date, text);

CREATE OR REPLACE FUNCTION public.crear_venta_directa(
  p_cliente_nombre varchar(255),
  p_valor_total numeric(10,2),
  p_id_vendedor integer,
  p_nombre_vendedor varchar(100),
  p_cliente_telefono varchar(50) DEFAULT NULL,
  p_cliente_email varchar(255) DEFAULT NULL,
  p_cliente_dni_cuit varchar(50) DEFAULT NULL,
  p_cliente_empresa varchar(255) DEFAULT NULL,
  p_cliente_direccion text DEFAULT NULL,
  p_metodo_pago varchar(50) DEFAULT NULL,
  p_estado_pago varchar(50) DEFAULT 'Pendiente',
  p_fecha_venta date DEFAULT CURRENT_DATE,
  p_observaciones text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
  v_numero_venta varchar(50);
  v_result json;
BEGIN
  -- Generar número de venta único
  v_numero_venta := 'VENT-' || TO_CHAR(now(), 'YYYYMMDD') || '-' || LPAD(
    (COALESCE((SELECT MAX(id) FROM public.ventas), 0) + 1)::text,
    4,
    '0'
  );

  -- Crear venta directamente (sin oportunidad ni OP)
  INSERT INTO public.ventas (
    numero_venta,
    id_oportunidad,
    cliente_nombre,
    cliente_telefono,
    cliente_email,
    cliente_dni_cuit,
    cliente_empresa,
    cliente_direccion,
    id_op,
    numero_op,
    valor_total,
    metodo_pago,
    estado_pago,
    fecha_venta,
    id_vendedor,
    nombre_vendedor,
    observaciones
  ) VALUES (
    v_numero_venta,
    NULL,
    p_cliente_nombre,
    p_cliente_telefono,
    p_cliente_email,
    p_cliente_dni_cuit,
    p_cliente_empresa,
    p_cliente_direccion,
    NULL,
    NULL,
    p_valor_total,
    p_metodo_pago,
    p_estado_pago,
    p_fecha_venta,
    p_id_vendedor,
    p_nombre_vendedor,
    p_observaciones
  ) RETURNING id INTO v_id;

  SELECT json_build_object(
    'success', true,
    'data', json_build_object(
      'id', v_id,
      'numero_venta', v_numero_venta
    )
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- ============================================
-- 5. Agregar id_venta a stock_movimientos si no existe
-- ============================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' 
    AND table_name = 'stock_movimientos' 
    AND column_name = 'id_venta'
  ) THEN
    ALTER TABLE public.stock_movimientos
    ADD COLUMN id_venta integer REFERENCES public.ventas(id) ON DELETE SET NULL;
    
    CREATE INDEX IF NOT EXISTS idx_stock_movimientos_venta ON public.stock_movimientos(id_venta);
  END IF;
END $$;

-- ============================================
-- 6. Verificar que las funciones se crearon correctamente
-- ============================================

DO $$
DECLARE
  v_func_count integer;
BEGIN
  SELECT COUNT(*) INTO v_func_count
  FROM information_schema.routines 
  WHERE routine_schema = 'public' 
    AND routine_name IN ('agregar_item_venta', 'crear_venta_directa');
  
  IF v_func_count < 2 THEN
    RAISE EXCEPTION 'No se pudieron crear todas las funciones necesarias';
  END IF;
  
  RAISE NOTICE '✅ Funciones creadas correctamente: agregar_item_venta, crear_venta_directa';
END $$;

COMMIT;

-- ============================================
-- VERIFICACIÓN FINAL
-- ============================================
-- Ejecuta esto para verificar que todo está bien:
-- SELECT routine_name 
-- FROM information_schema.routines 
-- WHERE routine_schema = 'public' 
--   AND routine_name IN ('agregar_item_venta', 'crear_venta_directa', 'obtener_ventas');

