-- Crear tabla de registro de tiempo de trabajo
CREATE TABLE IF NOT EXISTS public.tiempo_trabajo (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  usuario_nombre varchar(100) NOT NULL,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  hora_inicio time NOT NULL,
  hora_fin time,
  tiempo_minutos integer,
  descripcion text,
  tipo_trabajo text CHECK (tipo_trabajo IN ('diseno', 'revision', 'correccion', 'consulta', 'otro')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_tiempo_orden ON public.tiempo_trabajo(id_orden);
CREATE INDEX IF NOT EXISTS idx_tiempo_usuario ON public.tiempo_trabajo(usuario_id);
CREATE INDEX IF NOT EXISTS idx_tiempo_fecha ON public.tiempo_trabajo(fecha DESC);
CREATE INDEX IF NOT EXISTS idx_tiempo_usuario_fecha ON public.tiempo_trabajo(usuario_id, fecha DESC);

-- Función para iniciar registro de tiempo
CREATE OR REPLACE FUNCTION public.iniciar_tiempo_trabajo(
  p_id_orden integer,
  p_usuario_id integer,
  p_usuario_nombre varchar(100),
  p_hora_inicio time DEFAULT CURRENT_TIME,
  p_descripcion text DEFAULT NULL,
  p_tipo_trabajo text DEFAULT 'diseno'
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_id integer;
BEGIN
  -- Verificar si ya hay un registro activo (sin hora_fin) para esta orden y usuario
  SELECT id INTO v_new_id
  FROM public.tiempo_trabajo
  WHERE id_orden = p_id_orden
    AND usuario_id = p_usuario_id
    AND hora_fin IS NULL
    AND fecha = CURRENT_DATE;

  IF v_new_id IS NOT NULL THEN
    -- Ya existe un registro activo, retornar su ID
    RETURN v_new_id;
  END IF;

  -- Crear nuevo registro
  INSERT INTO public.tiempo_trabajo (
    id_orden,
    usuario_id,
    usuario_nombre,
    fecha,
    hora_inicio,
    descripcion,
    tipo_trabajo
  )
  VALUES (
    p_id_orden,
    p_usuario_id,
    p_usuario_nombre,
    CURRENT_DATE,
    p_hora_inicio,
    p_descripcion,
    p_tipo_trabajo
  )
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$;

-- Función para finalizar registro de tiempo
CREATE OR REPLACE FUNCTION public.finalizar_tiempo_trabajo(
  p_id_registro integer,
  p_hora_fin time DEFAULT CURRENT_TIME,
  p_descripcion text DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_tiempo_minutos integer;
  v_hora_inicio time;
BEGIN
  -- Obtener hora de inicio
  SELECT hora_inicio INTO v_hora_inicio
  FROM public.tiempo_trabajo
  WHERE id = p_id_registro;

  IF v_hora_inicio IS NULL THEN
    RAISE EXCEPTION 'Registro de tiempo no encontrado';
  END IF;

  -- Calcular tiempo en minutos
  v_tiempo_minutos := EXTRACT(EPOCH FROM (p_hora_fin::time - v_hora_inicio::time)) / 60;

  -- Actualizar registro
  UPDATE public.tiempo_trabajo
  SET hora_fin = p_hora_fin,
      tiempo_minutos = v_tiempo_minutos,
      descripcion = COALESCE(p_descripcion, descripcion),
      updated_at = now()
  WHERE id = p_id_registro;

  RETURN v_tiempo_minutos;
END;
$$;

-- Función para registrar tiempo manualmente
CREATE OR REPLACE FUNCTION public.registrar_tiempo_manual(
  p_id_orden integer,
  p_usuario_id integer,
  p_usuario_nombre varchar(100),
  p_fecha date DEFAULT CURRENT_DATE,
  p_hora_inicio time,
  p_hora_fin time,
  p_tiempo_minutos integer DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_tipo_trabajo text DEFAULT 'diseno'
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_id integer;
  v_tiempo_calculado integer;
BEGIN
  -- Calcular tiempo si no se proporciona
  IF p_tiempo_minutos IS NULL THEN
    v_tiempo_calculado := EXTRACT(EPOCH FROM (p_hora_fin::time - p_hora_inicio::time)) / 60;
  ELSE
    v_tiempo_calculado := p_tiempo_minutos;
  END IF;

  INSERT INTO public.tiempo_trabajo (
    id_orden,
    usuario_id,
    usuario_nombre,
    fecha,
    hora_inicio,
    hora_fin,
    tiempo_minutos,
    descripcion,
    tipo_trabajo
  )
  VALUES (
    p_id_orden,
    p_usuario_id,
    p_usuario_nombre,
    p_fecha,
    p_hora_inicio,
    p_hora_fin,
    v_tiempo_calculado,
    p_descripcion,
    p_tipo_trabajo
  )
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$;

-- Función para obtener tiempo de trabajo de una orden
CREATE OR REPLACE FUNCTION public.obtener_tiempo_trabajo_orden(
  p_id_orden integer
)
RETURNS TABLE (
  id integer,
  usuario_id integer,
  usuario_nombre varchar(100),
  fecha date,
  hora_inicio time,
  hora_fin time,
  tiempo_minutos integer,
  descripcion text,
  tipo_trabajo text,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    t.id,
    t.usuario_id,
    t.usuario_nombre,
    t.fecha,
    t.hora_inicio,
    t.hora_fin,
    t.tiempo_minutos,
    t.descripcion,
    t.tipo_trabajo,
    t.created_at
  FROM public.tiempo_trabajo t
  WHERE t.id_orden = p_id_orden
  ORDER BY t.fecha DESC, t.hora_inicio DESC;
END;
$$;

-- Función para obtener tiempo total de un usuario en un rango de fechas
CREATE OR REPLACE FUNCTION public.obtener_tiempo_usuario(
  p_usuario_id integer,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  fecha date,
  total_minutos integer,
  registros integer
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    t.fecha,
    SUM(t.tiempo_minutos)::integer as total_minutos,
    COUNT(*)::integer as registros
  FROM public.tiempo_trabajo t
  WHERE t.usuario_id = p_usuario_id
    AND (p_fecha_desde IS NULL OR t.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR t.fecha <= p_fecha_hasta)
    AND t.tiempo_minutos IS NOT NULL
  GROUP BY t.fecha
  ORDER BY t.fecha DESC;
END;
$$;

-- Comentarios
COMMENT ON TABLE public.tiempo_trabajo IS 'Registro de tiempo de trabajo por orden y usuario';
COMMENT ON FUNCTION public.iniciar_tiempo_trabajo IS 'Inicia un registro de tiempo de trabajo';
COMMENT ON FUNCTION public.finalizar_tiempo_trabajo IS 'Finaliza un registro de tiempo de trabajo';
COMMENT ON FUNCTION public.registrar_tiempo_manual IS 'Registra tiempo de trabajo manualmente';
COMMENT ON FUNCTION public.obtener_tiempo_trabajo_orden IS 'Obtiene todos los registros de tiempo de una orden';
COMMENT ON FUNCTION public.obtener_tiempo_usuario IS 'Obtiene el tiempo total de trabajo de un usuario';

