-- Crear tabla para historial de cambios de etapa en Metalúrgica
-- Incluye tracking de tiempo (fecha_inicio, fecha_fin)

BEGIN;

-- Tabla de historial de etapas
CREATE TABLE IF NOT EXISTS public.historial_etapas_metalurgica (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  etapa_anterior varchar(100),
  etapa_nueva varchar(100) NOT NULL,
  id_usuario integer REFERENCES public.usuarios(id),
  nombre_usuario varchar(255),
  comentario text,
  fecha_cambio timestamptz NOT NULL DEFAULT now(),
  fecha_inicio_etapa timestamptz NOT NULL DEFAULT now(),
  fecha_fin_etapa timestamptz,
  tiempo_en_etapa_seg integer -- Calculado automáticamente cuando se cambia de etapa
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_historial_etapas_metalurgica_orden 
ON public.historial_etapas_metalurgica(id_orden);

CREATE INDEX IF NOT EXISTS idx_historial_etapas_metalurgica_fecha 
ON public.historial_etapas_metalurgica(fecha_cambio DESC);

CREATE INDEX IF NOT EXISTS idx_historial_etapas_metalurgica_etapa 
ON public.historial_etapas_metalurgica(etapa_nueva);

-- Agregar campos de tiempo a ordenes_trabajo para la etapa actual
ALTER TABLE public.ordenes_trabajo
ADD COLUMN IF NOT EXISTS etapa_metalurgica_fecha_inicio timestamptz;

-- Función para obtener historial de etapas de una orden
CREATE OR REPLACE FUNCTION public.obtener_historial_etapas_metalurgica(p_id_orden integer)
RETURNS TABLE (
  id bigint,
  etapa_anterior varchar,
  etapa_nueva varchar,
  nombre_usuario varchar,
  comentario text,
  fecha_cambio timestamptz,
  fecha_inicio_etapa timestamptz,
  fecha_fin_etapa timestamptz,
  tiempo_en_etapa_seg integer,
  tiempo_formateado text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    h.id,
    h.etapa_anterior,
    h.etapa_nueva,
    h.nombre_usuario,
    h.comentario,
    h.fecha_cambio,
    h.fecha_inicio_etapa,
    h.fecha_fin_etapa,
    h.tiempo_en_etapa_seg,
    CASE 
      WHEN h.tiempo_en_etapa_seg IS NULL THEN 'En curso'
      WHEN h.tiempo_en_etapa_seg < 60 THEN h.tiempo_en_etapa_seg::text || ' seg'
      WHEN h.tiempo_en_etapa_seg < 3600 THEN (h.tiempo_en_etapa_seg / 60)::text || ' min'
      ELSE (h.tiempo_en_etapa_seg / 3600)::text || ' horas'
    END as tiempo_formateado
  FROM public.historial_etapas_metalurgica h
  WHERE h.id_orden = p_id_orden
  ORDER BY h.fecha_cambio DESC;
END;
$$;

COMMIT;

