-- Clientes que tienen acceso a Cuenta Corriente (Mostrador)
CREATE TABLE IF NOT EXISTS public.clientes_cuenta_corriente (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(id_cliente)
);

CREATE INDEX IF NOT EXISTS idx_clientes_cc_id_cliente ON public.clientes_cuenta_corriente(id_cliente);

COMMENT ON TABLE public.clientes_cuenta_corriente IS 'Clientes habilitados para Cuenta Corriente en Mostrador.';

ALTER TABLE public.clientes_cuenta_corriente ENABLE ROW LEVEL SECURITY;

CREATE POLICY "clientes_cc_select"
  ON public.clientes_cuenta_corriente FOR SELECT TO authenticated USING (true);

CREATE POLICY "clientes_cc_insert"
  ON public.clientes_cuenta_corriente FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "clientes_cc_delete"
  ON public.clientes_cuenta_corriente FOR DELETE TO authenticated USING (true);
