-- ============================================
-- SISTEMA DE SOLICITUDES Y PERMISOS
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE SOLICITUDES/PERMISOS
-- ============================================
CREATE TABLE IF NOT EXISTS public.solicitudes_permisos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo_solicitud varchar(50) NOT NULL, -- 'turno', 'ausencia', 'vacaciones', 'ropa', 'permiso', 'otro'
  titulo varchar(255) NOT NULL,
  descripcion text,
  fecha_solicitud date NOT NULL DEFAULT CURRENT_DATE,
  fecha_inicio date,
  fecha_fin date,
  dias_solicitados integer,
  estado varchar(50) DEFAULT 'pendiente', -- 'pendiente', 'aprobado', 'rechazado', 'cancelado'
  aprobado_por integer REFERENCES public.usuarios(id),
  fecha_aprobacion timestamptz,
  motivo_rechazo text,
  observaciones text,
  archivo_adjunto_url text, -- Para comprobantes, fotos, etc.
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_usuario ON public.solicitudes_permisos(id_usuario);
CREATE INDEX IF NOT EXISTS idx_solicitudes_estado ON public.solicitudes_permisos(estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_tipo ON public.solicitudes_permisos(tipo_solicitud);
CREATE INDEX IF NOT EXISTS idx_solicitudes_fecha ON public.solicitudes_permisos(fecha_solicitud);
CREATE INDEX IF NOT EXISTS idx_solicitudes_aprobador ON public.solicitudes_permisos(aprobado_por);

-- ============================================
-- 2. FUNCIONES PARA SOLICITUDES
-- ============================================

-- Crear solicitud
CREATE OR REPLACE FUNCTION public.crear_solicitud_permiso(
  p_id_usuario integer,
  p_tipo_solicitud varchar,
  p_titulo varchar,
  p_descripcion text DEFAULT NULL,
  p_fecha_solicitud date DEFAULT NULL,
  p_fecha_inicio date DEFAULT NULL,
  p_fecha_fin date DEFAULT NULL,
  p_dias_solicitados integer DEFAULT NULL,
  p_observaciones text DEFAULT NULL,
  p_archivo_adjunto_url text DEFAULT NULL
)
RETURNS public.solicitudes_permisos
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_solicitud_id integer;
  v_dias integer;
  v_result public.solicitudes_permisos;
BEGIN
  -- Calcular días si se proporcionan fechas
  IF p_fecha_inicio IS NOT NULL AND p_fecha_fin IS NOT NULL THEN
    v_dias := p_fecha_fin - p_fecha_inicio + 1;
  ELSE
    v_dias := p_dias_solicitados;
  END IF;

  INSERT INTO public.solicitudes_permisos (
    id_usuario, tipo_solicitud, titulo, descripcion, fecha_solicitud,
    fecha_inicio, fecha_fin, dias_solicitados, observaciones, archivo_adjunto_url
  )
  VALUES (
    p_id_usuario, p_tipo_solicitud, p_titulo, p_descripcion,
    COALESCE(p_fecha_solicitud, CURRENT_DATE),
    p_fecha_inicio, p_fecha_fin, v_dias, p_observaciones, p_archivo_adjunto_url
  )
  RETURNING id INTO v_solicitud_id;

  SELECT * INTO v_result FROM public.solicitudes_permisos WHERE id = v_solicitud_id;
  RETURN v_result;
END;
$$;

-- Listar solicitudes
CREATE OR REPLACE FUNCTION public.obtener_solicitudes_permisos(
  p_id_usuario integer DEFAULT NULL,
  p_estado varchar DEFAULT NULL,
  p_tipo_solicitud varchar DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_usuario integer,
  nombre_usuario varchar,
  tipo_solicitud varchar,
  titulo varchar,
  descripcion text,
  fecha_solicitud date,
  fecha_inicio date,
  fecha_fin date,
  dias_solicitados integer,
  estado varchar,
  aprobado_por integer,
  aprobado_por_nombre varchar,
  fecha_aprobacion timestamptz,
  motivo_rechazo text,
  observaciones text,
  archivo_adjunto_url text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    s.id,
    s.id_usuario,
    u.nombre::varchar AS nombre_usuario,
    s.tipo_solicitud,
    s.titulo,
    s.descripcion,
    s.fecha_solicitud,
    s.fecha_inicio,
    s.fecha_fin,
    s.dias_solicitados,
    s.estado,
    s.aprobado_por,
    u2.nombre::varchar AS aprobado_por_nombre,
    s.fecha_aprobacion,
    s.motivo_rechazo,
    s.observaciones,
    s.archivo_adjunto_url,
    s.created_at,
    s.updated_at
  FROM public.solicitudes_permisos s
  JOIN public.usuarios u ON u.id = s.id_usuario
  LEFT JOIN public.usuarios u2 ON u2.id = s.aprobado_por
  WHERE
    (p_id_usuario IS NULL OR s.id_usuario = p_id_usuario)
    AND (p_estado IS NULL OR s.estado = p_estado)
    AND (p_tipo_solicitud IS NULL OR s.tipo_solicitud = p_tipo_solicitud)
    AND (p_fecha_desde IS NULL OR s.fecha_solicitud >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR s.fecha_solicitud <= p_fecha_hasta)
  ORDER BY s.fecha_solicitud DESC, s.created_at DESC;
END;
$$;

-- Aprobar/Rechazar solicitud
CREATE OR REPLACE FUNCTION public.aprobar_rechazar_solicitud(
  p_id integer,
  p_estado varchar,
  p_id_aprobador integer,
  p_motivo_rechazo text DEFAULT NULL,
  p_observaciones text DEFAULT NULL
)
RETURNS public.solicitudes_permisos
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.solicitudes_permisos;
BEGIN
  UPDATE public.solicitudes_permisos
  SET
    estado = p_estado,
    aprobado_por = p_id_aprobador,
    fecha_aprobacion = CASE WHEN p_estado = 'aprobado' THEN now() ELSE NULL END,
    motivo_rechazo = CASE WHEN p_estado = 'rechazado' THEN p_motivo_rechazo ELSE NULL END,
    observaciones = COALESCE(p_observaciones, observaciones),
    updated_at = now()
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.solicitudes_permisos WHERE id = p_id;
  RETURN v_result;
END;
$$;

-- Cancelar solicitud (solo el usuario que la creó)
CREATE OR REPLACE FUNCTION public.cancelar_solicitud(
  p_id integer,
  p_id_usuario integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.solicitudes_permisos
  SET
    estado = 'cancelado',
    updated_at = now()
  WHERE id = p_id AND id_usuario = p_id_usuario AND estado = 'pendiente';

  RETURN FOUND;
END;
$$;

-- Eliminar solicitud
CREATE OR REPLACE FUNCTION public.eliminar_solicitud(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.solicitudes_permisos WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ============================================
-- 3. RLS POLICIES
-- ============================================

ALTER TABLE public.solicitudes_permisos ENABLE ROW LEVEL SECURITY;

-- Políticas para solicitudes_permisos
CREATE POLICY "Enable read access for authenticated users" ON public.solicitudes_permisos
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.solicitudes_permisos
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.solicitudes_permisos
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.solicitudes_permisos
  FOR DELETE USING (true);

COMMIT;

