-- Tabla de checklist con cronómetro por ficha

BEGIN;

CREATE TABLE IF NOT EXISTS public.tarea_subitems (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  titulo text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  duracion_estimada_min integer NOT NULL DEFAULT 15,
  tiempo_invertido_seg integer NOT NULL DEFAULT 0,
  iniciado_en timestamptz,
  completado_en timestamptz,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tarea_subitems_orden ON public.tarea_subitems(id_orden);

-- Trigger de updated_at
CREATE OR REPLACE FUNCTION public.tarea_subitems_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.actualizado_en = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_tarea_subitems_set_updated_at ON public.tarea_subitems;
CREATE TRIGGER trg_tarea_subitems_set_updated_at
BEFORE UPDATE ON public.tarea_subitems
FOR EACH ROW
EXECUTE FUNCTION public.tarea_subitems_set_updated_at();

COMMIT;

