-- Sistema CRM de Ventas
-- Integrado con OPs, ventas y stock
-- Acceso: mostrador y admin

BEGIN;

-- ============================================
-- 1. TABLA DE OPORTUNIDADES DE VENTA
-- ============================================
CREATE TABLE IF NOT EXISTS public.oportunidades_venta (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_oportunidad varchar(50) NOT NULL UNIQUE,
  cliente_nombre varchar(255) NOT NULL,
  cliente_telefono varchar(50),
  cliente_email varchar(255),
  cliente_dni_cuit varchar(50),
  cliente_empresa varchar(255),
  cliente_direccion text,
  descripcion text,
  valor_estimado numeric(10,2),
  probabilidad_cierre integer DEFAULT 50 CHECK (probabilidad_cierre >= 0 AND probabilidad_cierre <= 100),
  etapa varchar(50) NOT NULL DEFAULT 'Prospecto' CHECK (
    etapa IN ('Prospecto', 'Calificación', 'Propuesta', 'Negociación', 'Cerrado', 'Perdido')
  ),
  fecha_cierre_estimada date,
  id_vendedor integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_vendedor varchar(100) NOT NULL,
  id_op integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  numero_op varchar(255),
  observaciones text,
  activo boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_oportunidades_vendedor ON public.oportunidades_venta(id_vendedor);
CREATE INDEX IF NOT EXISTS idx_oportunidades_etapa ON public.oportunidades_venta(etapa);
CREATE INDEX IF NOT EXISTS idx_oportunidades_cliente ON public.oportunidades_venta(cliente_nombre);
CREATE INDEX IF NOT EXISTS idx_oportunidades_fecha_cierre ON public.oportunidades_venta(fecha_cierre_estimada);
CREATE INDEX IF NOT EXISTS idx_oportunidades_activo ON public.oportunidades_venta(activo);
CREATE INDEX IF NOT EXISTS idx_oportunidades_op ON public.oportunidades_venta(id_op);

-- ============================================
-- 2. TABLA DE VENTAS CONCRETADAS
-- ============================================
CREATE TABLE IF NOT EXISTS public.ventas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_venta varchar(50) NOT NULL UNIQUE,
  id_oportunidad integer REFERENCES public.oportunidades_venta(id) ON DELETE SET NULL,
  cliente_nombre varchar(255) NOT NULL,
  cliente_telefono varchar(50),
  cliente_email varchar(255),
  cliente_dni_cuit varchar(50),
  cliente_empresa varchar(255),
  cliente_direccion text,
  id_op integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  numero_op varchar(255) NOT NULL,
  valor_total numeric(10,2) NOT NULL,
  metodo_pago varchar(50) CHECK (
    metodo_pago IN ('Efectivo', 'Transferencia', 'Tarjeta', 'Cheque', 'Cuenta Corriente', 'Otro')
  ),
  estado_pago varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
    estado_pago IN ('Pendiente', 'Parcial', 'Pagado', 'Cancelado')
  ),
  fecha_venta date NOT NULL DEFAULT CURRENT_DATE,
  id_vendedor integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_vendedor varchar(100) NOT NULL,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ventas_oportunidad ON public.ventas(id_oportunidad);
CREATE INDEX IF NOT EXISTS idx_ventas_op ON public.ventas(id_op);
CREATE INDEX IF NOT EXISTS idx_ventas_vendedor ON public.ventas(id_vendedor);
CREATE INDEX IF NOT EXISTS idx_ventas_fecha ON public.ventas(fecha_venta);
CREATE INDEX IF NOT EXISTS idx_ventas_estado_pago ON public.ventas(estado_pago);
CREATE INDEX IF NOT EXISTS idx_ventas_cliente ON public.ventas(cliente_nombre);

-- ============================================
-- 3. TABLA DE SEGUIMIENTOS DE OPORTUNIDADES
-- ============================================
CREATE TABLE IF NOT EXISTS public.seguimientos_venta (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_oportunidad integer NOT NULL REFERENCES public.oportunidades_venta(id) ON DELETE CASCADE,
  tipo_seguimiento varchar(50) NOT NULL CHECK (
    tipo_seguimiento IN ('Llamada', 'Email', 'Reunión', 'WhatsApp', 'Visita', 'Propuesta', 'Otro')
  ),
  descripcion text NOT NULL,
  fecha_seguimiento timestamptz NOT NULL DEFAULT now(),
  proxima_accion text,
  fecha_proxima_accion date,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_usuario varchar(100) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_seguimientos_oportunidad ON public.seguimientos_venta(id_oportunidad);
CREATE INDEX IF NOT EXISTS idx_seguimientos_fecha ON public.seguimientos_venta(fecha_seguimiento);
CREATE INDEX IF NOT EXISTS idx_seguimientos_usuario ON public.seguimientos_venta(id_usuario);

-- ============================================
-- 4. TABLA DE ITEMS DE VENTA
-- ============================================
CREATE TABLE IF NOT EXISTS public.ventas_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta integer NOT NULL REFERENCES public.ventas(id) ON DELETE CASCADE,
  id_articulo_stock integer, -- ID del artículo en la base de stock
  codigo_articulo varchar(100),
  descripcion text NOT NULL,
  cantidad numeric(10,3) NOT NULL DEFAULT 1.000,
  precio_unitario numeric(10,2) NOT NULL,
  precio_total numeric(10,2) NOT NULL,
  descuento numeric(10,2) DEFAULT 0,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ventas_items_venta ON public.ventas_items(id_venta);
CREATE INDEX IF NOT EXISTS idx_ventas_items_articulo ON public.ventas_items(id_articulo_stock);

-- ============================================
-- 5. FUNCIONES SQL
-- ============================================

-- Función para crear oportunidad de venta
CREATE OR REPLACE FUNCTION public.crear_oportunidad_venta(
  p_cliente_nombre varchar(255),
  p_cliente_telefono varchar(50) DEFAULT NULL,
  p_cliente_email varchar(255) DEFAULT NULL,
  p_cliente_dni_cuit varchar(50) DEFAULT NULL,
  p_cliente_empresa varchar(255) DEFAULT NULL,
  p_cliente_direccion text DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_valor_estimado numeric(10,2) DEFAULT NULL,
  p_probabilidad_cierre integer DEFAULT 50,
  p_etapa varchar(50) DEFAULT 'Prospecto',
  p_fecha_cierre_estimada date DEFAULT NULL,
  p_id_vendedor integer,
  p_nombre_vendedor varchar(100),
  p_observaciones text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
  v_numero_oportunidad varchar(50);
  v_result json;
BEGIN
  -- Generar número de oportunidad
  v_numero_oportunidad := 'OPP-' || TO_CHAR(now(), 'YYYYMMDD') || '-' || LPAD(
    (COALESCE((SELECT MAX(id) FROM public.oportunidades_venta), 0) + 1)::text,
    4,
    '0'
  );

  -- Insertar oportunidad
  INSERT INTO public.oportunidades_venta (
    numero_oportunidad,
    cliente_nombre,
    cliente_telefono,
    cliente_email,
    cliente_dni_cuit,
    cliente_empresa,
    cliente_direccion,
    descripcion,
    valor_estimado,
    probabilidad_cierre,
    etapa,
    fecha_cierre_estimada,
    id_vendedor,
    nombre_vendedor,
    observaciones
  ) VALUES (
    v_numero_oportunidad,
    p_cliente_nombre,
    p_cliente_telefono,
    p_cliente_email,
    p_cliente_dni_cuit,
    p_cliente_empresa,
    p_cliente_direccion,
    p_descripcion,
    p_valor_estimado,
    p_probabilidad_cierre,
    p_etapa,
    p_fecha_cierre_estimada,
    p_id_vendedor,
    p_nombre_vendedor,
    p_observaciones
  ) RETURNING id INTO v_id;

  -- Retornar resultado
  SELECT json_build_object(
    'success', true,
    'data', json_build_object(
      'id', v_id,
      'numero_oportunidad', v_numero_oportunidad
    )
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- Función para actualizar oportunidad de venta
CREATE OR REPLACE FUNCTION public.actualizar_oportunidad_venta(
  p_id integer,
  p_cliente_nombre varchar(255) DEFAULT NULL,
  p_cliente_telefono varchar(50) DEFAULT NULL,
  p_cliente_email varchar(255) DEFAULT NULL,
  p_cliente_dni_cuit varchar(50) DEFAULT NULL,
  p_cliente_empresa varchar(255) DEFAULT NULL,
  p_cliente_direccion text DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_valor_estimado numeric(10,2) DEFAULT NULL,
  p_probabilidad_cierre integer DEFAULT NULL,
  p_etapa varchar(50) DEFAULT NULL,
  p_fecha_cierre_estimada date DEFAULT NULL,
  p_id_op integer DEFAULT NULL,
  p_numero_op varchar(255) DEFAULT NULL,
  p_observaciones text DEFAULT NULL,
  p_activo boolean DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result json;
BEGIN
  UPDATE public.oportunidades_venta
  SET
    cliente_nombre = COALESCE(p_cliente_nombre, cliente_nombre),
    cliente_telefono = COALESCE(p_cliente_telefono, cliente_telefono),
    cliente_email = COALESCE(p_cliente_email, cliente_email),
    cliente_dni_cuit = COALESCE(p_cliente_dni_cuit, cliente_dni_cuit),
    cliente_empresa = COALESCE(p_cliente_empresa, cliente_empresa),
    cliente_direccion = COALESCE(p_cliente_direccion, cliente_direccion),
    descripcion = COALESCE(p_descripcion, descripcion),
    valor_estimado = COALESCE(p_valor_estimado, valor_estimado),
    probabilidad_cierre = COALESCE(p_probabilidad_cierre, probabilidad_cierre),
    etapa = COALESCE(p_etapa, etapa),
    fecha_cierre_estimada = COALESCE(p_fecha_cierre_estimada, fecha_cierre_estimada),
    id_op = COALESCE(p_id_op, id_op),
    numero_op = COALESCE(p_numero_op, numero_op),
    observaciones = COALESCE(p_observaciones, observaciones),
    activo = COALESCE(p_activo, activo),
    updated_at = now()
  WHERE id = p_id;

  SELECT json_build_object('success', true) INTO v_result;
  RETURN v_result;
END;
$$;

-- Función para crear seguimiento
CREATE OR REPLACE FUNCTION public.crear_seguimiento_venta(
  p_id_oportunidad integer,
  p_tipo_seguimiento varchar(50),
  p_descripcion text,
  p_proxima_accion text DEFAULT NULL,
  p_fecha_proxima_accion date DEFAULT NULL,
  p_id_usuario integer,
  p_nombre_usuario varchar(100)
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
  v_result json;
BEGIN
  INSERT INTO public.seguimientos_venta (
    id_oportunidad,
    tipo_seguimiento,
    descripcion,
    proxima_accion,
    fecha_proxima_accion,
    id_usuario,
    nombre_usuario
  ) VALUES (
    p_id_oportunidad,
    p_tipo_seguimiento,
    p_descripcion,
    p_proxima_accion,
    p_fecha_proxima_accion,
    p_id_usuario,
    p_nombre_usuario
  ) RETURNING id INTO v_id;

  SELECT json_build_object(
    'success', true,
    'data', json_build_object('id', v_id)
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- Función para crear venta desde oportunidad
CREATE OR REPLACE FUNCTION public.crear_venta_desde_oportunidad(
  p_id_oportunidad integer,
  p_id_op integer,
  p_numero_op varchar(255),
  p_valor_total numeric(10,2),
  p_metodo_pago varchar(50) DEFAULT NULL,
  p_estado_pago varchar(50) DEFAULT 'Pendiente',
  p_fecha_venta date DEFAULT CURRENT_DATE,
  p_id_vendedor integer,
  p_nombre_vendedor varchar(100),
  p_observaciones text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
  v_numero_venta varchar(50);
  v_oportunidad record;
  v_result json;
BEGIN
  -- Obtener datos de la oportunidad
  SELECT * INTO v_oportunidad
  FROM public.oportunidades_venta
  WHERE id = p_id_oportunidad;

  IF NOT FOUND THEN
    SELECT json_build_object(
      'success', false,
      'error', 'Oportunidad no encontrada'
    ) INTO v_result;
    RETURN v_result;
  END IF;

  -- Generar número de venta
  v_numero_venta := 'VENT-' || TO_CHAR(now(), 'YYYYMMDD') || '-' || LPAD(
    (COALESCE((SELECT MAX(id) FROM public.ventas), 0) + 1)::text,
    4,
    '0'
  );

  -- Crear venta
  INSERT INTO public.ventas (
    numero_venta,
    id_oportunidad,
    cliente_nombre,
    cliente_telefono,
    cliente_email,
    cliente_dni_cuit,
    cliente_empresa,
    cliente_direccion,
    id_op,
    numero_op,
    valor_total,
    metodo_pago,
    estado_pago,
    fecha_venta,
    id_vendedor,
    nombre_vendedor,
    observaciones
  ) VALUES (
    v_numero_venta,
    p_id_oportunidad,
    v_oportunidad.cliente_nombre,
    v_oportunidad.cliente_telefono,
    v_oportunidad.cliente_email,
    v_oportunidad.cliente_dni_cuit,
    v_oportunidad.cliente_empresa,
    v_oportunidad.cliente_direccion,
    p_id_op,
    p_numero_op,
    p_valor_total,
    p_metodo_pago,
    p_estado_pago,
    p_fecha_venta,
    p_id_vendedor,
    p_nombre_vendedor,
    p_observaciones
  ) RETURNING id INTO v_id;

  -- Actualizar oportunidad a etapa "Cerrado"
  UPDATE public.oportunidades_venta
  SET etapa = 'Cerrado',
      id_op = p_id_op,
      numero_op = p_numero_op,
      updated_at = now()
  WHERE id = p_id_oportunidad;

  SELECT json_build_object(
    'success', true,
    'data', json_build_object(
      'id', v_id,
      'numero_venta', v_numero_venta
    )
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- Función para obtener oportunidades con seguimientos
CREATE OR REPLACE FUNCTION public.obtener_oportunidades_venta(
  p_id_vendedor integer DEFAULT NULL,
  p_etapa varchar(50) DEFAULT NULL,
  p_activo boolean DEFAULT true
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result json;
BEGIN
  SELECT json_agg(
    json_build_object(
      'id', o.id,
      'numero_oportunidad', o.numero_oportunidad,
      'cliente_nombre', o.cliente_nombre,
      'cliente_telefono', o.cliente_telefono,
      'cliente_email', o.cliente_email,
      'cliente_dni_cuit', o.cliente_dni_cuit,
      'cliente_empresa', o.cliente_empresa,
      'cliente_direccion', o.cliente_direccion,
      'descripcion', o.descripcion,
      'valor_estimado', o.valor_estimado,
      'probabilidad_cierre', o.probabilidad_cierre,
      'etapa', o.etapa,
      'fecha_cierre_estimada', o.fecha_cierre_estimada,
      'id_vendedor', o.id_vendedor,
      'nombre_vendedor', o.nombre_vendedor,
      'id_op', o.id_op,
      'numero_op', o.numero_op,
      'observaciones', o.observaciones,
      'activo', o.activo,
      'created_at', o.created_at,
      'updated_at', o.updated_at,
      'seguimientos', (
        SELECT json_agg(
          json_build_object(
            'id', s.id,
            'tipo_seguimiento', s.tipo_seguimiento,
            'descripcion', s.descripcion,
            'fecha_seguimiento', s.fecha_seguimiento,
            'proxima_accion', s.proxima_accion,
            'fecha_proxima_accion', s.fecha_proxima_accion,
            'nombre_usuario', s.nombre_usuario,
            'created_at', s.created_at
          )
        )
        FROM public.seguimientos_venta s
        WHERE s.id_oportunidad = o.id
        ORDER BY s.fecha_seguimiento DESC
      )
    )
  ) INTO v_result
  FROM public.oportunidades_venta o
  WHERE (p_id_vendedor IS NULL OR o.id_vendedor = p_id_vendedor)
    AND (p_etapa IS NULL OR o.etapa = p_etapa)
    AND (p_activo IS NULL OR o.activo = p_activo)
  ORDER BY o.created_at DESC;

  RETURN COALESCE(v_result, '[]'::json);
END;
$$;

-- Función para obtener ventas
CREATE OR REPLACE FUNCTION public.obtener_ventas(
  p_id_vendedor integer DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL,
  p_estado_pago varchar(50) DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result json;
BEGIN
  SELECT json_agg(
    json_build_object(
      'id', v.id,
      'numero_venta', v.numero_venta,
      'id_oportunidad', v.id_oportunidad,
      'cliente_nombre', v.cliente_nombre,
      'cliente_telefono', v.cliente_telefono,
      'cliente_email', v.cliente_email,
      'cliente_dni_cuit', v.cliente_dni_cuit,
      'cliente_empresa', v.cliente_empresa,
      'cliente_direccion', v.cliente_direccion,
      'id_op', v.id_op,
      'numero_op', v.numero_op,
      'valor_total', v.valor_total,
      'metodo_pago', v.metodo_pago,
      'estado_pago', v.estado_pago,
      'fecha_venta', v.fecha_venta,
      'id_vendedor', v.id_vendedor,
      'nombre_vendedor', v.nombre_vendedor,
      'observaciones', v.observaciones,
      'created_at', v.created_at,
      'updated_at', v.updated_at,
      'items', (
        SELECT json_agg(
          json_build_object(
            'id', vi.id,
            'codigo_articulo', vi.codigo_articulo,
            'descripcion', vi.descripcion,
            'cantidad', vi.cantidad,
            'precio_unitario', vi.precio_unitario,
            'precio_total', vi.precio_total,
            'descuento', vi.descuento,
            'observaciones', vi.observaciones
          )
        )
        FROM public.ventas_items vi
        WHERE vi.id_venta = v.id
      )
    )
  ) INTO v_result
  FROM public.ventas v
  WHERE (p_id_vendedor IS NULL OR v.id_vendedor = p_id_vendedor)
    AND (p_fecha_desde IS NULL OR v.fecha_venta >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR v.fecha_venta <= p_fecha_hasta)
    AND (p_estado_pago IS NULL OR v.estado_pago = p_estado_pago)
  ORDER BY v.fecha_venta DESC, v.created_at DESC;

  RETURN COALESCE(v_result, '[]'::json);
END;
$$;

-- Función para agregar item a una venta
CREATE OR REPLACE FUNCTION public.agregar_item_venta(
  p_id_venta integer,
  p_id_articulo_stock integer DEFAULT NULL,
  p_codigo_articulo varchar(100) DEFAULT NULL,
  p_descripcion text,
  p_cantidad numeric(10,3) DEFAULT 1.000,
  p_precio_unitario numeric(10,2),
  p_descuento numeric(10,2) DEFAULT 0,
  p_observaciones text DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
  v_precio_total numeric(10,2);
  v_result json;
BEGIN
  -- Calcular precio total
  v_precio_total := (p_precio_unitario * p_cantidad) - COALESCE(p_descuento, 0);

  -- Insertar item
  INSERT INTO public.ventas_items (
    id_venta,
    id_articulo_stock,
    codigo_articulo,
    descripcion,
    cantidad,
    precio_unitario,
    precio_total,
    descuento,
    observaciones
  ) VALUES (
    p_id_venta,
    p_id_articulo_stock,
    p_codigo_articulo,
    p_descripcion,
    p_cantidad,
    p_precio_unitario,
    v_precio_total,
    p_descuento,
    p_observaciones
  ) RETURNING id INTO v_id;

  -- Actualizar valor total de la venta
  UPDATE public.ventas
  SET valor_total = (
    SELECT COALESCE(SUM(precio_total), 0)
    FROM public.ventas_items
    WHERE id_venta = p_id_venta
  ),
  updated_at = now()
  WHERE id = p_id_venta;

  SELECT json_build_object(
    'success', true,
    'data', json_build_object('id', v_id)
  ) INTO v_result;

  RETURN v_result;
END;
$$;

-- Función para eliminar item de una venta
CREATE OR REPLACE FUNCTION public.eliminar_item_venta(
  p_id_item integer
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id_venta integer;
  v_result json;
BEGIN
  -- Obtener id_venta antes de eliminar
  SELECT id_venta INTO v_id_venta
  FROM public.ventas_items
  WHERE id = p_id_item;

  IF NOT FOUND THEN
    SELECT json_build_object(
      'success', false,
      'error', 'Item no encontrado'
    ) INTO v_result;
    RETURN v_result;
  END IF;

  -- Eliminar item
  DELETE FROM public.ventas_items
  WHERE id = p_id_item;

  -- Actualizar valor total de la venta
  UPDATE public.ventas
  SET valor_total = (
    SELECT COALESCE(SUM(precio_total), 0)
    FROM public.ventas_items
    WHERE id_venta = v_id_venta
  ),
  updated_at = now()
  WHERE id = v_id_venta;

  SELECT json_build_object('success', true) INTO v_result;
  RETURN v_result;
END;
$$;

-- ============================================
-- 6. RLS POLICIES
-- ============================================
-- Nota: Las funciones SQL ya validan permisos con SECURITY DEFINER
-- Las políticas RLS permiten acceso a todos los usuarios autenticados
-- La validación de roles se hace en las funciones

-- Habilitar RLS
ALTER TABLE public.oportunidades_venta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seguimientos_venta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ventas_items ENABLE ROW LEVEL SECURITY;

-- Políticas permisivas (las funciones SQL validan los permisos)
CREATE POLICY "Permitir acceso a oportunidades para usuarios autenticados"
  ON public.oportunidades_venta
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Permitir acceso a ventas para usuarios autenticados"
  ON public.ventas
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Permitir acceso a seguimientos para usuarios autenticados"
  ON public.seguimientos_venta
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Permitir acceso a items de venta para usuarios autenticados"
  ON public.ventas_items
  FOR ALL
  USING (true)
  WITH CHECK (true);

COMMIT;

