-- Crear tabla para datos completos de legajo de empleados
-- Esta tabla almacena información adicional de cada usuario/empleado

BEGIN;

-- Tabla de legajos de empleados
CREATE TABLE IF NOT EXISTS public.legajos_empleados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL UNIQUE REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre varchar(255),
  apellido varchar(255),
  telefono varchar(50),
  ubicacion text,
  foto_url text, -- URL de la foto almacenada en Supabase Storage
  sector varchar(100),
  funciones text, -- Descripción de funciones del empleado
  fecha_ingreso date,
  fecha_nacimiento date,
  dni varchar(20),
  direccion text,
  email varchar(255),
  estado_civil varchar(50),
  contacto_emergencia_nombre varchar(255),
  contacto_emergencia_telefono varchar(50),
  observaciones text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Índices para búsquedas rápidas
CREATE INDEX IF NOT EXISTS idx_legajos_usuario ON public.legajos_empleados(id_usuario);
CREATE INDEX IF NOT EXISTS idx_legajos_sector ON public.legajos_empleados(sector);
CREATE INDEX IF NOT EXISTS idx_legajos_fecha_ingreso ON public.legajos_empleados(fecha_ingreso);

-- Función para obtener legajo completo de un usuario
CREATE OR REPLACE FUNCTION public.obtener_legajo_empleado(p_id_usuario integer)
RETURNS TABLE (
  id integer,
  id_usuario integer,
  nombre varchar,
  apellido varchar,
  telefono varchar,
  ubicacion text,
  foto_url text,
  sector varchar,
  funciones text,
  fecha_ingreso date,
  fecha_nacimiento date,
  dni varchar,
  direccion text,
  email varchar,
  estado_civil varchar,
  contacto_emergencia_nombre varchar,
  contacto_emergencia_telefono varchar,
  observaciones text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    l.id,
    l.id_usuario,
    l.nombre,
    l.apellido,
    l.telefono,
    l.ubicacion,
    l.foto_url,
    l.sector,
    l.funciones,
    l.fecha_ingreso,
    l.fecha_nacimiento,
    l.dni,
    l.direccion,
    l.email,
    l.estado_civil,
    l.contacto_emergencia_nombre,
    l.contacto_emergencia_telefono,
    l.observaciones,
    l.created_at,
    l.updated_at
  FROM public.legajos_empleados l
  WHERE l.id_usuario = p_id_usuario
  LIMIT 1;
END;
$$;

-- Función para crear o actualizar legajo de empleado
CREATE OR REPLACE FUNCTION public.crear_actualizar_legajo(
  p_id_usuario integer,
  p_nombre varchar DEFAULT NULL,
  p_apellido varchar DEFAULT NULL,
  p_telefono varchar DEFAULT NULL,
  p_ubicacion text DEFAULT NULL,
  p_foto_url text DEFAULT NULL,
  p_sector varchar DEFAULT NULL,
  p_funciones text DEFAULT NULL,
  p_fecha_ingreso date DEFAULT NULL,
  p_fecha_nacimiento date DEFAULT NULL,
  p_dni varchar DEFAULT NULL,
  p_direccion text DEFAULT NULL,
  p_email varchar DEFAULT NULL,
  p_estado_civil varchar DEFAULT NULL,
  p_contacto_emergencia_nombre varchar DEFAULT NULL,
  p_contacto_emergencia_telefono varchar DEFAULT NULL,
  p_observaciones text DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_usuario integer,
  nombre varchar,
  apellido varchar,
  telefono varchar,
  ubicacion text,
  foto_url text,
  sector varchar,
  funciones text,
  fecha_ingreso date
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  legajo_id integer;
BEGIN
  -- Verificar que el usuario existe
  IF NOT EXISTS (SELECT 1 FROM public.usuarios WHERE id = p_id_usuario) THEN
    RAISE EXCEPTION 'Usuario con ID % no encontrado', p_id_usuario;
  END IF;

  -- Intentar actualizar si existe
  UPDATE public.legajos_empleados
  SET
    nombre = COALESCE(p_nombre, nombre),
    apellido = COALESCE(p_apellido, apellido),
    telefono = COALESCE(p_telefono, telefono),
    ubicacion = COALESCE(p_ubicacion, ubicacion),
    foto_url = COALESCE(p_foto_url, foto_url),
    sector = COALESCE(p_sector, sector),
    funciones = COALESCE(p_funciones, funciones),
    fecha_ingreso = COALESCE(p_fecha_ingreso, fecha_ingreso),
    fecha_nacimiento = COALESCE(p_fecha_nacimiento, fecha_nacimiento),
    dni = COALESCE(p_dni, dni),
    direccion = COALESCE(p_direccion, direccion),
    email = COALESCE(p_email, email),
    estado_civil = COALESCE(p_estado_civil, estado_civil),
    contacto_emergencia_nombre = COALESCE(p_contacto_emergencia_nombre, contacto_emergencia_nombre),
    contacto_emergencia_telefono = COALESCE(p_contacto_emergencia_telefono, contacto_emergencia_telefono),
    observaciones = COALESCE(p_observaciones, observaciones),
    updated_at = now()
  WHERE id_usuario = p_id_usuario
  RETURNING id INTO legajo_id;

  -- Si no existe, crear nuevo legajo
  IF NOT FOUND THEN
    INSERT INTO public.legajos_empleados (
      id_usuario,
      nombre,
      apellido,
      telefono,
      ubicacion,
      foto_url,
      sector,
      funciones,
      fecha_ingreso,
      fecha_nacimiento,
      dni,
      direccion,
      email,
      estado_civil,
      contacto_emergencia_nombre,
      contacto_emergencia_telefono,
      observaciones
    ) VALUES (
      p_id_usuario,
      p_nombre,
      p_apellido,
      p_telefono,
      p_ubicacion,
      p_foto_url,
      p_sector,
      p_funciones,
      p_fecha_ingreso,
      p_fecha_nacimiento,
      p_dni,
      p_direccion,
      p_email,
      p_estado_civil,
      p_contacto_emergencia_nombre,
      p_contacto_emergencia_telefono,
      p_observaciones
    )
    RETURNING id INTO legajo_id;
  END IF;

  -- Retornar datos actualizados
  RETURN QUERY
  SELECT
    l.id,
    l.id_usuario,
    l.nombre,
    l.apellido,
    l.telefono,
    l.ubicacion,
    l.foto_url,
    l.sector,
    l.funciones,
    l.fecha_ingreso
  FROM public.legajos_empleados l
  WHERE l.id = legajo_id;
END;
$$;

COMMENT ON TABLE public.legajos_empleados IS
'Tabla que almacena información completa del legajo de cada empleado/usuario del sistema.';

COMMENT ON FUNCTION public.obtener_legajo_empleado IS
'Obtiene todos los datos del legajo de un empleado por su ID de usuario.';

COMMENT ON FUNCTION public.crear_actualizar_legajo IS
'Crea o actualiza el legajo completo de un empleado. Si el legajo existe, lo actualiza; si no existe, lo crea.';

COMMIT;

