-- ============================================
-- SISTEMA DE EVALUACIONES DE DESEMPEÑO
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE EVALUACIONES
-- ============================================
CREATE TABLE IF NOT EXISTS public.evaluaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_evaluado integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_usuario_evaluador integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo_evaluacion varchar(50) NOT NULL DEFAULT 'anual', -- 'anual', 'semestral', 'trimestral', 'mensual', 'periodo_prueba', 'especial'
  periodo_evaluacion varchar(100) NOT NULL, -- Ej: "2024", "Q1 2024", "Enero 2024"
  fecha_evaluacion date NOT NULL DEFAULT CURRENT_DATE,
  fecha_inicio_periodo date,
  fecha_fin_periodo date,
  calificacion_general numeric(4,2), -- Calificación promedio (0-10 o 0-100)
  estado varchar(50) DEFAULT 'borrador', -- 'borrador', 'completada', 'revisada', 'aprobada'
  comentarios_evaluador text,
  comentarios_evaluado text,
  objetivos_cumplidos text,
  areas_mejora text,
  recomendaciones text,
  aprobado_por integer REFERENCES public.usuarios(id),
  fecha_aprobacion timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_evaluaciones_evaluado ON public.evaluaciones(id_usuario_evaluado);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_evaluador ON public.evaluaciones(id_usuario_evaluador);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_estado ON public.evaluaciones(estado);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_fecha ON public.evaluaciones(fecha_evaluacion);
CREATE INDEX IF NOT EXISTS idx_evaluaciones_tipo ON public.evaluaciones(tipo_evaluacion);

-- ============================================
-- 2. TABLA DE CRITERIOS DE EVALUACIÓN
-- ============================================
CREATE TABLE IF NOT EXISTS public.evaluaciones_criterios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_evaluacion integer NOT NULL REFERENCES public.evaluaciones(id) ON DELETE CASCADE,
  criterio varchar(255) NOT NULL, -- Ej: "Puntualidad", "Trabajo en equipo", "Calidad del trabajo"
  descripcion text,
  calificacion numeric(4,2) NOT NULL, -- Calificación del criterio (0-10 o 0-100)
  peso numeric(4,2) DEFAULT 1.0, -- Peso del criterio en la calificación general
  comentarios text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_criterios_evaluacion ON public.evaluaciones_criterios(id_evaluacion);

-- ============================================
-- 3. FUNCIONES PARA EVALUACIONES
-- ============================================

-- Crear evaluación
CREATE OR REPLACE FUNCTION public.crear_evaluacion(
  p_id_usuario_evaluado integer,
  p_id_usuario_evaluador integer,
  p_tipo_evaluacion varchar,
  p_periodo_evaluacion varchar,
  p_fecha_evaluacion date DEFAULT NULL,
  p_fecha_inicio_periodo date DEFAULT NULL,
  p_fecha_fin_periodo date DEFAULT NULL,
  p_comentarios_evaluador text DEFAULT NULL,
  p_objetivos_cumplidos text DEFAULT NULL,
  p_areas_mejora text DEFAULT NULL,
  p_recomendaciones text DEFAULT NULL
)
RETURNS public.evaluaciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_evaluacion_id integer;
  v_result public.evaluaciones;
BEGIN
  INSERT INTO public.evaluaciones (
    id_usuario_evaluado, id_usuario_evaluador, tipo_evaluacion, periodo_evaluacion,
    fecha_evaluacion, fecha_inicio_periodo, fecha_fin_periodo,
    comentarios_evaluador, objetivos_cumplidos, areas_mejora, recomendaciones
  )
  VALUES (
    p_id_usuario_evaluado, p_id_usuario_evaluador, p_tipo_evaluacion, p_periodo_evaluacion,
    COALESCE(p_fecha_evaluacion, CURRENT_DATE),
    p_fecha_inicio_periodo, p_fecha_fin_periodo,
    p_comentarios_evaluador, p_objetivos_cumplidos, p_areas_mejora, p_recomendaciones
  )
  RETURNING id INTO v_evaluacion_id;

  SELECT * INTO v_result FROM public.evaluaciones WHERE id = v_evaluacion_id;
  RETURN v_result;
END;
$$;

-- Agregar criterio a evaluación
CREATE OR REPLACE FUNCTION public.agregar_criterio_evaluacion(
  p_id_evaluacion integer,
  p_criterio varchar,
  p_calificacion numeric,
  p_descripcion text DEFAULT NULL,
  p_peso numeric DEFAULT 1.0,
  p_comentarios text DEFAULT NULL
)
RETURNS public.evaluaciones_criterios
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.evaluaciones_criterios;
BEGIN
  INSERT INTO public.evaluaciones_criterios (
    id_evaluacion, criterio, descripcion, calificacion, peso, comentarios
  )
  VALUES (
    p_id_evaluacion, p_criterio, p_descripcion, p_calificacion, p_peso, p_comentarios
  )
  RETURNING * INTO v_result;

  -- Actualizar calificación general de la evaluación
  UPDATE public.evaluaciones
  SET calificacion_general = (
    SELECT COALESCE(SUM(calificacion * peso) / NULLIF(SUM(peso), 0), 0)
    FROM public.evaluaciones_criterios
    WHERE id_evaluacion = p_id_evaluacion
  ),
  updated_at = now()
  WHERE id = p_id_evaluacion;

  RETURN v_result;
END;
$$;

-- Actualizar criterio
CREATE OR REPLACE FUNCTION public.actualizar_criterio_evaluacion(
  p_id integer,
  p_criterio varchar DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_calificacion numeric DEFAULT NULL,
  p_peso numeric DEFAULT NULL,
  p_comentarios text DEFAULT NULL
)
RETURNS public.evaluaciones_criterios
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id_evaluacion integer;
  v_result public.evaluaciones_criterios;
BEGIN
  SELECT id_evaluacion INTO v_id_evaluacion FROM public.evaluaciones_criterios WHERE id = p_id;

  UPDATE public.evaluaciones_criterios
  SET
    criterio = COALESCE(p_criterio, criterio),
    descripcion = COALESCE(p_descripcion, descripcion),
    calificacion = COALESCE(p_calificacion, calificacion),
    peso = COALESCE(p_peso, peso),
    comentarios = COALESCE(p_comentarios, comentarios)
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.evaluaciones_criterios WHERE id = p_id;

  -- Actualizar calificación general
  IF v_id_evaluacion IS NOT NULL THEN
    UPDATE public.evaluaciones
    SET calificacion_general = (
      SELECT COALESCE(SUM(calificacion * peso) / NULLIF(SUM(peso), 0), 0)
      FROM public.evaluaciones_criterios
      WHERE id_evaluacion = v_id_evaluacion
    ),
    updated_at = now()
    WHERE id = v_id_evaluacion;
  END IF;

  RETURN v_result;
END;
$$;

-- Listar evaluaciones
CREATE OR REPLACE FUNCTION public.obtener_evaluaciones(
  p_id_usuario_evaluado integer DEFAULT NULL,
  p_id_usuario_evaluador integer DEFAULT NULL,
  p_estado varchar DEFAULT NULL,
  p_tipo_evaluacion varchar DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_usuario_evaluado integer,
  nombre_evaluado varchar,
  id_usuario_evaluador integer,
  nombre_evaluador varchar,
  tipo_evaluacion varchar,
  periodo_evaluacion varchar,
  fecha_evaluacion date,
  fecha_inicio_periodo date,
  fecha_fin_periodo date,
  calificacion_general numeric,
  estado varchar,
  comentarios_evaluador text,
  comentarios_evaluado text,
  objetivos_cumplidos text,
  areas_mejora text,
  recomendaciones text,
  aprobado_por integer,
  aprobado_por_nombre varchar,
  fecha_aprobacion timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.id_usuario_evaluado,
    u1.nombre::varchar AS nombre_evaluado,
    e.id_usuario_evaluador,
    u2.nombre::varchar AS nombre_evaluador,
    e.tipo_evaluacion,
    e.periodo_evaluacion,
    e.fecha_evaluacion,
    e.fecha_inicio_periodo,
    e.fecha_fin_periodo,
    e.calificacion_general,
    e.estado,
    e.comentarios_evaluador,
    e.comentarios_evaluado,
    e.objetivos_cumplidos,
    e.areas_mejora,
    e.recomendaciones,
    e.aprobado_por,
    u3.nombre::varchar AS aprobado_por_nombre,
    e.fecha_aprobacion,
    e.created_at,
    e.updated_at
  FROM public.evaluaciones e
  JOIN public.usuarios u1 ON u1.id = e.id_usuario_evaluado
  JOIN public.usuarios u2 ON u2.id = e.id_usuario_evaluador
  LEFT JOIN public.usuarios u3 ON u3.id = e.aprobado_por
  WHERE
    (p_id_usuario_evaluado IS NULL OR e.id_usuario_evaluado = p_id_usuario_evaluado)
    AND (p_id_usuario_evaluador IS NULL OR e.id_usuario_evaluador = p_id_usuario_evaluador)
    AND (p_estado IS NULL OR e.estado = p_estado)
    AND (p_tipo_evaluacion IS NULL OR e.tipo_evaluacion = p_tipo_evaluacion)
    AND (p_fecha_desde IS NULL OR e.fecha_evaluacion >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR e.fecha_evaluacion <= p_fecha_hasta)
  ORDER BY e.fecha_evaluacion DESC, e.created_at DESC;
END;
$$;

-- Obtener criterios de una evaluación
CREATE OR REPLACE FUNCTION public.obtener_criterios_evaluacion(p_id_evaluacion integer)
RETURNS TABLE (
  id integer,
  id_evaluacion integer,
  criterio varchar,
  descripcion text,
  calificacion numeric,
  peso numeric,
  comentarios text,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ec.id,
    ec.id_evaluacion,
    ec.criterio,
    ec.descripcion,
    ec.calificacion,
    ec.peso,
    ec.comentarios,
    ec.created_at
  FROM public.evaluaciones_criterios ec
  WHERE ec.id_evaluacion = p_id_evaluacion
  ORDER BY ec.id;
END;
$$;

-- Actualizar evaluación
CREATE OR REPLACE FUNCTION public.actualizar_evaluacion(
  p_id integer,
  p_tipo_evaluacion varchar DEFAULT NULL,
  p_periodo_evaluacion varchar DEFAULT NULL,
  p_fecha_evaluacion date DEFAULT NULL,
  p_fecha_inicio_periodo date DEFAULT NULL,
  p_fecha_fin_periodo date DEFAULT NULL,
  p_estado varchar DEFAULT NULL,
  p_comentarios_evaluador text DEFAULT NULL,
  p_comentarios_evaluado text DEFAULT NULL,
  p_objetivos_cumplidos text DEFAULT NULL,
  p_areas_mejora text DEFAULT NULL,
  p_recomendaciones text DEFAULT NULL
)
RETURNS public.evaluaciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.evaluaciones;
BEGIN
  UPDATE public.evaluaciones
  SET
    tipo_evaluacion = COALESCE(p_tipo_evaluacion, tipo_evaluacion),
    periodo_evaluacion = COALESCE(p_periodo_evaluacion, periodo_evaluacion),
    fecha_evaluacion = COALESCE(p_fecha_evaluacion, fecha_evaluacion),
    fecha_inicio_periodo = COALESCE(p_fecha_inicio_periodo, fecha_inicio_periodo),
    fecha_fin_periodo = COALESCE(p_fecha_fin_periodo, fecha_fin_periodo),
    estado = COALESCE(p_estado, estado),
    comentarios_evaluador = COALESCE(p_comentarios_evaluador, comentarios_evaluador),
    comentarios_evaluado = COALESCE(p_comentarios_evaluado, comentarios_evaluado),
    objetivos_cumplidos = COALESCE(p_objetivos_cumplidos, objetivos_cumplidos),
    areas_mejora = COALESCE(p_areas_mejora, areas_mejora),
    recomendaciones = COALESCE(p_recomendaciones, recomendaciones),
    updated_at = now()
  WHERE id = p_id;

  -- Recalcular calificación general
  UPDATE public.evaluaciones
  SET calificacion_general = (
    SELECT COALESCE(SUM(calificacion * peso) / NULLIF(SUM(peso), 0), 0)
    FROM public.evaluaciones_criterios
    WHERE id_evaluacion = p_id
  )
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.evaluaciones WHERE id = p_id;
  RETURN v_result;
END;
$$;

-- Aprobar evaluación
CREATE OR REPLACE FUNCTION public.aprobar_evaluacion(
  p_id integer,
  p_id_aprobador integer
)
RETURNS public.evaluaciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.evaluaciones;
BEGIN
  UPDATE public.evaluaciones
  SET
    estado = 'aprobada',
    aprobado_por = p_id_aprobador,
    fecha_aprobacion = now(),
    updated_at = now()
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.evaluaciones WHERE id = p_id;
  RETURN v_result;
END;
$$;

-- Eliminar criterio
CREATE OR REPLACE FUNCTION public.eliminar_criterio_evaluacion(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id_evaluacion integer;
BEGIN
  SELECT id_evaluacion INTO v_id_evaluacion FROM public.evaluaciones_criterios WHERE id = p_id;
  
  DELETE FROM public.evaluaciones_criterios WHERE id = p_id;

  -- Recalcular calificación general
  IF v_id_evaluacion IS NOT NULL THEN
    UPDATE public.evaluaciones
    SET calificacion_general = (
      SELECT COALESCE(SUM(calificacion * peso) / NULLIF(SUM(peso), 0), 0)
      FROM public.evaluaciones_criterios
      WHERE id_evaluacion = v_id_evaluacion
    ),
    updated_at = now()
    WHERE id = v_id_evaluacion;
  END IF;

  RETURN FOUND;
END;
$$;

-- Eliminar evaluación
CREATE OR REPLACE FUNCTION public.eliminar_evaluacion(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.evaluaciones WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ============================================
-- 4. RLS POLICIES
-- ============================================

ALTER TABLE public.evaluaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluaciones_criterios ENABLE ROW LEVEL SECURITY;

-- Políticas para evaluaciones
CREATE POLICY "Enable read access for authenticated users" ON public.evaluaciones
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.evaluaciones
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.evaluaciones
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.evaluaciones
  FOR DELETE USING (true);

-- Políticas para criterios
CREATE POLICY "Enable read access for authenticated users" ON public.evaluaciones_criterios
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.evaluaciones_criterios
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.evaluaciones_criterios
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.evaluaciones_criterios
  FOR DELETE USING (true);

COMMIT;

