-- Tabla para guardar la firma del cliente en tablet (uso real: tablet y PC distintos)
-- La tablet (anon) inserta/actualiza; la PC (usuario logueado) lee al cargar Entrega.
CREATE TABLE IF NOT EXISTS public.firmas_entrega_cliente (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_op text NOT NULL UNIQUE,
  firma_data_url text NOT NULL,
  entregado_a text NOT NULL,
  dni_retira text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_firmas_entrega_cliente_numero_op ON public.firmas_entrega_cliente(numero_op);

COMMENT ON TABLE public.firmas_entrega_cliente IS 'Firma del cliente capturada en tablet; se consulta desde Entrega en PC.';

-- RLS
ALTER TABLE public.firmas_entrega_cliente ENABLE ROW LEVEL SECURITY;

-- Tablet (anon): puede insertar y actualizar por numero_op (página pública de firma)
CREATE POLICY "firmas_entrega_cliente_anon_insert"
  ON public.firmas_entrega_cliente FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "firmas_entrega_cliente_anon_update"
  ON public.firmas_entrega_cliente FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);

-- Usuarios autenticados: pueden leer para prellenar Entrega
CREATE POLICY "firmas_entrega_cliente_auth_select"
  ON public.firmas_entrega_cliente FOR SELECT
  TO authenticated
  USING (true);

-- Anon necesita SELECT para que INSERT ... ON CONFLICT DO UPDATE (upsert) funcione con RLS
CREATE POLICY "firmas_entrega_cliente_anon_select"
  ON public.firmas_entrega_cliente FOR SELECT
  TO anon
  USING (true);

-- No añadimos DELETE; si se quiere limpiar después de procesar entrega, puede hacerse desde backend.
