-- ============================================
-- SISTEMA DE PRESUPUESTOS DE VENTAS PRESENCIALES
-- Presupuestos creados desde el CRM/Mostrador para ventas presenciales
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE PRESUPUESTOS DE VENTAS PRESENCIALES
-- ============================================
CREATE TABLE IF NOT EXISTS public.presupuestos_ventas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer REFERENCES public.clientes(id) ON DELETE SET NULL,
  numero_presupuesto varchar(50) NOT NULL UNIQUE,
  estado varchar(50) NOT NULL DEFAULT 'borrador' CHECK (
    estado IN ('borrador', 'enviado', 'aceptado', 'rechazado', 'cancelado', 'convertido')
  ),
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_envio timestamptz,
  fecha_respuesta timestamptz,
  fecha_vencimiento date,
  observaciones_cliente text,
  observaciones_internas text,
  precio_total numeric(10,2) DEFAULT 0,
  id_op_asociada integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  id_venta_asociada integer REFERENCES public.ventas(id) ON DELETE SET NULL,
  id_vendedor integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  nombre_vendedor varchar(100),
  cliente_nombre varchar(255),
  cliente_telefono varchar(50),
  cliente_email varchar(255),
  cliente_dni_cuit varchar(50),
  cliente_empresa varchar(255),
  cliente_direccion text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_cliente ON public.presupuestos_ventas(id_cliente);
CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_numero ON public.presupuestos_ventas(numero_presupuesto);
CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_estado ON public.presupuestos_ventas(estado);
CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_fecha ON public.presupuestos_ventas(fecha_creacion DESC);
CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_op ON public.presupuestos_ventas(id_op_asociada);
CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_venta ON public.presupuestos_ventas(id_venta_asociada);
CREATE INDEX IF NOT EXISTS idx_presupuestos_ventas_vendedor ON public.presupuestos_ventas(id_vendedor);

-- ============================================
-- 2. TABLA DE ITEMS DEL PRESUPUESTO DE VENTA
-- ============================================
CREATE TABLE IF NOT EXISTS public.presupuestos_ventas_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_presupuesto integer NOT NULL REFERENCES public.presupuestos_ventas(id) ON DELETE CASCADE,
  id_articulo_stock integer REFERENCES public.articulos_stock(id) ON DELETE SET NULL,
  codigo_articulo varchar(100),
  descripcion text NOT NULL,
  cantidad numeric(10,3) NOT NULL,
  precio_unitario numeric(10,2) NOT NULL,
  descuento numeric(10,2) DEFAULT 0,
  precio_total numeric(10,2) NOT NULL,
  observaciones text,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_presupuesto_venta ON public.presupuestos_ventas_items(id_presupuesto);
CREATE INDEX IF NOT EXISTS idx_items_articulo_presupuesto_venta ON public.presupuestos_ventas_items(id_articulo_stock);

-- ============================================
-- 3. FUNCIÓN PARA GENERAR NÚMERO ÚNICO DE PRESUPUESTO DE VENTA
-- ============================================
CREATE OR REPLACE FUNCTION public.generar_numero_presupuesto_venta()
RETURNS varchar(50)
LANGUAGE plpgsql
AS $$
DECLARE
  nuevo_numero varchar(50);
  contador integer;
  año_mes varchar(6);
BEGIN
  -- Formato: PRES-VENT-YYYYMM-0001 (reinicia cada mes)
  año_mes := TO_CHAR(CURRENT_DATE, 'YYYYMM');
  
  -- Buscar el último número del mes actual
  SELECT COALESCE(MAX(CAST(SUBSTRING(numero_presupuesto FROM '[0-9]+$') AS INTEGER)), 0) + 1
  INTO contador
  FROM public.presupuestos_ventas
  WHERE numero_presupuesto LIKE 'PRES-VENT-' || año_mes || '-%';
  
  nuevo_numero := 'PRES-VENT-' || año_mes || '-' || LPAD(contador::text, 4, '0');
  
  -- Verificar que no exista (por si acaso)
  WHILE EXISTS (SELECT 1 FROM public.presupuestos_ventas WHERE numero_presupuesto = nuevo_numero) LOOP
    contador := contador + 1;
    nuevo_numero := 'PRES-VENT-' || año_mes || '-' || LPAD(contador::text, 4, '0');
  END LOOP;
  
  RETURN nuevo_numero;
END;
$$;

-- ============================================
-- 4. FUNCIÓN PARA CREAR PRESUPUESTO DE VENTA PRESENCIAL
-- ============================================
CREATE OR REPLACE FUNCTION public.crear_presupuesto_venta(
  p_id_cliente integer DEFAULT NULL,
  p_cliente_nombre varchar(255) DEFAULT NULL,
  p_cliente_telefono varchar(50) DEFAULT NULL,
  p_cliente_email varchar(255) DEFAULT NULL,
  p_cliente_dni_cuit varchar(50) DEFAULT NULL,
  p_cliente_empresa varchar(255) DEFAULT NULL,
  p_cliente_direccion text DEFAULT NULL,
  p_id_vendedor integer DEFAULT NULL,
  p_nombre_vendedor varchar(100) DEFAULT NULL,
  p_items jsonb DEFAULT '[]'::jsonb,
  p_fecha_vencimiento date DEFAULT NULL,
  p_observaciones_cliente text DEFAULT NULL,
  p_observaciones_internas text DEFAULT NULL,
  p_estado varchar(50) DEFAULT 'borrador'
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  estado varchar,
  precio_total numeric
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  nuevo_presupuesto_id integer;
  numero_presupuesto_generado varchar(50);
  item_record jsonb;
  precio_total_calculado numeric(10,2) := 0;
BEGIN
  -- Validar estado
  IF p_estado NOT IN ('borrador', 'enviado', 'aceptado', 'rechazado', 'cancelado', 'convertido') THEN
    RAISE EXCEPTION 'Estado inválido: %', p_estado;
  END IF;

  -- Generar número de presupuesto
  numero_presupuesto_generado := public.generar_numero_presupuesto_venta();

  -- Crear presupuesto
  INSERT INTO public.presupuestos_ventas (
    id_cliente,
    numero_presupuesto,
    estado,
    fecha_vencimiento,
    observaciones_cliente,
    observaciones_internas,
    fecha_envio,
    id_vendedor,
    nombre_vendedor,
    cliente_nombre,
    cliente_telefono,
    cliente_email,
    cliente_dni_cuit,
    cliente_empresa,
    cliente_direccion
  ) VALUES (
    p_id_cliente,
    numero_presupuesto_generado,
    p_estado,
    p_fecha_vencimiento,
    p_observaciones_cliente,
    p_observaciones_internas,
    CASE WHEN p_estado = 'enviado' THEN NOW() ELSE NULL END,
    p_id_vendedor,
    p_nombre_vendedor,
    p_cliente_nombre,
    p_cliente_telefono,
    p_cliente_email,
    p_cliente_dni_cuit,
    p_cliente_empresa,
    p_cliente_direccion
  )
  RETURNING id INTO nuevo_presupuesto_id;

  -- Procesar items
  FOR item_record IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    INSERT INTO public.presupuestos_ventas_items (
      id_presupuesto,
      id_articulo_stock,
      codigo_articulo,
      descripcion,
      cantidad,
      precio_unitario,
      descuento,
      precio_total,
      observaciones
    ) VALUES (
      nuevo_presupuesto_id,
      (item_record->>'id_articulo_stock')::integer,
      item_record->>'codigo_articulo',
      item_record->>'descripcion',
      COALESCE((item_record->>'cantidad')::numeric, 1),
      (item_record->>'precio_unitario')::numeric,
      COALESCE((item_record->>'descuento')::numeric, 0),
      (item_record->>'precio_total')::numeric,
      item_record->>'observaciones'
    );

    precio_total_calculado := precio_total_calculado + ((item_record->>'precio_total')::numeric);
  END LOOP;

  -- Actualizar precio total del presupuesto
  UPDATE public.presupuestos_ventas
  SET precio_total = precio_total_calculado
  WHERE id = nuevo_presupuesto_id;

  RETURN QUERY
  SELECT p.id, p.numero_presupuesto, p.estado, p.precio_total
  FROM public.presupuestos_ventas p
  WHERE p.id = nuevo_presupuesto_id;
END;
$$;

-- ============================================
-- 5. FUNCIÓN PARA LISTAR PRESUPUESTOS DE VENTAS (ADMIN)
-- ============================================
CREATE OR REPLACE FUNCTION public.listar_presupuestos_ventas_admin(
  p_estado varchar(50) DEFAULT NULL,
  p_id_cliente integer DEFAULT NULL,
  p_id_vendedor integer DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_cliente integer,
  numero_presupuesto varchar,
  estado varchar,
  fecha_creacion timestamptz,
  fecha_envio timestamptz,
  fecha_respuesta timestamptz,
  fecha_vencimiento date,
  observaciones_cliente text,
  observaciones_internas text,
  precio_total numeric,
  id_op_asociada integer,
  id_venta_asociada integer,
  id_vendedor integer,
  nombre_vendedor varchar,
  cliente_nombre varchar,
  cliente_telefono varchar,
  cliente_email varchar,
  cliente_dni_cuit varchar,
  cliente_empresa varchar,
  cliente_direccion text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id,
    p.id_cliente,
    p.numero_presupuesto,
    p.estado,
    p.fecha_creacion,
    p.fecha_envio,
    p.fecha_respuesta,
    p.fecha_vencimiento,
    p.observaciones_cliente,
    p.observaciones_internas,
    p.precio_total,
    p.id_op_asociada,
    p.id_venta_asociada,
    p.id_vendedor,
    p.nombre_vendedor,
    p.cliente_nombre,
    p.cliente_telefono,
    p.cliente_email,
    p.cliente_dni_cuit,
    p.cliente_empresa,
    p.cliente_direccion,
    p.created_at,
    p.updated_at
  FROM public.presupuestos_ventas p
  WHERE 
    (p_estado IS NULL OR p.estado = p_estado)
    AND (p_id_cliente IS NULL OR p.id_cliente = p_id_cliente)
    AND (p_id_vendedor IS NULL OR p.id_vendedor = p_id_vendedor)
    AND (p_fecha_desde IS NULL OR DATE(p.fecha_creacion) >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR DATE(p.fecha_creacion) <= p_fecha_hasta)
  ORDER BY p.fecha_creacion DESC;
END;
$$;

-- ============================================
-- 6. FUNCIÓN PARA ACTUALIZAR ESTADO DE PRESUPUESTO DE VENTA
-- ============================================
CREATE OR REPLACE FUNCTION public.actualizar_estado_presupuesto_venta(
  p_id_presupuesto integer,
  p_estado varchar(50),
  p_observaciones_internas text DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  numero_presupuesto varchar,
  estado varchar
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  presupuesto_record RECORD;
BEGIN
  -- Validar estado
  IF p_estado NOT IN ('borrador', 'enviado', 'aceptado', 'rechazado', 'cancelado', 'convertido') THEN
    RAISE EXCEPTION 'Estado inválido: %', p_estado;
  END IF;

  -- Actualizar presupuesto
  UPDATE public.presupuestos_ventas
  SET 
    estado = p_estado,
    observaciones_internas = COALESCE(p_observaciones_internas, observaciones_internas),
    fecha_envio = CASE WHEN p_estado = 'enviado' AND fecha_envio IS NULL THEN NOW() ELSE fecha_envio END,
    fecha_respuesta = CASE WHEN p_estado IN ('aceptado', 'rechazado') THEN NOW() ELSE fecha_respuesta END,
    updated_at = NOW()
  WHERE id = p_id_presupuesto
  RETURNING * INTO presupuesto_record;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Presupuesto no encontrado';
  END IF;

  RETURN QUERY
  SELECT presupuesto_record.id, presupuesto_record.numero_presupuesto, presupuesto_record.estado;
END;
$$;

-- ============================================
-- 7. FUNCIÓN PARA OBTENER DETALLE COMPLETO DE PRESUPUESTO DE VENTA
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_detalle_presupuesto_venta(
  p_id_presupuesto integer
)
RETURNS TABLE (
  presupuesto jsonb,
  items jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  presupuesto_data jsonb;
  items_data jsonb;
BEGIN
  -- Obtener datos del presupuesto
  SELECT to_jsonb(p.*)
  INTO presupuesto_data
  FROM public.presupuestos_ventas p
  WHERE p.id = p_id_presupuesto;

  IF presupuesto_data IS NULL THEN
    RAISE EXCEPTION 'Presupuesto no encontrado';
  END IF;

  -- Obtener items del presupuesto
  SELECT COALESCE(jsonb_agg(to_jsonb(i.*)), '[]'::jsonb)
  INTO items_data
  FROM public.presupuestos_ventas_items i
  WHERE i.id_presupuesto = p_id_presupuesto;

  RETURN QUERY
  SELECT presupuesto_data, items_data;
END;
$$;

COMMIT;

