-- Crear tablas para sistema de conciliación bancaria

BEGIN;

-- Tabla de pagos
CREATE TABLE IF NOT EXISTS public.pagos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pago varchar(50) NOT NULL UNIQUE,
  id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  monto_total numeric(15,2) NOT NULL,
  monto_pagado numeric(15,2) NOT NULL DEFAULT 0,
  moneda varchar(10) NOT NULL DEFAULT 'ARS',
  fecha_vencimiento date,
  fecha_pago timestamptz,
  metodo_pago varchar(50),
  numero_comprobante varchar(100),
  banco varchar(100),
  cuenta_bancaria varchar(100),
  estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
    estado IN ('Pendiente', 'Parcial', 'Completado', 'Vencido', 'Cancelado')
  ),
  observaciones text,
  id_usuario_registro integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  nombre_usuario_registro varchar(100),
  fecha_conciliacion timestamptz,
  id_usuario_conciliacion integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de movimientos bancarios
CREATE TABLE IF NOT EXISTS public.movimientos_bancarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_movimiento date NOT NULL,
  fecha_valor date,
  tipo varchar(20) NOT NULL CHECK (tipo IN ('Ingreso', 'Egreso')),
  concepto text NOT NULL,
  monto numeric(15,2) NOT NULL,
  moneda varchar(10) NOT NULL DEFAULT 'ARS',
  banco varchar(100) NOT NULL,
  cuenta_bancaria varchar(100) NOT NULL,
  numero_comprobante varchar(100),
  referencia varchar(255),
  id_pago_asociado integer REFERENCES public.pagos(id) ON DELETE SET NULL,
  conciliado boolean NOT NULL DEFAULT false,
  fecha_conciliacion timestamptz,
  id_usuario_conciliacion integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de conciliaciones bancarias
CREATE TABLE IF NOT EXISTS public.conciliaciones_bancarias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_conciliacion timestamptz NOT NULL DEFAULT now(),
  fecha_desde date NOT NULL,
  fecha_hasta date NOT NULL,
  banco varchar(100) NOT NULL,
  cuenta_bancaria varchar(100) NOT NULL,
  saldo_inicial numeric(15,2) NOT NULL DEFAULT 0,
  saldo_final numeric(15,2) NOT NULL DEFAULT 0,
  total_ingresos numeric(15,2) NOT NULL DEFAULT 0,
  total_egresos numeric(15,2) NOT NULL DEFAULT 0,
  movimientos_conciliados integer NOT NULL DEFAULT 0,
  movimientos_pendientes integer NOT NULL DEFAULT 0,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  nombre_usuario varchar(100),
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_pagos_pedido ON public.pagos(id_pedido_compra);
CREATE INDEX IF NOT EXISTS idx_pagos_proveedor ON public.pagos(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_pagos_estado ON public.pagos(estado);
CREATE INDEX IF NOT EXISTS idx_pagos_fecha_vencimiento ON public.pagos(fecha_vencimiento);

CREATE INDEX IF NOT EXISTS idx_movimientos_banco_cuenta ON public.movimientos_bancarios(banco, cuenta_bancaria);
CREATE INDEX IF NOT EXISTS idx_movimientos_fecha ON public.movimientos_bancarios(fecha_movimiento DESC);
CREATE INDEX IF NOT EXISTS idx_movimientos_conciliado ON public.movimientos_bancarios(conciliado);
CREATE INDEX IF NOT EXISTS idx_movimientos_pago ON public.movimientos_bancarios(id_pago_asociado);

CREATE INDEX IF NOT EXISTS idx_conciliaciones_banco_cuenta ON public.conciliaciones_bancarias(banco, cuenta_bancaria);
CREATE INDEX IF NOT EXISTS idx_conciliaciones_fecha ON public.conciliaciones_bancarias(fecha_conciliacion DESC);

-- Trigger para actualizar updated_at en pagos
CREATE OR REPLACE FUNCTION public.update_pagos_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_pagos_updated_at
  BEFORE UPDATE ON public.pagos
  FOR EACH ROW
  EXECUTE FUNCTION public.update_pagos_updated_at();

-- Trigger para actualizar updated_at en movimientos_bancarios
CREATE OR REPLACE FUNCTION public.update_movimientos_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_movimientos_updated_at
  BEFORE UPDATE ON public.movimientos_bancarios
  FOR EACH ROW
  EXECUTE FUNCTION public.update_movimientos_updated_at();

COMMIT;

