-- ============================================
-- SISTEMA DE GESTIÓN DE HORARIOS Y TURNOS
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE HORARIOS DE EMPLEADOS
-- ============================================
CREATE TABLE IF NOT EXISTS public.horarios_empleados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo_horario varchar(50) NOT NULL DEFAULT 'fijo', -- 'fijo', 'flexible', 'turnos'
  dia_semana integer, -- 0=Domingo, 1=Lunes, ..., 6=Sábado (NULL para horarios flexibles)
  hora_entrada time,
  hora_salida time,
  horas_semanales numeric(5,2), -- Para horarios flexibles
  activo boolean DEFAULT true,
  fecha_inicio date,
  fecha_fin date, -- NULL para horarios indefinidos
  observaciones text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_horarios_usuario ON public.horarios_empleados(id_usuario);
CREATE INDEX IF NOT EXISTS idx_horarios_activo ON public.horarios_empleados(activo);
CREATE INDEX IF NOT EXISTS idx_horarios_dia ON public.horarios_empleados(dia_semana);

-- ============================================
-- 2. TABLA DE TURNOS ASIGNADOS
-- ============================================
CREATE TABLE IF NOT EXISTS public.turnos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  fecha date NOT NULL,
  hora_entrada time NOT NULL,
  hora_salida time NOT NULL,
  tipo_turno varchar(50) DEFAULT 'normal', -- 'normal', 'extra', 'nocturno'
  observaciones text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(id_usuario, fecha)
);

CREATE INDEX IF NOT EXISTS idx_turnos_usuario ON public.turnos(id_usuario);
CREATE INDEX IF NOT EXISTS idx_turnos_fecha ON public.turnos(fecha);
CREATE INDEX IF NOT EXISTS idx_turnos_usuario_fecha ON public.turnos(id_usuario, fecha);

-- ============================================
-- 3. TABLA DE AUSENCIAS
-- ============================================
CREATE TABLE IF NOT EXISTS public.ausencias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  tipo_ausencia varchar(50) NOT NULL, -- 'vacaciones', 'licencia', 'inasistencia', 'permiso', 'enfermedad'
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  dias integer, -- Calculado automáticamente
  motivo text,
  estado varchar(50) DEFAULT 'pendiente', -- 'pendiente', 'aprobado', 'rechazado'
  aprobado_por integer REFERENCES public.usuarios(id),
  fecha_aprobacion timestamptz,
  observaciones text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ausencias_usuario ON public.ausencias(id_usuario);
CREATE INDEX IF NOT EXISTS idx_ausencias_fecha ON public.ausencias(fecha_inicio, fecha_fin);
CREATE INDEX IF NOT EXISTS idx_ausencias_estado ON public.ausencias(estado);

-- ============================================
-- 4. TABLA DE ASISTENCIA (ENTRADA/SALIDA)
-- ============================================
CREATE TABLE IF NOT EXISTS public.asistencia (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  fecha date NOT NULL,
  hora_entrada timestamptz,
  hora_salida timestamptz,
  horas_trabajadas numeric(5,2), -- Calculado automáticamente
  tipo_registro varchar(50) DEFAULT 'normal', -- 'normal', 'tarde', 'ausente', 'justificado'
  observaciones text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(id_usuario, fecha)
);

CREATE INDEX IF NOT EXISTS idx_asistencia_usuario ON public.asistencia(id_usuario);
CREATE INDEX IF NOT EXISTS idx_asistencia_fecha ON public.asistencia(fecha);
CREATE INDEX IF NOT EXISTS idx_asistencia_usuario_fecha ON public.asistencia(id_usuario, fecha);

-- ============================================
-- 5. FUNCIONES PARA HORARIOS
-- ============================================

-- Crear/Actualizar horario
CREATE OR REPLACE FUNCTION public.crear_actualizar_horario(
  p_id_usuario integer,
  p_tipo_horario varchar,
  p_dia_semana integer DEFAULT NULL,
  p_hora_entrada time DEFAULT NULL,
  p_hora_salida time DEFAULT NULL,
  p_horas_semanales numeric DEFAULT NULL,
  p_fecha_inicio date DEFAULT NULL,
  p_fecha_fin date DEFAULT NULL,
  p_observaciones text DEFAULT NULL,
  p_activo boolean DEFAULT true
)
RETURNS public.horarios_empleados
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_horario_id integer;
  v_result public.horarios_empleados;
BEGIN
  INSERT INTO public.horarios_empleados (
    id_usuario, tipo_horario, dia_semana, hora_entrada, hora_salida,
    horas_semanales, fecha_inicio, fecha_fin, observaciones, activo
  )
  VALUES (
    p_id_usuario, p_tipo_horario, p_dia_semana, p_hora_entrada, p_hora_salida,
    p_horas_semanales, p_fecha_inicio, p_fecha_fin, p_observaciones, p_activo
  )
  RETURNING id INTO v_horario_id;

  SELECT * INTO v_result FROM public.horarios_empleados WHERE id = v_horario_id;
  RETURN v_result;
END;
$$;

-- Listar horarios de un usuario
CREATE OR REPLACE FUNCTION public.obtener_horarios_usuario(p_id_usuario integer)
RETURNS SETOF public.horarios_empleados
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT * FROM public.horarios_empleados
  WHERE id_usuario = p_id_usuario
  ORDER BY dia_semana NULLS LAST, fecha_inicio DESC;
END;
$$;

-- Eliminar horario
CREATE OR REPLACE FUNCTION public.eliminar_horario(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.horarios_empleados WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ============================================
-- 6. FUNCIONES PARA TURNOS
-- ============================================

-- Crear/Actualizar turno
CREATE OR REPLACE FUNCTION public.crear_actualizar_turno(
  p_id_usuario integer,
  p_fecha date,
  p_hora_entrada time,
  p_hora_salida time,
  p_tipo_turno varchar DEFAULT 'normal',
  p_observaciones text DEFAULT NULL
)
RETURNS public.turnos
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_turno_id integer;
  v_result public.turnos;
BEGIN
  INSERT INTO public.turnos (
    id_usuario, fecha, hora_entrada, hora_salida, tipo_turno, observaciones
  )
  VALUES (
    p_id_usuario, p_fecha, p_hora_entrada, p_hora_salida, p_tipo_turno, p_observaciones
  )
  ON CONFLICT (id_usuario, fecha) DO UPDATE
  SET
    hora_entrada = EXCLUDED.hora_entrada,
    hora_salida = EXCLUDED.hora_salida,
    tipo_turno = EXCLUDED.tipo_turno,
    observaciones = EXCLUDED.observaciones,
    updated_at = now()
  RETURNING id INTO v_turno_id;

  SELECT * INTO v_result FROM public.turnos WHERE id = v_turno_id;
  RETURN v_result;
END;
$$;

-- Listar turnos por rango de fechas
CREATE OR REPLACE FUNCTION public.obtener_turnos(
  p_id_usuario integer DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_usuario integer,
  nombre_usuario varchar,
  fecha date,
  hora_entrada time,
  hora_salida time,
  tipo_turno varchar,
  observaciones text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    t.id,
    t.id_usuario,
    u.nombre::varchar AS nombre_usuario,
    t.fecha,
    t.hora_entrada,
    t.hora_salida,
    t.tipo_turno,
    t.observaciones,
    t.created_at,
    t.updated_at
  FROM public.turnos t
  JOIN public.usuarios u ON u.id = t.id_usuario
  WHERE
    (p_id_usuario IS NULL OR t.id_usuario = p_id_usuario)
    AND (p_fecha_desde IS NULL OR t.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR t.fecha <= p_fecha_hasta)
  ORDER BY t.fecha DESC, u.nombre;
END;
$$;

-- Eliminar turno
CREATE OR REPLACE FUNCTION public.eliminar_turno(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.turnos WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ============================================
-- 7. FUNCIONES PARA AUSENCIAS
-- ============================================

-- Crear ausencia
CREATE OR REPLACE FUNCTION public.crear_ausencia(
  p_id_usuario integer,
  p_tipo_ausencia varchar,
  p_fecha_inicio date,
  p_fecha_fin date,
  p_motivo text DEFAULT NULL,
  p_observaciones text DEFAULT NULL
)
RETURNS public.ausencias
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_ausencia_id integer;
  v_dias integer;
  v_result public.ausencias;
BEGIN
  -- Calcular días
  v_dias := p_fecha_fin - p_fecha_inicio + 1;

  INSERT INTO public.ausencias (
    id_usuario, tipo_ausencia, fecha_inicio, fecha_fin, dias, motivo, observaciones
  )
  VALUES (
    p_id_usuario, p_tipo_ausencia, p_fecha_inicio, p_fecha_fin, v_dias, p_motivo, p_observaciones
  )
  RETURNING id INTO v_ausencia_id;

  SELECT * INTO v_result FROM public.ausencias WHERE id = v_ausencia_id;
  RETURN v_result;
END;
$$;

-- Listar ausencias
CREATE OR REPLACE FUNCTION public.obtener_ausencias(
  p_id_usuario integer DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL,
  p_estado varchar DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_usuario integer,
  nombre_usuario varchar,
  tipo_ausencia varchar,
  fecha_inicio date,
  fecha_fin date,
  dias integer,
  motivo text,
  estado varchar,
  aprobado_por integer,
  aprobado_por_nombre varchar,
  fecha_aprobacion timestamptz,
  observaciones text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    a.id,
    a.id_usuario,
    u.nombre::varchar AS nombre_usuario,
    a.tipo_ausencia,
    a.fecha_inicio,
    a.fecha_fin,
    a.dias,
    a.motivo,
    a.estado,
    a.aprobado_por,
    u2.nombre::varchar AS aprobado_por_nombre,
    a.fecha_aprobacion,
    a.observaciones,
    a.created_at,
    a.updated_at
  FROM public.ausencias a
  JOIN public.usuarios u ON u.id = a.id_usuario
  LEFT JOIN public.usuarios u2 ON u2.id = a.aprobado_por
  WHERE
    (p_id_usuario IS NULL OR a.id_usuario = p_id_usuario)
    AND (p_fecha_desde IS NULL OR a.fecha_fin >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR a.fecha_inicio <= p_fecha_hasta)
    AND (p_estado IS NULL OR a.estado = p_estado)
  ORDER BY a.fecha_inicio DESC;
END;
$$;

-- Aprobar/Rechazar ausencia
CREATE OR REPLACE FUNCTION public.aprobar_rechazar_ausencia(
  p_id integer,
  p_estado varchar,
  p_id_aprobador integer,
  p_observaciones text DEFAULT NULL
)
RETURNS public.ausencias
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.ausencias;
BEGIN
  UPDATE public.ausencias
  SET
    estado = p_estado,
    aprobado_por = p_id_aprobador,
    fecha_aprobacion = CASE WHEN p_estado = 'aprobado' THEN now() ELSE NULL END,
    observaciones = COALESCE(p_observaciones, observaciones),
    updated_at = now()
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.ausencias WHERE id = p_id;
  RETURN v_result;
END;
$$;

-- Eliminar ausencia
CREATE OR REPLACE FUNCTION public.eliminar_ausencia(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.ausencias WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ============================================
-- 8. FUNCIONES PARA ASISTENCIA
-- ============================================

-- Registrar entrada
CREATE OR REPLACE FUNCTION public.registrar_entrada(
  p_id_usuario integer,
  p_fecha date DEFAULT NULL,
  p_hora_entrada timestamptz DEFAULT NULL
)
RETURNS public.asistencia
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_fecha date;
  v_hora_entrada timestamptz;
  v_asistencia_id integer;
  v_result public.asistencia;
BEGIN
  v_fecha := COALESCE(p_fecha, CURRENT_DATE);
  v_hora_entrada := COALESCE(p_hora_entrada, now());

  INSERT INTO public.asistencia (id_usuario, fecha, hora_entrada)
  VALUES (p_id_usuario, v_fecha, v_hora_entrada)
  ON CONFLICT (id_usuario, fecha) DO UPDATE
  SET
    hora_entrada = EXCLUDED.hora_entrada,
    updated_at = now()
  RETURNING id INTO v_asistencia_id;

  SELECT * INTO v_result FROM public.asistencia WHERE id = v_asistencia_id;
  RETURN v_result;
END;
$$;

-- Registrar salida
CREATE OR REPLACE FUNCTION public.registrar_salida(
  p_id_usuario integer,
  p_fecha date DEFAULT NULL,
  p_hora_salida timestamptz DEFAULT NULL
)
RETURNS public.asistencia
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_fecha date;
  v_hora_salida timestamptz;
  v_horas_trabajadas numeric;
  v_asistencia_id integer;
  v_result public.asistencia;
BEGIN
  v_fecha := COALESCE(p_fecha, CURRENT_DATE);
  v_hora_salida := COALESCE(p_hora_salida, now());

  -- Calcular horas trabajadas
  SELECT EXTRACT(EPOCH FROM (v_hora_salida - hora_entrada)) / 3600
  INTO v_horas_trabajadas
  FROM public.asistencia
  WHERE id_usuario = p_id_usuario AND fecha = v_fecha;

  INSERT INTO public.asistencia (id_usuario, fecha, hora_salida, horas_trabajadas)
  VALUES (p_id_usuario, v_fecha, v_hora_salida, v_horas_trabajadas)
  ON CONFLICT (id_usuario, fecha) DO UPDATE
  SET
    hora_salida = EXCLUDED.hora_salida,
    horas_trabajadas = EXCLUDED.horas_trabajadas,
    updated_at = now()
  RETURNING id INTO v_asistencia_id;

  SELECT * INTO v_result FROM public.asistencia WHERE id = v_asistencia_id;
  RETURN v_result;
END;
$$;

-- Listar asistencia
CREATE OR REPLACE FUNCTION public.obtener_asistencia(
  p_id_usuario integer DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_usuario integer,
  nombre_usuario varchar,
  fecha date,
  hora_entrada timestamptz,
  hora_salida timestamptz,
  horas_trabajadas numeric,
  tipo_registro varchar,
  observaciones text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    a.id,
    a.id_usuario,
    u.nombre::varchar AS nombre_usuario,
    a.fecha,
    a.hora_entrada,
    a.hora_salida,
    a.horas_trabajadas,
    a.tipo_registro,
    a.observaciones,
    a.created_at,
    a.updated_at
  FROM public.asistencia a
  JOIN public.usuarios u ON u.id = a.id_usuario
  WHERE
    (p_id_usuario IS NULL OR a.id_usuario = p_id_usuario)
    AND (p_fecha_desde IS NULL OR a.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR a.fecha <= p_fecha_hasta)
  ORDER BY a.fecha DESC, u.nombre;
END;
$$;

-- ============================================
-- 9. RLS POLICIES
-- ============================================

ALTER TABLE public.horarios_empleados ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.turnos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ausencias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asistencia ENABLE ROW LEVEL SECURITY;

-- Políticas para horarios_empleados
CREATE POLICY "Enable read access for authenticated users" ON public.horarios_empleados
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.horarios_empleados
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.horarios_empleados
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.horarios_empleados
  FOR DELETE USING (true);

-- Políticas para turnos
CREATE POLICY "Enable read access for authenticated users" ON public.turnos
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.turnos
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.turnos
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.turnos
  FOR DELETE USING (true);

-- Políticas para ausencias
CREATE POLICY "Enable read access for authenticated users" ON public.ausencias
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.ausencias
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.ausencias
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.ausencias
  FOR DELETE USING (true);

-- Políticas para asistencia
CREATE POLICY "Enable read access for authenticated users" ON public.asistencia
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.asistencia
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.asistencia
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.asistencia
  FOR DELETE USING (true);

COMMIT;


