-- ============================================
-- AGENDA DEL ASESOR TÉCNICO
-- Sistema para gestionar citas con clientes
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE CITAS DEL ASESOR TÉCNICO
-- ============================================
CREATE TABLE IF NOT EXISTS public.citas_asesor_tecnico (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asesor integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_cliente integer REFERENCES public.clientes(id) ON DELETE SET NULL,
  id_ficha_no_op integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  titulo varchar(255) NOT NULL,
  descripcion text,
  fecha_cita timestamptz NOT NULL,
  duracion_minutos integer DEFAULT 60,
  direccion text,
  ubicacion_link text,
  estado varchar(50) DEFAULT 'programada', -- 'programada', 'confirmada', 'en_curso', 'completada', 'cancelada'
  notas text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  created_by integer REFERENCES public.usuarios(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_citas_asesor ON public.citas_asesor_tecnico(id_asesor);
CREATE INDEX IF NOT EXISTS idx_citas_cliente ON public.citas_asesor_tecnico(id_cliente);
CREATE INDEX IF NOT EXISTS idx_citas_fecha ON public.citas_asesor_tecnico(fecha_cita);
CREATE INDEX IF NOT EXISTS idx_citas_estado ON public.citas_asesor_tecnico(estado);
CREATE INDEX IF NOT EXISTS idx_citas_ficha_no_op ON public.citas_asesor_tecnico(id_ficha_no_op);

-- ============================================
-- 2. FUNCIÓN PARA OBTENER CITAS DEL ASESOR
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_citas_asesor(
  p_id_asesor integer,
  p_fecha_desde timestamptz DEFAULT NULL,
  p_fecha_hasta timestamptz DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_asesor integer,
  id_cliente integer,
  id_ficha_no_op integer,
  titulo varchar,
  descripcion text,
  fecha_cita timestamptz,
  duracion_minutos integer,
  direccion text,
  ubicacion_link text,
  estado varchar,
  notas text,
  created_at timestamptz,
  updated_at timestamptz,
  created_by integer,
  cliente_nombre varchar,
  cliente_telefono varchar,
  cliente_email varchar,
  ficha_numero varchar
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    c.id,
    c.id_asesor,
    c.id_cliente,
    c.id_ficha_no_op,
    c.titulo,
    c.descripcion,
    c.fecha_cita,
    c.duracion_minutos,
    c.direccion,
    c.ubicacion_link,
    c.estado,
    c.notas,
    c.created_at,
    c.updated_at,
    c.created_by,
    cl.nombre AS cliente_nombre,
    cl.telefono AS cliente_telefono,
    cl.email AS cliente_email,
    ot.numero_op AS ficha_numero
  FROM public.citas_asesor_tecnico c
  LEFT JOIN public.clientes cl ON c.id_cliente = cl.id
  LEFT JOIN public.ordenes_trabajo ot ON c.id_ficha_no_op = ot.id
  WHERE c.id_asesor = p_id_asesor
    AND (p_fecha_desde IS NULL OR c.fecha_cita >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR c.fecha_cita <= p_fecha_hasta)
  ORDER BY c.fecha_cita ASC;
END;
$$;

-- ============================================
-- 3. FUNCIÓN PARA CREAR CITA
-- ============================================
CREATE OR REPLACE FUNCTION public.crear_cita_asesor(
  p_id_asesor integer,
  p_titulo varchar,
  p_fecha_cita timestamptz,
  p_id_cliente integer DEFAULT NULL,
  p_id_ficha_no_op integer DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_duracion_minutos integer DEFAULT 60,
  p_direccion text DEFAULT NULL,
  p_ubicacion_link text DEFAULT NULL,
  p_estado varchar DEFAULT 'programada',
  p_notas text DEFAULT NULL,
  p_created_by integer DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  titulo varchar,
  fecha_cita timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  nueva_cita_id integer;
BEGIN
  INSERT INTO public.citas_asesor_tecnico (
    id_asesor,
    id_cliente,
    id_ficha_no_op,
    titulo,
    descripcion,
    fecha_cita,
    duracion_minutos,
    direccion,
    ubicacion_link,
    estado,
    notas,
    created_by
  ) VALUES (
    p_id_asesor,
    p_id_cliente,
    p_id_ficha_no_op,
    p_titulo,
    p_descripcion,
    p_fecha_cita,
    p_duracion_minutos,
    p_direccion,
    p_ubicacion_link,
    p_estado,
    p_notas,
    p_created_by
  )
  RETURNING public.citas_asesor_tecnico.id INTO nueva_cita_id;

  RETURN QUERY
  SELECT 
    c.id,
    c.titulo,
    c.fecha_cita
  FROM public.citas_asesor_tecnico c
  WHERE c.id = nueva_cita_id;
END;
$$;

-- ============================================
-- 4. FUNCIÓN PARA ACTUALIZAR CITA
-- ============================================
CREATE OR REPLACE FUNCTION public.actualizar_cita_asesor(
  p_id integer,
  p_titulo varchar DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_fecha_cita timestamptz DEFAULT NULL,
  p_duracion_minutos integer DEFAULT NULL,
  p_direccion text DEFAULT NULL,
  p_ubicacion_link text DEFAULT NULL,
  p_estado varchar DEFAULT NULL,
  p_notas text DEFAULT NULL
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.citas_asesor_tecnico
  SET 
    titulo = COALESCE(p_titulo, titulo),
    descripcion = COALESCE(p_descripcion, descripcion),
    fecha_cita = COALESCE(p_fecha_cita, fecha_cita),
    duracion_minutos = COALESCE(p_duracion_minutos, duracion_minutos),
    direccion = COALESCE(p_direccion, direccion),
    ubicacion_link = COALESCE(p_ubicacion_link, ubicacion_link),
    estado = COALESCE(p_estado, estado),
    notas = COALESCE(p_notas, notas),
    updated_at = now()
  WHERE id = p_id;

  RETURN FOUND;
END;
$$;

-- ============================================
-- 5. FUNCIÓN PARA ELIMINAR CITA
-- ============================================
CREATE OR REPLACE FUNCTION public.eliminar_cita_asesor(
  p_id integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.citas_asesor_tecnico
  WHERE id = p_id;

  RETURN FOUND;
END;
$$;

-- ============================================
-- 6. POLÍTICAS RLS (Row Level Security)
-- ============================================
ALTER TABLE public.citas_asesor_tecnico ENABLE ROW LEVEL SECURITY;

-- Permitir a los asesores técnicos ver sus propias citas
CREATE POLICY "Asesores pueden ver sus citas"
  ON public.citas_asesor_tecnico
  FOR SELECT
  USING (
    auth.uid() IN (
      SELECT id FROM public.usuarios 
      WHERE id = id_asesor 
        AND (roles @> '["asesor-tecnico"]'::jsonb OR roles @> '["administracion"]'::jsonb)
    )
  );

-- Permitir a administradores ver todas las citas
CREATE POLICY "Admin puede ver todas las citas"
  ON public.citas_asesor_tecnico
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios 
      WHERE id::text = auth.uid()::text 
        AND roles @> '["administracion"]'::jsonb
    )
  );

-- Permitir crear citas
CREATE POLICY "Asesores pueden crear citas"
  ON public.citas_asesor_tecnico
  FOR INSERT
  WITH CHECK (
    auth.uid() IN (
      SELECT id FROM public.usuarios 
      WHERE (roles @> '["asesor-tecnico"]'::jsonb OR roles @> '["administracion"]'::jsonb)
    )
  );

-- Permitir actualizar citas propias
CREATE POLICY "Asesores pueden actualizar sus citas"
  ON public.citas_asesor_tecnico
  FOR UPDATE
  USING (
    auth.uid() IN (
      SELECT id FROM public.usuarios 
      WHERE id = id_asesor 
        AND (roles @> '["asesor-tecnico"]'::jsonb OR roles @> '["administracion"]'::jsonb)
    )
  );

-- Permitir eliminar citas propias
CREATE POLICY "Asesores pueden eliminar sus citas"
  ON public.citas_asesor_tecnico
  FOR DELETE
  USING (
    auth.uid() IN (
      SELECT id FROM public.usuarios 
      WHERE id = id_asesor 
        AND (roles @> '["asesor-tecnico"]'::jsonb OR roles @> '["administracion"]'::jsonb)
    )
  );

COMMIT;

