-- Crear tablas para sistema de pedidos de compra

BEGIN;

-- Tabla principal de pedidos de compra
CREATE TABLE IF NOT EXISTS public.pedidos_compras (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_pedido varchar(50) NOT NULL UNIQUE,
  id_solicitante integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_solicitante varchar(100) NOT NULL,
  sector_solicitante varchar(100),
  estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
    estado IN ('Pendiente', 'En Revisión', 'Aprobado', 'Rechazado', 'En Compra', 'Completado', 'Cancelado')
  ),
  prioridad varchar(50) NOT NULL DEFAULT 'Normal' CHECK (
    prioridad IN ('Baja', 'Normal', 'Alta', 'Urgente')
  ),
  motivo text,
  observaciones text,
  fecha_solicitud timestamptz NOT NULL DEFAULT now(),
  fecha_aprobacion timestamptz,
  fecha_rechazo timestamptz,
  fecha_completado timestamptz,
  id_aprobador integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  nombre_aprobador varchar(100),
  motivo_rechazo text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de items de pedidos de compra
CREATE TABLE IF NOT EXISTS public.pedidos_compras_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido integer NOT NULL REFERENCES public.pedidos_compras(id) ON DELETE CASCADE,
  id_articulo_stock integer, -- ID del artículo en la base de stock
  codigo_articulo varchar(100),
  descripcion text NOT NULL,
  cantidad_solicitada numeric(10,3) NOT NULL DEFAULT 1.000,
  cantidad_aprobada numeric(10,3),
  cantidad_comprada numeric(10,3),
  unidad varchar(50) DEFAULT 'unidad',
  precio_unitario numeric(10,2),
  precio_total numeric(10,2),
  proveedor varchar(255),
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de comentarios en pedidos de compra
CREATE TABLE IF NOT EXISTS public.pedidos_compras_comentarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido integer NOT NULL REFERENCES public.pedidos_compras(id) ON DELETE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  nombre_usuario varchar(100) NOT NULL,
  comentario text NOT NULL,
  es_interno boolean DEFAULT false, -- Si es true, solo lo ve compras
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Tabla de historial de movimientos de stock
CREATE TABLE IF NOT EXISTS public.stock_movimientos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo_stock integer NOT NULL,
  codigo_articulo varchar(100),
  descripcion text NOT NULL,
  tipo_movimiento varchar(50) NOT NULL CHECK (
    tipo_movimiento IN ('Entrada', 'Salida', 'Ajuste', 'Pedido', 'Venta', 'Devolución')
  ),
  cantidad numeric(10,3) NOT NULL,
  cantidad_anterior numeric(10,3),
  cantidad_nueva numeric(10,3),
  motivo text,
  id_orden_trabajo integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  nombre_usuario varchar(100),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_solicitante ON public.pedidos_compras(id_solicitante);
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_estado ON public.pedidos_compras(estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_fecha ON public.pedidos_compras(fecha_solicitud DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_aprobador ON public.pedidos_compras(id_aprobador);

CREATE INDEX IF NOT EXISTS idx_pedidos_compras_items_pedido ON public.pedidos_compras_items(id_pedido);
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_items_articulo ON public.pedidos_compras_items(id_articulo_stock);

CREATE INDEX IF NOT EXISTS idx_pedidos_compras_comentarios_pedido ON public.pedidos_compras_comentarios(id_pedido);
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_comentarios_usuario ON public.pedidos_compras_comentarios(id_usuario);
CREATE INDEX IF NOT EXISTS idx_pedidos_compras_comentarios_fecha ON public.pedidos_compras_comentarios(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_articulo ON public.stock_movimientos(id_articulo_stock);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_tipo ON public.stock_movimientos(tipo_movimiento);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_fecha ON public.stock_movimientos(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_orden ON public.stock_movimientos(id_orden_trabajo);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_pedido ON public.stock_movimientos(id_pedido_compra);

-- Función para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION public.update_pedido_compra_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para actualizar updated_at
DROP TRIGGER IF EXISTS trigger_update_pedido_compra_updated_at ON public.pedidos_compras;
CREATE TRIGGER trigger_update_pedido_compra_updated_at
  BEFORE UPDATE ON public.pedidos_compras
  FOR EACH ROW
  EXECUTE FUNCTION public.update_pedido_compra_updated_at();

-- Función para generar número de pedido automático
CREATE OR REPLACE FUNCTION public.generar_numero_pedido()
RETURNS TRIGGER AS $$
DECLARE
  nuevo_numero varchar(50);
  año_actual varchar(4);
  ultimo_numero integer;
BEGIN
  año_actual := TO_CHAR(now(), 'YYYY');
  
  -- Obtener el último número del año actual
  SELECT COALESCE(MAX(CAST(SUBSTRING(numero_pedido FROM '[0-9]+$') AS integer)), 0)
  INTO ultimo_numero
  FROM public.pedidos_compras
  WHERE numero_pedido LIKE 'PC-' || año_actual || '-%';
  
  -- Generar nuevo número
  nuevo_numero := 'PC-' || año_actual || '-' || LPAD((ultimo_numero + 1)::text, 4, '0');
  
  NEW.numero_pedido := nuevo_numero;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para generar número de pedido automáticamente
DROP TRIGGER IF EXISTS trigger_generar_numero_pedido ON public.pedidos_compras;
CREATE TRIGGER trigger_generar_numero_pedido
  BEFORE INSERT ON public.pedidos_compras
  FOR EACH ROW
  WHEN (NEW.numero_pedido IS NULL OR NEW.numero_pedido = '')
  EXECUTE FUNCTION public.generar_numero_pedido();

COMMIT;

