-- Crear tabla de galería de trabajos completados
CREATE TABLE IF NOT EXISTS public.galeria_trabajos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  numero_op varchar(255) NOT NULL,
  cliente varchar(255) NOT NULL,
  titulo text,
  descripcion text,
  imagen_url text NOT NULL,
  categoria text,
  tags text[],
  fecha_completado date NOT NULL,
  usuario_subio_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  usuario_subio_nombre varchar(100),
  visible_publico boolean DEFAULT true,
  destacado boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_galeria_orden ON public.galeria_trabajos(id_orden);
CREATE INDEX IF NOT EXISTS idx_galeria_fecha ON public.galeria_trabajos(fecha_completado DESC);
CREATE INDEX IF NOT EXISTS idx_galeria_categoria ON public.galeria_trabajos(categoria);
CREATE INDEX IF NOT EXISTS idx_galeria_destacado ON public.galeria_trabajos(destacado) WHERE destacado = true;
CREATE INDEX IF NOT EXISTS idx_galeria_visible ON public.galeria_trabajos(visible_publico) WHERE visible_publico = true;

-- Función para agregar trabajo a la galería
CREATE OR REPLACE FUNCTION public.agregar_trabajo_galeria(
  p_id_orden integer,
  p_numero_op varchar(255),
  p_cliente varchar(255),
  p_titulo text DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_imagen_url text,
  p_categoria text DEFAULT NULL,
  p_tags text[] DEFAULT NULL,
  p_fecha_completado date DEFAULT CURRENT_DATE,
  p_usuario_subio_id integer DEFAULT NULL,
  p_usuario_subio_nombre varchar(100) DEFAULT NULL,
  p_visible_publico boolean DEFAULT true,
  p_destacado boolean DEFAULT false
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_id integer;
BEGIN
  INSERT INTO public.galeria_trabajos (
    id_orden,
    numero_op,
    cliente,
    titulo,
    descripcion,
    imagen_url,
    categoria,
    tags,
    fecha_completado,
    usuario_subio_id,
    usuario_subio_nombre,
    visible_publico,
    destacado
  )
  VALUES (
    p_id_orden,
    p_numero_op,
    p_cliente,
    p_titulo,
    p_descripcion,
    p_imagen_url,
    p_categoria,
    p_tags,
    p_fecha_completado,
    p_usuario_subio_id,
    p_usuario_subio_nombre,
    p_visible_publico,
    p_destacado
  )
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$;

-- Función para obtener trabajos de la galería
CREATE OR REPLACE FUNCTION public.obtener_trabajos_galeria(
  p_categoria text DEFAULT NULL,
  p_limit integer DEFAULT 50,
  p_offset integer DEFAULT 0,
  p_solo_destacados boolean DEFAULT false,
  p_solo_publicos boolean DEFAULT true
)
RETURNS TABLE (
  id integer,
  id_orden integer,
  numero_op varchar(255),
  cliente varchar(255),
  titulo text,
  descripcion text,
  imagen_url text,
  categoria text,
  tags text[],
  fecha_completado date,
  usuario_subio_nombre varchar(100),
  visible_publico boolean,
  destacado boolean,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    g.id,
    g.id_orden,
    g.numero_op,
    g.cliente,
    g.titulo,
    g.descripcion,
    g.imagen_url,
    g.categoria,
    g.tags,
    g.fecha_completado,
    g.usuario_subio_nombre,
    g.visible_publico,
    g.destacado,
    g.created_at
  FROM public.galeria_trabajos g
  WHERE 
    (p_categoria IS NULL OR g.categoria = p_categoria) AND
    (NOT p_solo_destacados OR g.destacado = true) AND
    (NOT p_solo_publicos OR g.visible_publico = true)
  ORDER BY g.destacado DESC, g.fecha_completado DESC
  LIMIT p_limit
  OFFSET p_offset;
END;
$$;

-- Función para obtener categorías disponibles
CREATE OR REPLACE FUNCTION public.obtener_categorias_galeria()
RETURNS TABLE (categoria text, cantidad integer)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    g.categoria,
    COUNT(*)::integer as cantidad
  FROM public.galeria_trabajos g
  WHERE g.visible_publico = true
  GROUP BY g.categoria
  ORDER BY cantidad DESC;
END;
$$;

-- Comentarios
COMMENT ON TABLE public.galeria_trabajos IS 'Galería de trabajos completados para mostrar al público';
COMMENT ON FUNCTION public.agregar_trabajo_galeria IS 'Agrega un trabajo completado a la galería';
COMMENT ON FUNCTION public.obtener_trabajos_galeria IS 'Obtiene trabajos de la galería con filtros';
COMMENT ON FUNCTION public.obtener_categorias_galeria IS 'Obtiene las categorías disponibles en la galería';

