-- ============================================
-- VERIFICACIÓN Y CREACIÓN DE ESTRUCTURA PARA DASHBOARD DE CAJA
-- ============================================
-- Este script verifica y crea las tablas y funciones necesarias
-- para el Dashboard de Caja si no existen

BEGIN;

-- Verificar y crear tabla cuentas_por_cobrar si no existe
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'cuentas_por_cobrar') THEN
    CREATE TABLE public.cuentas_por_cobrar (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id_factura integer,
      id_cliente integer REFERENCES public.clientes(id) ON DELETE SET NULL,
      cliente_nombre varchar(255) NOT NULL,
      monto_total numeric(15,2) NOT NULL,
      monto_pagado numeric(15,2) NOT NULL DEFAULT 0,
      monto_pendiente numeric(15,2) NOT NULL,
      fecha_emision date NOT NULL,
      fecha_vencimiento date,
      estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
        estado IN ('Pendiente', 'Parcial', 'Pagado', 'Vencido', 'Cancelado')
      ),
      observaciones text,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    );

    -- Agregar foreign key a facturas_venta solo si la tabla existe
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'facturas_venta') THEN
      ALTER TABLE public.cuentas_por_cobrar 
      ADD CONSTRAINT cuentas_por_cobrar_id_factura_fkey 
      FOREIGN KEY (id_factura) REFERENCES public.facturas_venta(id) ON DELETE CASCADE;
    END IF;

    CREATE INDEX idx_cxc_factura ON public.cuentas_por_cobrar(id_factura);
    CREATE INDEX idx_cxc_cliente ON public.cuentas_por_cobrar(id_cliente);
    CREATE INDEX idx_cxc_estado ON public.cuentas_por_cobrar(estado);
    CREATE INDEX idx_cxc_vencimiento ON public.cuentas_por_cobrar(fecha_vencimiento);
    
    RAISE NOTICE 'Tabla cuentas_por_cobrar creada';
  ELSE
    RAISE NOTICE 'Tabla cuentas_por_cobrar ya existe';
  END IF;
END $$;

-- Verificar y crear tabla cuentas_por_pagar si no existe
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'cuentas_por_pagar') THEN
    CREATE TABLE public.cuentas_por_pagar (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL,
      id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
      proveedor_nombre varchar(255) NOT NULL,
      numero_documento varchar(100),
      monto_total numeric(15,2) NOT NULL,
      monto_pagado numeric(15,2) NOT NULL DEFAULT 0,
      monto_pendiente numeric(15,2) NOT NULL,
      fecha_emision date NOT NULL,
      fecha_vencimiento date,
      estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
        estado IN ('Pendiente', 'Parcial', 'Pagado', 'Vencido', 'Cancelado')
      ),
      observaciones text,
      created_at timestamptz NOT NULL DEFAULT now(),
      updated_at timestamptz NOT NULL DEFAULT now()
    );

    CREATE INDEX idx_cxp_pedido ON public.cuentas_por_pagar(id_pedido_compra);
    CREATE INDEX idx_cxp_proveedor ON public.cuentas_por_pagar(id_proveedor);
    CREATE INDEX idx_cxp_estado ON public.cuentas_por_pagar(estado);
    CREATE INDEX idx_cxp_vencimiento ON public.cuentas_por_pagar(fecha_vencimiento);
    
    RAISE NOTICE 'Tabla cuentas_por_pagar creada';
  ELSE
    RAISE NOTICE 'Tabla cuentas_por_pagar ya existe';
  END IF;
END $$;

-- Verificar y crear función obtener_flujo_caja si no existe
CREATE OR REPLACE FUNCTION public.obtener_flujo_caja(
  p_fecha_desde date,
  p_fecha_hasta date
)
RETURNS TABLE (
  fecha date,
  concepto varchar,
  tipo varchar,
  ingreso numeric,
  egreso numeric,
  saldo_acumulado numeric
) AS $$
DECLARE
  v_saldo_inicial numeric := 0;
  v_saldo_actual numeric := 0;
BEGIN
  
  -- Calcular saldo inicial solo si las tablas existen
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'plan_cuentas')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'asientos_contables')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'asientos_detalle') THEN
    
    SELECT COALESCE(SUM(
    CASE
      WHEN pc.tipo IN ('Activo') AND pc.codigo LIKE '1.1.1%' THEN
        CASE WHEN pc.naturaleza = 'Deudora' THEN ad.debe - ad.haber ELSE ad.haber - ad.debe END
      ELSE 0
    END
  ), 0) INTO v_saldo_inicial
  FROM public.asientos_detalle ad
  JOIN public.plan_cuentas pc ON pc.id = ad.id_cuenta
  JOIN public.asientos_contables ac ON ac.id = ad.id_asiento
  WHERE ac.fecha < p_fecha_desde
      AND ac.estado = 'Contabilizado'
      AND pc.codigo LIKE '1.1.1%'; -- Caja y Bancos
  END IF;

  v_saldo_actual := v_saldo_inicial;

  -- Retornar movimientos en el período solo si las tablas existen
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'plan_cuentas')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'asientos_contables')
     AND EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'asientos_detalle') THEN
    
    RETURN QUERY
  WITH movimientos AS (
    SELECT
      ac.fecha,
      ac.concepto,
      CASE
        WHEN pc.codigo LIKE '4.%' THEN 'Ingreso'
        WHEN pc.codigo LIKE '5.%' OR pc.codigo LIKE '6.%' THEN 'Egreso'
        WHEN pc.codigo LIKE '1.1.1%' THEN 'Movimiento'
        ELSE 'Otro'
      END as tipo_movimiento,
      CASE
        WHEN pc.codigo LIKE '4.%' AND ad.haber > 0 THEN ad.haber
        WHEN pc.codigo LIKE '1.1.1%' AND ad.debe > 0 THEN ad.debe
        ELSE 0
      END as ingreso,
      CASE
        WHEN (pc.codigo LIKE '5.%' OR pc.codigo LIKE '6.%') AND ad.debe > 0 THEN ad.debe
        WHEN pc.codigo LIKE '1.1.1%' AND ad.haber > 0 THEN ad.haber
        ELSE 0
      END as egreso
    FROM public.asientos_detalle ad
    JOIN public.plan_cuentas pc ON pc.id = ad.id_cuenta
    JOIN public.asientos_contables ac ON ac.id = ad.id_asiento
    WHERE ac.fecha >= p_fecha_desde
      AND ac.fecha <= p_fecha_hasta
      AND ac.estado = 'Contabilizado'
      AND (
        pc.codigo LIKE '1.1.1%' OR -- Caja y Bancos
        pc.codigo LIKE '4.%' OR     -- Ingresos
        pc.codigo LIKE '5.%' OR     -- Costos
        pc.codigo LIKE '6.%'        -- Gastos
      )
  )
  SELECT
    m.fecha,
    m.concepto::varchar,
    m.tipo_movimiento::varchar as tipo,
    m.ingreso,
    m.egreso,
    (v_saldo_inicial + SUM(m.ingreso - m.egreso) OVER (ORDER BY m.fecha, m.concepto))::numeric as saldo_acumulado
    FROM movimientos m
    ORDER BY m.fecha, m.concepto;
  ELSE
    -- Si no existen las tablas del ERP, retornar tabla vacía
    RETURN;
  END IF;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.obtener_flujo_caja IS 'Obtiene el flujo de caja para un período determinado';

-- Verificar que existan las tablas necesarias para flujo de caja
DO $$
BEGIN
  -- Verificar plan_cuentas
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'plan_cuentas') THEN
    RAISE WARNING 'Tabla plan_cuentas no existe. El flujo de caja puede no funcionar correctamente.';
  END IF;
  
  -- Verificar asientos_contables
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'asientos_contables') THEN
    RAISE WARNING 'Tabla asientos_contables no existe. El flujo de caja puede no funcionar correctamente.';
  END IF;
  
  -- Verificar asientos_detalle
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'asientos_detalle') THEN
    RAISE WARNING 'Tabla asientos_detalle no existe. El flujo de caja puede no funcionar correctamente.';
  END IF;
END $$;

COMMIT;

-- Mensaje final
DO $$
BEGIN
  RAISE NOTICE 'Verificación completada. El Dashboard de Caja está listo para usar.';
END $$;

