-- ============================================
-- SISTEMA ERP COMPLETO - INTEGRACIÓN CON SISTEMA EXISTENTE
-- ============================================
-- Este script crea la estructura completa para:
-- - Plan de Cuentas Contable
-- - Asientos Contables (Partida Doble)
-- - Facturación (con preparación para AFIP)
-- - Control de Costos por OP
-- - Cuentas por Pagar/Cobrar
-- - Reportes Financieros
-- ============================================

-- ============================================
-- 1. PLAN DE CUENTAS
-- ============================================
CREATE TABLE IF NOT EXISTS public.plan_cuentas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(20) NOT NULL UNIQUE,
  nombre varchar(255) NOT NULL,
  tipo varchar(50) NOT NULL CHECK (
    tipo IN ('Activo', 'Pasivo', 'Patrimonio', 'Ingreso', 'Costo', 'Gasto', 'Cuenta de Orden')
  ),
  nivel integer NOT NULL DEFAULT 1 CHECK (nivel >= 1 AND nivel <= 5),
  cuenta_padre_id integer REFERENCES public.plan_cuentas(id) ON DELETE SET NULL,
  naturaleza varchar(10) NOT NULL CHECK (naturaleza IN ('Deudora', 'Acreedora')),
  activa boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_plan_cuentas_codigo ON public.plan_cuentas(codigo);
CREATE INDEX IF NOT EXISTS idx_plan_cuentas_tipo ON public.plan_cuentas(tipo);
CREATE INDEX IF NOT EXISTS idx_plan_cuentas_padre ON public.plan_cuentas(cuenta_padre_id);
CREATE INDEX IF NOT EXISTS idx_plan_cuentas_activa ON public.plan_cuentas(activa);

-- ============================================
-- 2. ASIENTOS CONTABLES
-- ============================================
CREATE TABLE IF NOT EXISTS public.asientos_contables (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_asiento varchar(50) NOT NULL UNIQUE,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  concepto text NOT NULL,
  tipo_asiento varchar(50) NOT NULL DEFAULT 'Manual' CHECK (
    tipo_asiento IN ('Manual', 'Automático', 'Facturación', 'Compra', 'Pago', 'Cobro', 'Ajuste')
  ),
  id_origen integer, -- ID de la operación que originó el asiento (factura, compra, etc.)
  tipo_origen varchar(50), -- Tipo de origen: 'factura', 'compra', 'op', etc.
  total_debe numeric(15,2) NOT NULL DEFAULT 0,
  total_haber numeric(15,2) NOT NULL DEFAULT 0,
  estado varchar(50) NOT NULL DEFAULT 'Borrador' CHECK (
    estado IN ('Borrador', 'Contabilizado', 'Anulado')
  ),
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT check_partida_doble CHECK (total_debe = total_haber)
);

CREATE INDEX IF NOT EXISTS idx_asientos_fecha ON public.asientos_contables(fecha);
CREATE INDEX IF NOT EXISTS idx_asientos_tipo ON public.asientos_contables(tipo_asiento);
CREATE INDEX IF NOT EXISTS idx_asientos_estado ON public.asientos_contables(estado);
CREATE INDEX IF NOT EXISTS idx_asientos_origen ON public.asientos_contables(tipo_origen, id_origen);

-- ============================================
-- 3. DETALLE DE ASIENTOS CONTABLES
-- ============================================
CREATE TABLE IF NOT EXISTS public.asientos_detalle (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asiento integer NOT NULL REFERENCES public.asientos_contables(id) ON DELETE CASCADE,
  id_cuenta integer NOT NULL REFERENCES public.plan_cuentas(id) ON DELETE RESTRICT,
  debe numeric(15,2) NOT NULL DEFAULT 0,
  haber numeric(15,2) NOT NULL DEFAULT 0,
  concepto text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT check_debe_haber CHECK (
    (debe > 0 AND haber = 0) OR (debe = 0 AND haber > 0)
  )
);

CREATE INDEX IF NOT EXISTS idx_asientos_detalle_asiento ON public.asientos_detalle(id_asiento);
CREATE INDEX IF NOT EXISTS idx_asientos_detalle_cuenta ON public.asientos_detalle(id_cuenta);

-- ============================================
-- 4. FACTURAS DE VENTA
-- ============================================
CREATE TABLE IF NOT EXISTS public.facturas_venta (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_factura varchar(50) NOT NULL UNIQUE,
  punto_venta integer NOT NULL DEFAULT 1,
  numero_comprobante integer NOT NULL,
  tipo_comprobante varchar(50) NOT NULL DEFAULT 'Factura A' CHECK (
    tipo_comprobante IN ('Factura A', 'Factura B', 'Factura C', 'Nota de Crédito A', 'Nota de Crédito B', 'Nota de Crédito C', 'Nota de Débito A', 'Nota de Débito B', 'Nota de Débito C')
  ),
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  fecha_vencimiento date,
  id_cliente integer REFERENCES public.clientes(id) ON DELETE SET NULL,
  cliente_nombre varchar(255) NOT NULL,
  cliente_dni_cuit varchar(50),
  cliente_direccion text,
  cliente_condicion_iva varchar(50) CHECK (
    cliente_condicion_iva IN ('Responsable Inscripto', 'Monotributista', 'Exento', 'Consumidor Final', 'No Responsable')
  ),
  id_op integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  numero_op varchar(255),
  id_venta integer REFERENCES public.ventas(id) ON DELETE SET NULL,
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  descuento numeric(15,2) NOT NULL DEFAULT 0,
  iva numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  estado varchar(50) NOT NULL DEFAULT 'Borrador' CHECK (
    estado IN ('Borrador', 'Emitida', 'Anulada', 'Cancelada')
  ),
  estado_afip varchar(50), -- 'Pendiente', 'Autorizada', 'Rechazada', 'Error', 'Enviando'
  cae varchar(50), -- Código de Autorización Electrónico (AFIP)
  fecha_vencimiento_cae date, -- Fecha de vencimiento del CAE
  numero_cae varchar(50), -- Número de CAE asignado por AFIP
  resultado_afip text, -- Mensaje de resultado de AFIP (si hay error)
  codigo_resultado_afip varchar(10), -- Código de resultado de AFIP
  fecha_autorizacion_afip timestamptz, -- Fecha de autorización por AFIP
  id_asiento_contable integer REFERENCES public.asientos_contables(id) ON DELETE SET NULL,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_facturas_numero ON public.facturas_venta(numero_factura);
CREATE INDEX IF NOT EXISTS idx_facturas_fecha ON public.facturas_venta(fecha_emision);
CREATE INDEX IF NOT EXISTS idx_facturas_cliente ON public.facturas_venta(id_cliente);
CREATE INDEX IF NOT EXISTS idx_facturas_op ON public.facturas_venta(id_op);
CREATE INDEX IF NOT EXISTS idx_facturas_venta ON public.facturas_venta(id_venta);
CREATE INDEX IF NOT EXISTS idx_facturas_estado ON public.facturas_venta(estado);
CREATE INDEX IF NOT EXISTS idx_facturas_tipo ON public.facturas_venta(tipo_comprobante);

-- ============================================
-- 5. ITEMS DE FACTURAS
-- ============================================
CREATE TABLE IF NOT EXISTS public.facturas_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura integer NOT NULL REFERENCES public.facturas_venta(id) ON DELETE CASCADE,
  item_numero integer NOT NULL,
  descripcion text NOT NULL,
  cantidad numeric(10,2) NOT NULL DEFAULT 1,
  unidad_medida varchar(20) DEFAULT 'UN',
  precio_unitario numeric(15,2) NOT NULL,
  descuento numeric(15,2) NOT NULL DEFAULT 0,
  iva_porcentaje numeric(5,2) NOT NULL DEFAULT 21.00,
  iva_monto numeric(15,2) NOT NULL DEFAULT 0,
  subtotal numeric(15,2) NOT NULL,
  total numeric(15,2) NOT NULL,
  id_articulo integer, -- Referencia opcional a artículo
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_facturas_items_factura ON public.facturas_items(id_factura);

-- ============================================
-- 6. COSTOS POR ORDEN DE TRABAJO
-- ============================================
CREATE TABLE IF NOT EXISTS public.costos_op (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_op integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  numero_op varchar(255) NOT NULL,
  tipo_costo varchar(50) NOT NULL CHECK (
    tipo_costo IN ('Materiales', 'Mano de Obra', 'Gastos Generales', 'Subcontratación', 'Otros')
  ),
  concepto text NOT NULL,
  cantidad numeric(10,2) NOT NULL DEFAULT 1,
  costo_unitario numeric(15,2) NOT NULL,
  costo_total numeric(15,2) NOT NULL,
  id_material integer, -- Referencia opcional a material usado
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  fecha_costo date NOT NULL DEFAULT CURRENT_DATE,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_costos_op ON public.costos_op(id_op);
CREATE INDEX IF NOT EXISTS idx_costos_tipo ON public.costos_op(tipo_costo);
CREATE INDEX IF NOT EXISTS idx_costos_fecha ON public.costos_op(fecha_costo);

-- ============================================
-- 7. CUENTAS POR COBRAR
-- ============================================
CREATE TABLE IF NOT EXISTS public.cuentas_por_cobrar (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura integer NOT NULL REFERENCES public.facturas_venta(id) ON DELETE CASCADE,
  id_cliente integer REFERENCES public.clientes(id) ON DELETE SET NULL,
  cliente_nombre varchar(255) NOT NULL,
  monto_total numeric(15,2) NOT NULL,
  monto_pagado numeric(15,2) NOT NULL DEFAULT 0,
  monto_pendiente numeric(15,2) NOT NULL,
  fecha_emision date NOT NULL,
  fecha_vencimiento date,
  estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
    estado IN ('Pendiente', 'Parcial', 'Pagado', 'Vencido', 'Cancelado')
  ),
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cxc_factura ON public.cuentas_por_cobrar(id_factura);
CREATE INDEX IF NOT EXISTS idx_cxc_cliente ON public.cuentas_por_cobrar(id_cliente);
CREATE INDEX IF NOT EXISTS idx_cxc_estado ON public.cuentas_por_cobrar(estado);
CREATE INDEX IF NOT EXISTS idx_cxc_vencimiento ON public.cuentas_por_cobrar(fecha_vencimiento);

-- ============================================
-- 8. CUENTAS POR PAGAR
-- ============================================
CREATE TABLE IF NOT EXISTS public.cuentas_por_pagar (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  proveedor_nombre varchar(255) NOT NULL,
  numero_documento varchar(100),
  monto_total numeric(15,2) NOT NULL,
  monto_pagado numeric(15,2) NOT NULL DEFAULT 0,
  monto_pendiente numeric(15,2) NOT NULL,
  fecha_emision date NOT NULL,
  fecha_vencimiento date,
  estado varchar(50) NOT NULL DEFAULT 'Pendiente' CHECK (
    estado IN ('Pendiente', 'Parcial', 'Pagado', 'Vencido', 'Cancelado')
  ),
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cxp_pedido ON public.cuentas_por_pagar(id_pedido_compra);
CREATE INDEX IF NOT EXISTS idx_cxp_proveedor ON public.cuentas_por_pagar(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_cxp_estado ON public.cuentas_por_pagar(estado);
CREATE INDEX IF NOT EXISTS idx_cxp_vencimiento ON public.cuentas_por_pagar(fecha_vencimiento);

-- ============================================
-- 9. PAGOS Y COBROS
-- ============================================
CREATE TABLE IF NOT EXISTS public.pagos_cobros (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo varchar(10) NOT NULL CHECK (tipo IN ('Pago', 'Cobro')),
  id_cuenta_por_cobrar integer REFERENCES public.cuentas_por_cobrar(id) ON DELETE SET NULL,
  id_cuenta_por_pagar integer REFERENCES public.cuentas_por_pagar(id) ON DELETE SET NULL,
  monto numeric(15,2) NOT NULL,
  fecha_pago date NOT NULL DEFAULT CURRENT_DATE,
  metodo_pago varchar(50) NOT NULL CHECK (
    metodo_pago IN ('Efectivo', 'Transferencia', 'Tarjeta', 'Cheque', 'Depósito', 'Otro')
  ),
  numero_comprobante varchar(100),
  id_cuenta_bancaria integer, -- Referencia a cuenta bancaria (si aplica)
  id_asiento_contable integer REFERENCES public.asientos_contables(id) ON DELETE SET NULL,
  observaciones text,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pagos_cobros_tipo ON public.pagos_cobros(tipo);
CREATE INDEX IF NOT EXISTS idx_pagos_cobros_cxc ON public.pagos_cobros(id_cuenta_por_cobrar);
CREATE INDEX IF NOT EXISTS idx_pagos_cobros_cxp ON public.pagos_cobros(id_cuenta_por_pagar);
CREATE INDEX IF NOT EXISTS idx_pagos_cobros_fecha ON public.pagos_cobros(fecha_pago);

-- ============================================
-- 10. CONFIGURACIÓN AFIP
-- ============================================
-- Nota: Para facturación electrónica con detalle de items, se utiliza wsmtxca (R.G. N° 2.904)
-- Documentación: https://www.afip.gob.ar/ws/documentacion/ws-factura-electronica.asp
-- Homologación Externa (R.G. N° 5.616/2024): https://www.afip.gob.ar/ws/documentacion/homologacion-externa.asp
-- IMPORTANTE: Es obligatorio realizar homologación externa antes de pasar a producción
CREATE TABLE IF NOT EXISTS public.configuracion_afip (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cuit varchar(20) NOT NULL,
  punto_venta integer NOT NULL DEFAULT 1,
  razon_social varchar(255) NOT NULL,
  domicilio_comercial text,
  condicion_iva varchar(50) NOT NULL,
  ingresos_brutos varchar(100),
  fecha_inicio_actividades date,
  actividad_principal text,
  -- Certificados digitales (encriptados)
  certificado_afip bytea, -- Certificado .p12 o .pfx
  clave_certificado text, -- Clave del certificado (encriptada)
  -- Configuración del Web Service
  webservice varchar(50) NOT NULL DEFAULT 'wsmtxca' CHECK (webservice IN ('wsfev1', 'wsmtxca', 'wsfexv1')),
  -- wsmtxca: Para facturas A y B con detalle de items (recomendado)
  -- wsfev1: Para facturas A, B, C, M sin detalle de items
  -- wsfexv1: Para facturas tipo E (exportación)
  ambiente varchar(20) NOT NULL DEFAULT 'Testing' CHECK (ambiente IN ('Testing', 'Homologación', 'Producción')),
  -- Testing: Desarrollo y pruebas locales
  -- Homologación: Proceso de homologación externa con AFIP (obligatorio)
  -- Producción: Solo después de aprobación de homologación
  homologacion_aprobada boolean NOT NULL DEFAULT false, -- Indica si la homologación fue aprobada
  fecha_aprobacion_homologacion date, -- Fecha de aprobación de homologación
  numero_expediente_homologacion varchar(100), -- Número de expediente de homologación
  -- URLs de los servicios AFIP
  url_wsaa_testing varchar(255) DEFAULT 'https://wsaahomo.afip.gov.ar/ws/services/LoginCms',
  url_wsaa_produccion varchar(255) DEFAULT 'https://wsaa.afip.gov.ar/ws/services/LoginCms',
  url_wsmtxca_testing varchar(255) DEFAULT 'https://wswhomo.afip.gov.ar/wsfev1/service.asmx',
  url_wsmtxca_produccion varchar(255) DEFAULT 'https://servicios1.afip.gov.ar/wsmtxca/services/MTXCAService',
  -- Numeración de comprobantes
  ultimo_numero_factura_a integer DEFAULT 0,
  ultimo_numero_factura_b integer DEFAULT 0,
  ultimo_numero_factura_c integer DEFAULT 0,
  -- Tokens y autenticación (se renuevan periódicamente)
  token_afip text, -- Token obtenido de WSAA (temporal)
  sign_afip text, -- Sign obtenido de WSAA (temporal)
  token_expira_en timestamptz, -- Fecha de expiración del token
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================
-- 11. FUNCIONES RPC
-- ============================================

-- Generar número de asiento contable
CREATE OR REPLACE FUNCTION public.generar_numero_asiento()
RETURNS varchar(50) AS $$
DECLARE
  nuevo_numero varchar(50);
  ultimo_numero integer;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(numero_asiento FROM '[0-9]+$') AS integer)), 0) + 1
  INTO ultimo_numero
  FROM public.asientos_contables
  WHERE numero_asiento ~ '^AS-[0-9]+$';
  
  nuevo_numero := 'AS-' || LPAD(ultimo_numero::text, 6, '0');
  RETURN nuevo_numero;
END;
$$ LANGUAGE plpgsql;

-- Generar número de factura
CREATE OR REPLACE FUNCTION public.generar_numero_factura(
  p_tipo_comprobante varchar(50),
  p_punto_venta integer DEFAULT 1
)
RETURNS integer AS $$
DECLARE
  nuevo_numero integer;
  config_afip RECORD;
BEGIN
  -- Obtener configuración AFIP
  SELECT * INTO config_afip
  FROM public.configuracion_afip
  WHERE activo = true
  LIMIT 1;
  
  -- Determinar último número según tipo
  IF p_tipo_comprobante LIKE 'Factura A%' OR p_tipo_comprobante LIKE 'Nota de Crédito A%' OR p_tipo_comprobante LIKE 'Nota de Débito A%' THEN
    nuevo_numero := COALESCE(config_afip.ultimo_numero_factura_a, 0) + 1;
  ELSIF p_tipo_comprobante LIKE 'Factura B%' OR p_tipo_comprobante LIKE 'Nota de Crédito B%' OR p_tipo_comprobante LIKE 'Nota de Débito B%' THEN
    nuevo_numero := COALESCE(config_afip.ultimo_numero_factura_b, 0) + 1;
  ELSIF p_tipo_comprobante LIKE 'Factura C%' OR p_tipo_comprobante LIKE 'Nota de Crédito C%' OR p_tipo_comprobante LIKE 'Nota de Débito C%' THEN
    nuevo_numero := COALESCE(config_afip.ultimo_numero_factura_c, 0) + 1;
  ELSE
    nuevo_numero := 1;
  END IF;
  
  RETURN nuevo_numero;
END;
$$ LANGUAGE plpgsql;

-- Crear asiento contable automático desde factura
CREATE OR REPLACE FUNCTION public.crear_asiento_desde_factura(
  p_id_factura integer
)
RETURNS integer AS $$
DECLARE
  v_factura RECORD;
  v_asiento_id integer;
  v_numero_asiento varchar(50);
  v_cuenta_ventas integer;
  v_cuenta_iva integer;
  v_cuenta_clientes integer;
BEGIN
  -- Obtener datos de la factura
  SELECT * INTO v_factura
  FROM public.facturas_venta
  WHERE id = p_id_factura;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Factura no encontrada: %', p_id_factura;
  END IF;
  
  -- Buscar cuentas contables (configurables)
  -- Cuenta de Ventas
  SELECT id INTO v_cuenta_ventas
  FROM public.plan_cuentas
  WHERE codigo = '4.1.1.01' -- Ejemplo: Ventas de productos
  LIMIT 1;
  
  -- Cuenta de IVA Débito Fiscal
  SELECT id INTO v_cuenta_iva
  FROM public.plan_cuentas
  WHERE codigo = '1.1.2.01' -- Ejemplo: IVA Débito Fiscal
  LIMIT 1;
  
  -- Cuenta de Clientes
  SELECT id INTO v_cuenta_clientes
  FROM public.plan_cuentas
  WHERE codigo = '1.1.1.01' -- Ejemplo: Clientes
  LIMIT 1;
  
  -- Generar número de asiento
  v_numero_asiento := public.generar_numero_asiento();
  
  -- Crear asiento contable
  INSERT INTO public.asientos_contables (
    numero_asiento,
    fecha,
    concepto,
    tipo_asiento,
    id_origen,
    tipo_origen,
    total_debe,
    total_haber,
    estado
  ) VALUES (
    v_numero_asiento,
    v_factura.fecha_emision,
    'Factura ' || v_factura.numero_factura || ' - ' || v_factura.cliente_nombre,
    'Facturación',
    v_factura.id,
    'factura',
    v_factura.total,
    v_factura.total,
    'Contabilizado'
  ) RETURNING id INTO v_asiento_id;
  
  -- Crear detalles del asiento
  -- Débito: Clientes
  IF v_cuenta_clientes IS NOT NULL THEN
    INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
    VALUES (v_asiento_id, v_cuenta_clientes, v_factura.total, 0, 'Cliente: ' || v_factura.cliente_nombre);
  END IF;
  
  -- Haber: Ventas
  IF v_cuenta_ventas IS NOT NULL THEN
    INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
    VALUES (v_asiento_id, v_cuenta_ventas, 0, v_factura.subtotal, 'Ventas');
  END IF;
  
  -- Haber: IVA
  IF v_cuenta_iva IS NOT NULL AND v_factura.iva > 0 THEN
    INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
    VALUES (v_asiento_id, v_cuenta_iva, 0, v_factura.iva, 'IVA Débito Fiscal');
  END IF;
  
  -- Actualizar factura con ID del asiento
  UPDATE public.facturas_venta
  SET id_asiento_contable = v_asiento_id
  WHERE id = p_id_factura;
  
  RETURN v_asiento_id;
END;
$$ LANGUAGE plpgsql;

-- Calcular costos totales de una OP
CREATE OR REPLACE FUNCTION public.calcular_costos_op(
  p_id_op integer
)
RETURNS TABLE (
  costo_materiales numeric,
  costo_mano_obra numeric,
  costo_gastos_generales numeric,
  costo_total numeric
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COALESCE(SUM(CASE WHEN tipo_costo = 'Materiales' THEN costo_total ELSE 0 END), 0) as costo_materiales,
    COALESCE(SUM(CASE WHEN tipo_costo = 'Mano de Obra' THEN costo_total ELSE 0 END), 0) as costo_mano_obra,
    COALESCE(SUM(CASE WHEN tipo_costo = 'Gastos Generales' THEN costo_total ELSE 0 END), 0) as costo_gastos_generales,
    COALESCE(SUM(costo_total), 0) as costo_total
  FROM public.costos_op
  WHERE id_op = p_id_op;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- REPORTES FINANCIEROS
-- ============================================

-- Balance General
CREATE OR REPLACE FUNCTION public.obtener_balance_general(
  p_fecha_corte date DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  tipo_cuenta varchar,
  codigo_cuenta varchar,
  nombre_cuenta varchar,
  saldo_deudor numeric,
  saldo_acreedor numeric,
  saldo_final numeric
) AS $$
BEGIN
  RETURN QUERY
  WITH saldos_cuentas AS (
    SELECT
      pc.id,
      pc.codigo,
      pc.nombre,
      pc.tipo,
      pc.naturaleza,
      COALESCE(SUM(CASE WHEN ad.debe > 0 THEN ad.debe ELSE 0 END), 0) as total_debe,
      COALESCE(SUM(CASE WHEN ad.haber > 0 THEN ad.haber ELSE 0 END), 0) as total_haber
    FROM public.plan_cuentas pc
    LEFT JOIN public.asientos_detalle ad ON ad.id_cuenta = pc.id
    LEFT JOIN public.asientos_contables ac ON ac.id = ad.id_asiento
    WHERE pc.activa = true
      AND (ac.fecha IS NULL OR ac.fecha <= p_fecha_corte)
      AND (ac.estado IS NULL OR ac.estado = 'Contabilizado')
    GROUP BY pc.id, pc.codigo, pc.nombre, pc.tipo, pc.naturaleza
  )
  SELECT
    sc.tipo::varchar as tipo_cuenta,
    sc.codigo::varchar as codigo_cuenta,
    sc.nombre::varchar as nombre_cuenta,
    sc.total_debe as saldo_deudor,
    sc.total_haber as saldo_acreedor,
    CASE
      WHEN sc.naturaleza = 'Deudora' THEN sc.total_debe - sc.total_haber
      ELSE sc.total_haber - sc.total_debe
    END as saldo_final
  FROM saldos_cuentas sc
  WHERE sc.total_debe > 0 OR sc.total_haber > 0
  ORDER BY sc.codigo;
END;
$$ LANGUAGE plpgsql;

-- Flujo de Caja
CREATE OR REPLACE FUNCTION public.obtener_flujo_caja(
  p_fecha_desde date,
  p_fecha_hasta date
)
RETURNS TABLE (
  fecha date,
  concepto varchar,
  tipo varchar,
  ingreso numeric,
  egreso numeric,
  saldo_acumulado numeric
) AS $$
DECLARE
  v_saldo_inicial numeric := 0;
  v_saldo_actual numeric := 0;
BEGIN
  -- Calcular saldo inicial (hasta fecha_desde)
  SELECT COALESCE(SUM(
    CASE
      WHEN pc.tipo IN ('Activo') AND pc.codigo LIKE '1.1.1%' THEN
        CASE WHEN pc.naturaleza = 'Deudora' THEN ad.debe - ad.haber ELSE ad.haber - ad.debe END
      ELSE 0
    END
  ), 0) INTO v_saldo_inicial
  FROM public.asientos_detalle ad
  JOIN public.plan_cuentas pc ON pc.id = ad.id_cuenta
  JOIN public.asientos_contables ac ON ac.id = ad.id_asiento
  WHERE ac.fecha < p_fecha_desde
    AND ac.estado = 'Contabilizado'
    AND pc.codigo LIKE '1.1.1%'; -- Caja y Bancos

  v_saldo_actual := v_saldo_inicial;

  -- Retornar movimientos en el período
  RETURN QUERY
  WITH movimientos AS (
    SELECT
      ac.fecha,
      ac.concepto,
      CASE
        WHEN pc.codigo LIKE '4.%' THEN 'Ingreso'
        WHEN pc.codigo LIKE '5.%' OR pc.codigo LIKE '6.%' THEN 'Egreso'
        WHEN pc.codigo LIKE '1.1.1%' THEN 'Movimiento'
        ELSE 'Otro'
      END as tipo_movimiento,
      CASE
        WHEN pc.codigo LIKE '4.%' AND ad.haber > 0 THEN ad.haber
        WHEN pc.codigo LIKE '1.1.1%' AND ad.debe > 0 THEN ad.debe
        ELSE 0
      END as ingreso,
      CASE
        WHEN (pc.codigo LIKE '5.%' OR pc.codigo LIKE '6.%') AND ad.debe > 0 THEN ad.debe
        WHEN pc.codigo LIKE '1.1.1%' AND ad.haber > 0 THEN ad.haber
        ELSE 0
      END as egreso
    FROM public.asientos_detalle ad
    JOIN public.plan_cuentas pc ON pc.id = ad.id_cuenta
    JOIN public.asientos_contables ac ON ac.id = ad.id_asiento
    WHERE ac.fecha >= p_fecha_desde
      AND ac.fecha <= p_fecha_hasta
      AND ac.estado = 'Contabilizado'
      AND (
        pc.codigo LIKE '1.1.1%' OR -- Caja y Bancos
        pc.codigo LIKE '4.%' OR     -- Ingresos
        pc.codigo LIKE '5.%' OR     -- Costos
        pc.codigo LIKE '6.%'        -- Gastos
      )
  )
  SELECT
    m.fecha,
    m.concepto::varchar,
    m.tipo_movimiento::varchar,
    SUM(m.ingreso) OVER (ORDER BY m.fecha, m.concepto) as ingreso,
    SUM(m.egreso) OVER (ORDER BY m.fecha, m.concepto) as egreso,
    v_saldo_inicial + SUM(m.ingreso - m.egreso) OVER (ORDER BY m.fecha, m.concepto) as saldo_acumulado
  FROM movimientos m
  WHERE m.ingreso > 0 OR m.egreso > 0
  ORDER BY m.fecha, m.concepto;
END;
$$ LANGUAGE plpgsql;

-- Obtener resumen de cuentas por tipo
CREATE OR REPLACE FUNCTION public.obtener_resumen_cuentas(
  p_fecha_corte date DEFAULT CURRENT_DATE
)
RETURNS TABLE (
  tipo_cuenta varchar,
  total_deudor numeric,
  total_acreedor numeric,
  saldo_final numeric
) AS $$
BEGIN
  RETURN QUERY
  WITH saldos_por_tipo AS (
    SELECT
      pc.tipo,
      COALESCE(SUM(ad.debe), 0) as total_debe,
      COALESCE(SUM(ad.haber), 0) as total_haber
    FROM public.plan_cuentas pc
    LEFT JOIN public.asientos_detalle ad ON ad.id_cuenta = pc.id
    LEFT JOIN public.asientos_contables ac ON ac.id = ad.id_asiento
    WHERE pc.activa = true
      AND (ac.fecha IS NULL OR ac.fecha <= p_fecha_corte)
      AND (ac.estado IS NULL OR ac.estado = 'Contabilizado')
    GROUP BY pc.tipo
  )
  SELECT
    spt.tipo::varchar,
    spt.total_debe as total_deudor,
    spt.total_haber as total_acreedor,
    CASE
      WHEN spt.tipo IN ('Activo', 'Costo', 'Gasto') THEN spt.total_debe - spt.total_haber
      ELSE spt.total_haber - spt.total_debe
    END as saldo_final
  FROM saldos_por_tipo spt
  WHERE spt.total_debe > 0 OR spt.total_haber > 0
  ORDER BY spt.tipo;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 12. TRIGGERS
-- ============================================

-- Trigger para actualizar monto pendiente en cuentas por cobrar
CREATE OR REPLACE FUNCTION public.actualizar_cxc_pendiente()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.cuentas_por_cobrar
  SET 
    monto_pagado = (
      SELECT COALESCE(SUM(monto), 0)
      FROM public.pagos_cobros
      WHERE id_cuenta_por_cobrar = NEW.id_cuenta_por_cobrar
        AND tipo = 'Cobro'
    ),
    monto_pendiente = monto_total - (
      SELECT COALESCE(SUM(monto), 0)
      FROM public.pagos_cobros
      WHERE id_cuenta_por_cobrar = NEW.id_cuenta_por_cobrar
        AND tipo = 'Cobro'
    ),
    estado = CASE
      WHEN monto_total - (
        SELECT COALESCE(SUM(monto), 0)
        FROM public.pagos_cobros
        WHERE id_cuenta_por_cobrar = NEW.id_cuenta_por_cobrar
          AND tipo = 'Cobro'
      ) <= 0 THEN 'Pagado'
      WHEN monto_total - (
        SELECT COALESCE(SUM(monto), 0)
        FROM public.pagos_cobros
        WHERE id_cuenta_por_cobrar = NEW.id_cuenta_por_cobrar
          AND tipo = 'Cobro'
      ) < monto_total THEN 'Parcial'
      WHEN fecha_vencimiento < CURRENT_DATE THEN 'Vencido'
      ELSE 'Pendiente'
    END,
    updated_at = now()
  WHERE id = NEW.id_cuenta_por_cobrar;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_actualizar_cxc_pago
AFTER INSERT OR UPDATE OR DELETE ON public.pagos_cobros
FOR EACH ROW
WHEN (NEW.tipo = 'Cobro' OR OLD.tipo = 'Cobro')
EXECUTE FUNCTION public.actualizar_cxc_pendiente();

-- Trigger para actualizar monto pendiente en cuentas por pagar
CREATE OR REPLACE FUNCTION public.actualizar_cxp_pendiente()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.cuentas_por_pagar
  SET 
    monto_pagado = (
      SELECT COALESCE(SUM(monto), 0)
      FROM public.pagos_cobros
      WHERE id_cuenta_por_pagar = NEW.id_cuenta_por_pagar
        AND tipo = 'Pago'
    ),
    monto_pendiente = monto_total - (
      SELECT COALESCE(SUM(monto), 0)
      FROM public.pagos_cobros
      WHERE id_cuenta_por_pagar = NEW.id_cuenta_por_pagar
        AND tipo = 'Pago'
    ),
    estado = CASE
      WHEN monto_total - (
        SELECT COALESCE(SUM(monto), 0)
        FROM public.pagos_cobros
        WHERE id_cuenta_por_pagar = NEW.id_cuenta_por_pagar
          AND tipo = 'Pago'
      ) <= 0 THEN 'Pagado'
      WHEN monto_total - (
        SELECT COALESCE(SUM(monto), 0)
        FROM public.pagos_cobros
        WHERE id_cuenta_por_pagar = NEW.id_cuenta_por_pagar
          AND tipo = 'Pago'
      ) < monto_total THEN 'Parcial'
      WHEN fecha_vencimiento < CURRENT_DATE THEN 'Vencido'
      ELSE 'Pendiente'
    END,
    updated_at = now()
  WHERE id = NEW.id_cuenta_por_pagar;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_actualizar_cxp_pago
AFTER INSERT OR UPDATE OR DELETE ON public.pagos_cobros
FOR EACH ROW
WHEN (NEW.tipo = 'Pago' OR OLD.tipo = 'Pago')
EXECUTE FUNCTION public.actualizar_cxp_pendiente();

-- Trigger para crear factura automática al entregar OP
CREATE OR REPLACE FUNCTION public.crear_factura_automatica_op()
RETURNS TRIGGER AS $$
DECLARE
  v_venta RECORD;
  v_config_afip RECORD;
  v_numero_comprobante integer;
  v_numero_factura varchar(50);
  v_factura_id integer;
  v_items_factura RECORD;
BEGIN
  -- Solo procesar si la OP cambió a estado "Entregado" o "Finalizado"
  IF (NEW.entregado = true AND (OLD.entregado IS NULL OR OLD.entregado = false))
     OR (NEW.estado = 'Finalizado' AND OLD.estado != 'Finalizado') THEN
    
    -- Verificar si ya existe una factura para esta OP
    IF EXISTS (SELECT 1 FROM public.facturas_venta WHERE id_op = NEW.id) THEN
      RETURN NEW;
    END IF;

    -- Buscar venta asociada
    SELECT * INTO v_venta
    FROM public.ventas
    WHERE id_op = NEW.id
    LIMIT 1;

    -- Si no hay venta, no crear factura automáticamente
    IF NOT FOUND THEN
      RETURN NEW;
    END IF;

    -- Obtener configuración AFIP
    SELECT * INTO v_config_afip
    FROM public.configuracion_afip
    WHERE activo = true
    LIMIT 1;

    IF NOT FOUND THEN
      -- Si no hay configuración AFIP, no crear factura
      RETURN NEW;
    END IF;

    -- Determinar tipo de comprobante según cliente
    DECLARE
      v_tipo_comprobante varchar(50) := 'Factura B';
    BEGIN
      IF NEW.dni_cuit IS NOT NULL AND LENGTH(NEW.dni_cuit) = 11 THEN
        v_tipo_comprobante := 'Factura A';
      END IF;

      -- Generar número de comprobante
      SELECT public.generar_numero_factura(v_tipo_comprobante, v_config_afip.punto_venta)
      INTO v_numero_comprobante;

      -- Crear número de factura
      v_numero_factura := LPAD(v_config_afip.punto_venta::text, 4, '0') || '-' || LPAD(v_numero_comprobante::text, 8, '0');

      -- Obtener items de la venta
      -- Calcular totales
      DECLARE
        v_subtotal numeric := 0;
        v_descuento_total numeric := 0;
        v_iva_total numeric := 0;
        v_total numeric := 0;
      BEGIN
        -- Calcular desde items de venta
        SELECT 
          COALESCE(SUM((cantidad * precio_unitario) - COALESCE(descuento, 0)), 0),
          COALESCE(SUM(descuento), 0),
          COALESCE(SUM(((cantidad * precio_unitario) - COALESCE(descuento, 0)) * 0.21), 0)
        INTO v_subtotal, v_descuento_total, v_iva_total
        FROM public.ventas_items
        WHERE id_venta = v_venta.id;

        v_total := v_subtotal + v_iva_total;

        -- Crear factura
        INSERT INTO public.facturas_venta (
          numero_factura,
          punto_venta,
          numero_comprobante,
          tipo_comprobante,
          fecha_emision,
          id_cliente,
          cliente_nombre,
          cliente_dni_cuit,
          cliente_direccion,
          id_op,
          numero_op,
          id_venta,
          subtotal,
          descuento,
          iva,
          total,
          estado,
          estado_afip
        ) VALUES (
          v_numero_factura,
          v_config_afip.punto_venta,
          v_numero_comprobante,
          v_tipo_comprobante,
          CURRENT_DATE,
          NULL, -- Se puede asociar después
          COALESCE(NEW.cliente, 'Cliente'),
          NEW.dni_cuit,
          NEW.direccion_cliente,
          NEW.id,
          NEW.numero_op,
          v_venta.id,
          v_subtotal,
          v_descuento_total,
          v_iva_total,
          v_total,
          'Borrador',
          'Pendiente'
        ) RETURNING id INTO v_factura_id;

        -- Crear items de factura desde items de venta
        FOR v_items_factura IN 
          SELECT 
            vi.descripcion,
            vi.cantidad,
            vi.precio_unitario,
            COALESCE(vi.descuento, 0) as descuento,
            21.0 as iva_porcentaje
          FROM public.ventas_items vi
          WHERE vi.id_venta = v_venta.id
        LOOP
          DECLARE
            v_subtotal_item numeric := (v_items_factura.cantidad * v_items_factura.precio_unitario) - v_items_factura.descuento;
            v_iva_item numeric := v_subtotal_item * (v_items_factura.iva_porcentaje / 100);
            v_total_item numeric := v_subtotal_item + v_iva_item;
          BEGIN
            INSERT INTO public.facturas_items (
              id_factura,
              item_numero,
              descripcion,
              cantidad,
              unidad_medida,
              precio_unitario,
              descuento,
              iva_porcentaje,
              iva_monto,
              subtotal,
              total
            ) VALUES (
              v_factura_id,
              (SELECT COALESCE(MAX(item_numero), 0) + 1 FROM public.facturas_items WHERE id_factura = v_factura_id),
              v_items_factura.descripcion,
              v_items_factura.cantidad,
              'UN',
              v_items_factura.precio_unitario,
              v_items_factura.descuento,
              v_items_factura.iva_porcentaje,
              v_iva_item,
              v_subtotal_item,
              v_total_item
            );
          END;
        END LOOP;
      END;
    END;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_crear_factura_automatica_op
AFTER UPDATE ON public.ordenes_trabajo
FOR EACH ROW
WHEN (
  (NEW.entregado = true AND (OLD.entregado IS NULL OR OLD.entregado = false))
  OR (NEW.estado = 'Finalizado' AND OLD.estado != 'Finalizado')
)
EXECUTE FUNCTION public.crear_factura_automatica_op();

-- ============================================
-- 13. POLÍTICAS RLS (Row Level Security)
-- ============================================

-- Habilitar RLS en todas las tablas
ALTER TABLE public.plan_cuentas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asientos_contables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asientos_detalle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas_venta ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.costos_op ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cuentas_por_cobrar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cuentas_por_pagar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pagos_cobros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.configuracion_afip ENABLE ROW LEVEL SECURITY;

-- Políticas: Todos los usuarios autenticados pueden leer, solo admin puede escribir
-- (Ajustar según necesidades de seguridad)

-- Plan de cuentas: lectura para todos, escritura solo admin
CREATE POLICY "Plan cuentas lectura" ON public.plan_cuentas
  FOR SELECT USING (true);

CREATE POLICY "Plan cuentas escritura" ON public.plan_cuentas
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
      AND usuarios.rol IN ('administracion', 'gerencia')
    )
  );

-- Asientos contables: lectura para todos, escritura solo admin
CREATE POLICY "Asientos lectura" ON public.asientos_contables
  FOR SELECT USING (true);

CREATE POLICY "Asientos escritura" ON public.asientos_contables
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
      AND usuarios.rol IN ('administracion', 'gerencia', 'caja')
    )
  );

-- Facturas: lectura para todos, escritura para admin, caja, mostrador
CREATE POLICY "Facturas lectura" ON public.facturas_venta
  FOR SELECT USING (true);

CREATE POLICY "Facturas escritura" ON public.facturas_venta
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
      AND usuarios.rol IN ('administracion', 'gerencia', 'caja', 'mostrador')
    )
  );

-- Costos OP: lectura para todos, escritura para admin y sectores
CREATE POLICY "Costos lectura" ON public.costos_op
  FOR SELECT USING (true);

CREATE POLICY "Costos escritura" ON public.costos_op
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
    )
  );

-- Cuentas por cobrar/pagar: lectura para todos, escritura solo admin y caja
CREATE POLICY "CXC lectura" ON public.cuentas_por_cobrar
  FOR SELECT USING (true);

CREATE POLICY "CXC escritura" ON public.cuentas_por_cobrar
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
      AND usuarios.rol IN ('administracion', 'gerencia', 'caja')
    )
  );

CREATE POLICY "CXP lectura" ON public.cuentas_por_pagar
  FOR SELECT USING (true);

CREATE POLICY "CXP escritura" ON public.cuentas_por_pagar
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
      AND usuarios.rol IN ('administracion', 'gerencia', 'caja')
    )
  );

-- Configuración AFIP: solo admin
CREATE POLICY "AFIP solo admin" ON public.configuracion_afip
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE usuarios.id = auth.uid()::integer
      AND usuarios.rol IN ('administracion', 'gerencia')
    )
  );

-- ============================================
-- 14. DATOS INICIALES - PLAN DE CUENTAS BÁSICO
-- ============================================

-- Insertar plan de cuentas básico (estructura simplificada)
INSERT INTO public.plan_cuentas (codigo, nombre, tipo, nivel, naturaleza, activa) VALUES
-- Activos
('1', 'ACTIVO', 'Activo', 1, 'Deudora', true),
('1.1', 'Activo Corriente', 'Activo', 2, 'Deudora', true),
('1.1.1', 'Caja y Bancos', 'Activo', 3, 'Deudora', true),
('1.1.1.01', 'Caja', 'Activo', 4, 'Deudora', true),
('1.1.1.02', 'Bancos Cta. Cte.', 'Activo', 4, 'Deudora', true),
('1.1.1.03', 'Clientes', 'Activo', 4, 'Deudora', true),
('1.1.2', 'Créditos', 'Activo', 3, 'Deudora', true),
('1.1.2.01', 'IVA Débito Fiscal', 'Activo', 4, 'Deudora', true),
('1.2', 'Activo No Corriente', 'Activo', 2, 'Deudora', true),
-- Pasivos
('2', 'PASIVO', 'Pasivo', 1, 'Acreedora', true),
('2.1', 'Pasivo Corriente', 'Pasivo', 2, 'Acreedora', true),
('2.1.1', 'Proveedores', 'Pasivo', 3, 'Acreedora', true),
('2.1.1.01', 'Proveedores', 'Pasivo', 4, 'Acreedora', true),
('2.1.2', 'Obligaciones Fiscales', 'Pasivo', 3, 'Acreedora', true),
('2.1.2.01', 'IVA Crédito Fiscal', 'Pasivo', 4, 'Acreedora', true),
-- Patrimonio
('3', 'PATRIMONIO', 'Patrimonio', 1, 'Acreedora', true),
('3.1', 'Capital', 'Patrimonio', 2, 'Acreedora', true),
('3.1.1', 'Capital Social', 'Patrimonio', 3, 'Acreedora', true),
-- Ingresos
('4', 'INGRESOS', 'Ingreso', 1, 'Acreedora', true),
('4.1', 'Ventas', 'Ingreso', 2, 'Acreedora', true),
('4.1.1', 'Ventas de Productos', 'Ingreso', 3, 'Acreedora', true),
('4.1.1.01', 'Ventas de Productos', 'Ingreso', 4, 'Acreedora', true),
-- Costos
('5', 'COSTOS', 'Costo', 1, 'Deudora', true),
('5.1', 'Costo de Ventas', 'Costo', 2, 'Deudora', true),
('5.1.1', 'Costo de Productos Vendidos', 'Costo', 3, 'Deudora', true),
('5.1.1.01', 'Costo de Productos Vendidos', 'Costo', 4, 'Deudora', true),
-- Gastos
('6', 'GASTOS', 'Gasto', 1, 'Deudora', true),
('6.1', 'Gastos de Administración', 'Gasto', 2, 'Deudora', true),
('6.1.1', 'Sueldos y Cargas Sociales', 'Gasto', 3, 'Deudora', true),
('6.1.2', 'Alquileres', 'Gasto', 3, 'Deudora', true),
('6.1.3', 'Servicios Públicos', 'Gasto', 3, 'Deudora', true)
ON CONFLICT (codigo) DO NOTHING;

-- ============================================
-- COMENTARIOS FINALES
-- ============================================
COMMENT ON TABLE public.plan_cuentas IS 'Plan de cuentas contable del sistema ERP';
COMMENT ON TABLE public.asientos_contables IS 'Asientos contables con partida doble';
COMMENT ON TABLE public.facturas_venta IS 'Facturas de venta con preparación para AFIP';
COMMENT ON TABLE public.costos_op IS 'Control de costos por orden de trabajo';
COMMENT ON TABLE public.cuentas_por_cobrar IS 'Cuentas por cobrar de clientes';
COMMENT ON TABLE public.cuentas_por_pagar IS 'Cuentas por pagar a proveedores';
COMMENT ON TABLE public.configuracion_afip IS 'Configuración para facturación electrónica AFIP';

