-- Tabla para almacenar la memoria y aprendizaje de PlotAI
-- Permite que PlotAI aprenda de conversaciones anteriores y patrones

BEGIN;

CREATE TABLE IF NOT EXISTS public.plotai_memoria (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL CHECK (tipo IN ('conversacion', 'patron', 'conocimiento', 'preferencia')),
  categoria text,
  contenido text NOT NULL,
  contexto jsonb,
  importancia integer NOT NULL DEFAULT 5 CHECK (importancia >= 1 AND importancia <= 10),
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  fecha_actualizacion timestamptz NOT NULL DEFAULT now(),
  veces_usado integer DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_plotai_memoria_tipo ON public.plotai_memoria(tipo);
CREATE INDEX IF NOT EXISTS idx_plotai_memoria_categoria ON public.plotai_memoria(categoria);
CREATE INDEX IF NOT EXISTS idx_plotai_memoria_importancia ON public.plotai_memoria(importancia DESC);
CREATE INDEX IF NOT EXISTS idx_plotai_memoria_fecha_creacion ON public.plotai_memoria(fecha_creacion DESC);

COMMENT ON TABLE public.plotai_memoria IS 'Almacena la memoria y aprendizaje de PlotAI para mejorar sus respuestas';
COMMENT ON COLUMN public.plotai_memoria.tipo IS 'Tipo de memoria: conversacion, patron, conocimiento, preferencia';
COMMENT ON COLUMN public.plotai_memoria.importancia IS 'Importancia de 1 a 10, donde 10 es más importante';
COMMENT ON COLUMN public.plotai_memoria.veces_usado IS 'Cantidad de veces que se ha utilizado esta memoria';

COMMIT;

