-- Simplificar sistema de menú diario
-- Solo platos, múltiples platos por día, sin campos innecesarios

-- Eliminar tablas antiguas si existen
DROP TABLE IF EXISTS public.menu_selecciones CASCADE;
DROP TABLE IF EXISTS public.menus_diarios CASCADE;

-- Tabla de menús diarios (simplificada)
CREATE TABLE IF NOT EXISTS public.menus_diarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date NOT NULL DEFAULT CURRENT_DATE,
  creado_por integer NOT NULL REFERENCES public.usuarios(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(fecha) -- Solo un menú por día
);

-- Tabla de platos del menú (múltiples platos por menú)
CREATE TABLE IF NOT EXISTS public.menu_platos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_menu integer NOT NULL REFERENCES public.menus_diarios(id) ON DELETE CASCADE,
  nombre_plato varchar(255) NOT NULL,
  orden integer DEFAULT 0, -- Para ordenar los platos
  created_at timestamptz DEFAULT now()
);

-- Tabla de selecciones de empleados
CREATE TABLE IF NOT EXISTS public.menu_selecciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_menu integer NOT NULL REFERENCES public.menus_diarios(id) ON DELETE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_plato integer NOT NULL REFERENCES public.menu_platos(id) ON DELETE CASCADE,
  fecha_seleccion timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  UNIQUE(id_menu, id_usuario) -- Un empleado solo puede seleccionar una vez por menú
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_menus_diarios_fecha ON public.menus_diarios(fecha);
CREATE INDEX IF NOT EXISTS idx_menu_platos_menu ON public.menu_platos(id_menu);
CREATE INDEX IF NOT EXISTS idx_menu_selecciones_menu ON public.menu_selecciones(id_menu);
CREATE INDEX IF NOT EXISTS idx_menu_selecciones_usuario ON public.menu_selecciones(id_usuario);
CREATE INDEX IF NOT EXISTS idx_menu_selecciones_plato ON public.menu_selecciones(id_plato);

-- Eliminar funciones antiguas si existen
DROP FUNCTION IF EXISTS public.crear_actualizar_menu_diario CASCADE;
DROP FUNCTION IF EXISTS public.obtener_menu_dia_actual CASCADE;
DROP FUNCTION IF EXISTS public.obtener_menus_diarios CASCADE;
DROP FUNCTION IF EXISTS public.seleccionar_plato_menu CASCADE;
DROP FUNCTION IF EXISTS public.obtener_selecciones_menu CASCADE;
DROP FUNCTION IF EXISTS public.obtener_seleccion_usuario_menu CASCADE;
DROP FUNCTION IF EXISTS public.eliminar_menu_diario CASCADE;
DROP FUNCTION IF EXISTS public.cancelar_seleccion_menu CASCADE;

-- Función para crear o actualizar menú del día con sus platos
CREATE OR REPLACE FUNCTION public.crear_actualizar_menu_diario(
  p_creado_por integer,
  p_platos varchar(255)[], -- Array de nombres de platos
  p_fecha date DEFAULT CURRENT_DATE
)
RETURNS public.menus_diarios
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.menus_diarios;
  v_menu_id integer;
  v_plato varchar(255);
BEGIN
  -- Crear o obtener el menú del día
  INSERT INTO public.menus_diarios (fecha, creado_por)
  VALUES (p_fecha, p_creado_por)
  ON CONFLICT (fecha) DO UPDATE SET
    creado_por = EXCLUDED.creado_por,
    updated_at = now()
  RETURNING * INTO v_result;
  
  v_menu_id := v_result.id;
  
  -- Eliminar platos existentes del menú
  DELETE FROM public.menu_platos WHERE id_menu = v_menu_id;
  
  -- Insertar nuevos platos
  IF p_platos IS NOT NULL AND array_length(p_platos, 1) > 0 THEN
    FOR i IN 1..array_length(p_platos, 1) LOOP
      v_plato := p_platos[i];
      IF v_plato IS NOT NULL AND trim(v_plato) != '' THEN
        INSERT INTO public.menu_platos (id_menu, nombre_plato, orden)
        VALUES (v_menu_id, trim(v_plato), i);
      END IF;
    END LOOP;
  END IF;
  
  RETURN v_result;
END;
$$;

-- Función para obtener menú del día actual con sus platos
CREATE OR REPLACE FUNCTION public.obtener_menu_dia_actual()
RETURNS TABLE (
  id integer,
  fecha date,
  creado_por integer,
  creado_por_nombre varchar(255),
  platos jsonb,
  total_selecciones bigint,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    m.id,
    m.fecha,
    m.creado_por,
    u.nombre as creado_por_nombre,
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'id', mp.id,
          'nombre_plato', mp.nombre_plato,
          'orden', mp.orden
        ) ORDER BY mp.orden
      ) FILTER (WHERE mp.id IS NOT NULL),
      '[]'::jsonb
    ) as platos,
    COUNT(DISTINCT ms.id_usuario)::bigint as total_selecciones,
    m.created_at,
    m.updated_at
  FROM public.menus_diarios m
  LEFT JOIN public.usuarios u ON m.creado_por = u.id
  LEFT JOIN public.menu_platos mp ON m.id = mp.id_menu
  LEFT JOIN public.menu_selecciones ms ON m.id = ms.id_menu
  WHERE m.fecha = CURRENT_DATE
  GROUP BY m.id, m.fecha, m.creado_por, u.nombre, m.created_at, m.updated_at
  LIMIT 1;
END;
$$;

-- Función para obtener menús con sus platos (para historial)
CREATE OR REPLACE FUNCTION public.obtener_menus_diarios(
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  fecha date,
  creado_por integer,
  creado_por_nombre varchar(255),
  platos jsonb,
  total_selecciones bigint,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    m.id,
    m.fecha,
    m.creado_por,
    u.nombre as creado_por_nombre,
    COALESCE(
      jsonb_agg(
        jsonb_build_object(
          'id', mp.id,
          'nombre_plato', mp.nombre_plato,
          'orden', mp.orden
        ) ORDER BY mp.orden
      ) FILTER (WHERE mp.id IS NOT NULL),
      '[]'::jsonb
    ) as platos,
    COUNT(DISTINCT ms.id_usuario)::bigint as total_selecciones,
    m.created_at,
    m.updated_at
  FROM public.menus_diarios m
  LEFT JOIN public.usuarios u ON m.creado_por = u.id
  LEFT JOIN public.menu_platos mp ON m.id = mp.id_menu
  LEFT JOIN public.menu_selecciones ms ON m.id = ms.id_menu
  WHERE 
    (p_fecha_desde IS NULL OR m.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR m.fecha <= p_fecha_hasta)
  GROUP BY m.id, m.fecha, m.creado_por, u.nombre, m.created_at, m.updated_at
  ORDER BY m.fecha DESC;
END;
$$;

-- Función para seleccionar plato del menú
CREATE OR REPLACE FUNCTION public.seleccionar_plato_menu(
  p_id_menu integer,
  p_id_usuario integer,
  p_id_plato integer
)
RETURNS public.menu_selecciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_menu public.menus_diarios;
  v_hora_actual time;
  v_fecha_menu date;
  v_result public.menu_selecciones;
BEGIN
  -- Obtener el menú
  SELECT * INTO v_menu FROM public.menus_diarios WHERE id = p_id_menu;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menú no encontrado';
  END IF;

  -- Verificar fecha del menú
  v_fecha_menu := v_menu.fecha;
  IF v_fecha_menu != CURRENT_DATE THEN
    RAISE EXCEPTION 'Solo se puede seleccionar el menú del día actual';
  END IF;

  -- Verificar horario (hasta las 9:30 AM)
  v_hora_actual := CURRENT_TIME;
  IF v_hora_actual > '09:30:00'::time THEN
    RAISE EXCEPTION 'El plazo para seleccionar el menú ha expirado. Debes hacerlo antes de las 9:30 AM';
  END IF;

  -- Verificar que el plato pertenezca al menú
  IF NOT EXISTS (SELECT 1 FROM public.menu_platos WHERE id = p_id_plato AND id_menu = p_id_menu) THEN
    RAISE EXCEPTION 'El plato no pertenece a este menú';
  END IF;

  -- Insertar o actualizar selección
  INSERT INTO public.menu_selecciones (
    id_menu, id_usuario, id_plato
  )
  VALUES (
    p_id_menu, p_id_usuario, p_id_plato
  )
  ON CONFLICT (id_menu, id_usuario) DO UPDATE SET
    id_plato = EXCLUDED.id_plato,
    fecha_seleccion = now()
  RETURNING * INTO v_result;
  
  RETURN v_result;
END;
$$;

-- Función para obtener selecciones de un menú
CREATE OR REPLACE FUNCTION public.obtener_selecciones_menu(
  p_id_menu integer
)
RETURNS TABLE (
  id integer,
  id_menu integer,
  id_usuario integer,
  nombre_usuario varchar(255),
  id_plato integer,
  nombre_plato varchar(255),
  fecha_seleccion timestamptz,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ms.id,
    ms.id_menu,
    ms.id_usuario,
    u.nombre as nombre_usuario,
    ms.id_plato,
    mp.nombre_plato,
    ms.fecha_seleccion,
    ms.created_at
  FROM public.menu_selecciones ms
  JOIN public.usuarios u ON ms.id_usuario = u.id
  JOIN public.menu_platos mp ON ms.id_plato = mp.id
  WHERE ms.id_menu = p_id_menu
  ORDER BY ms.fecha_seleccion ASC;
END;
$$;

-- Función para obtener selección del usuario para un menú
CREATE OR REPLACE FUNCTION public.obtener_seleccion_usuario_menu(
  p_id_menu integer,
  p_id_usuario integer
)
RETURNS TABLE (
  id integer,
  id_menu integer,
  id_usuario integer,
  id_plato integer,
  nombre_plato varchar(255),
  fecha_seleccion timestamptz,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ms.id,
    ms.id_menu,
    ms.id_usuario,
    ms.id_plato,
    mp.nombre_plato,
    ms.fecha_seleccion,
    ms.created_at
  FROM public.menu_selecciones ms
  JOIN public.menu_platos mp ON ms.id_plato = mp.id
  WHERE ms.id_menu = p_id_menu AND ms.id_usuario = p_id_usuario;
END;
$$;

-- Función para eliminar menú diario
CREATE OR REPLACE FUNCTION public.eliminar_menu_diario(
  p_id integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.menus_diarios WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- Función para cancelar selección
CREATE OR REPLACE FUNCTION public.cancelar_seleccion_menu(
  p_id_menu integer,
  p_id_usuario integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_menu public.menus_diarios;
  v_hora_actual time;
BEGIN
  -- Obtener el menú
  SELECT * INTO v_menu FROM public.menus_diarios WHERE id = p_id_menu;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menú no encontrado';
  END IF;

  -- Verificar fecha del menú
  IF v_menu.fecha != CURRENT_DATE THEN
    RAISE EXCEPTION 'Solo se puede cancelar la selección del menú del día actual';
  END IF;

  -- Verificar horario (hasta las 9:30 AM)
  v_hora_actual := CURRENT_TIME;
  IF v_hora_actual > '09:30:00'::time THEN
    RAISE EXCEPTION 'El plazo para cancelar la selección ha expirado. Debes hacerlo antes de las 9:30 AM';
  END IF;

  DELETE FROM public.menu_selecciones 
  WHERE id_menu = p_id_menu AND id_usuario = p_id_usuario;
  
  RETURN FOUND;
END;
$$;

-- RLS Policies
ALTER TABLE public.menus_diarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_platos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_selecciones ENABLE ROW LEVEL SECURITY;

-- Políticas para menus_diarios
-- Todos pueden ver menús
CREATE POLICY "Todos pueden ver menús"
  ON public.menus_diarios FOR SELECT
  USING (true);

-- Solo RRHH y Admin pueden crear/actualizar menús
CREATE POLICY "RRHH y Admin pueden crear menús"
  ON public.menus_diarios FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

CREATE POLICY "RRHH y Admin pueden actualizar menús"
  ON public.menus_diarios FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

CREATE POLICY "RRHH y Admin pueden eliminar menús"
  ON public.menus_diarios FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

-- Políticas para menu_platos
CREATE POLICY "Todos pueden ver platos"
  ON public.menu_platos FOR SELECT
  USING (true);

CREATE POLICY "RRHH y Admin pueden crear platos"
  ON public.menu_platos FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

CREATE POLICY "RRHH y Admin pueden eliminar platos"
  ON public.menu_platos FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

-- Políticas para menu_selecciones
CREATE POLICY "Usuarios pueden ver sus selecciones"
  ON public.menu_selecciones FOR SELECT
  USING (
    id_usuario = auth.uid()::text::integer
    OR EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

CREATE POLICY "Usuarios pueden crear selecciones"
  ON public.menu_selecciones FOR INSERT
  WITH CHECK (id_usuario = auth.uid()::text::integer);

CREATE POLICY "Usuarios pueden actualizar sus selecciones"
  ON public.menu_selecciones FOR UPDATE
  USING (id_usuario = auth.uid()::text::integer);

CREATE POLICY "Usuarios pueden eliminar sus selecciones"
  ON public.menu_selecciones FOR DELETE
  USING (
    id_usuario = auth.uid()::text::integer
    OR EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );


