-- Sistema de Pedidos Web - Tablas y estructura base
-- Clientes pueden hacer pedidos por web que se convierten en OPs

BEGIN;

-- ============================================
-- 1. TABLA DE CLIENTES
-- ============================================
CREATE TABLE IF NOT EXISTS public.clientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario varchar(100) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  nombre varchar(255) NOT NULL,
  apellido varchar(255),
  empresa varchar(255),
  telefono varchar(50),
  email varchar(255),
  dni_cuit varchar(50),
  direccion text,
  activo boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_clientes_usuario ON public.clientes(usuario);
CREATE INDEX IF NOT EXISTS idx_clientes_email ON public.clientes(email);
CREATE INDEX IF NOT EXISTS idx_clientes_activo ON public.clientes(activo);

-- ============================================
-- 2. TABLA DE ARTÍCULOS DE LA EMPRESA
-- ============================================
CREATE TABLE IF NOT EXISTS public.articulos_empresa (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(100) NOT NULL UNIQUE,
  nombre varchar(255) NOT NULL,
  descripcion text,
  categoria varchar(100),
  precio_base numeric(10,2),
  activo boolean DEFAULT true,
  imagen_url text,
  tiempo_estimado_dias integer,
  requiere_archivos boolean DEFAULT false,
  visible_clientes boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_articulos_codigo ON public.articulos_empresa(codigo);
CREATE INDEX IF NOT EXISTS idx_articulos_categoria ON public.articulos_empresa(categoria);
CREATE INDEX IF NOT EXISTS idx_articulos_activo ON public.articulos_empresa(activo);
CREATE INDEX IF NOT EXISTS idx_articulos_visible ON public.articulos_empresa(visible_clientes);

-- ============================================
-- 3. TABLA DE PEDIDOS DE CLIENTES
-- ============================================
CREATE TABLE IF NOT EXISTS public.pedidos_clientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente integer NOT NULL REFERENCES public.clientes(id) ON DELETE CASCADE,
  numero_pedido varchar(50) NOT NULL UNIQUE,
  estado varchar(50) NOT NULL DEFAULT 'pendiente' CHECK (
    estado IN ('pendiente', 'en_revision', 'aprobado', 'rechazado', 'convertido_parcial', 'convertido_completo', 'cancelado')
  ),
  id_op_asociada integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  fecha_pedido timestamptz NOT NULL DEFAULT now(),
  fecha_limite_deseada date,
  observaciones_cliente text,
  observaciones_internas text,
  precio_total numeric(10,2) DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pedidos_cliente ON public.pedidos_clientes(id_cliente);
CREATE INDEX IF NOT EXISTS idx_pedidos_numero ON public.pedidos_clientes(numero_pedido);
CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON public.pedidos_clientes(estado);
CREATE INDEX IF NOT EXISTS idx_pedidos_fecha ON public.pedidos_clientes(fecha_pedido DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_op ON public.pedidos_clientes(id_op_asociada);

-- ============================================
-- 4. TABLA DE ITEMS DEL PEDIDO
-- ============================================
CREATE TABLE IF NOT EXISTS public.pedidos_clientes_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido integer NOT NULL REFERENCES public.pedidos_clientes(id) ON DELETE CASCADE,
  id_articulo integer NOT NULL REFERENCES public.articulos_empresa(id) ON DELETE RESTRICT,
  cantidad integer NOT NULL DEFAULT 1,
  precio_unitario numeric(10,2) NOT NULL,
  precio_total numeric(10,2) NOT NULL,
  descripcion_personalizada text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_items_pedido ON public.pedidos_clientes_items(id_pedido);
CREATE INDEX IF NOT EXISTS idx_items_articulo ON public.pedidos_clientes_items(id_articulo);

-- ============================================
-- 5. TABLA DE ARCHIVOS ADJUNTOS DEL PEDIDO
-- ============================================
CREATE TABLE IF NOT EXISTS public.pedidos_clientes_archivos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pedido integer NOT NULL REFERENCES public.pedidos_clientes(id) ON DELETE CASCADE,
  id_item integer REFERENCES public.pedidos_clientes_items(id) ON DELETE CASCADE,
  url text NOT NULL,
  nombre_archivo varchar(255) NOT NULL,
  tipo varchar(100),
  tamaño bigint,
  uploaded_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_archivos_pedido ON public.pedidos_clientes_archivos(id_pedido);
CREATE INDEX IF NOT EXISTS idx_archivos_item ON public.pedidos_clientes_archivos(id_item);

-- ============================================
-- 6. AGREGAR CAMPOS A ordenes_trabajo
-- ============================================
ALTER TABLE public.ordenes_trabajo
ADD COLUMN IF NOT EXISTS id_pedido_cliente integer REFERENCES public.pedidos_clientes(id) ON DELETE SET NULL;

ALTER TABLE public.ordenes_trabajo
ADD COLUMN IF NOT EXISTS origen_pedido_web boolean DEFAULT false;

CREATE INDEX IF NOT EXISTS idx_ordenes_pedido_cliente ON public.ordenes_trabajo(id_pedido_cliente);
CREATE INDEX IF NOT EXISTS idx_ordenes_origen_web ON public.ordenes_trabajo(origen_pedido_web);

-- ============================================
-- 7. FUNCIÓN PARA GENERAR NÚMERO DE PEDIDO
-- ============================================
CREATE OR REPLACE FUNCTION public.generar_numero_pedido_cliente()
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  año_actual text;
  ultimo_numero integer;
  nuevo_numero text;
BEGIN
  año_actual := TO_CHAR(CURRENT_DATE, 'YYYY');
  
  -- Obtener el último número del año actual
  SELECT COALESCE(MAX(CAST(SUBSTRING(numero_pedido FROM '[0-9]+$') AS integer)), 0)
  INTO ultimo_numero
  FROM public.pedidos_clientes
  WHERE numero_pedido LIKE 'PED-' || año_actual || '-%';
  
  -- Incrementar y formatear
  ultimo_numero := ultimo_numero + 1;
  nuevo_numero := 'PED-' || año_actual || '-' || LPAD(ultimo_numero::text, 4, '0');
  
  RETURN nuevo_numero;
END;
$$;

-- ============================================
-- 8. TRIGGER PARA ACTUALIZAR updated_at
-- ============================================
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_clientes_updated_at
  BEFORE UPDATE ON public.clientes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_articulos_empresa_updated_at
  BEFORE UPDATE ON public.articulos_empresa
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_pedidos_clientes_updated_at
  BEFORE UPDATE ON public.pedidos_clientes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_pedidos_clientes_items_updated_at
  BEFORE UPDATE ON public.pedidos_clientes_items
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

COMMIT;

