-- Crear tabla de revisiones y aprobaciones
CREATE TABLE IF NOT EXISTS public.revisiones_orden (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  usuario_revisor_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  usuario_revisor_nombre varchar(100) NOT NULL,
  estado_revision text NOT NULL CHECK (estado_revision IN ('pendiente', 'en_revision', 'aprobado', 'requiere_cambios')),
  comentarios text,
  fecha_revision timestamptz DEFAULT now(),
  fecha_aprobacion timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_revisiones_orden ON public.revisiones_orden(id_orden);
CREATE INDEX IF NOT EXISTS idx_revisiones_usuario ON public.revisiones_orden(usuario_revisor_id);
CREATE INDEX IF NOT EXISTS idx_revisiones_estado ON public.revisiones_orden(estado_revision);
CREATE INDEX IF NOT EXISTS idx_revisiones_fecha ON public.revisiones_orden(fecha_revision);

-- Agregar campo de estado de revisión a la orden (para fácil acceso)
ALTER TABLE public.ordenes_trabajo
  ADD COLUMN IF NOT EXISTS estado_revision text CHECK (estado_revision IN ('pendiente', 'en_revision', 'aprobado', 'requiere_cambios', NULL));

CREATE INDEX IF NOT EXISTS idx_ordenes_estado_revision ON public.ordenes_trabajo(estado_revision) WHERE estado_revision IS NOT NULL;

-- Función para solicitar revisión
CREATE OR REPLACE FUNCTION public.solicitar_revision_orden(
  p_id_orden integer,
  p_usuario_revisor_id integer,
  p_usuario_revisor_nombre varchar(100),
  p_comentarios text DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_id integer;
BEGIN
  -- Crear registro de revisión
  INSERT INTO public.revisiones_orden (
    id_orden,
    usuario_revisor_id,
    usuario_revisor_nombre,
    estado_revision,
    comentarios
  )
  VALUES (
    p_id_orden,
    p_usuario_revisor_id,
    p_usuario_revisor_nombre,
    'en_revision',
    p_comentarios
  )
  RETURNING id INTO v_new_id;

  -- Actualizar estado de revisión en la orden
  UPDATE public.ordenes_trabajo
  SET estado_revision = 'en_revision'
  WHERE id = p_id_orden;

  RETURN v_new_id;
END;
$$;

-- Función para aprobar orden
CREATE OR REPLACE FUNCTION public.aprobar_revision_orden(
  p_id_revision integer,
  p_comentarios text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id_orden integer;
BEGIN
  -- Actualizar revisión
  UPDATE public.revisiones_orden
  SET estado_revision = 'aprobado',
      comentarios = COALESCE(p_comentarios, comentarios),
      fecha_aprobacion = now()
  WHERE id = p_id_revision
  RETURNING id_orden INTO v_id_orden;

  -- Actualizar estado de revisión en la orden
  IF v_id_orden IS NOT NULL THEN
    UPDATE public.ordenes_trabajo
    SET estado_revision = 'aprobado'
    WHERE id = v_id_orden;
  END IF;
END;
$$;

-- Función para rechazar/rechazar con cambios
CREATE OR REPLACE FUNCTION public.rechazar_revision_orden(
  p_id_revision integer,
  p_comentarios text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id_orden integer;
BEGIN
  -- Actualizar revisión
  UPDATE public.revisiones_orden
  SET estado_revision = 'requiere_cambios',
      comentarios = p_comentarios
  WHERE id = p_id_revision
  RETURNING id_orden INTO v_id_orden;

  -- Actualizar estado de revisión en la orden
  IF v_id_orden IS NOT NULL THEN
    UPDATE public.ordenes_trabajo
    SET estado_revision = 'requiere_cambios'
    WHERE id = v_id_orden;
  END IF;
END;
$$;

-- Función para obtener revisiones de una orden
CREATE OR REPLACE FUNCTION public.obtener_revisiones_orden(
  p_id_orden integer
)
RETURNS TABLE (
  id integer,
  id_orden integer,
  usuario_revisor_id integer,
  usuario_revisor_nombre varchar(100),
  estado_revision text,
  comentarios text,
  fecha_revision timestamptz,
  fecha_aprobacion timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    r.id,
    r.id_orden,
    r.usuario_revisor_id,
    r.usuario_revisor_nombre,
    r.estado_revision,
    r.comentarios,
    r.fecha_revision,
    r.fecha_aprobacion
  FROM public.revisiones_orden r
  WHERE r.id_orden = p_id_orden
  ORDER BY r.fecha_revision DESC;
END;
$$;

-- Comentarios
COMMENT ON TABLE public.revisiones_orden IS 'Registro de revisiones y aprobaciones de órdenes';
COMMENT ON FUNCTION public.solicitar_revision_orden IS 'Solicita una revisión para una orden';
COMMENT ON FUNCTION public.aprobar_revision_orden IS 'Aprueba una revisión';
COMMENT ON FUNCTION public.rechazar_revision_orden IS 'Rechaza una revisión solicitando cambios';
COMMENT ON FUNCTION public.obtener_revisiones_orden IS 'Obtiene todas las revisiones de una orden';

