-- ============================================
-- SISTEMA DE CAPACITACIONES
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE CAPACITACIONES
-- ============================================
CREATE TABLE IF NOT EXISTS public.capacitaciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo varchar(255) NOT NULL,
  descripcion text,
  tipo_capacitacion varchar(100) NOT NULL DEFAULT 'presencial', -- 'presencial', 'virtual', 'mixta', 'online'
  categoria varchar(100), -- 'tecnica', 'seguridad', 'soft_skills', 'compliance', 'otra'
  duracion_horas numeric(5,2), -- Duración en horas
  fecha_inicio date,
  fecha_fin date,
  fecha_limite_inscripcion date,
  cupo_maximo integer,
  lugar varchar(255), -- Para capacitaciones presenciales
  link_virtual text, -- Para capacitaciones virtuales
  instructor varchar(255),
  estado varchar(50) DEFAULT 'planificada', -- 'planificada', 'abierta', 'en_curso', 'completada', 'cancelada'
  es_obligatoria boolean DEFAULT false,
  requiere_aprobacion boolean DEFAULT true,
  material_adjunto_url text, -- URL de materiales, PDFs, etc.
  observaciones text,
  creado_por integer NOT NULL REFERENCES public.usuarios(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_capacitaciones_estado ON public.capacitaciones(estado);
CREATE INDEX IF NOT EXISTS idx_capacitaciones_tipo ON public.capacitaciones(tipo_capacitacion);
CREATE INDEX IF NOT EXISTS idx_capacitaciones_categoria ON public.capacitaciones(categoria);
CREATE INDEX IF NOT EXISTS idx_capacitaciones_fecha_inicio ON public.capacitaciones(fecha_inicio);
CREATE INDEX IF NOT EXISTS idx_capacitaciones_creado_por ON public.capacitaciones(creado_por);

-- ============================================
-- 2. TABLA DE INSCRIPCIONES
-- ============================================
CREATE TABLE IF NOT EXISTS public.capacitaciones_inscripciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_capacitacion integer NOT NULL REFERENCES public.capacitaciones(id) ON DELETE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  fecha_inscripcion timestamptz DEFAULT now(),
  estado varchar(50) DEFAULT 'pendiente', -- 'pendiente', 'inscrito', 'aprobado', 'rechazado', 'completado', 'ausente', 'cancelado'
  asistio boolean DEFAULT false,
  calificacion numeric(4,2), -- Calificación obtenida (0-10)
  comentarios text,
  aprobado_por integer REFERENCES public.usuarios(id),
  fecha_aprobacion timestamptz,
  motivo_rechazo text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE(id_capacitacion, id_usuario)
);

CREATE INDEX IF NOT EXISTS idx_inscripciones_capacitacion ON public.capacitaciones_inscripciones(id_capacitacion);
CREATE INDEX IF NOT EXISTS idx_inscripciones_usuario ON public.capacitaciones_inscripciones(id_usuario);
CREATE INDEX IF NOT EXISTS idx_inscripciones_estado ON public.capacitaciones_inscripciones(estado);

-- ============================================
-- 3. FUNCIONES PARA CAPACITACIONES
-- ============================================

-- Crear capacitación
CREATE OR REPLACE FUNCTION public.crear_capacitacion(
  p_titulo varchar,
  p_descripcion text,
  p_tipo_capacitacion varchar DEFAULT 'presencial',
  p_categoria varchar DEFAULT NULL,
  p_duracion_horas numeric DEFAULT NULL,
  p_fecha_inicio date DEFAULT NULL,
  p_fecha_fin date DEFAULT NULL,
  p_fecha_limite_inscripcion date DEFAULT NULL,
  p_cupo_maximo integer DEFAULT NULL,
  p_lugar varchar DEFAULT NULL,
  p_link_virtual text DEFAULT NULL,
  p_instructor varchar DEFAULT NULL,
  p_es_obligatoria boolean DEFAULT false,
  p_requiere_aprobacion boolean DEFAULT true,
  p_material_adjunto_url text DEFAULT NULL,
  p_observaciones text DEFAULT NULL,
  p_creado_por integer
)
RETURNS public.capacitaciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.capacitaciones;
BEGIN
  INSERT INTO public.capacitaciones (
    titulo, descripcion, tipo_capacitacion, categoria, duracion_horas,
    fecha_inicio, fecha_fin, fecha_limite_inscripcion, cupo_maximo,
    lugar, link_virtual, instructor, es_obligatoria, requiere_aprobacion,
    material_adjunto_url, observaciones, creado_por
  )
  VALUES (
    p_titulo, p_descripcion, p_tipo_capacitacion, p_categoria, p_duracion_horas,
    p_fecha_inicio, p_fecha_fin, p_fecha_limite_inscripcion, p_cupo_maximo,
    p_lugar, p_link_virtual, p_instructor, p_es_obligatoria, p_requiere_aprobacion,
    p_material_adjunto_url, p_observaciones, p_creado_por
  )
  RETURNING * INTO v_result;

  RETURN v_result;
END;
$$;

-- Listar capacitaciones
CREATE OR REPLACE FUNCTION public.obtener_capacitaciones(
  p_estado varchar DEFAULT NULL,
  p_tipo_capacitacion varchar DEFAULT NULL,
  p_categoria varchar DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL,
  p_id_usuario integer DEFAULT NULL -- Si se proporciona, incluye estado de inscripción
)
RETURNS TABLE (
  id integer,
  titulo varchar,
  descripcion text,
  tipo_capacitacion varchar,
  categoria varchar,
  duracion_horas numeric,
  fecha_inicio date,
  fecha_fin date,
  fecha_limite_inscripcion date,
  cupo_maximo integer,
  lugar varchar,
  link_virtual text,
  instructor varchar,
  estado varchar,
  es_obligatoria boolean,
  requiere_aprobacion boolean,
  material_adjunto_url text,
  observaciones text,
  creado_por integer,
  creado_por_nombre varchar,
  inscripciones_count integer,
  cupos_disponibles integer,
  usuario_inscrito boolean,
  estado_inscripcion varchar,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.id,
    c.titulo,
    c.descripcion,
    c.tipo_capacitacion,
    c.categoria,
    c.duracion_horas,
    c.fecha_inicio,
    c.fecha_fin,
    c.fecha_limite_inscripcion,
    c.cupo_maximo,
    c.lugar,
    c.link_virtual,
    c.instructor,
    c.estado,
    c.es_obligatoria,
    c.requiere_aprobacion,
    c.material_adjunto_url,
    c.observaciones,
    c.creado_por,
    u.nombre::varchar AS creado_por_nombre,
    COUNT(DISTINCT ci.id)::integer AS inscripciones_count,
    CASE 
      WHEN c.cupo_maximo IS NOT NULL THEN 
        GREATEST(0, c.cupo_maximo - COUNT(DISTINCT CASE WHEN ci.estado IN ('inscrito', 'aprobado', 'completado') THEN ci.id END))
      ELSE NULL
    END::integer AS cupos_disponibles,
    CASE WHEN p_id_usuario IS NOT NULL AND EXISTS (
      SELECT 1 FROM public.capacitaciones_inscripciones 
      WHERE id_capacitacion = c.id AND id_usuario = p_id_usuario
    ) THEN true ELSE false END AS usuario_inscrito,
    COALESCE(
      (SELECT ci2.estado FROM public.capacitaciones_inscripciones ci2 
       WHERE ci2.id_capacitacion = c.id AND ci2.id_usuario = p_id_usuario LIMIT 1),
      NULL
    )::varchar AS estado_inscripcion,
    c.created_at,
    c.updated_at
  FROM public.capacitaciones c
  LEFT JOIN public.usuarios u ON u.id = c.creado_por
  LEFT JOIN public.capacitaciones_inscripciones ci ON ci.id_capacitacion = c.id
  WHERE
    (p_estado IS NULL OR c.estado = p_estado)
    AND (p_tipo_capacitacion IS NULL OR c.tipo_capacitacion = p_tipo_capacitacion)
    AND (p_categoria IS NULL OR c.categoria = p_categoria)
    AND (p_fecha_desde IS NULL OR c.fecha_inicio >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR c.fecha_inicio <= p_fecha_hasta)
  GROUP BY c.id, u.nombre
  ORDER BY c.fecha_inicio DESC, c.created_at DESC;
END;
$$;

-- Inscribirse a capacitación
CREATE OR REPLACE FUNCTION public.inscribirse_capacitacion(
  p_id_capacitacion integer,
  p_id_usuario integer
)
RETURNS public.capacitaciones_inscripciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_capacitacion public.capacitaciones;
  v_cupos_disponibles integer;
  v_inscripcion_existente integer;
  v_result public.capacitaciones_inscripciones;
BEGIN
  -- Verificar que la capacitación existe
  SELECT * INTO v_capacitacion FROM public.capacitaciones WHERE id = p_id_capacitacion;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Capacitación no encontrada';
  END IF;

  -- Verificar que no esté ya inscrito
  SELECT id INTO v_inscripcion_existente 
  FROM public.capacitaciones_inscripciones 
  WHERE id_capacitacion = p_id_capacitacion AND id_usuario = p_id_usuario;
  
  IF v_inscripcion_existente IS NOT NULL THEN
    RAISE EXCEPTION 'Ya estás inscrito en esta capacitación';
  END IF;

  -- Verificar cupos disponibles
  IF v_capacitacion.cupo_maximo IS NOT NULL THEN
    SELECT COUNT(*) INTO v_cupos_disponibles
    FROM public.capacitaciones_inscripciones
    WHERE id_capacitacion = p_id_capacitacion 
      AND estado IN ('inscrito', 'aprobado', 'completado');
    
    IF v_cupos_disponibles >= v_capacitacion.cupo_maximo THEN
      RAISE EXCEPTION 'No hay cupos disponibles';
    END IF;
  END IF;

  -- Verificar fecha límite
  IF v_capacitacion.fecha_limite_inscripcion IS NOT NULL 
     AND v_capacitacion.fecha_limite_inscripcion < CURRENT_DATE THEN
    RAISE EXCEPTION 'La fecha límite de inscripción ha pasado';
  END IF;

  -- Crear inscripción
  INSERT INTO public.capacitaciones_inscripciones (
    id_capacitacion, id_usuario, estado
  )
  VALUES (
    p_id_capacitacion, p_id_usuario,
    CASE WHEN v_capacitacion.requiere_aprobacion THEN 'pendiente' ELSE 'inscrito' END
  )
  RETURNING * INTO v_result;

  RETURN v_result;
END;
$$;

-- Aprobar/Rechazar inscripción
CREATE OR REPLACE FUNCTION public.aprobar_rechazar_inscripcion(
  p_id integer,
  p_estado varchar, -- 'aprobado' o 'rechazado'
  p_id_aprobador integer,
  p_motivo_rechazo text DEFAULT NULL
)
RETURNS public.capacitaciones_inscripciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.capacitaciones_inscripciones;
BEGIN
  IF p_estado NOT IN ('aprobado', 'rechazado') THEN
    RAISE EXCEPTION 'Estado inválido. Debe ser "aprobado" o "rechazado"';
  END IF;

  UPDATE public.capacitaciones_inscripciones
  SET
    estado = p_estado,
    aprobado_por = p_id_aprobador,
    fecha_aprobacion = now(),
    motivo_rechazo = CASE WHEN p_estado = 'rechazado' THEN p_motivo_rechazo ELSE NULL END,
    updated_at = now()
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.capacitaciones_inscripciones WHERE id = p_id;
  RETURN v_result;
END;
$$;

-- Obtener inscripciones de una capacitación
CREATE OR REPLACE FUNCTION public.obtener_inscripciones_capacitacion(
  p_id_capacitacion integer,
  p_estado varchar DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  id_capacitacion integer,
  id_usuario integer,
  nombre_usuario varchar,
  fecha_inscripcion timestamptz,
  estado varchar,
  asistio boolean,
  calificacion numeric,
  comentarios text,
  aprobado_por integer,
  aprobado_por_nombre varchar,
  fecha_aprobacion timestamptz,
  motivo_rechazo text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ci.id,
    ci.id_capacitacion,
    ci.id_usuario,
    u.nombre::varchar AS nombre_usuario,
    ci.fecha_inscripcion,
    ci.estado,
    ci.asistio,
    ci.calificacion,
    ci.comentarios,
    ci.aprobado_por,
    u2.nombre::varchar AS aprobado_por_nombre,
    ci.fecha_aprobacion,
    ci.motivo_rechazo,
    ci.created_at,
    ci.updated_at
  FROM public.capacitaciones_inscripciones ci
  JOIN public.usuarios u ON u.id = ci.id_usuario
  LEFT JOIN public.usuarios u2 ON u2.id = ci.aprobado_por
  WHERE ci.id_capacitacion = p_id_capacitacion
    AND (p_estado IS NULL OR ci.estado = p_estado)
  ORDER BY ci.fecha_inscripcion DESC;
END;
$$;

-- Obtener capacitaciones de un usuario
CREATE OR REPLACE FUNCTION public.obtener_capacitaciones_usuario(
  p_id_usuario integer,
  p_estado_inscripcion varchar DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  titulo varchar,
  descripcion text,
  tipo_capacitacion varchar,
  categoria varchar,
  duracion_horas numeric,
  fecha_inicio date,
  fecha_fin date,
  lugar varchar,
  link_virtual text,
  instructor varchar,
  estado varchar,
  estado_inscripcion varchar,
  asistio boolean,
  calificacion numeric,
  fecha_inscripcion timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.id,
    c.titulo,
    c.descripcion,
    c.tipo_capacitacion,
    c.categoria,
    c.duracion_horas,
    c.fecha_inicio,
    c.fecha_fin,
    c.lugar,
    c.link_virtual,
    c.instructor,
    c.estado,
    ci.estado AS estado_inscripcion,
    ci.asistio,
    ci.calificacion,
    ci.fecha_inscripcion
  FROM public.capacitaciones_inscripciones ci
  JOIN public.capacitaciones c ON c.id = ci.id_capacitacion
  WHERE ci.id_usuario = p_id_usuario
    AND (p_estado_inscripcion IS NULL OR ci.estado = p_estado_inscripcion)
  ORDER BY c.fecha_inicio DESC;
END;
$$;

-- Actualizar capacitación
CREATE OR REPLACE FUNCTION public.actualizar_capacitacion(
  p_id integer,
  p_titulo varchar DEFAULT NULL,
  p_descripcion text DEFAULT NULL,
  p_tipo_capacitacion varchar DEFAULT NULL,
  p_categoria varchar DEFAULT NULL,
  p_duracion_horas numeric DEFAULT NULL,
  p_fecha_inicio date DEFAULT NULL,
  p_fecha_fin date DEFAULT NULL,
  p_fecha_limite_inscripcion date DEFAULT NULL,
  p_cupo_maximo integer DEFAULT NULL,
  p_lugar varchar DEFAULT NULL,
  p_link_virtual text DEFAULT NULL,
  p_instructor varchar DEFAULT NULL,
  p_estado varchar DEFAULT NULL,
  p_es_obligatoria boolean DEFAULT NULL,
  p_requiere_aprobacion boolean DEFAULT NULL,
  p_material_adjunto_url text DEFAULT NULL,
  p_observaciones text DEFAULT NULL
)
RETURNS public.capacitaciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.capacitaciones;
BEGIN
  UPDATE public.capacitaciones
  SET
    titulo = COALESCE(p_titulo, titulo),
    descripcion = COALESCE(p_descripcion, descripcion),
    tipo_capacitacion = COALESCE(p_tipo_capacitacion, tipo_capacitacion),
    categoria = COALESCE(p_categoria, categoria),
    duracion_horas = COALESCE(p_duracion_horas, duracion_horas),
    fecha_inicio = COALESCE(p_fecha_inicio, fecha_inicio),
    fecha_fin = COALESCE(p_fecha_fin, fecha_fin),
    fecha_limite_inscripcion = COALESCE(p_fecha_limite_inscripcion, fecha_limite_inscripcion),
    cupo_maximo = COALESCE(p_cupo_maximo, cupo_maximo),
    lugar = COALESCE(p_lugar, lugar),
    link_virtual = COALESCE(p_link_virtual, link_virtual),
    instructor = COALESCE(p_instructor, instructor),
    estado = COALESCE(p_estado, estado),
    es_obligatoria = COALESCE(p_es_obligatoria, es_obligatoria),
    requiere_aprobacion = COALESCE(p_requiere_aprobacion, requiere_aprobacion),
    material_adjunto_url = COALESCE(p_material_adjunto_url, material_adjunto_url),
    observaciones = COALESCE(p_observaciones, observaciones),
    updated_at = now()
  WHERE id = p_id;

  SELECT * INTO v_result FROM public.capacitaciones WHERE id = p_id;
  RETURN v_result;
END;
$$;

-- Registrar asistencia y calificación
CREATE OR REPLACE FUNCTION public.registrar_asistencia_capacitacion(
  p_id_inscripcion integer,
  p_asistio boolean,
  p_calificacion numeric DEFAULT NULL,
  p_comentarios text DEFAULT NULL
)
RETURNS public.capacitaciones_inscripciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.capacitaciones_inscripciones;
BEGIN
  UPDATE public.capacitaciones_inscripciones
  SET
    asistio = p_asistio,
    calificacion = COALESCE(p_calificacion, calificacion),
    comentarios = COALESCE(p_comentarios, comentarios),
    estado = CASE WHEN p_asistio THEN 'completado' ELSE 'ausente' END,
    updated_at = now()
  WHERE id = p_id_inscripcion;

  SELECT * INTO v_result FROM public.capacitaciones_inscripciones WHERE id = p_id_inscripcion;
  RETURN v_result;
END;
$$;

-- Cancelar inscripción
CREATE OR REPLACE FUNCTION public.cancelar_inscripcion(
  p_id_inscripcion integer,
  p_id_usuario integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.capacitaciones_inscripciones
  SET estado = 'cancelado', updated_at = now()
  WHERE id = p_id_inscripcion 
    AND id_usuario = p_id_usuario
    AND estado IN ('pendiente', 'inscrito', 'aprobado');

  RETURN FOUND;
END;
$$;

-- Eliminar capacitación
CREATE OR REPLACE FUNCTION public.eliminar_capacitacion(p_id integer)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.capacitaciones WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- ============================================
-- 4. RLS POLICIES
-- ============================================

ALTER TABLE public.capacitaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.capacitaciones_inscripciones ENABLE ROW LEVEL SECURITY;

-- Políticas para capacitaciones (todos pueden ver)
CREATE POLICY "Enable read access for all authenticated users" ON public.capacitaciones
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.capacitaciones
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.capacitaciones
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.capacitaciones
  FOR DELETE USING (true);

-- Políticas para inscripciones
CREATE POLICY "Enable read access for all authenticated users" ON public.capacitaciones_inscripciones
  FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated users" ON public.capacitaciones_inscripciones
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON public.capacitaciones_inscripciones
  FOR UPDATE USING (true);

CREATE POLICY "Enable delete for authenticated users" ON public.capacitaciones_inscripciones
  FOR DELETE USING (true);

COMMIT;

