-- Crear tabla de atenciones de mostrador
CREATE TABLE IF NOT EXISTS public.atenciones_mostrador (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  cliente_nombre varchar(255) NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('virtual', 'consulta', 'venta')),
  orden_id integer REFERENCES public.ordenes_trabajo(id) ON DELETE SET NULL,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  usuario_nombre varchar(100) NOT NULL,
  fecha_atencion timestamptz NOT NULL DEFAULT now(),
  notas text,
  created_at timestamptz DEFAULT now()
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_atenciones_usuario ON public.atenciones_mostrador(usuario_id);
CREATE INDEX IF NOT EXISTS idx_atenciones_timestamp ON public.atenciones_mostrador(fecha_atencion);
CREATE INDEX IF NOT EXISTS idx_atenciones_tipo ON public.atenciones_mostrador(tipo);
CREATE INDEX IF NOT EXISTS idx_atenciones_orden ON public.atenciones_mostrador(orden_id);
CREATE INDEX IF NOT EXISTS idx_atenciones_cliente_nombre ON public.atenciones_mostrador(cliente_nombre);

-- Función para crear una atención
CREATE OR REPLACE FUNCTION public.crear_atencion_mostrador(
  p_cliente_nombre varchar(255),
  p_tipo text,
  p_usuario_id integer,
  p_usuario_nombre varchar(100),
  p_orden_id integer DEFAULT NULL,
  p_cliente_id integer DEFAULT NULL,
  p_notas text DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_new_id integer;
BEGIN
  -- Validar tipo
  IF p_tipo NOT IN ('virtual', 'consulta', 'venta') THEN
    RAISE EXCEPTION 'Tipo de atención inválido: %. Debe ser virtual, consulta o venta', p_tipo;
  END IF;

  -- Insertar atención
  INSERT INTO public.atenciones_mostrador (
    cliente_nombre,
    tipo,
    usuario_id,
    usuario_nombre,
    orden_id,
    cliente_id,
    notas,
    fecha_atencion
  )
  VALUES (
    p_cliente_nombre,
    p_tipo,
    p_usuario_id,
    p_usuario_nombre,
    p_orden_id,
    p_cliente_id,
    p_notas,
    now()
  )
  RETURNING id INTO v_new_id;

  RETURN v_new_id;
END;
$$;

-- Función para obtener atenciones por rango de fechas
CREATE OR REPLACE FUNCTION public.obtener_atenciones_mostrador(
  p_fecha_inicio timestamptz DEFAULT NULL,
  p_fecha_fin timestamptz DEFAULT NULL
)
RETURNS TABLE (
  id integer,
  cliente_id integer,
  cliente_nombre varchar(255),
  tipo text,
  orden_id integer,
  usuario_id integer,
  usuario_nombre varchar(100),
  fecha_atencion timestamptz,
  notas text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    a.id,
    a.cliente_id,
    a.cliente_nombre,
    a.tipo,
    a.orden_id,
    a.usuario_id,
    a.usuario_nombre,
    a.fecha_atencion,
    a.notas
  FROM public.atenciones_mostrador a
  WHERE 
    (p_fecha_inicio IS NULL OR a.fecha_atencion >= p_fecha_inicio)
    AND (p_fecha_fin IS NULL OR a.fecha_atencion <= p_fecha_fin)
  ORDER BY a.fecha_atencion DESC;
END;
$$;

-- Comentarios
COMMENT ON TABLE public.atenciones_mostrador IS 'Registro de atenciones realizadas en mostrador';
COMMENT ON FUNCTION public.crear_atencion_mostrador IS 'Crea una nueva atención de mostrador';
COMMENT ON FUNCTION public.obtener_atenciones_mostrador IS 'Obtiene atenciones de mostrador por rango de fechas';

