-- Sistema de Menú Diario
-- Permite a RRHH/Admin cargar el menú del día y a los empleados seleccionar su plato

-- Tabla de menús diarios
CREATE TABLE IF NOT EXISTS public.menus_diarios (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date NOT NULL UNIQUE, -- Solo un menú por día
  plato_principal varchar(255) NOT NULL,
  plato_secundario varchar(255),
  guarnicion varchar(255),
  ensalada varchar(255),
  postre varchar(255),
  bebida varchar(255),
  opcion_vegetariana varchar(255),
  observaciones text,
  activo boolean DEFAULT true,
  creado_por integer NOT NULL REFERENCES public.usuarios(id),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Tabla de selecciones de empleados
CREATE TABLE IF NOT EXISTS public.menu_selecciones (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_menu integer NOT NULL REFERENCES public.menus_diarios(id) ON DELETE CASCADE,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  seleccion varchar(50) NOT NULL, -- 'principal', 'secundario', 'vegetariano'
  observaciones text,
  fecha_seleccion timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now(),
  UNIQUE(id_menu, id_usuario) -- Un empleado solo puede seleccionar una vez por menú
);

-- Índices para mejorar rendimiento
CREATE INDEX IF NOT EXISTS idx_menus_diarios_fecha ON public.menus_diarios(fecha);
CREATE INDEX IF NOT EXISTS idx_menus_diarios_activo ON public.menus_diarios(activo);
CREATE INDEX IF NOT EXISTS idx_menu_selecciones_menu ON public.menu_selecciones(id_menu);
CREATE INDEX IF NOT EXISTS idx_menu_selecciones_usuario ON public.menu_selecciones(id_usuario);
CREATE INDEX IF NOT EXISTS idx_menu_selecciones_fecha ON public.menu_selecciones(fecha_seleccion);

-- Función para crear o actualizar menú diario
CREATE OR REPLACE FUNCTION public.crear_actualizar_menu_diario(
  p_fecha date,
  p_plato_principal varchar(255),
  p_plato_secundario varchar(255) DEFAULT NULL,
  p_guarnicion varchar(255) DEFAULT NULL,
  p_ensalada varchar(255) DEFAULT NULL,
  p_postre varchar(255) DEFAULT NULL,
  p_bebida varchar(255) DEFAULT NULL,
  p_opcion_vegetariana varchar(255) DEFAULT NULL,
  p_observaciones text DEFAULT NULL,
  p_activo boolean DEFAULT true,
  p_creado_por integer
)
RETURNS public.menus_diarios
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.menus_diarios;
BEGIN
  INSERT INTO public.menus_diarios (
    fecha, plato_principal, plato_secundario, guarnicion, ensalada,
    postre, bebida, opcion_vegetariana, observaciones, activo, creado_por
  )
  VALUES (
    p_fecha, p_plato_principal, p_plato_secundario, p_guarnicion, p_ensalada,
    p_postre, p_bebida, p_opcion_vegetariana, p_observaciones, p_activo, p_creado_por
  )
  ON CONFLICT (fecha) DO UPDATE SET
    plato_principal = EXCLUDED.plato_principal,
    plato_secundario = EXCLUDED.plato_secundario,
    guarnicion = EXCLUDED.guarnicion,
    ensalada = EXCLUDED.ensalada,
    postre = EXCLUDED.postre,
    bebida = EXCLUDED.bebida,
    opcion_vegetariana = EXCLUDED.opcion_vegetariana,
    observaciones = EXCLUDED.observaciones,
    activo = EXCLUDED.activo,
    updated_at = now()
  RETURNING * INTO v_result;
  
  RETURN v_result;
END;
$$;

-- Función para obtener menús diarios
CREATE OR REPLACE FUNCTION public.obtener_menus_diarios(
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL,
  p_solo_activos boolean DEFAULT true
)
RETURNS TABLE (
  id integer,
  fecha date,
  plato_principal varchar(255),
  plato_secundario varchar(255),
  guarnicion varchar(255),
  ensalada varchar(255),
  postre varchar(255),
  bebida varchar(255),
  opcion_vegetariana varchar(255),
  observaciones text,
  activo boolean,
  creado_por integer,
  creado_por_nombre varchar(255),
  created_at timestamptz,
  updated_at timestamptz,
  total_selecciones bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    m.id,
    m.fecha,
    m.plato_principal,
    m.plato_secundario,
    m.guarnicion,
    m.ensalada,
    m.postre,
    m.bebida,
    m.opcion_vegetariana,
    m.observaciones,
    m.activo,
    m.creado_por,
    u.nombre as creado_por_nombre,
    m.created_at,
    m.updated_at,
    COUNT(ms.id)::bigint as total_selecciones
  FROM public.menus_diarios m
  LEFT JOIN public.usuarios u ON m.creado_por = u.id
  LEFT JOIN public.menu_selecciones ms ON m.id = ms.id_menu
  WHERE 
    (p_fecha_desde IS NULL OR m.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR m.fecha <= p_fecha_hasta)
    AND (NOT p_solo_activos OR m.activo = true)
  GROUP BY m.id, u.nombre
  ORDER BY m.fecha DESC;
END;
$$;

-- Función para obtener menú del día actual
CREATE OR REPLACE FUNCTION public.obtener_menu_dia_actual()
RETURNS TABLE (
  id integer,
  fecha date,
  plato_principal varchar(255),
  plato_secundario varchar(255),
  guarnicion varchar(255),
  ensalada varchar(255),
  postre varchar(255),
  bebida varchar(255),
  opcion_vegetariana varchar(255),
  observaciones text,
  activo boolean,
  creado_por integer,
  creado_por_nombre varchar(255),
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    m.id,
    m.fecha,
    m.plato_principal,
    m.plato_secundario,
    m.guarnicion,
    m.ensalada,
    m.postre,
    m.bebida,
    m.opcion_vegetariana,
    m.observaciones,
    m.activo,
    m.creado_por,
    u.nombre as creado_por_nombre,
    m.created_at,
    m.updated_at
  FROM public.menus_diarios m
  LEFT JOIN public.usuarios u ON m.creado_por = u.id
  WHERE m.fecha = CURRENT_DATE
    AND m.activo = true
  LIMIT 1;
END;
$$;

-- Función para seleccionar plato del menú
CREATE OR REPLACE FUNCTION public.seleccionar_plato_menu(
  p_id_menu integer,
  p_id_usuario integer,
  p_seleccion varchar(50),
  p_observaciones text DEFAULT NULL
)
RETURNS public.menu_selecciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_menu public.menus_diarios;
  v_hora_actual time;
  v_fecha_menu date;
  v_result public.menu_selecciones;
BEGIN
  -- Obtener el menú
  SELECT * INTO v_menu FROM public.menus_diarios WHERE id = p_id_menu;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menú no encontrado';
  END IF;

  -- Verificar que el menú esté activo
  IF NOT v_menu.activo THEN
    RAISE EXCEPTION 'El menú no está activo';
  END IF;

  -- Verificar fecha del menú
  v_fecha_menu := v_menu.fecha;
  IF v_fecha_menu != CURRENT_DATE THEN
    RAISE EXCEPTION 'Solo se puede seleccionar el menú del día actual';
  END IF;

  -- Verificar horario (hasta las 9:30 AM)
  v_hora_actual := CURRENT_TIME;
  IF v_hora_actual > '09:30:00'::time THEN
    RAISE EXCEPTION 'El plazo para seleccionar el menú ha expirado. Debes hacerlo antes de las 9:30 AM';
  END IF;

  -- Verificar que la selección sea válida
  IF p_seleccion NOT IN ('principal', 'secundario', 'vegetariano') THEN
    RAISE EXCEPTION 'Selección inválida. Debe ser: principal, secundario o vegetariano';
  END IF;

  -- Insertar o actualizar selección
  INSERT INTO public.menu_selecciones (
    id_menu, id_usuario, seleccion, observaciones
  )
  VALUES (
    p_id_menu, p_id_usuario, p_seleccion, p_observaciones
  )
  ON CONFLICT (id_menu, id_usuario) DO UPDATE SET
    seleccion = EXCLUDED.seleccion,
    observaciones = EXCLUDED.observaciones,
    fecha_seleccion = now()
  RETURNING * INTO v_result;
  
  RETURN v_result;
END;
$$;

-- Función para obtener selecciones de un menú
CREATE OR REPLACE FUNCTION public.obtener_selecciones_menu(
  p_id_menu integer
)
RETURNS TABLE (
  id integer,
  id_menu integer,
  id_usuario integer,
  nombre_usuario varchar(255),
  seleccion varchar(50),
  observaciones text,
  fecha_seleccion timestamptz,
  created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    ms.id,
    ms.id_menu,
    ms.id_usuario,
    u.nombre as nombre_usuario,
    ms.seleccion,
    ms.observaciones,
    ms.fecha_seleccion,
    ms.created_at
  FROM public.menu_selecciones ms
  JOIN public.usuarios u ON ms.id_usuario = u.id
  WHERE ms.id_menu = p_id_menu
  ORDER BY ms.fecha_seleccion ASC;
END;
$$;

-- Función para obtener selección del usuario para un menú
CREATE OR REPLACE FUNCTION public.obtener_seleccion_usuario_menu(
  p_id_menu integer,
  p_id_usuario integer
)
RETURNS public.menu_selecciones
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_result public.menu_selecciones;
BEGIN
  SELECT * INTO v_result
  FROM public.menu_selecciones
  WHERE id_menu = p_id_menu AND id_usuario = p_id_usuario;
  
  RETURN v_result;
END;
$$;

-- Función para eliminar menú diario
CREATE OR REPLACE FUNCTION public.eliminar_menu_diario(
  p_id integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.menus_diarios WHERE id = p_id;
  RETURN FOUND;
END;
$$;

-- Función para cancelar selección
CREATE OR REPLACE FUNCTION public.cancelar_seleccion_menu(
  p_id_menu integer,
  p_id_usuario integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_menu public.menus_diarios;
  v_hora_actual time;
BEGIN
  -- Obtener el menú
  SELECT * INTO v_menu FROM public.menus_diarios WHERE id = p_id_menu;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menú no encontrado';
  END IF;

  -- Verificar fecha del menú
  IF v_menu.fecha != CURRENT_DATE THEN
    RAISE EXCEPTION 'Solo se puede cancelar la selección del menú del día actual';
  END IF;

  -- Verificar horario (hasta las 9:30 AM)
  v_hora_actual := CURRENT_TIME;
  IF v_hora_actual > '09:30:00'::time THEN
    RAISE EXCEPTION 'El plazo para cancelar la selección ha expirado. Debes hacerlo antes de las 9:30 AM';
  END IF;

  DELETE FROM public.menu_selecciones 
  WHERE id_menu = p_id_menu AND id_usuario = p_id_usuario;
  
  RETURN FOUND;
END;
$$;

-- RLS Policies
ALTER TABLE public.menus_diarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_selecciones ENABLE ROW LEVEL SECURITY;

-- Políticas para menus_diarios
-- Todos pueden ver menús activos
CREATE POLICY "Todos pueden ver menús activos"
  ON public.menus_diarios FOR SELECT
  USING (activo = true);

-- Solo RRHH y Admin pueden ver todos los menús
CREATE POLICY "RRHH y Admin pueden ver todos los menús"
  ON public.menus_diarios FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

-- Solo RRHH y Admin pueden crear/actualizar menús
CREATE POLICY "RRHH y Admin pueden crear menús"
  ON public.menus_diarios FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

CREATE POLICY "RRHH y Admin pueden actualizar menús"
  ON public.menus_diarios FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

CREATE POLICY "RRHH y Admin pueden eliminar menús"
  ON public.menus_diarios FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

-- Políticas para menu_selecciones
-- Los usuarios pueden ver sus propias selecciones
CREATE POLICY "Usuarios pueden ver sus selecciones"
  ON public.menu_selecciones FOR SELECT
  USING (
    id_usuario = auth.uid()::text::integer
    OR EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

-- Los usuarios pueden crear sus propias selecciones
CREATE POLICY "Usuarios pueden crear selecciones"
  ON public.menu_selecciones FOR INSERT
  WITH CHECK (id_usuario = auth.uid()::text::integer);

-- Los usuarios pueden actualizar sus propias selecciones
CREATE POLICY "Usuarios pueden actualizar sus selecciones"
  ON public.menu_selecciones FOR UPDATE
  USING (id_usuario = auth.uid()::text::integer);

-- Los usuarios pueden eliminar sus propias selecciones
CREATE POLICY "Usuarios pueden eliminar sus selecciones"
  ON public.menu_selecciones FOR DELETE
  USING (
    id_usuario = auth.uid()::text::integer
    OR EXISTS (
      SELECT 1 FROM public.usuarios
      WHERE id = auth.uid()::text::integer
      AND (rol = 'admin' OR rol = 'recursos_humanos')
    )
  );

