-- ============================================
-- PREFERENCIAS Y NOTAS DE CLIENTES FRECUENTES
-- Permite guardar preferencias, notas y estado VIP por DNI/CUIT
-- ============================================

BEGIN;

-- ============================================
-- 1. TABLA DE PREFERENCIAS DE CLIENTES
-- ============================================
CREATE TABLE IF NOT EXISTS public.preferencias_clientes (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni_cuit varchar(50) NOT NULL UNIQUE,
  preferencias text,
  notas_internas text,
  es_vip boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_preferencias_dni_cuit ON public.preferencias_clientes(dni_cuit);
CREATE INDEX IF NOT EXISTS idx_preferencias_vip ON public.preferencias_clientes(es_vip);

-- ============================================
-- 2. FUNCIÓN PARA OBTENER PREFERENCIAS
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_preferencias_cliente(p_dni_cuit varchar(50))
RETURNS TABLE (
  id integer,
  dni_cuit varchar(50),
  preferencias text,
  notas_internas text,
  es_vip boolean,
  created_at timestamptz,
  updated_at timestamptz
) 
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pc.id,
    pc.dni_cuit,
    pc.preferencias,
    pc.notas_internas,
    pc.es_vip,
    pc.created_at,
    pc.updated_at
  FROM public.preferencias_clientes pc
  WHERE pc.dni_cuit = UPPER(p_dni_cuit);
END;
$$;

-- ============================================
-- 3. FUNCIÓN PARA GUARDAR/ACTUALIZAR PREFERENCIAS
-- ============================================
CREATE OR REPLACE FUNCTION public.guardar_preferencias_cliente(
  p_dni_cuit varchar(50),
  p_preferencias text DEFAULT NULL,
  p_notas_internas text DEFAULT NULL,
  p_es_vip boolean DEFAULT false
)
RETURNS TABLE (
  id integer,
  dni_cuit varchar(50),
  preferencias text,
  notas_internas text,
  es_vip boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_id integer;
BEGIN
  INSERT INTO public.preferencias_clientes (dni_cuit, preferencias, notas_internas, es_vip)
  VALUES (UPPER(p_dni_cuit), p_preferencias, p_notas_internas, p_es_vip)
  ON CONFLICT (dni_cuit) 
  DO UPDATE SET
    preferencias = EXCLUDED.preferencias,
    notas_internas = EXCLUDED.notas_internas,
    es_vip = EXCLUDED.es_vip,
    updated_at = now()
  RETURNING preferencias_clientes.id INTO v_id;

  RETURN QUERY
  SELECT 
    pc.id,
    pc.dni_cuit,
    pc.preferencias,
    pc.notas_internas,
    pc.es_vip
  FROM public.preferencias_clientes pc
  WHERE pc.id = v_id;
END;
$$;

-- ============================================
-- 4. FUNCIÓN PARA OBTENER TODAS LAS PREFERENCIAS
-- ============================================
CREATE OR REPLACE FUNCTION public.obtener_todas_preferencias_clientes()
RETURNS TABLE (
  dni_cuit varchar(50),
  preferencias text,
  notas_internas text,
  es_vip boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pc.dni_cuit,
    pc.preferencias,
    pc.notas_internas,
    pc.es_vip
  FROM public.preferencias_clientes pc
  ORDER BY pc.dni_cuit;
END;
$$;

-- ============================================
-- 5. RLS POLICIES
-- ============================================
ALTER TABLE public.preferencias_clientes ENABLE ROW LEVEL SECURITY;

-- Permitir lectura a usuarios autenticados
CREATE POLICY "Usuarios autenticados pueden leer preferencias"
  ON public.preferencias_clientes
  FOR SELECT
  TO authenticated
  USING (true);

-- Permitir inserción/actualización a usuarios autenticados
CREATE POLICY "Usuarios autenticados pueden insertar/actualizar preferencias"
  ON public.preferencias_clientes
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

COMMIT;

