-- Deudas a proveedores (migrado desde Listado De Deudas A Proveedores.XLS)
BEGIN;

CREATE TABLE IF NOT EXISTS public.deudas_proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo varchar(20) NOT NULL UNIQUE,
  razon_social text NOT NULL,
  telefono varchar(80) DEFAULT '-',
  saldo numeric(15,2) NOT NULL DEFAULT 0,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  fecha_corte date NOT NULL DEFAULT CURRENT_DATE,
  notas text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deudas_proveedores_proveedor ON public.deudas_proveedores(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_deudas_proveedores_codigo ON public.deudas_proveedores(codigo);

ALTER TABLE public.deudas_proveedores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS deudas_proveedores_all ON public.deudas_proveedores;
CREATE POLICY deudas_proveedores_all ON public.deudas_proveedores FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

INSERT INTO public.deudas_proveedores (codigo, razon_social, telefono, saldo, fecha_corte)
VALUES
  ('00009', 'ALANIZ MOLINA, MARCELO EMILIANO', '-', 941986.37, '2026-06-19'),
  ('00013', 'ALESSI MARTIN ESTEBAN SRL', '-', 110000.00, '2026-06-19'),
  ('00935', 'ALFREDO ALEJANDRO DARONI', '(264) 5641800', 26000000.00, '2026-06-19'),
  ('00014', 'ALUMETAL S A', '-', 877906.21, '2026-06-19'),
  ('00861', 'ARACENA RUZYCKI MARIANO AGUSTIN', '(-264) 4227030', 1802000.00, '2026-06-19'),
  ('00969', 'ARANCIBIA MOYANO GUSTAVO A', '( 0264) 44444444', 1800000.00, '2026-06-19'),
  ('00801', 'BANCO DE GALICIA Y BUENOS AIRES S.A.U.', '-', 690806.01, '2026-06-19'),
  ('00023', 'BANCO SANTANDER RIO SOCIEDAD ANONIMA', '-', -711372.01, '2026-06-19'),
  ('00033', 'BULONERA RAWSON S.R.L', '-', 300000.01, '2026-06-19'),
  ('00049', 'CICCHITTI, MARIA BIBIANA', '-', -341.95, '2026-06-19'),
  ('00059', 'COSTAUGO MENDOZA SA', '-', 3622923.92, '2026-06-19'),
  ('00997', 'D.G.A/SERVICIOS INTEGRALES S.A.S', '2644898982', 86712.94, '2026-06-19'),
  ('00996', 'DELAL S.A.S', '00000', 36542.00, '2026-06-19'),
  ('00071', 'DIMAGRAF S A C I F', '-', 1203521.86, '2026-06-19'),
  ('00852', 'DISTRIBUIDORA FERRETERIA SRL', '4228080', 154391.60, '2026-06-19'),
  ('00102', 'FLEXXUS S A', '-', -1549056.36, '2026-06-19'),
  ('00109', 'GALVAN HERMANOS SRL', '-', 118000.09, '2026-06-19'),
  ('00929', 'GALVAN MANCHINI PABLO EDUARDO', '( 264) 4221563', 138000.00, '2026-06-19'),
  ('00889', 'GAMA SONIC ARGENTINA SRL', '54 9 11 6996-3302', 203988.00, '2026-06-19'),
  ('00117', 'GIMENEZ, CAROLINA H', '1156225814', 21477.50, '2026-06-19'),
  ('00121', 'GOLDSTEIN AUTOMOTORES SACI', '-', 2593649.41, '2026-06-19'),
  ('00761', 'GORANSKY DE LA TORRE NICOLAS ABRAHAM', '-', 1200944.91, '2026-06-19'),
  ('00125', 'GRAF OESTE S A', '-', 32372.34, '2026-06-19'),
  ('00130', 'GUSBERTI, FABIO', '-', 2578994.61, '2026-06-19'),
  ('00778', 'IFRIMEN SRL', '4218282', 1268694.31, '2026-06-19'),
  ('00868', 'IGENAR ARGENTINA S.A.', '(011) 47626788', 13872134.21, '2026-06-19'),
  ('00847', 'L.C SUMINISTROS GRAFICOS S.R.L', '5464', 3913917.86, '2026-06-19'),
  ('00950', 'MACSTATION', '1', 159990.00, '2026-06-19'),
  ('00164', 'MANANTO S.A.', '-', 5630275.77, '2026-06-19'),
  ('00165', 'MARIO GOLDSTEIN S A C I', '-2644227141', 300000.00, '2026-06-19'),
  ('00167', 'MARTIN CAVA S A', '-', 761974.92, '2026-06-19'),
  ('00991', 'MAZA LUIS CESAR', '646464', 150000.00, '2026-06-19'),
  ('00176', 'MEYNIEL SRL', '-', 589188.71, '2026-06-19'),
  ('00177', 'MIADOSQUI, JORGE ERNESTO', '-', 2611176.96, '2026-06-19'),
  ('00762', 'MUNICIPALIDAD DE LA CIUDAD DE SAN JUAN', '-', -7700110.00, '2026-06-19'),
  ('00087', 'NATURGY SAN JUAN S.A.', '-', 5099118.13, '2026-06-19'),
  ('00814', 'PIACENZA SRL', '25', 510879.62, '2026-06-19'),
  ('00205', 'PINTURERIA CORDOBA S R L', '-', 9550557.89, '2026-06-19'),
  ('00806', 'PM SERVICIOS EMPRESARIOS SRL', '-', 6420290.25, '2026-06-19'),
  ('00207', 'POLITO, NORMA GLADIS MERCEDES', '-', 2224078.16, '2026-06-19'),
  ('00910', 'R&R S.A', '2644 17-3422', 468137.10, '2026-06-19'),
  ('00228', 'SAN FRANCISCO HOGAR SOCIEDAD DE RESPONSABILIDAD LI', '-', -30253886.11, '2026-06-19'),
  ('00186', 'SAN SISTEMAS SRL', '-', 73999.99, '2026-06-19'),
  ('00232', 'SASTRE SIREROL, PERFECTO', '-', -500000.00, '2026-06-19'),
  ('00796', 'SERVICIOS INTEGRALES DE MEDICINA LABORAL S.R.L', '4', 264381.37, '2026-06-19'),
  ('00758', 'SERVINFO SRL', '54 9 2615 73-1955', -292427.96, '2026-06-19'),
  ('00858', 'SEÑALAR SRL', '544', 325.25, '2026-06-19'),
  ('00793', 'SOSTEN S.A.', '4210415', 405043.49, '2026-06-19'),
  ('00243', 'SWISS MEDICAL S A', '-', 169192.06, '2026-06-19'),
  ('00247', 'TELEFONICA MOVILES ARGENTINA SOCIEDAD ANONIMA', '-', 48154.31, '2026-06-19'),
  ('00248', 'TORO DIGITAL S.A.', '-', 1838897.52, '2026-06-19'),
  ('00776', 'WAYPOINT S.R.L', '4212893', 228268.25, '2026-06-19')
ON CONFLICT (codigo) DO UPDATE SET
  razon_social = EXCLUDED.razon_social,
  telefono = EXCLUDED.telefono,
  saldo = EXCLUDED.saldo,
  fecha_corte = EXCLUDED.fecha_corte,
  updated_at = now();

CREATE OR REPLACE FUNCTION public.vincular_deudas_proveedores()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE v_count integer;
BEGIN
  UPDATE public.deudas_proveedores d
  SET id_proveedor = p.id, updated_at = now()
  FROM public.proveedores p
  WHERE d.id_proveedor IS NULL
    AND (
      upper(trim(coalesce(p.razon_social, ''))) = upper(trim(d.razon_social))
      OR upper(trim(p.nombre)) = upper(trim(d.razon_social))
      OR upper(trim(p.nombre)) LIKE '%' || upper(trim(split_part(d.razon_social, ',', 1))) || '%'
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

SELECT public.vincular_deudas_proveedores();

COMMIT;
