-- KPIs con clasificación: ventas por rubro y motivos de insatisfacción en entregas.
--
-- clasificaciones_ia guarda UNA categoría por registro (se clasifica una sola vez):
--   fuente 'catalogo' → rubro del artículo (articulos_empresa.categoria, viene de Flexxus)
--   fuente 'regla'    → regla fija (ej. encuesta sin comentario)
--   fuente 'ia'       → TypeSafe (solo texto libre: descripción del ítem / comentario de la encuesta)
--   fuente 'manual'   → corregido por una persona
-- Los KPIs se calculan con SQL sobre esa tabla: la IA nunca calcula montos.
--
-- Todo es solo service_role: lo usa /api/erp/clasificacion-ia (staff JWT + rol admin).
-- Idempotente.

BEGIN;

CREATE TABLE IF NOT EXISTS public.clasificaciones_ia (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo text NOT NULL CHECK (tipo IN ('rubro_venta_item', 'motivo_falla_entrega')),
  entidad_id bigint NOT NULL,
  categoria text NOT NULL,
  confianza numeric(5,4),
  fuente text NOT NULL CHECK (fuente IN ('catalogo', 'regla', 'ia', 'manual')),
  -- Confianza baja: se muestra como "Sin clasificar" hasta que alguien lo revise
  revisar boolean NOT NULL DEFAULT false,
  modelo text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT clasificaciones_ia_tipo_entidad_key UNIQUE (tipo, entidad_id)
);

CREATE INDEX IF NOT EXISTS idx_clasificaciones_ia_tipo_categoria
  ON public.clasificaciones_ia (tipo, categoria);

ALTER TABLE public.clasificaciones_ia ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.clasificaciones_ia FROM anon, authenticated;
GRANT ALL ON TABLE public.clasificaciones_ia TO service_role;

COMMENT ON TABLE public.clasificaciones_ia IS
  'Categoría por registro para KPIs (rubro de ítems de venta, motivo de insatisfacción en entregas). Solo service_role.';

-- Registros todavía sin clasificar -------------------------------------------------
DROP FUNCTION IF EXISTS public.clasificacion_ia_pendientes(text, integer);
CREATE OR REPLACE FUNCTION public.clasificacion_ia_pendientes(
  p_tipo text,
  p_limite integer DEFAULT 40
)
RETURNS TABLE (
  entidad_id bigint,
  texto text,
  codigo text,
  rating smallint,
  contexto text,
  rubro_catalogo text
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_tipo = 'rubro_venta_item' THEN
    -- rubro_catalogo: si el código del ítem existe en el catálogo, su rubro se usa sin IA
    RETURN QUERY
    SELECT vi.id::bigint, vi.descripcion::text, NULLIF(btrim(vi.codigo_articulo), '')::text, NULL::smallint, NULL::text,
           ae.categoria::text
    FROM public.ventas_items vi
    JOIN public.ventas v ON v.id = vi.id_venta
    LEFT JOIN LATERAL (
      SELECT a.categoria
      FROM public.articulos_empresa a
      WHERE NULLIF(btrim(vi.codigo_articulo), '') IS NOT NULL
        AND upper(btrim(a.codigo)) = upper(btrim(vi.codigo_articulo))
        AND NULLIF(btrim(a.categoria), '') IS NOT NULL
      LIMIT 1
    ) ae ON true
    LEFT JOIN public.clasificaciones_ia c ON c.tipo = 'rubro_venta_item' AND c.entidad_id = vi.id
    WHERE c.id IS NULL
      AND COALESCE(v.estado_pago, '') <> 'Cancelado'
    -- Primero los que se resuelven por catálogo (no necesitan IA)
    ORDER BY (ae.categoria IS NULL), vi.id DESC
    LIMIT GREATEST(1, LEAST(COALESCE(p_limite, 40), 200));

  ELSIF p_tipo = 'motivo_falla_entrega' THEN
    -- Solo encuestas insatisfechas (1 a 3 sobre 5)
    RETURN QUERY
    SELECT s.id::bigint, s.comentario::text, NULL::text, s.rating, left(o.descripcion, 300)::text, NULL::text
    FROM public.atencion_satisfaccion_entrega s
    LEFT JOIN public.ordenes_trabajo o
      ON o.id = s.orden_id OR (s.orden_id IS NULL AND o.numero_op = s.numero_op)
    LEFT JOIN public.clasificaciones_ia c ON c.tipo = 'motivo_falla_entrega' AND c.entidad_id = s.id
    WHERE c.id IS NULL
      AND s.rating <= 3
    -- Primero los sin comentario (se resuelven por regla)
    ORDER BY (NULLIF(btrim(s.comentario), '') IS NOT NULL), s.id DESC
    LIMIT GREATEST(1, LEAST(COALESCE(p_limite, 40), 200));

  ELSE
    RAISE EXCEPTION 'Tipo de clasificación desconocido: %', p_tipo;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.clasificacion_ia_contar_pendientes()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'rubro_venta_item', (
      SELECT count(*)
      FROM public.ventas_items vi
      JOIN public.ventas v ON v.id = vi.id_venta
      LEFT JOIN public.clasificaciones_ia c ON c.tipo = 'rubro_venta_item' AND c.entidad_id = vi.id
      WHERE c.id IS NULL AND COALESCE(v.estado_pago, '') <> 'Cancelado'
    ),
    'motivo_falla_entrega', (
      SELECT count(*)
      FROM public.atencion_satisfaccion_entrega s
      LEFT JOIN public.clasificaciones_ia c ON c.tipo = 'motivo_falla_entrega' AND c.entidad_id = s.id
      WHERE c.id IS NULL AND s.rating <= 3
    )
  );
$$;

-- Rubros del catálogo (Flexxus) con 3 productos de ejemplo: son las opciones que recibe la IA
CREATE OR REPLACE FUNCTION public.clasificacion_ia_rubros_catalogo()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(jsonb_agg(jsonb_build_object('categoria', categoria, 'ejemplos', ejemplos) ORDER BY categoria), '[]'::jsonb)
  FROM (
    SELECT btrim(a.categoria) AS categoria,
           (array_agg(a.nombre ORDER BY a.nombre))[1:3] AS ejemplos
    FROM public.articulos_empresa a
    WHERE NULLIF(btrim(a.categoria), '') IS NOT NULL
      AND COALESCE(a.activo, true)
    GROUP BY btrim(a.categoria)
  ) r;
$$;

-- KPI: ventas por rubro ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.kpi_ventas_por_rubro(
  p_desde date,
  p_hasta date
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH items AS (
    SELECT
      vi.precio_total,
      CASE
        WHEN c.id IS NULL THEN 'Pendiente de clasificar'
        WHEN c.revisar THEN 'Sin clasificar (revisar)'
        ELSE c.categoria
      END AS rubro,
      c.fuente
    FROM public.ventas_items vi
    JOIN public.ventas v ON v.id = vi.id_venta
    LEFT JOIN public.clasificaciones_ia c ON c.tipo = 'rubro_venta_item' AND c.entidad_id = vi.id
    WHERE v.fecha_venta BETWEEN p_desde AND p_hasta
      AND COALESCE(v.estado_pago, '') <> 'Cancelado'
  ),
  por_rubro AS (
    SELECT
      rubro,
      round(sum(COALESCE(precio_total, 0)), 2) AS monto,
      count(*) AS items,
      count(*) FILTER (WHERE fuente = 'ia') AS items_ia
    FROM items
    GROUP BY rubro
  )
  SELECT jsonb_build_object(
    'monto_total', COALESCE((SELECT round(sum(COALESCE(precio_total, 0)), 2) FROM items), 0),
    'items', (SELECT count(*) FROM items),
    'por_rubro', COALESCE(
      (SELECT jsonb_agg(jsonb_build_object('rubro', rubro, 'monto', monto, 'items', items, 'items_ia', items_ia)
                        ORDER BY monto DESC)
       FROM por_rubro),
      '[]'::jsonb
    )
  );
$$;

-- KPI: motivos de insatisfacción en entregas --------------------------------------------
CREATE OR REPLACE FUNCTION public.kpi_fallas_entrega(
  p_desde date,
  p_hasta date
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH encuestas AS (
    SELECT
      s.id,
      s.rating,
      COALESCE(NULLIF(btrim(o.sector), ''), 'Sin sector') AS sector,
      CASE
        WHEN s.rating > 3 THEN NULL
        WHEN c.id IS NULL THEN 'Pendiente de clasificar'
        WHEN c.revisar THEN 'Sin clasificar (revisar)'
        ELSE c.categoria
      END AS motivo
    FROM public.atencion_satisfaccion_entrega s
    LEFT JOIN public.ordenes_trabajo o
      ON o.id = s.orden_id OR (s.orden_id IS NULL AND o.numero_op = s.numero_op)
    LEFT JOIN public.clasificaciones_ia c ON c.tipo = 'motivo_falla_entrega' AND c.entidad_id = s.id
    WHERE (s.created_at AT TIME ZONE 'America/Argentina/Buenos_Aires')::date BETWEEN p_desde AND p_hasta
  ),
  fallas AS (
    SELECT * FROM encuestas WHERE motivo IS NOT NULL
  )
  SELECT jsonb_build_object(
    'encuestas', (SELECT count(*) FROM encuestas),
    'insatisfechas', (SELECT count(*) FROM fallas),
    'rating_promedio', (SELECT round(avg(rating)::numeric, 2) FROM encuestas),
    'por_motivo', COALESCE(
      (SELECT jsonb_agg(jsonb_build_object('motivo', motivo, 'cantidad', cantidad) ORDER BY cantidad DESC)
       FROM (SELECT motivo, count(*) AS cantidad FROM fallas GROUP BY motivo) m),
      '[]'::jsonb
    ),
    'por_sector', COALESCE(
      (SELECT jsonb_agg(jsonb_build_object('sector', sector, 'motivo', motivo, 'cantidad', cantidad)
                        ORDER BY cantidad DESC, sector)
       FROM (SELECT sector, motivo, count(*) AS cantidad FROM fallas GROUP BY sector, motivo) sm),
      '[]'::jsonb
    )
  );
$$;

REVOKE ALL ON FUNCTION public.clasificacion_ia_pendientes(text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.clasificacion_ia_contar_pendientes() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.clasificacion_ia_rubros_catalogo() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.clasificacion_ia_rubros_catalogo() TO service_role;
REVOKE ALL ON FUNCTION public.kpi_ventas_por_rubro(date, date) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.kpi_fallas_entrega(date, date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.clasificacion_ia_pendientes(text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.clasificacion_ia_contar_pendientes() TO service_role;
GRANT EXECUTE ON FUNCTION public.kpi_ventas_por_rubro(date, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.kpi_fallas_entrega(date, date) TO service_role;

COMMIT;
