-- Solicitudes de impresión desde tótem: datos del cliente, archivo, notificaciones a imprenta/mostrador/caja y marca de pago
BEGIN;

CREATE TABLE IF NOT EXISTS public.totem_impresion_solicitudes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_nombre varchar(255) NOT NULL,
  cliente_dni varchar(80) NOT NULL,
  cliente_telefono varchar(80) NOT NULL,
  cantidad_hojas integer NOT NULL CHECK (cantidad_hojas > 0 AND cantidad_hojas <= 9999),
  tipo_impresion varchar(120) NOT NULL,
  origen_archivo varchar(40) NOT NULL,
  archivo_url text NOT NULL,
  archivo_nombre varchar(512) NOT NULL,
  orden_id integer REFERENCES public.ordenes_trabajo (id) ON DELETE SET NULL,
  numero_op varchar(80),
  id_venta integer REFERENCES public.ventas (id) ON DELETE SET NULL,
  estado_pago text NOT NULL DEFAULT 'pendiente' CHECK (estado_pago IN ('pendiente', 'pagado')),
  created_at timestamptz NOT NULL DEFAULT now(),
  pagado_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_totem_impresion_created ON public.totem_impresion_solicitudes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_totem_impresion_pago ON public.totem_impresion_solicitudes (estado_pago);
CREATE INDEX IF NOT EXISTS idx_totem_impresion_venta ON public.totem_impresion_solicitudes (id_venta);

COMMENT ON TABLE public.totem_impresion_solicitudes IS 'Pedidos de impresión desde /totem/consulta-cliente; notifica imprenta, mostrador y caja';

-- Crear solicitud y notificar a imprenta, mostrador y caja (área de impresión + cobro)
CREATE OR REPLACE FUNCTION public.crear_solicitud_impresion_totem(
  p_cliente_nombre varchar(255),
  p_cliente_dni varchar(80),
  p_cliente_telefono varchar(80),
  p_cantidad_hojas integer,
  p_tipo_impresion varchar(120),
  p_origen_archivo varchar(40),
  p_archivo_url text,
  p_archivo_nombre varchar(512),
  p_orden_id integer DEFAULT NULL,
  p_numero_op varchar(80) DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
  v_titulo text := 'Tótem: nueva solicitud de impresión';
  v_desc text;
  v_user record;
BEGIN
  INSERT INTO public.totem_impresion_solicitudes (
    cliente_nombre,
    cliente_dni,
    cliente_telefono,
    cantidad_hojas,
    tipo_impresion,
    origen_archivo,
    archivo_url,
    archivo_nombre,
    orden_id,
    numero_op
  )
  VALUES (
    trim(p_cliente_nombre),
    trim(p_cliente_dni),
    trim(p_cliente_telefono),
    p_cantidad_hojas,
    trim(p_tipo_impresion),
    trim(p_origen_archivo),
    trim(p_archivo_url),
    trim(p_archivo_nombre),
    p_orden_id,
    NULLIF(trim(p_numero_op), '')
  )
  RETURNING id INTO v_id;

  v_desc :=
    'Cliente: ' || trim(p_cliente_nombre) || E'\n' ||
    'DNI/CUIT: ' || trim(p_cliente_dni) || ' | Tel: ' || trim(p_cliente_telefono) || E'\n' ||
    'Hojas: ' || p_cantidad_hojas::text || ' | Tipo: ' || trim(p_tipo_impresion) ||
    ' | Origen archivo: ' || trim(p_origen_archivo) || E'\n' ||
    'Archivo: ' || trim(p_archivo_nombre) || E'\n' ||
    'Descargar: ' || trim(p_archivo_url) || E'\n' ||
    'Solicitud #' || v_id::text || E'\n' ||
    'Pago: pendiente (Mercado Pago en caja).';

  FOR v_user IN
    SELECT id FROM public.usuarios
    WHERE rol IN ('imprenta', 'mostrador', 'caja')
  LOOP
    INSERT INTO public.user_notifications (
      user_id,
      title,
      description,
      type,
      is_read,
      orden_id
    ) VALUES (
      v_user.id,
      v_titulo,
      v_desc,
      'info',
      false,
      p_orden_id
    );
  END LOOP;

  RETURN v_id;
END;
$$;

COMMENT ON FUNCTION public.crear_solicitud_impresion_totem IS 'Tótem público: registra pedido de impresión y notifica imprenta, mostrador y caja';

-- Listar solicitudes recientes (personal imprenta, mostrador, caja, admin)
CREATE OR REPLACE FUNCTION public.listar_solicitudes_impresion_totem(
  p_usuario_id integer,
  p_limite integer DEFAULT 80
)
RETURNS TABLE (
  id bigint,
  cliente_nombre varchar,
  cliente_dni varchar,
  cliente_telefono varchar,
  cantidad_hojas integer,
  tipo_impresion varchar,
  origen_archivo varchar,
  archivo_url text,
  archivo_nombre varchar,
  numero_op varchar,
  estado_pago text,
  created_at timestamptz,
  pagado_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.id = p_usuario_id
      AND u.rol IN ('imprenta', 'mostrador', 'caja', 'administracion', 'gerencia')
  ) THEN
    RAISE EXCEPTION 'Sin permiso para listar solicitudes de impresión del tótem';
  END IF;

  RETURN QUERY
  SELECT
    s.id,
    s.cliente_nombre,
    s.cliente_dni,
    s.cliente_telefono,
    s.cantidad_hojas,
    s.tipo_impresion,
    s.origen_archivo,
    s.archivo_url,
    s.archivo_nombre,
    s.numero_op,
    s.estado_pago,
    s.created_at,
    s.pagado_at
  FROM public.totem_impresion_solicitudes s
  ORDER BY s.created_at DESC
  LIMIT GREATEST(1, LEAST(p_limite, 200));
END;
$$;

-- Marcar pagado + re-notificar (para que imprenta imprima con tranquilidad)
CREATE OR REPLACE FUNCTION public.marcar_pago_solicitud_impresion_totem(
  p_solicitud_id bigint,
  p_usuario_id integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_ok boolean := false;
  v_row public.totem_impresion_solicitudes%ROWTYPE;
  v_user record;
  v_titulo text := 'Tótem: pago confirmado — impresión';
  v_desc text;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.id = p_usuario_id
      AND u.rol IN ('caja', 'administracion', 'gerencia')
  ) THEN
    RAISE EXCEPTION 'Solo caja o administración pueden marcar el pago';
  END IF;

  UPDATE public.totem_impresion_solicitudes s
  SET estado_pago = 'pagado',
      pagado_at = now()
  WHERE s.id = p_solicitud_id
    AND s.estado_pago = 'pendiente'
  RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RETURN false;
  END IF;

  v_ok := true;

  v_desc :=
    'Solicitud #' || v_row.id::text || ' — Cliente: ' || v_row.cliente_nombre || E'\n' ||
    'Archivo: ' || v_row.archivo_nombre || E'\n' ||
    'Link: ' || v_row.archivo_url || E'\n' ||
    'Pago registrado desde caja. Podés imprimir / entregar.';

  FOR v_user IN
    SELECT id FROM public.usuarios
    WHERE rol IN ('imprenta', 'mostrador', 'caja')
  LOOP
    INSERT INTO public.user_notifications (
      user_id,
      title,
      description,
      type,
      is_read,
      orden_id
    ) VALUES (
      v_user.id,
      v_titulo,
      v_desc,
      'info',
      false,
      v_row.orden_id
    );
  END LOOP;

  RETURN v_ok;
END;
$$;

GRANT EXECUTE ON FUNCTION public.crear_solicitud_impresion_totem TO anon;
GRANT EXECUTE ON FUNCTION public.crear_solicitud_impresion_totem TO authenticated;
GRANT EXECUTE ON FUNCTION public.listar_solicitudes_impresion_totem TO anon;
GRANT EXECUTE ON FUNCTION public.listar_solicitudes_impresion_totem TO authenticated;
GRANT EXECUTE ON FUNCTION public.marcar_pago_solicitud_impresion_totem TO anon;
GRANT EXECUTE ON FUNCTION public.marcar_pago_solicitud_impresion_totem TO authenticated;

COMMIT;
