BEGIN;

-- =============================================================================
-- Cuentas bancarias / cajas para tesorería
-- - Permite asociar cobros/pagos a una cuenta (pagos_cobros.id_cuenta_bancaria)
-- - Base para conciliación bancaria y posición de caja
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cuentas_bancarias (
  -- int para compatibilidad con public.pagos_cobros.id_cuenta_bancaria (ERP base)
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  banco text NULL,
  tipo text NULL, -- 'Banco' | 'Efectivo' | 'MercadoPago' | etc. (texto libre por ahora)
  moneda text NOT NULL DEFAULT 'ARS',
  activa boolean NOT NULL DEFAULT true,
  saldo_inicial numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- updated_at trigger (simple, local a esta tabla)
CREATE OR REPLACE FUNCTION public.set_updated_at_cuentas_bancarias()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_set_updated_at_cuentas_bancarias ON public.cuentas_bancarias;
CREATE TRIGGER trigger_set_updated_at_cuentas_bancarias
BEFORE UPDATE ON public.cuentas_bancarias
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_cuentas_bancarias();

-- Permisos
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cuentas_bancarias TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.cuentas_bancarias_id_seq TO anon, authenticated;

-- FK desde pagos_cobros → cuentas_bancarias (si existen ambas tablas)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'pagos_cobros') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.table_constraints tc
      WHERE tc.constraint_schema = 'public'
        AND tc.table_name = 'pagos_cobros'
        AND tc.constraint_type = 'FOREIGN KEY'
        AND tc.constraint_name = 'pagos_cobros_id_cuenta_bancaria_fkey'
    ) THEN
      ALTER TABLE public.pagos_cobros
      ADD CONSTRAINT pagos_cobros_id_cuenta_bancaria_fkey
      FOREIGN KEY (id_cuenta_bancaria) REFERENCES public.cuentas_bancarias(id) ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

-- RLS (si se usa)
ALTER TABLE public.cuentas_bancarias ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cuentas_bancarias' AND policyname = 'Allow anon select cuentas bancarias'
  ) THEN
    CREATE POLICY "Allow anon select cuentas bancarias"
    ON public.cuentas_bancarias
    FOR SELECT
    TO anon
    USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cuentas_bancarias' AND policyname = 'Allow anon write cuentas bancarias'
  ) THEN
    CREATE POLICY "Allow anon write cuentas bancarias"
    ON public.cuentas_bancarias
    FOR ALL
    TO anon
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;

COMMIT;

