-- Valoraciones admin sobre diseñadores/operarios de la bolsa
-- Applied via MCP 2026-08-20

CREATE TABLE IF NOT EXISTS public.work_pool_valoraciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_job integer NULL REFERENCES public.work_pool_jobs(id) ON DELETE SET NULL,
  numero_op text NULL,
  rating smallint NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comentario text NULL,
  id_usuario_autor integer NULL REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_work_pool_valoraciones_usuario
  ON public.work_pool_valoraciones(id_usuario, created_at DESC);

ALTER TABLE public.work_pool_valoraciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS work_pool_valoraciones_all ON public.work_pool_valoraciones;
CREATE POLICY work_pool_valoraciones_all ON public.work_pool_valoraciones
  FOR ALL USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.work_pool_valoraciones TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.work_pool_valoraciones_id_seq TO anon, authenticated;
