-- Registro obligatorio de motivo al eliminar usuario (baja)
-- Reemplaza eliminar_usuario(integer) por eliminar_usuario(integer, text, integer)

CREATE TABLE IF NOT EXISTS public.usuarios_bajas_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL,
  nombre_snapshot text NOT NULL,
  motivo text NOT NULL,
  registrado_por integer REFERENCES public.usuarios(id),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_usuarios_bajas_log_created ON public.usuarios_bajas_log(created_at DESC);

COMMENT ON TABLE public.usuarios_bajas_log IS 'Motivo de baja al eliminar un usuario (auditoría RRHH)';

DROP FUNCTION IF EXISTS public.eliminar_usuario(integer);

CREATE OR REPLACE FUNCTION public.eliminar_usuario(
  p_id integer,
  p_motivo text,
  p_registrado_por integer
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  usuario_existente record;
  autentificacion_exists boolean;
  v_motivo text;
BEGIN
  v_motivo := trim(COALESCE(p_motivo, ''));
  IF length(v_motivo) < 5 THEN
    RAISE EXCEPTION 'El motivo de baja es obligatorio (mínimo 5 caracteres)';
  END IF;

  SELECT * INTO usuario_existente
  FROM public.usuarios
  WHERE id = p_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Usuario con ID % no encontrado', p_id;
  END IF;

  IF usuario_existente.rol = 'administracion' THEN
    RAISE EXCEPTION 'No se puede eliminar un usuario con rol administración';
  END IF;

  INSERT INTO public.usuarios_bajas_log (id_usuario, nombre_snapshot, motivo, registrado_por)
  VALUES (p_id, usuario_existente.nombre, v_motivo, p_registrado_por);

  SELECT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'autentificacion'
  ) INTO autentificacion_exists;

  IF autentificacion_exists THEN
    BEGIN
      EXECUTE format('
        DELETE FROM public.autentificacion
        WHERE nombre = %L
      ', usuario_existente.nombre);
    EXCEPTION
      WHEN OTHERS THEN
        RAISE WARNING 'No se pudo eliminar de autentificacion: %', SQLERRM;
    END;
  END IF;

  DELETE FROM public.usuarios
  WHERE id = p_id;
END;
$$;

COMMENT ON FUNCTION public.eliminar_usuario(integer, text, integer) IS
'Elimina usuario tras registrar motivo de baja. p_registrado_por = quien ejecuta la baja.';

GRANT EXECUTE ON FUNCTION public.eliminar_usuario(integer, text, integer) TO anon, authenticated;
