-- Relevamiento (app campo): notas, adjuntos marcados en enlaces_adjuntos, checklist aparte de tarea_subitems.

CREATE TABLE IF NOT EXISTS public.orden_relevamiento (
  id_orden integer PRIMARY KEY REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  notas text NOT NULL DEFAULT '',
  actualizado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_por varchar(255)
);

COMMENT ON TABLE public.orden_relevamiento IS 'Notas de relevamiento cargadas desde la app campo (Instalaciones / Metalúrgica).';

CREATE TABLE IF NOT EXISTS public.relevamiento_subitems (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  titulo varchar(500) NOT NULL,
  done boolean NOT NULL DEFAULT false,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_relevamiento_subitems_orden ON public.relevamiento_subitems(id_orden);

COMMENT ON TABLE public.relevamiento_subitems IS 'Checklist de relevamiento (app campo), independiente de tarea_subitems.';

ALTER TABLE public.enlaces_adjuntos
  ADD COLUMN IF NOT EXISTS origen_relevamiento boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN public.enlaces_adjuntos.origen_relevamiento IS 'true si el adjunto (foto/audio data URL) viene de la sección Relevamiento de la app campo.';

CREATE INDEX IF NOT EXISTS idx_enlaces_relevamiento
  ON public.enlaces_adjuntos (id_orden)
  WHERE origen_relevamiento = true;
