-- =============================================================================
-- BUNDLE CORTO: solo secciones 1 a 4 (IVA compras + depósitos / stock_movimientos).
--
-- Usalo si tu proyecto AÚN NO tiene el bloque contable ERP completo en esta base:
--   facturas_venta, asientos_contables, asientos_detalle, pagos_cobros, plan_cuentas,
--   función generar_numero_asiento(), etc.
-- En ese caso el bundle grande (2026-04-21) fallaría en las secciones 5–6.
--
-- Requiere ya existir: proveedores, usuarios, pedidos_compras, cuentas_por_pagar,
-- stock_movimientos (como en tu esquema actual).
--
-- NO ejecutes el SQL que Supabase muestra como "schema for context only": es
-- documentación, no un script de migración válido.
-- =============================================================================


-- =============================================================================
-- SECCIÓN 1 — 2026-04-16_create_cuentas_bancarias.sql
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.cuentas_bancarias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  banco text NULL,
  tipo text NULL,
  moneda text NOT NULL DEFAULT 'ARS',
  activa boolean NOT NULL DEFAULT true,
  saldo_inicial numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.set_updated_at_cuentas_bancarias()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_set_updated_at_cuentas_bancarias ON public.cuentas_bancarias;
CREATE TRIGGER trigger_set_updated_at_cuentas_bancarias
BEFORE UPDATE ON public.cuentas_bancarias
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_cuentas_bancarias();

GRANT SELECT, INSERT, UPDATE, DELETE ON public.cuentas_bancarias TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.cuentas_bancarias_id_seq TO anon, authenticated;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'pagos_cobros') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.table_constraints tc
      WHERE tc.constraint_schema = 'public'
        AND tc.table_name = 'pagos_cobros'
        AND tc.constraint_type = 'FOREIGN KEY'
        AND tc.constraint_name = 'pagos_cobros_id_cuenta_bancaria_fkey'
    ) THEN
      ALTER TABLE public.pagos_cobros
      ADD CONSTRAINT pagos_cobros_id_cuenta_bancaria_fkey
      FOREIGN KEY (id_cuenta_bancaria) REFERENCES public.cuentas_bancarias(id) ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

ALTER TABLE public.cuentas_bancarias ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cuentas_bancarias' AND policyname = 'Allow anon select cuentas bancarias'
  ) THEN
    CREATE POLICY "Allow anon select cuentas bancarias"
    ON public.cuentas_bancarias
    FOR SELECT
    TO anon
    USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cuentas_bancarias' AND policyname = 'Allow anon write cuentas bancarias'
  ) THEN
    CREATE POLICY "Allow anon write cuentas bancarias"
    ON public.cuentas_bancarias
    FOR ALL
    TO anon
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;

COMMIT;


-- =============================================================================
-- SECCIÓN 2 — 2026-04-16_facturas_compra_libro_iva_compras.sql
-- Requiere: public.proveedores(id), public.usuarios(id) para FK/RLS.
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.facturas_compra (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_comprobante varchar(50) NOT NULL DEFAULT 'Factura' CHECK (
    tipo_comprobante IN ('Factura', 'Nota de Crédito', 'Nota de Débito')
  ),
  letra varchar(2) NOT NULL DEFAULT 'A' CHECK (letra IN ('A', 'B', 'C')),
  punto_venta integer NOT NULL DEFAULT 1,
  numero_comprobante integer NOT NULL,
  numero_factura varchar(50) NOT NULL,
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  proveedor_nombre varchar(255) NOT NULL,
  proveedor_cuit varchar(50),
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  iva numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  observaciones text,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT facturas_compra_num_unique UNIQUE (punto_venta, numero_comprobante, letra, tipo_comprobante)
);

CREATE INDEX IF NOT EXISTS idx_facturas_compra_fecha ON public.facturas_compra(fecha_emision);
CREATE INDEX IF NOT EXISTS idx_facturas_compra_proveedor ON public.facturas_compra(id_proveedor);

CREATE TABLE IF NOT EXISTS public.facturas_compra_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura integer NOT NULL REFERENCES public.facturas_compra(id) ON DELETE CASCADE,
  item_numero integer NOT NULL,
  descripcion text NOT NULL,
  cantidad numeric(10,2) NOT NULL DEFAULT 1,
  precio_unitario numeric(15,2) NOT NULL DEFAULT 0,
  descuento numeric(15,2) NOT NULL DEFAULT 0,
  iva_porcentaje numeric(5,2) NOT NULL DEFAULT 21.00,
  iva_monto numeric(15,2) NOT NULL DEFAULT 0,
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_facturas_compra_items_factura ON public.facturas_compra_items(id_factura);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at'
  ) THEN
    CREATE OR REPLACE FUNCTION public.set_updated_at()
    RETURNS TRIGGER AS $f$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $f$ LANGUAGE plpgsql;
  END IF;
END$$;

DROP TRIGGER IF EXISTS set_updated_at_facturas_compra ON public.facturas_compra;
CREATE TRIGGER set_updated_at_facturas_compra
BEFORE UPDATE ON public.facturas_compra
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.facturas_compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas_compra_items ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.facturas_compra TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facturas_compra_items TO anon, authenticated;

DO $$
DECLARE
  s text;
BEGIN
  s := pg_get_serial_sequence('public.facturas_compra', 'id');
  IF s IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', s);
  END IF;
  s := pg_get_serial_sequence('public.facturas_compra_items', 'id');
  IF s IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', s);
  END IF;
END $$;

DROP POLICY IF EXISTS "facturas_compra lectura" ON public.facturas_compra;
CREATE POLICY "facturas_compra lectura" ON public.facturas_compra
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "facturas_compra_items lectura" ON public.facturas_compra_items;
CREATE POLICY "facturas_compra_items lectura" ON public.facturas_compra_items
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "facturas_compra escritura" ON public.facturas_compra;
CREATE POLICY "facturas_compra escritura" ON public.facturas_compra
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "facturas_compra_items escritura" ON public.facturas_compra_items;
CREATE POLICY "facturas_compra_items escritura" ON public.facturas_compra_items
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

COMMIT;


-- =============================================================================
-- SECCIÓN 3 — 2026-04-17_facturas_compra_vinculos_pedido_cxp.sql
-- =============================================================================
BEGIN;

ALTER TABLE public.facturas_compra
  ADD COLUMN IF NOT EXISTS id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL;

ALTER TABLE public.facturas_compra
  ADD COLUMN IF NOT EXISTS id_cuenta_por_pagar integer REFERENCES public.cuentas_por_pagar(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_facturas_compra_pedido ON public.facturas_compra(id_pedido_compra);
CREATE INDEX IF NOT EXISTS idx_facturas_compra_cxp ON public.facturas_compra(id_cuenta_por_pagar);

COMMENT ON COLUMN public.facturas_compra.id_pedido_compra IS 'Pedido de compra origen (precarga IVA compras / ERP).';
COMMENT ON COLUMN public.facturas_compra.id_cuenta_por_pagar IS 'Cuenta por pagar vinculada al comprobante.';

COMMIT;


-- =============================================================================
-- SECCIÓN 4 — 2026-04-18_stock_depositos_saldos_transferencia.sql
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.stock_depositos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  codigo varchar(40),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_depositos_codigo_unique UNIQUE (codigo)
);

CREATE INDEX IF NOT EXISTS idx_stock_depositos_activo ON public.stock_depositos(activo);

CREATE TABLE IF NOT EXISTS public.stock_saldo_deposito (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo_stock integer NOT NULL,
  id_deposito integer NOT NULL REFERENCES public.stock_depositos(id) ON DELETE RESTRICT,
  cantidad numeric(12, 3) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_saldo_deposito_unique UNIQUE (id_articulo_stock, id_deposito)
);

CREATE INDEX IF NOT EXISTS idx_stock_saldo_deposito_articulo ON public.stock_saldo_deposito(id_articulo_stock);
CREATE INDEX IF NOT EXISTS idx_stock_saldo_deposito_deposito ON public.stock_saldo_deposito(id_deposito);

INSERT INTO public.stock_depositos (nombre, codigo, activo)
VALUES ('Principal', 'PRINCIPAL', true)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS id_deposito_origen integer REFERENCES public.stock_depositos(id) ON DELETE SET NULL;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS id_deposito_destino integer REFERENCES public.stock_depositos(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_dep_origen ON public.stock_movimientos(id_deposito_origen);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_dep_destino ON public.stock_movimientos(id_deposito_destino);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_depositos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_saldo_deposito TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_depositos_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_saldo_deposito_id_seq TO anon, authenticated;

ALTER TABLE public.stock_depositos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_saldo_deposito ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stock_depositos all" ON public.stock_depositos;
CREATE POLICY "stock_depositos all" ON public.stock_depositos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "stock_saldo_deposito all" ON public.stock_saldo_deposito;
CREATE POLICY "stock_saldo_deposito all" ON public.stock_saldo_deposito FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE public.stock_depositos IS 'Depósitos / ubicaciones para inventario multi-almacén (referencia por id_articulo_stock en base de stock).';
COMMENT ON TABLE public.stock_saldo_deposito IS 'Cantidad por artículo y depósito. La suma puede alinearse con articulos.stock vía sincronización en app.';

COMMIT;
