-- RRHH: novedades laborales (faltas, tardanzas, licencias, horas extra) con adjuntos y vínculo opcional a solicitudes_permisos.

BEGIN;

CREATE TABLE IF NOT EXISTS public.rrhh_novedades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_solicitud_permiso integer REFERENCES public.solicitudes_permisos(id) ON DELETE SET NULL,
  grupo text NOT NULL CHECK (grupo IN ('falta', 'tardanza_retiro', 'licencia', 'horas_extra')),
  codigo text NOT NULL,
  fecha_desde date NOT NULL,
  fecha_hasta date NOT NULL,
  duracion_minutos integer,
  horas_extra_cantidad numeric(12, 2),
  observaciones text,
  adjuntos jsonb NOT NULL DEFAULT '[]'::jsonb,
  registrado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rrhh_novedades_fechas_ok CHECK (fecha_hasta >= fecha_desde)
);

CREATE INDEX IF NOT EXISTS idx_rrhh_novedades_usuario_fecha ON public.rrhh_novedades(id_usuario, fecha_desde);
CREATE INDEX IF NOT EXISTS idx_rrhh_novedades_grupo_codigo ON public.rrhh_novedades(grupo, codigo);
CREATE INDEX IF NOT EXISTS idx_rrhh_novedades_rango ON public.rrhh_novedades(fecha_desde, fecha_hasta);
CREATE INDEX IF NOT EXISTS idx_rrhh_novedades_permiso ON public.rrhh_novedades(id_solicitud_permiso);

ALTER TABLE public.rrhh_novedades ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rrhh_novedades_select_authenticated" ON public.rrhh_novedades;
DROP POLICY IF EXISTS "rrhh_novedades_insert_authenticated" ON public.rrhh_novedades;
DROP POLICY IF EXISTS "rrhh_novedades_update_authenticated" ON public.rrhh_novedades;
DROP POLICY IF EXISTS "rrhh_novedades_delete_authenticated" ON public.rrhh_novedades;

CREATE POLICY "rrhh_novedades_select_authenticated" ON public.rrhh_novedades
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "rrhh_novedades_insert_authenticated" ON public.rrhh_novedades
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "rrhh_novedades_update_authenticated" ON public.rrhh_novedades
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "rrhh_novedades_delete_authenticated" ON public.rrhh_novedades
  FOR DELETE TO authenticated USING (true);

COMMENT ON TABLE public.rrhh_novedades IS 'Novedades RRHH: categorías cerradas para filtros y liquidación; adjuntos en bucket archivos path rrhh-novedades/*';

COMMIT;
