-- Solicitudes de horas extra declaradas por el empleado (además del reloj).
-- RRHH/admin aprueba 1x1; si se aprueba, se crea novedad horas_extra para liquidación.

CREATE TABLE IF NOT EXISTS public.rrhh_solicitudes_he (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  fecha date NOT NULL,
  tipo text NOT NULL CHECK (tipo IN ('horas_extra_50', 'horas_extra_100')),
  horas numeric(6,2) NOT NULL CHECK (horas > 0 AND horas <= 24),
  observaciones text NOT NULL,
  adjuntos jsonb NOT NULL DEFAULT '[]'::jsonb,
  estado text NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aprobado', 'rechazado', 'cancelado')),
  motivo_rechazo text,
  aprobado_por integer REFERENCES public.usuarios(id),
  aprobado_at timestamptz,
  id_novedad bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_rrhh_solicitudes_he_usuario ON public.rrhh_solicitudes_he(id_usuario);
CREATE INDEX IF NOT EXISTS idx_rrhh_solicitudes_he_estado ON public.rrhh_solicitudes_he(estado);
CREATE INDEX IF NOT EXISTS idx_rrhh_solicitudes_he_fecha ON public.rrhh_solicitudes_he(fecha);

ALTER TABLE public.rrhh_solicitudes_he ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS rrhh_solicitudes_he_select ON public.rrhh_solicitudes_he;
CREATE POLICY rrhh_solicitudes_he_select ON public.rrhh_solicitudes_he
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS rrhh_solicitudes_he_insert ON public.rrhh_solicitudes_he;
CREATE POLICY rrhh_solicitudes_he_insert ON public.rrhh_solicitudes_he
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS rrhh_solicitudes_he_update ON public.rrhh_solicitudes_he;
CREATE POLICY rrhh_solicitudes_he_update ON public.rrhh_solicitudes_he
  FOR UPDATE TO authenticated USING (true);

GRANT SELECT, INSERT, UPDATE ON public.rrhh_solicitudes_he TO authenticated;
GRANT ALL ON public.rrhh_solicitudes_he TO service_role;

CREATE OR REPLACE FUNCTION public.crear_solicitud_he(
  p_id_usuario integer,
  p_fecha date,
  p_tipo text,
  p_horas numeric,
  p_observaciones text,
  p_adjuntos jsonb DEFAULT '[]'::jsonb
)
RETURNS public.rrhh_solicitudes_he
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.rrhh_solicitudes_he;
BEGIN
  IF p_id_usuario IS NULL OR p_id_usuario <= 0 THEN
    RAISE EXCEPTION 'Usuario inválido';
  END IF;
  IF p_fecha IS NULL THEN
    RAISE EXCEPTION 'Indicá la fecha de las horas extra';
  END IF;
  IF p_tipo NOT IN ('horas_extra_50', 'horas_extra_100') THEN
    RAISE EXCEPTION 'Tipo inválido (50%% o 100%%)';
  END IF;
  IF p_horas IS NULL OR p_horas <= 0 OR p_horas > 24 THEN
    RAISE EXCEPTION 'La cantidad de horas debe ser entre 0 y 24';
  END IF;
  IF p_observaciones IS NULL OR btrim(p_observaciones) = '' THEN
    RAISE EXCEPTION 'Escribí un breve motivo o detalle';
  END IF;

  INSERT INTO public.rrhh_solicitudes_he (
    id_usuario, fecha, tipo, horas, observaciones, adjuntos
  ) VALUES (
    p_id_usuario,
    p_fecha,
    p_tipo,
    round(p_horas, 2),
    btrim(p_observaciones),
    COALESCE(p_adjuntos, '[]'::jsonb)
  )
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_solicitudes_he(
  p_id_usuario integer DEFAULT NULL,
  p_estado text DEFAULT NULL,
  p_fecha_desde date DEFAULT NULL,
  p_fecha_hasta date DEFAULT NULL
)
RETURNS TABLE (
  id bigint,
  id_usuario integer,
  nombre_usuario text,
  fecha date,
  tipo text,
  horas numeric,
  observaciones text,
  adjuntos jsonb,
  estado text,
  motivo_rechazo text,
  aprobado_por integer,
  aprobado_por_nombre text,
  aprobado_at timestamptz,
  id_novedad bigint,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    s.id,
    s.id_usuario,
    u.nombre::text,
    s.fecha,
    s.tipo,
    s.horas,
    s.observaciones,
    s.adjuntos,
    s.estado,
    s.motivo_rechazo,
    s.aprobado_por,
    ua.nombre::text,
    s.aprobado_at,
    s.id_novedad,
    s.created_at,
    s.updated_at
  FROM public.rrhh_solicitudes_he s
  LEFT JOIN public.usuarios u ON u.id = s.id_usuario
  LEFT JOIN public.usuarios ua ON ua.id = s.aprobado_por
  WHERE (p_id_usuario IS NULL OR s.id_usuario = p_id_usuario)
    AND (p_estado IS NULL OR btrim(p_estado) = '' OR s.estado = p_estado)
    AND (p_fecha_desde IS NULL OR s.fecha >= p_fecha_desde)
    AND (p_fecha_hasta IS NULL OR s.fecha <= p_fecha_hasta)
  ORDER BY
    CASE s.estado WHEN 'pendiente' THEN 0 ELSE 1 END,
    s.fecha DESC,
    s.id DESC;
END;
$$;

CREATE OR REPLACE FUNCTION public.aprobar_rechazar_solicitud_he(
  p_id bigint,
  p_estado text,
  p_id_aprobador integer,
  p_motivo_rechazo text DEFAULT NULL
)
RETURNS public.rrhh_solicitudes_he
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.rrhh_solicitudes_he;
  v_novedad_id bigint;
  v_obs text;
BEGIN
  IF p_estado NOT IN ('aprobado', 'rechazado') THEN
    RAISE EXCEPTION 'Estado inválido';
  END IF;
  IF p_id_aprobador IS NULL OR p_id_aprobador <= 0 THEN
    RAISE EXCEPTION 'Aprobador inválido';
  END IF;

  SELECT * INTO v_row FROM public.rrhh_solicitudes_he WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitud no encontrada';
  END IF;
  IF v_row.estado <> 'pendiente' THEN
    RAISE EXCEPTION 'La solicitud ya fue procesada';
  END IF;
  IF v_row.id_usuario = p_id_aprobador THEN
    RAISE EXCEPTION 'No podés aprobar o rechazar tu propia solicitud';
  END IF;

  IF p_estado = 'rechazado' THEN
    IF p_motivo_rechazo IS NULL OR btrim(p_motivo_rechazo) = '' THEN
      RAISE EXCEPTION 'Indicá el motivo del rechazo';
    END IF;
    UPDATE public.rrhh_solicitudes_he
    SET estado = 'rechazado',
        motivo_rechazo = btrim(p_motivo_rechazo),
        aprobado_por = p_id_aprobador,
        aprobado_at = now(),
        updated_at = now()
    WHERE id = p_id
    RETURNING * INTO v_row;
    RETURN v_row;
  END IF;

  v_obs := '[HE declarada] ' || v_row.observaciones;
  v_novedad_id := nextval('public.rrhh_novedades_id_seq');

  INSERT INTO public.rrhh_novedades (
    id, id_usuario, id_solicitud_permiso, grupo, codigo,
    fecha_desde, fecha_hasta, duracion_minutos, horas_extra_cantidad,
    observaciones, adjuntos, registrado_por, created_at, updated_at
  ) VALUES (
    v_novedad_id,
    v_row.id_usuario,
    NULL,
    'horas_extra',
    v_row.tipo,
    v_row.fecha,
    v_row.fecha,
    NULL,
    v_row.horas,
    v_obs,
    COALESCE(v_row.adjuntos, '[]'::jsonb),
    p_id_aprobador,
    now(),
    now()
  );

  UPDATE public.rrhh_solicitudes_he
  SET estado = 'aprobado',
      aprobado_por = p_id_aprobador,
      aprobado_at = now(),
      id_novedad = v_novedad_id,
      motivo_rechazo = NULL,
      updated_at = now()
  WHERE id = p_id
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.cancelar_solicitud_he(
  p_id bigint,
  p_id_usuario integer
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.rrhh_solicitudes_he
  SET estado = 'cancelado',
      updated_at = now()
  WHERE id = p_id
    AND id_usuario = p_id_usuario
    AND estado = 'pendiente';
  RETURN FOUND;
END;
$$;

GRANT EXECUTE ON FUNCTION public.crear_solicitud_he(integer, date, text, numeric, text, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.obtener_solicitudes_he(integer, text, date, date) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.aprobar_rechazar_solicitud_he(bigint, text, integer, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.cancelar_solicitud_he(bigint, integer) TO authenticated, service_role;
