-- Deuda total en cuenta corriente proveedores (migrado desde Deuda Total en Cuenta Corriente.XLS)
BEGIN;

CREATE TABLE IF NOT EXISTS public.deuda_cc_proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_codigo varchar(20) NOT NULL DEFAULT '',
  proveedor_nombre text NOT NULL,
  fecha_corte date NOT NULL,
  tipo_comprobante varchar(10) NOT NULL,
  numero_comprobante varchar(50) NOT NULL,
  fecha_comprobante date,
  fecha_vencimiento date,
  total numeric(15,2) NOT NULL DEFAULT 0,
  pagado numeric(15,2) NOT NULL DEFAULT 0,
  deuda numeric(15,2) NOT NULL DEFAULT 0,
  dias_vencido integer,
  total_moneda_origen text,
  total_actualizado numeric(15,2) NOT NULL DEFAULT 0,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(proveedor_nombre, tipo_comprobante, numero_comprobante, fecha_comprobante)
);

CREATE INDEX IF NOT EXISTS idx_deuda_cc_prov_proveedor ON public.deuda_cc_proveedores(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_deuda_cc_prov_fecha ON public.deuda_cc_proveedores(fecha_vencimiento);
CREATE INDEX IF NOT EXISTS idx_deuda_cc_prov_deuda ON public.deuda_cc_proveedores(deuda DESC);

ALTER TABLE public.deuda_cc_proveedores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS deuda_cc_proveedores_all ON public.deuda_cc_proveedores;
CREATE POLICY deuda_cc_proveedores_all ON public.deuda_cc_proveedores FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

INSERT INTO public.deuda_cc_proveedores (
  proveedor_codigo, proveedor_nombre, fecha_corte, tipo_comprobante, numero_comprobante,
  fecha_comprobante, fecha_vencimiento, total, pagado, deuda, dias_vencido,
  total_moneda_origen, total_actualizado
)
VALUES
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00064243', '2025-12-22', '2025-12-22', 39117000.00, 6478512.79, 32638487.21, 179, '$ 39117000,00', 32638487.21),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00064287', '2025-12-23', '2025-12-23', 1060444.00, 0.00, 1060444.00, 178, '$ 1060444,00', 1060444.00),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'NDA', '00007-00001654', '2026-01-06', '2026-01-07', 7260.00, 0.00, 7260.00, 163, '$ 7260,00', 7260.00),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'NDA', '00025-00000558', '2026-01-06', '2026-01-07', 1349198.40, 0.00, 1349198.40, 163, '$ 1349198,40', 1349198.40),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'NDA', '00007-00001656', '2026-01-09', '2026-01-09', 7260.00, 0.00, 7260.00, 161, '$ 7260,00', 7260.00),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'NDA', '00025-00000559', '2026-01-09', '2026-01-10', 3324701.17, 0.00, 3324701.17, 160, '$ 3324701,17', 3324701.17),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'NCA', '00007-00004215', '2026-02-09', '2026-02-10', -39117000.02, 0.00, -39117000.02, 129, '$ (39117000,02)', -39117000.02),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00065173', '2026-02-19', '2026-02-20', 833682.00, 0.00, 833682.00, 119, '$ 833682,00', 833682.00),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00065194', '2026-02-20', '2026-02-21', 7854788.39, 0.00, 7854788.39, 118, '$ 7854788,39', 7854788.39),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00065195', '2026-02-20', '2026-03-22', 604806.40, 30780.20, 574026.20, 89, '$ 604806,40', 574026.20),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00066792', '2026-04-30', '2026-05-01', 3163405.18, 0.00, 3163405.18, 49, '$ 3163405,18', 3163405.18),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00066815', '2026-04-30', '2026-05-01', 1679649.40, 0.00, 1679649.40, 49, '$ 1679649,40', 1679649.40),
  ('00868', 'IGENAR ARGENTINA S.A.', '2026-06-19', 'FA', '00007-00067723', '2026-06-16', '2026-06-17', 1722919.00, 1226686.72, 496232.28, 2, '$ 1722919,00', 496232.28)
ON CONFLICT (proveedor_nombre, tipo_comprobante, numero_comprobante, fecha_comprobante) DO UPDATE SET
  total = EXCLUDED.total,
  pagado = EXCLUDED.pagado,
  deuda = EXCLUDED.deuda,
  dias_vencido = EXCLUDED.dias_vencido,
  total_actualizado = EXCLUDED.total_actualizado,
  fecha_vencimiento = EXCLUDED.fecha_vencimiento,
  fecha_corte = EXCLUDED.fecha_corte,
  updated_at = now();

CREATE OR REPLACE FUNCTION public.vincular_deuda_cc_proveedores()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE v_count integer;
BEGIN
  UPDATE public.deuda_cc_proveedores d
  SET id_proveedor = p.id, updated_at = now()
  FROM public.proveedores p
  WHERE d.id_proveedor IS NULL
    AND (
      upper(trim(coalesce(p.razon_social, ''))) = upper(trim(d.proveedor_nombre))
      OR upper(trim(p.nombre)) = upper(trim(d.proveedor_nombre))
      OR upper(trim(p.nombre)) LIKE '%' || upper(trim(split_part(d.proveedor_nombre, ' ', 1))) || '%'
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

SELECT public.vincular_deuda_cc_proveedores();

COMMIT;
