-- Libro IVA Compras: comprobantes de proveedores + items por alícuota
-- Aplica este patch en Supabase antes de usar la UI de IVA Compras.

BEGIN;

-- ============================================
-- 1) FACTURAS DE COMPRA (proveedores)
-- ============================================
CREATE TABLE IF NOT EXISTS public.facturas_compra (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_comprobante varchar(50) NOT NULL DEFAULT 'Factura' CHECK (
    tipo_comprobante IN ('Factura', 'Nota de Crédito', 'Nota de Débito')
  ),
  letra varchar(2) NOT NULL DEFAULT 'A' CHECK (letra IN ('A', 'B', 'C')),
  punto_venta integer NOT NULL DEFAULT 1,
  numero_comprobante integer NOT NULL,
  numero_factura varchar(50) NOT NULL,
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  proveedor_nombre varchar(255) NOT NULL,
  proveedor_cuit varchar(50),
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  iva numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  observaciones text,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT facturas_compra_num_unique UNIQUE (punto_venta, numero_comprobante, letra, tipo_comprobante)
);

CREATE INDEX IF NOT EXISTS idx_facturas_compra_fecha ON public.facturas_compra(fecha_emision);
CREATE INDEX IF NOT EXISTS idx_facturas_compra_proveedor ON public.facturas_compra(id_proveedor);

-- ============================================
-- 2) ITEMS (para totalizar por alícuota)
-- ============================================
CREATE TABLE IF NOT EXISTS public.facturas_compra_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura integer NOT NULL REFERENCES public.facturas_compra(id) ON DELETE CASCADE,
  item_numero integer NOT NULL,
  descripcion text NOT NULL,
  cantidad numeric(10,2) NOT NULL DEFAULT 1,
  precio_unitario numeric(15,2) NOT NULL DEFAULT 0,
  descuento numeric(15,2) NOT NULL DEFAULT 0,
  iva_porcentaje numeric(5,2) NOT NULL DEFAULT 21.00,
  iva_monto numeric(15,2) NOT NULL DEFAULT 0,
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_facturas_compra_items_factura ON public.facturas_compra_items(id_factura);

-- updated_at trigger (si existe función genérica en tu repo, reusala; si no, definimos una simple)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at'
  ) THEN
    CREATE OR REPLACE FUNCTION public.set_updated_at()
    RETURNS TRIGGER AS $f$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $f$ LANGUAGE plpgsql;
  END IF;
END$$;

DROP TRIGGER IF EXISTS set_updated_at_facturas_compra ON public.facturas_compra;
CREATE TRIGGER set_updated_at_facturas_compra
BEFORE UPDATE ON public.facturas_compra
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- ============================================
-- 3) RLS + grants
-- Nota: auth.uid() en Supabase es UUID; public.usuarios.id es integer. No usar auth.uid()::integer.
-- La app suele usar la clave anon; permisos finos van en la UI / API.
-- ============================================
ALTER TABLE public.facturas_compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas_compra_items ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.facturas_compra TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facturas_compra_items TO anon, authenticated;

DO $$
DECLARE
  s text;
BEGIN
  s := pg_get_serial_sequence('public.facturas_compra', 'id');
  IF s IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', s);
  END IF;
  s := pg_get_serial_sequence('public.facturas_compra_items', 'id');
  IF s IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', s);
  END IF;
END $$;

DROP POLICY IF EXISTS "facturas_compra lectura" ON public.facturas_compra;
CREATE POLICY "facturas_compra lectura" ON public.facturas_compra
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "facturas_compra_items lectura" ON public.facturas_compra_items;
CREATE POLICY "facturas_compra_items lectura" ON public.facturas_compra_items
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "facturas_compra escritura" ON public.facturas_compra;
CREATE POLICY "facturas_compra escritura" ON public.facturas_compra
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "facturas_compra_items escritura" ON public.facturas_compra_items;
CREATE POLICY "facturas_compra_items escritura" ON public.facturas_compra_items
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

COMMIT;

