-- Movimientos de proveedores (migrado desde Listado de Movimientos.XLS)
BEGIN;

CREATE TABLE IF NOT EXISTS public.movimientos_proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proveedor_nombre text NOT NULL,
  moneda varchar(20) NOT NULL DEFAULT 'PESOS',
  fecha_desde date,
  fecha_hasta date,
  fecha_hora timestamptz NOT NULL,
  fecha_comprobante date,
  tipo_movimiento text NOT NULL,
  comprobante varchar(120) NOT NULL DEFAULT '',
  debe numeric(15,2) NOT NULL DEFAULT 0,
  haber numeric(15,2) NOT NULL DEFAULT 0,
  saldo numeric(15,2) NOT NULL DEFAULT 0,
  es_saldo_inicial boolean NOT NULL DEFAULT false,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(proveedor_nombre, fecha_hora, comprobante, tipo_movimiento)
);

CREATE INDEX IF NOT EXISTS idx_mov_prov_proveedor ON public.movimientos_proveedores(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_mov_prov_fecha ON public.movimientos_proveedores(fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_mov_prov_comprobante ON public.movimientos_proveedores(comprobante);

ALTER TABLE public.movimientos_proveedores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS movimientos_proveedores_all ON public.movimientos_proveedores;
CREATE POLICY movimientos_proveedores_all ON public.movimientos_proveedores FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

INSERT INTO public.movimientos_proveedores (
  proveedor_nombre, moneda, fecha_desde, fecha_hasta, fecha_hora, fecha_comprobante,
  tipo_movimiento, comprobante, debe, haber, saldo, es_saldo_inicial
)
VALUES
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '1899-12-30T00:00:00', '2000-01-01', 'SALDO INICIAL', '- Saldo al Inicio -', 98058070.48, 99118514.48, 1060444.00, true),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-01-13T11:14:27', '2025-12-22', 'FACTURA A - Cta. Cte.', 'FA  00007-00064243', 0.00, 39117000.00, 40177444.00, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-01-29T12:57:25', '2026-01-09', 'NOTA DE DEBITO A - Cta. Cte.', 'NDA 00007-00001656', 0.00, 7260.00, 40184704.00, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-18T11:27:37', '2026-03-18', 'FACTURA A - Cta. Cte.', 'FA  00007-00065753', 0.00, 3122961.60, 43307665.60, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-18T12:40:55', '2026-03-18', 'PAGO', 'PA  00000-00010447', 6478512.79, 0.00, 36829152.81, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:36:49', '2026-02-09', 'NOTA DE CREDITO A - Cta. Cte.', 'NCA 00007-00004215', 0.00, -39117000.02, -2287847.21, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:45:25', '2026-02-19', 'FACTURA A - Cta. Cte.', 'FA  00007-00065173', 0.00, 833682.00, -1454165.21, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:49:27', '2026-02-20', 'FACTURA A - Cta. Cte.', 'FA  00007-00065194', 0.00, 7854788.39, 6400623.17, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:51:55', '2026-02-20', 'FACTURA A - Cta. Cte.', 'FA  00007-00065195', 0.00, 604806.40, 7005429.57, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:55:28', '2026-01-06', 'NOTA DE DEBITO A - Cta. Cte.', 'NDA 00025-00000558', 0.00, 1349198.40, 8354627.97, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:56:42', '2026-01-06', 'NOTA DE DEBITO A - Cta. Cte.', 'NDA 00007-00001654', 0.00, 7260.00, 8361887.97, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-03-26T10:58:59', '2026-01-09', 'NOTA DE DEBITO A - Cta. Cte.', 'NDA 00025-00000559', 0.00, 3324701.17, 11686589.14, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-04-17T08:46:33', '2026-04-16', 'FACTURA A - Cta. Cte.', 'FA  00007-00066437', 0.00, 1120620.02, 12807209.17, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-04-17T11:11:56', '2026-04-17', 'PAGO', 'PA  00000-00010621', 4274361.82, 0.00, 8532847.35, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-04-30T09:31:13', '2026-04-30', 'FACTURA A - Cta. Cte.', 'FA  00007-00066792', 0.00, 3163405.18, 11696252.53, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-05-04T10:44:46', '2026-04-30', 'FACTURA A - Cta. Cte.', 'FA  00007-00066815', 0.00, 1679649.40, 13375901.93, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-06-11T11:39:22', '2026-06-11', 'FACTURA A - Cta. Cte.', 'FA  00007-00067671', 0.00, 3278848.32, 16654750.25, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-06-17T08:31:02', '2026-06-16', 'FACTURA A - Cta. Cte.', 'FA  00007-00067723', 0.00, 1722919.00, 18377669.25, false),
  ('IGENAR ARGENTINA S.A.', 'PESOS', '2025-12-31', '2026-06-19', '2026-06-18T08:19:50', '2026-06-18', 'PAGO', 'PA  00000-00010774', 4505535.04, 0.00, 13872134.21, false)
ON CONFLICT (proveedor_nombre, fecha_hora, comprobante, tipo_movimiento) DO UPDATE SET
  debe = EXCLUDED.debe,
  haber = EXCLUDED.haber,
  saldo = EXCLUDED.saldo,
  fecha_comprobante = EXCLUDED.fecha_comprobante,
  updated_at = now();

CREATE OR REPLACE FUNCTION public.vincular_movimientos_proveedores()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE v_count integer;
BEGIN
  UPDATE public.movimientos_proveedores m
  SET id_proveedor = p.id, updated_at = now()
  FROM public.proveedores p
  WHERE m.id_proveedor IS NULL
    AND (
      upper(trim(coalesce(p.razon_social, ''))) = upper(trim(m.proveedor_nombre))
      OR upper(trim(p.nombre)) = upper(trim(m.proveedor_nombre))
      OR upper(trim(p.nombre)) LIKE '%' || upper(trim(split_part(m.proveedor_nombre, ' ', 1))) || '%'
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

SELECT public.vincular_movimientos_proveedores();

COMMIT;
