-- Inventario pañol Metalúrgica: herramientas + historial de cambios.
-- RLS permisivo (anon/authenticated) alineado al uso del cliente con anon key + auth app en localStorage.
-- Ejecutar en Supabase SQL editor o como migración.

CREATE TABLE IF NOT EXISTS public.metalurgica_inventario_herramientas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cantidad integer NOT NULL DEFAULT 0 CHECK (cantidad >= 0),
  herramienta text NOT NULL,
  tipo_marca text,
  descripcion text,
  foto_url text,
  slot_pañol text,
  umbral_minimo integer NOT NULL DEFAULT 2 CHECK (umbral_minimo >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.metalurgica_inventario_herramientas IS 'Inventario del pañol de metalúrgica (cantidad, herramienta, tipo/marca, descripción, foto URL, ubicación en pañol).';
COMMENT ON COLUMN public.metalurgica_inventario_herramientas.slot_pañol IS 'Ubicación en el pañol, ej. A1, B3 (rejilla letra+fila).';
COMMENT ON COLUMN public.metalurgica_inventario_herramientas.umbral_minimo IS 'Cantidad mínima deseada; por debajo se considera stock bajo para alertas.';

CREATE OR REPLACE FUNCTION public.metalurgica_inventario_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_metalurgica_inventario_updated ON public.metalurgica_inventario_herramientas;
CREATE TRIGGER trg_metalurgica_inventario_updated
  BEFORE UPDATE ON public.metalurgica_inventario_herramientas
  FOR EACH ROW
  EXECUTE FUNCTION public.metalurgica_inventario_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.metalurgica_inventario_movimientos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  herramienta_id bigint REFERENCES public.metalurgica_inventario_herramientas (id) ON DELETE SET NULL,
  herramienta_nombre text NOT NULL,
  cantidad_anterior integer,
  cantidad_nueva integer,
  usuario_nombre text,
  detalle text,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.metalurgica_inventario_movimientos IS 'Historial de altas y cambios de cantidad del inventario metalúrgica.';

CREATE INDEX IF NOT EXISTS idx_metal_inv_mov_herr ON public.metalurgica_inventario_movimientos (herramienta_id);
CREATE INDEX IF NOT EXISTS idx_metal_inv_mov_created ON public.metalurgica_inventario_movimientos (created_at DESC);

ALTER TABLE public.metalurgica_inventario_herramientas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metalurgica_inventario_movimientos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS metal_inv_h_all_anon ON public.metalurgica_inventario_herramientas;
CREATE POLICY metal_inv_h_all_anon
  ON public.metalurgica_inventario_herramientas
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS metal_inv_h_all_auth ON public.metalurgica_inventario_herramientas;
CREATE POLICY metal_inv_h_all_auth
  ON public.metalurgica_inventario_herramientas
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS metal_inv_m_all_anon ON public.metalurgica_inventario_movimientos;
CREATE POLICY metal_inv_m_all_anon
  ON public.metalurgica_inventario_movimientos
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS metal_inv_m_all_auth ON public.metalurgica_inventario_movimientos;
CREATE POLICY metal_inv_m_all_auth
  ON public.metalurgica_inventario_movimientos
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
