-- Comisiones por ventas: configuración, devengado por venta y liquidaciones mensuales.
--
-- Criterio por defecto (todo configurable desde Contable → Comisiones):
--   base 'neto'      → se comisiona sobre la venta sin IVA
--   momento 'cobro'  → se devenga en proporción a lo efectivamente cobrado
--   porcentaje por vendedor, con un valor general por defecto
--
-- Flujo: recalcular (devengado por venta) → generar liquidación del mes (borrador)
--        → aprobar → marcar pagada (recién ahí se descuenta del pendiente).
-- Una venta cancelada o con nota de crédito baja el devengado; si ya se había pagado,
-- la diferencia sale como ajuste negativo en la liquidación siguiente.
--
-- Todo pasa por RPC con actor (administración / gerencia). Las tablas no se tocan desde el front.
-- Idempotente.

BEGIN;

-- 1) Configuración ------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comisiones_config (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  base text NOT NULL DEFAULT 'neto' CHECK (base IN ('neto', 'total')),
  momento text NOT NULL DEFAULT 'cobro' CHECK (momento IN ('cobro', 'venta', 'factura')),
  porcentaje_default numeric(5,2) NOT NULL DEFAULT 0 CHECK (porcentaje_default >= 0 AND porcentaje_default <= 100),
  alicuota_iva numeric(5,2) NOT NULL DEFAULT 21 CHECK (alicuota_iva >= 0 AND alicuota_iva < 100),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.comisiones_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.comisiones_vendedores (
  id_usuario integer PRIMARY KEY REFERENCES public.usuarios(id) ON DELETE CASCADE,
  porcentaje numeric(5,2) NOT NULL DEFAULT 0 CHECK (porcentaje >= 0 AND porcentaje <= 100),
  activo boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 2) Devengado por venta -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comisiones_ventas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta integer NOT NULL UNIQUE REFERENCES public.ventas(id) ON DELETE CASCADE,
  numero_venta text,
  id_vendedor integer,
  nombre_vendedor text,
  fecha_venta date,
  base text NOT NULL,
  monto_venta numeric(15,2) NOT NULL DEFAULT 0,
  monto_cobrado numeric(15,2) NOT NULL DEFAULT 0,
  base_monto numeric(15,2) NOT NULL DEFAULT 0,
  porcentaje numeric(5,2) NOT NULL DEFAULT 0,
  monto_devengado numeric(15,2) NOT NULL DEFAULT 0,
  monto_liquidado numeric(15,2) NOT NULL DEFAULT 0,
  estado text NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'parcial', 'liquidada', 'anulada')),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comisiones_ventas_vendedor ON public.comisiones_ventas (id_vendedor, fecha_venta);
CREATE INDEX IF NOT EXISTS idx_comisiones_ventas_estado ON public.comisiones_ventas (estado);

-- 3) Liquidaciones --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.comisiones_liquidaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  periodo date NOT NULL,
  id_vendedor integer NOT NULL,
  nombre_vendedor text,
  total numeric(15,2) NOT NULL DEFAULT 0,
  estado text NOT NULL DEFAULT 'borrador' CHECK (estado IN ('borrador', 'aprobada', 'pagada', 'anulada')),
  creada_por integer,
  aprobada_por integer,
  fecha_aprobacion timestamptz,
  fecha_pago date,
  observaciones text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT comisiones_liquidaciones_periodo_vendedor_key UNIQUE (periodo, id_vendedor)
);

CREATE TABLE IF NOT EXISTS public.comisiones_liquidacion_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_liquidacion bigint NOT NULL REFERENCES public.comisiones_liquidaciones(id) ON DELETE CASCADE,
  id_venta integer,
  numero_venta text,
  base_monto numeric(15,2) NOT NULL DEFAULT 0,
  porcentaje numeric(5,2) NOT NULL DEFAULT 0,
  monto numeric(15,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_comisiones_liq_items ON public.comisiones_liquidacion_items (id_liquidacion);

ALTER TABLE public.comisiones_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comisiones_vendedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comisiones_ventas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comisiones_liquidaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comisiones_liquidacion_items ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.comisiones_config, public.comisiones_vendedores, public.comisiones_ventas,
  public.comisiones_liquidaciones, public.comisiones_liquidacion_items FROM anon, authenticated;
GRANT ALL ON TABLE public.comisiones_config, public.comisiones_vendedores, public.comisiones_ventas,
  public.comisiones_liquidaciones, public.comisiones_liquidacion_items TO service_role;

-- 4) Actor habilitado (sueldos: solo administración / gerencia) -------------------------
CREATE OR REPLACE FUNCTION public.actor_puede_comisiones(p_actor_id integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.id = p_actor_id
      AND COALESCE(u.activo, true) = true
      AND u.rol IN ('administracion', 'gerencia')
  );
$$;

REVOKE ALL ON FUNCTION public.actor_puede_comisiones(integer) FROM PUBLIC, anon, authenticated;

-- 5) Configuración: leer / guardar -----------------------------------------------------
CREATE OR REPLACE FUNCTION public.comisiones_config_get(p_actor_id integer)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_out jsonb;
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para ver comisiones';
  END IF;

  SELECT jsonb_build_object(
    'config', (SELECT to_jsonb(c) FROM public.comisiones_config c WHERE c.id = 1),
    'vendedores', COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
               'id_usuario', u.id,
               'nombre', u.nombre,
               'rol', u.rol,
               'porcentaje', COALESCE(cv.porcentaje, 0),
               'activo', COALESCE(cv.activo, false),
               'ventas', COALESCE(vt.ventas, 0)
             ) ORDER BY u.nombre)
      FROM public.usuarios u
      LEFT JOIN public.comisiones_vendedores cv ON cv.id_usuario = u.id
      LEFT JOIN LATERAL (
        SELECT count(*) AS ventas FROM public.ventas v WHERE v.id_vendedor = u.id
      ) vt ON true
      WHERE COALESCE(u.activo, true) = true
        AND (vt.ventas > 0 OR cv.id_usuario IS NOT NULL)
    ), '[]'::jsonb)
  ) INTO v_out;

  RETURN v_out;
END;
$$;

CREATE OR REPLACE FUNCTION public.comisiones_guardar_config(p_actor_id integer, p_payload jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para configurar comisiones';
  END IF;

  UPDATE public.comisiones_config SET
    base = COALESCE(NULLIF(p_payload->>'base', ''), base),
    momento = COALESCE(NULLIF(p_payload->>'momento', ''), momento),
    porcentaje_default = COALESCE(NULLIF(p_payload->>'porcentaje_default', '')::numeric, porcentaje_default),
    alicuota_iva = COALESCE(NULLIF(p_payload->>'alicuota_iva', '')::numeric, alicuota_iva),
    updated_at = now()
  WHERE id = 1;

  RETURN public.comisiones_config_get(p_actor_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.comisiones_guardar_vendedor(
  p_actor_id integer,
  p_id_usuario integer,
  p_porcentaje numeric,
  p_activo boolean
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para configurar comisiones';
  END IF;

  INSERT INTO public.comisiones_vendedores (id_usuario, porcentaje, activo, updated_at)
  VALUES (p_id_usuario, COALESCE(p_porcentaje, 0), COALESCE(p_activo, true), now())
  ON CONFLICT (id_usuario) DO UPDATE
    SET porcentaje = EXCLUDED.porcentaje, activo = EXCLUDED.activo, updated_at = now();

  RETURN public.comisiones_config_get(p_actor_id);
END;
$$;

-- 6) Recalcular el devengado -----------------------------------------------------------
CREATE OR REPLACE FUNCTION public.comisiones_recalcular(
  p_actor_id integer,
  p_desde date,
  p_hasta date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_cfg public.comisiones_config%ROWTYPE;
  v_procesadas integer := 0;
  v_devengado numeric := 0;
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para calcular comisiones';
  END IF;

  SELECT * INTO v_cfg FROM public.comisiones_config WHERE id = 1;

  WITH calculo AS (
    SELECT
      v.id AS id_venta,
      v.numero_venta::text,
      v.id_vendedor,
      v.nombre_vendedor::text,
      v.fecha_venta,
      COALESCE(v.valor_total, 0) AS monto_venta,
      -- Cobrado según el momento configurado
      CASE
        WHEN COALESCE(v.estado_pago, '') = 'Cancelado' THEN 0
        WHEN v_cfg.momento = 'venta' THEN COALESCE(v.valor_total, 0)
        WHEN v_cfg.momento = 'factura' THEN
          CASE WHEN EXISTS (
            SELECT 1 FROM public.facturas_venta f
            WHERE f.id_venta = v.id AND f.estado_afip = 'Autorizada' AND f.estado = 'Emitida'
          ) THEN COALESCE(v.valor_total, 0) ELSE 0 END
        WHEN COALESCE(v.estado_pago, '') = 'Pagado' THEN COALESCE(v.valor_total, 0)
        WHEN COALESCE(v.estado_pago, '') = 'Parcial' THEN
          LEAST(COALESCE(v.valor_total, 0), GREATEST(COALESCE(v.monto_pagado, 0), 0))
        ELSE 0
      END AS cobrado,
      -- Notas de crédito autorizadas de esa venta: bajan la base
      COALESCE((
        SELECT sum(ABS(f.total))
        FROM public.facturas_venta f
        WHERE f.id_venta = v.id
          AND f.tipo_comprobante LIKE 'Nota de Crédito%'
          AND f.estado_afip = 'Autorizada'
      ), 0) AS notas_credito,
      COALESCE(cv.porcentaje, v_cfg.porcentaje_default) AS porcentaje_bruto,
      COALESCE(cv.activo, true) AS vendedor_activo,
      COALESCE(v.estado_pago, '') = 'Cancelado' AS cancelada
    FROM public.ventas v
    LEFT JOIN public.comisiones_vendedores cv ON cv.id_usuario = v.id_vendedor
    -- El período pedido, MÁS lo que todavía puede moverse: una venta vieja que recién se cobra
    -- tiene que devengar ahora, sin depender de que alguien vuelva al mes de esa venta.
    WHERE v.fecha_venta BETWEEN p_desde AND p_hasta
       OR (
         v.fecha_venta >= (p_desde - INTERVAL '12 months')::date
         AND v.fecha_venta < p_desde
         AND NOT EXISTS (
           SELECT 1 FROM public.comisiones_ventas cvv
           WHERE cvv.id_venta = v.id AND cvv.estado IN ('liquidada', 'anulada')
         )
       )
  ),
  calculo_final AS (
    SELECT
      id_venta, numero_venta, id_vendedor, nombre_vendedor, fecha_venta, monto_venta, cancelada,
      GREATEST(cobrado - notas_credito, 0) AS cobrado_neto_nc,
      CASE WHEN vendedor_activo THEN porcentaje_bruto ELSE 0 END AS porcentaje
    FROM calculo
  ),
  upserted AS (
    INSERT INTO public.comisiones_ventas (
      id_venta, numero_venta, id_vendedor, nombre_vendedor, fecha_venta, base,
      monto_venta, monto_cobrado, base_monto, porcentaje, monto_devengado, estado, updated_at
    )
    SELECT
      f.id_venta, f.numero_venta, f.id_vendedor, f.nombre_vendedor, f.fecha_venta, v_cfg.base,
      f.monto_venta,
      f.cobrado_neto_nc,
      CASE WHEN v_cfg.base = 'neto'
        THEN round(f.cobrado_neto_nc / (1 + v_cfg.alicuota_iva / 100), 2)
        ELSE round(f.cobrado_neto_nc, 2) END,
      f.porcentaje,
      round(
        (CASE WHEN v_cfg.base = 'neto'
          THEN f.cobrado_neto_nc / (1 + v_cfg.alicuota_iva / 100)
          ELSE f.cobrado_neto_nc END) * f.porcentaje / 100, 2),
      CASE WHEN f.cancelada THEN 'anulada' ELSE 'pendiente' END,
      now()
    FROM calculo_final f
    ON CONFLICT (id_venta) DO UPDATE SET
      numero_venta = EXCLUDED.numero_venta,
      id_vendedor = EXCLUDED.id_vendedor,
      nombre_vendedor = EXCLUDED.nombre_vendedor,
      fecha_venta = EXCLUDED.fecha_venta,
      base = EXCLUDED.base,
      monto_venta = EXCLUDED.monto_venta,
      monto_cobrado = EXCLUDED.monto_cobrado,
      base_monto = EXCLUDED.base_monto,
      porcentaje = EXCLUDED.porcentaje,
      monto_devengado = EXCLUDED.monto_devengado,
      estado = CASE
        WHEN EXCLUDED.estado = 'anulada' THEN 'anulada'
        WHEN comisiones_ventas.monto_liquidado >= EXCLUDED.monto_devengado
             AND EXCLUDED.monto_devengado > 0 THEN 'liquidada'
        WHEN comisiones_ventas.monto_liquidado <> 0 THEN 'parcial'
        ELSE 'pendiente'
      END,
      updated_at = now()
    RETURNING monto_devengado
  )
  SELECT count(*), COALESCE(sum(monto_devengado), 0) INTO v_procesadas, v_devengado FROM upserted;

  RETURN jsonb_build_object('procesadas', v_procesadas, 'devengado', v_devengado);
END;
$$;

-- 7) Consultas para la pantalla ---------------------------------------------------------
CREATE OR REPLACE FUNCTION public.comisiones_listar(
  p_actor_id integer,
  p_desde date,
  p_hasta date
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_out jsonb;
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para ver comisiones';
  END IF;

  SELECT jsonb_build_object(
    'por_vendedor', COALESCE((
      SELECT jsonb_agg(x ORDER BY x->>'nombre_vendedor')
      FROM (
        SELECT jsonb_build_object(
          'id_vendedor', cv.id_vendedor,
          'nombre_vendedor', COALESCE(cv.nombre_vendedor, 'Sin vendedor'),
          'ventas', count(*),
          'monto_venta', round(sum(cv.monto_venta), 2),
          'base_monto', round(sum(cv.base_monto), 2),
          'devengado', round(sum(cv.monto_devengado), 2),
          'liquidado', round(sum(cv.monto_liquidado), 2),
          'pendiente', round(sum(cv.monto_devengado - cv.monto_liquidado), 2)
        ) AS x
        FROM public.comisiones_ventas cv
        WHERE cv.fecha_venta BETWEEN p_desde AND p_hasta
        GROUP BY cv.id_vendedor, cv.nombre_vendedor
      ) s
    ), '[]'::jsonb),
    'ventas', COALESCE((
      SELECT jsonb_agg(to_jsonb(cv) ORDER BY cv.fecha_venta DESC, cv.id DESC)
      FROM (
        SELECT * FROM public.comisiones_ventas c2
        WHERE c2.fecha_venta BETWEEN p_desde AND p_hasta
        ORDER BY c2.fecha_venta DESC, c2.id DESC
        LIMIT 500
      ) cv
    ), '[]'::jsonb),
    'pendiente_total', COALESCE((
      SELECT round(sum(monto_devengado - monto_liquidado), 2)
      FROM public.comisiones_ventas
      WHERE estado <> 'anulada'
    ), 0)
  ) INTO v_out;

  RETURN v_out;
END;
$$;

CREATE OR REPLACE FUNCTION public.comisiones_listar_liquidaciones(
  p_actor_id integer,
  p_limite integer DEFAULT 24
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_out jsonb;
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para ver comisiones';
  END IF;

  SELECT COALESCE(jsonb_agg(to_jsonb(l) || jsonb_build_object('items', items) ORDER BY l.periodo DESC, l.nombre_vendedor), '[]'::jsonb)
  INTO v_out
  FROM (
    SELECT * FROM public.comisiones_liquidaciones
    ORDER BY periodo DESC, id DESC
    LIMIT GREATEST(1, LEAST(COALESCE(p_limite, 24), 200))
  ) l
  LEFT JOIN LATERAL (
    SELECT COALESCE(jsonb_agg(to_jsonb(i) ORDER BY i.id), '[]'::jsonb) AS items
    FROM public.comisiones_liquidacion_items i
    WHERE i.id_liquidacion = l.id
  ) it ON true;

  RETURN v_out;
END;
$$;

-- 8) Liquidación mensual ------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.comisiones_generar_liquidacion(
  p_actor_id integer,
  p_periodo date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_periodo date := date_trunc('month', COALESCE(p_periodo, CURRENT_DATE))::date;
  v_vendedor RECORD;
  v_id_liq bigint;
  v_total numeric;
  v_generadas integer := 0;
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para liquidar comisiones';
  END IF;

  -- Los borradores de este período se rearman de cero: se vacían antes de recalcular
  -- (así sus ítems no cuentan como "ya tomados" más abajo).
  DELETE FROM public.comisiones_liquidacion_items i
  USING public.comisiones_liquidaciones l
  WHERE l.id = i.id_liquidacion AND l.periodo = v_periodo AND l.estado = 'borrador';

  UPDATE public.comisiones_liquidaciones
  SET total = 0, updated_at = now()
  WHERE periodo = v_periodo AND estado = 'borrador';

  FOR v_vendedor IN
    SELECT cv.id_vendedor, max(cv.nombre_vendedor) AS nombre_vendedor
    FROM public.comisiones_ventas cv
    WHERE cv.id_vendedor IS NOT NULL
      AND round(cv.monto_devengado - cv.monto_liquidado, 2) <> 0
      -- Sin esto, una comisión que ya está en otro borrador o en una aprobada sin pagar
      -- entraría de nuevo acá y terminaría pagándose dos veces.
      AND NOT EXISTS (
        SELECT 1
        FROM public.comisiones_liquidacion_items i
        JOIN public.comisiones_liquidaciones l ON l.id = i.id_liquidacion
        WHERE i.id_venta = cv.id_venta AND l.estado IN ('borrador', 'aprobada')
      )
    GROUP BY cv.id_vendedor
  LOOP
    SELECT id INTO v_id_liq
    FROM public.comisiones_liquidaciones
    WHERE periodo = v_periodo AND id_vendedor = v_vendedor.id_vendedor;

    -- Una liquidación aprobada o pagada no se vuelve a armar
    IF v_id_liq IS NOT NULL THEN
      IF EXISTS (SELECT 1 FROM public.comisiones_liquidaciones WHERE id = v_id_liq AND estado <> 'borrador') THEN
        CONTINUE;
      END IF;
    ELSE
      INSERT INTO public.comisiones_liquidaciones (periodo, id_vendedor, nombre_vendedor, creada_por)
      VALUES (v_periodo, v_vendedor.id_vendedor, v_vendedor.nombre_vendedor, p_actor_id)
      RETURNING id INTO v_id_liq;
    END IF;

    INSERT INTO public.comisiones_liquidacion_items (id_liquidacion, id_venta, numero_venta, base_monto, porcentaje, monto)
    SELECT v_id_liq, cv.id_venta, cv.numero_venta, cv.base_monto, cv.porcentaje,
           round(cv.monto_devengado - cv.monto_liquidado, 2)
    FROM public.comisiones_ventas cv
    WHERE cv.id_vendedor = v_vendedor.id_vendedor
      AND round(cv.monto_devengado - cv.monto_liquidado, 2) <> 0
      AND NOT EXISTS (
        SELECT 1
        FROM public.comisiones_liquidacion_items i
        JOIN public.comisiones_liquidaciones l ON l.id = i.id_liquidacion
        WHERE i.id_venta = cv.id_venta AND l.estado IN ('borrador', 'aprobada')
      );

    SELECT COALESCE(sum(monto), 0) INTO v_total
    FROM public.comisiones_liquidacion_items WHERE id_liquidacion = v_id_liq;

    UPDATE public.comisiones_liquidaciones
    SET total = v_total, nombre_vendedor = v_vendedor.nombre_vendedor, updated_at = now()
    WHERE id = v_id_liq;

    v_generadas := v_generadas + 1;
  END LOOP;

  -- Borradores que quedaron sin nada (todo su contenido ya estaba liquidado o pagado)
  DELETE FROM public.comisiones_liquidaciones l
  WHERE l.periodo = v_periodo
    AND l.estado = 'borrador'
    AND NOT EXISTS (SELECT 1 FROM public.comisiones_liquidacion_items i WHERE i.id_liquidacion = l.id);

  RETURN jsonb_build_object('periodo', v_periodo, 'liquidaciones', v_generadas);
END;
$$;

CREATE OR REPLACE FUNCTION public.comisiones_cambiar_estado_liquidacion(
  p_actor_id integer,
  p_id bigint,
  p_estado text,
  p_fecha_pago date DEFAULT NULL,
  p_observaciones text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_liq public.comisiones_liquidaciones%ROWTYPE;
BEGIN
  IF NOT public.actor_puede_comisiones(p_actor_id) THEN
    RAISE EXCEPTION 'No autorizado para liquidar comisiones';
  END IF;
  IF p_estado NOT IN ('borrador', 'aprobada', 'pagada', 'anulada') THEN
    RAISE EXCEPTION 'Estado inválido: %', p_estado;
  END IF;

  SELECT * INTO v_liq FROM public.comisiones_liquidaciones WHERE id = p_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Liquidación % no encontrada', p_id; END IF;
  IF v_liq.estado = p_estado THEN
    RETURN to_jsonb(v_liq);
  END IF;
  IF v_liq.estado = 'pagada' THEN
    RAISE EXCEPTION 'La liquidación ya fue pagada: no se puede modificar';
  END IF;
  IF p_estado = 'pagada' AND v_liq.estado <> 'aprobada' THEN
    RAISE EXCEPTION 'Primero hay que aprobar la liquidación';
  END IF;

  -- Al pagar se descuenta del pendiente de cada venta (recién ahí queda saldada)
  IF p_estado = 'pagada' THEN
    UPDATE public.comisiones_ventas cv
    SET monto_liquidado = round(cv.monto_liquidado + i.monto, 2),
        estado = CASE
          WHEN cv.estado = 'anulada' THEN 'anulada'
          WHEN round(cv.monto_liquidado + i.monto, 2) >= cv.monto_devengado AND cv.monto_devengado > 0 THEN 'liquidada'
          WHEN round(cv.monto_liquidado + i.monto, 2) <> 0 THEN 'parcial'
          ELSE 'pendiente'
        END,
        updated_at = now()
    FROM public.comisiones_liquidacion_items i
    WHERE i.id_liquidacion = p_id AND cv.id_venta = i.id_venta;
  END IF;

  UPDATE public.comisiones_liquidaciones SET
    estado = p_estado,
    aprobada_por = CASE WHEN p_estado IN ('aprobada', 'pagada') THEN p_actor_id ELSE aprobada_por END,
    fecha_aprobacion = CASE WHEN p_estado = 'aprobada' THEN now() ELSE fecha_aprobacion END,
    fecha_pago = CASE WHEN p_estado = 'pagada' THEN COALESCE(p_fecha_pago, CURRENT_DATE) ELSE fecha_pago END,
    observaciones = COALESCE(p_observaciones, observaciones),
    updated_at = now()
  WHERE id = p_id
  RETURNING * INTO v_liq;

  RETURN to_jsonb(v_liq);
END;
$$;

GRANT EXECUTE ON FUNCTION public.comisiones_config_get(integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_guardar_config(integer, jsonb) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_guardar_vendedor(integer, integer, numeric, boolean) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_recalcular(integer, date, date) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_listar(integer, date, date) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_listar_liquidaciones(integer, integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_generar_liquidacion(integer, date) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.comisiones_cambiar_estado_liquidacion(integer, bigint, text, date, text) TO anon, authenticated;

COMMENT ON TABLE public.comisiones_ventas IS
  'Comisión devengada por venta. monto_liquidado avanza solo cuando se marca pagada la liquidación.';
COMMENT ON TABLE public.comisiones_liquidaciones IS
  'Liquidación mensual por vendedor: borrador → aprobada → pagada.';

COMMIT;
