-- Prueba verificable de mensajes DM + helpers de participación en room.

CREATE TABLE IF NOT EXISTS public.chat_message_proof_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id integer NOT NULL REFERENCES public.chat_messages(id) ON DELETE CASCADE,
  room_id integer NOT NULL,
  generated_by integer NOT NULL,
  proof_token uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  download_count integer NOT NULL DEFAULT 0,
  last_downloaded_at timestamptz,
  CONSTRAINT chat_message_proof_tokens_token_unique UNIQUE (proof_token)
);

CREATE INDEX IF NOT EXISTS idx_chat_message_proof_tokens_message
  ON public.chat_message_proof_tokens(message_id);

CREATE INDEX IF NOT EXISTS idx_chat_message_proof_tokens_token
  ON public.chat_message_proof_tokens(proof_token);

CREATE OR REPLACE FUNCTION public.usuario_participa_room_dm(p_user_id integer, p_room_id integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.chat_rooms r
    WHERE r.id = p_room_id
      AND r.tipo = 'privado'
      AND r.nombre ~ '^dm:\d+:\d+$'
      AND (
        r.nombre LIKE 'dm:' || p_user_id::text || ':%'
        OR r.nombre LIKE 'dm:%:' || p_user_id::text
      )
  );
$$;

CREATE OR REPLACE FUNCTION public.generar_prueba_mensaje_dm(p_message_id integer, p_user_id integer)
RETURNS TABLE (
  proof_token uuid,
  message_id integer,
  room_id integer,
  id_usuario integer,
  nombre_usuario text,
  mensaje text,
  msg_timestamp timestamptz,
  archivos_urls jsonb,
  token_created_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_room_id integer;
  v_id_usuario integer;
  v_nombre_usuario text;
  v_mensaje text;
  v_timestamp timestamptz;
  v_archivos jsonb;
  v_token uuid;
  v_created timestamptz;
BEGIN
  SELECT m.room_id, m.id_usuario, m.nombre_usuario, m.mensaje, m.timestamp, COALESCE(m.archivos_urls, '[]'::jsonb)
  INTO v_room_id, v_id_usuario, v_nombre_usuario, v_mensaje, v_timestamp, v_archivos
  FROM public.chat_messages m
  WHERE m.id = p_message_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'mensaje_no_encontrado';
  END IF;

  IF NOT public.usuario_participa_room_dm(p_user_id, v_room_id) THEN
    RAISE EXCEPTION 'sin_permiso';
  END IF;

  SELECT t.proof_token, t.created_at
  INTO v_token, v_created
  FROM public.chat_message_proof_tokens t
  WHERE t.message_id = p_message_id AND t.generated_by = p_user_id
  ORDER BY t.created_at DESC
  LIMIT 1;

  IF v_token IS NULL THEN
    INSERT INTO public.chat_message_proof_tokens (message_id, room_id, generated_by)
    VALUES (p_message_id, v_room_id, p_user_id)
    RETURNING chat_message_proof_tokens.proof_token, chat_message_proof_tokens.created_at
    INTO v_token, v_created;
  END IF;

  RETURN QUERY
  SELECT
    v_token,
    p_message_id,
    v_room_id,
    v_id_usuario,
    v_nombre_usuario,
    v_mensaje,
    v_timestamp,
    v_archivos,
    v_created;
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_prueba_mensaje_por_token(p_token uuid)
RETURNS TABLE (
  proof_token uuid,
  message_id integer,
  room_id integer,
  id_usuario integer,
  nombre_usuario text,
  mensaje text,
  msg_timestamp timestamptz,
  archivos_urls jsonb,
  token_created_at timestamptz,
  generated_by integer,
  download_count integer,
  room_nombre text,
  es_dm boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.chat_message_proof_tokens t
  SET download_count = t.download_count + 1,
      last_downloaded_at = now()
  WHERE t.proof_token = p_token;

  RETURN QUERY
  SELECT
    t.proof_token,
    t.message_id,
    t.room_id,
    m.id_usuario,
    m.nombre_usuario,
    m.mensaje,
    m.timestamp,
    COALESCE(m.archivos_urls, '[]'::jsonb),
    t.created_at,
    t.generated_by,
    t.download_count,
    r.nombre,
    (r.tipo = 'privado' AND r.nombre ~ '^dm:\d+:\d+$')
  FROM public.chat_message_proof_tokens t
  JOIN public.chat_messages m ON m.id = t.message_id
  JOIN public.chat_rooms r ON r.id = t.room_id
  WHERE t.proof_token = p_token;
END;
$$;

COMMENT ON TABLE public.chat_message_proof_tokens IS
  'Tokens de prueba verificable para mensajes DM (mensajería interna).';

GRANT EXECUTE ON FUNCTION public.usuario_participa_room_dm(integer, integer) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.generar_prueba_mensaje_dm(integer, integer) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.obtener_prueba_mensaje_por_token(uuid) TO anon, authenticated, service_role;
