-- Sesiones y páginas abiertas en Plot Lab (admin actividad)
-- Aplicado en plot2: platform_activity_tracking

CREATE TABLE IF NOT EXISTS public.platform_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  client_session_id text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz,
  entry_path text,
  user_agent text,
  ip_address text,
  device_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  kind text NOT NULL DEFAULT 'staff',
  page_view_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_platform_sessions_client
  ON public.platform_sessions (usuario_id, client_session_id)
  WHERE ended_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_platform_sessions_usuario_started
  ON public.platform_sessions (usuario_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_sessions_started
  ON public.platform_sessions (started_at DESC);

CREATE TABLE IF NOT EXISTS public.platform_page_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NOT NULL REFERENCES public.platform_sessions(id) ON DELETE CASCADE,
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  path text NOT NULL,
  title text,
  referrer_path text,
  viewed_at timestamptz NOT NULL DEFAULT now(),
  visibility text,
  viewport_w integer,
  viewport_h integer,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_platform_page_views_session
  ON public.platform_page_views (session_id, viewed_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_page_views_usuario
  ON public.platform_page_views (usuario_id, viewed_at DESC);

CREATE INDEX IF NOT EXISTS idx_platform_page_views_viewed
  ON public.platform_page_views (viewed_at DESC);

ALTER TABLE public.platform_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_page_views ENABLE ROW LEVEL SECURITY;

-- Fix 2026-07-20: "column reference id is ambiguous" en RETURNS TABLE
-- (variables de salida shadowean usuarios.id). Ver migración
-- fix_platform_activity_ambiguous_id aplicada en plot2.
