-- =============================================================================
-- BUNDLE: ejecutar en Supabase SQL Editor EN EL ORDEN de las secciones.
-- No incluye el ERP base antiguo (pedidos, CxP, pagos_cobros, plan de cuentas):
--   eso debería existir ya (p. ej. patches 2025-01-15_create_pedidos_compras_tables,
--   2025-01-23_create_erp_sistema_completo, etc.).
--
-- Si tu base NO tiene aún: facturas_venta, asientos_contables, pagos_cobros,
-- plan_cuentas, generar_numero_asiento — ejecutá solo secciones 1–4:
--   2026-04-23_BUNDLE_iva_compras_y_stock_secciones_1_a_4.sql
--
-- Lo que SÍ agrega este bundle:
--   1) Cuentas bancarias + FK desde pagos_cobros (si aplica)
--   2) Libro IVA compras: facturas_compra + items + RLS
--   3) Vínculos factura compra ↔ pedido / CxP
--   4) Depósitos, saldos por depósito, columnas depósito en stock_movimientos
--   5) Notas crédito/débito ventas + función crear_asiento_desde_factura (OPCIONAL)
--   6) Función crear_asiento_desde_pago_cobro (tesorería)
--
-- OPCIONAL (idempotencia recepción stock en BD): archivo aparte
--   2026-04-25_stock_mov_entrada_unique_index_pedido_articulo.sql
-- Secciones 5–6 por separado: 2026-04-24_BUNDLE_contabilidad_secciones_5_y_6.sql
--
-- OP borrado lógico (columnas eliminada / motivo_eliminacion / fecha_eliminacion + vista auditoría):
--   2026-04-27_ordenes_soft_delete_eliminada.sql  ← ejecutarlo aparte si la app ya elimina con motivo
-- =============================================================================


-- =============================================================================
-- SECCIÓN 1 — 2026-04-16_create_cuentas_bancarias.sql
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.cuentas_bancarias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  banco text NULL,
  tipo text NULL,
  moneda text NOT NULL DEFAULT 'ARS',
  activa boolean NOT NULL DEFAULT true,
  saldo_inicial numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.set_updated_at_cuentas_bancarias()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_set_updated_at_cuentas_bancarias ON public.cuentas_bancarias;
CREATE TRIGGER trigger_set_updated_at_cuentas_bancarias
BEFORE UPDATE ON public.cuentas_bancarias
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at_cuentas_bancarias();

GRANT SELECT, INSERT, UPDATE, DELETE ON public.cuentas_bancarias TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.cuentas_bancarias_id_seq TO anon, authenticated;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'pagos_cobros') THEN
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.table_constraints tc
      WHERE tc.constraint_schema = 'public'
        AND tc.table_name = 'pagos_cobros'
        AND tc.constraint_type = 'FOREIGN KEY'
        AND tc.constraint_name = 'pagos_cobros_id_cuenta_bancaria_fkey'
    ) THEN
      ALTER TABLE public.pagos_cobros
      ADD CONSTRAINT pagos_cobros_id_cuenta_bancaria_fkey
      FOREIGN KEY (id_cuenta_bancaria) REFERENCES public.cuentas_bancarias(id) ON DELETE SET NULL;
    END IF;
  END IF;
END $$;

ALTER TABLE public.cuentas_bancarias ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cuentas_bancarias' AND policyname = 'Allow anon select cuentas bancarias'
  ) THEN
    CREATE POLICY "Allow anon select cuentas bancarias"
    ON public.cuentas_bancarias
    FOR SELECT
    TO anon
    USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'cuentas_bancarias' AND policyname = 'Allow anon write cuentas bancarias'
  ) THEN
    CREATE POLICY "Allow anon write cuentas bancarias"
    ON public.cuentas_bancarias
    FOR ALL
    TO anon
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;

COMMIT;


-- =============================================================================
-- SECCIÓN 2 — 2026-04-16_facturas_compra_libro_iva_compras.sql
-- Requiere: public.proveedores(id), public.usuarios(id) para FK/RLS.
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.facturas_compra (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_comprobante varchar(50) NOT NULL DEFAULT 'Factura' CHECK (
    tipo_comprobante IN ('Factura', 'Nota de Crédito', 'Nota de Débito')
  ),
  letra varchar(2) NOT NULL DEFAULT 'A' CHECK (letra IN ('A', 'B', 'C')),
  punto_venta integer NOT NULL DEFAULT 1,
  numero_comprobante integer NOT NULL,
  numero_factura varchar(50) NOT NULL,
  fecha_emision date NOT NULL DEFAULT CURRENT_DATE,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  proveedor_nombre varchar(255) NOT NULL,
  proveedor_cuit varchar(50),
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  iva numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  observaciones text,
  id_usuario integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT facturas_compra_num_unique UNIQUE (punto_venta, numero_comprobante, letra, tipo_comprobante)
);

CREATE INDEX IF NOT EXISTS idx_facturas_compra_fecha ON public.facturas_compra(fecha_emision);
CREATE INDEX IF NOT EXISTS idx_facturas_compra_proveedor ON public.facturas_compra(id_proveedor);

CREATE TABLE IF NOT EXISTS public.facturas_compra_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_factura integer NOT NULL REFERENCES public.facturas_compra(id) ON DELETE CASCADE,
  item_numero integer NOT NULL,
  descripcion text NOT NULL,
  cantidad numeric(10,2) NOT NULL DEFAULT 1,
  precio_unitario numeric(15,2) NOT NULL DEFAULT 0,
  descuento numeric(15,2) NOT NULL DEFAULT 0,
  iva_porcentaje numeric(5,2) NOT NULL DEFAULT 21.00,
  iva_monto numeric(15,2) NOT NULL DEFAULT 0,
  subtotal numeric(15,2) NOT NULL DEFAULT 0,
  total numeric(15,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_facturas_compra_items_factura ON public.facturas_compra_items(id_factura);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at'
  ) THEN
    CREATE OR REPLACE FUNCTION public.set_updated_at()
    RETURNS TRIGGER AS $f$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $f$ LANGUAGE plpgsql;
  END IF;
END$$;

DROP TRIGGER IF EXISTS set_updated_at_facturas_compra ON public.facturas_compra;
CREATE TRIGGER set_updated_at_facturas_compra
BEFORE UPDATE ON public.facturas_compra
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.facturas_compra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facturas_compra_items ENABLE ROW LEVEL SECURITY;

-- auth.uid() es UUID; usuarios.id es integer — no usar auth.uid()::integer (error 42846).
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facturas_compra TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facturas_compra_items TO anon, authenticated;

DO $$
DECLARE
  s text;
BEGIN
  s := pg_get_serial_sequence('public.facturas_compra', 'id');
  IF s IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', s);
  END IF;
  s := pg_get_serial_sequence('public.facturas_compra_items', 'id');
  IF s IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO anon, authenticated', s);
  END IF;
END $$;

DROP POLICY IF EXISTS "facturas_compra lectura" ON public.facturas_compra;
CREATE POLICY "facturas_compra lectura" ON public.facturas_compra
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "facturas_compra_items lectura" ON public.facturas_compra_items;
CREATE POLICY "facturas_compra_items lectura" ON public.facturas_compra_items
FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "facturas_compra escritura" ON public.facturas_compra;
CREATE POLICY "facturas_compra escritura" ON public.facturas_compra
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "facturas_compra_items escritura" ON public.facturas_compra_items;
CREATE POLICY "facturas_compra_items escritura" ON public.facturas_compra_items
FOR ALL TO anon, authenticated
USING (true)
WITH CHECK (true);

COMMIT;


-- =============================================================================
-- SECCIÓN 3 — 2026-04-17_facturas_compra_vinculos_pedido_cxp.sql
-- Requiere: facturas_compra (sección 2), pedidos_compras, cuentas_por_pagar.
-- =============================================================================
BEGIN;

ALTER TABLE public.facturas_compra
  ADD COLUMN IF NOT EXISTS id_pedido_compra integer REFERENCES public.pedidos_compras(id) ON DELETE SET NULL;

ALTER TABLE public.facturas_compra
  ADD COLUMN IF NOT EXISTS id_cuenta_por_pagar integer REFERENCES public.cuentas_por_pagar(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_facturas_compra_pedido ON public.facturas_compra(id_pedido_compra);
CREATE INDEX IF NOT EXISTS idx_facturas_compra_cxp ON public.facturas_compra(id_cuenta_por_pagar);

COMMENT ON COLUMN public.facturas_compra.id_pedido_compra IS 'Pedido de compra origen (precarga IVA compras / ERP).';
COMMENT ON COLUMN public.facturas_compra.id_cuenta_por_pagar IS 'Cuenta por pagar vinculada al comprobante.';

COMMIT;


-- =============================================================================
-- SECCIÓN 4 — 2026-04-18_stock_depositos_saldos_transferencia.sql
-- Requiere: public.stock_movimientos (patch pedidos/stock 2025-01-15 u otro).
-- =============================================================================
BEGIN;

CREATE TABLE IF NOT EXISTS public.stock_depositos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  codigo varchar(40),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_depositos_codigo_unique UNIQUE (codigo)
);

CREATE INDEX IF NOT EXISTS idx_stock_depositos_activo ON public.stock_depositos(activo);

CREATE TABLE IF NOT EXISTS public.stock_saldo_deposito (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo_stock integer NOT NULL,
  id_deposito integer NOT NULL REFERENCES public.stock_depositos(id) ON DELETE RESTRICT,
  cantidad numeric(12, 3) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_saldo_deposito_unique UNIQUE (id_articulo_stock, id_deposito)
);

CREATE INDEX IF NOT EXISTS idx_stock_saldo_deposito_articulo ON public.stock_saldo_deposito(id_articulo_stock);
CREATE INDEX IF NOT EXISTS idx_stock_saldo_deposito_deposito ON public.stock_saldo_deposito(id_deposito);

INSERT INTO public.stock_depositos (nombre, codigo, activo)
VALUES ('Principal', 'PRINCIPAL', true)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS id_deposito_origen integer REFERENCES public.stock_depositos(id) ON DELETE SET NULL;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS id_deposito_destino integer REFERENCES public.stock_depositos(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_dep_origen ON public.stock_movimientos(id_deposito_origen);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_dep_destino ON public.stock_movimientos(id_deposito_destino);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_depositos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_saldo_deposito TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_depositos_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_saldo_deposito_id_seq TO anon, authenticated;

ALTER TABLE public.stock_depositos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_saldo_deposito ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stock_depositos all" ON public.stock_depositos;
CREATE POLICY "stock_depositos all" ON public.stock_depositos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "stock_saldo_deposito all" ON public.stock_saldo_deposito;
CREATE POLICY "stock_saldo_deposito all" ON public.stock_saldo_deposito FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE public.stock_depositos IS 'Depósitos / ubicaciones para inventario multi-almacén (referencia por id_articulo_stock en base de stock).';
COMMENT ON TABLE public.stock_saldo_deposito IS 'Cantidad por artículo y depósito. La suma puede alinearse con articulos.stock vía sincronización en app.';

COMMIT;


-- =============================================================================
-- SECCIÓN 5 — 2026-04-16_facturas_notas_credito_debito.sql (ventas / AFIP)
-- Solo si usás facturas_venta + crear_asiento_desde_factura. Sobrescribe la función.
-- =============================================================================
BEGIN;

SET LOCAL check_function_bodies TO FALSE;

ALTER TABLE IF EXISTS public.facturas_venta
  ADD COLUMN IF NOT EXISTS id_factura_referencia integer NULL;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'facturas_venta'
      AND column_name = 'id_factura_referencia'
  ) THEN
    IF NOT EXISTS (
      SELECT 1
      FROM information_schema.table_constraints tc
      WHERE tc.table_schema = 'public'
        AND tc.table_name = 'facturas_venta'
        AND tc.constraint_type = 'FOREIGN KEY'
        AND tc.constraint_name = 'facturas_venta_id_factura_referencia_fkey'
    ) THEN
      ALTER TABLE public.facturas_venta
        ADD CONSTRAINT facturas_venta_id_factura_referencia_fkey
        FOREIGN KEY (id_factura_referencia)
        REFERENCES public.facturas_venta(id)
        ON DELETE SET NULL;
    END IF;
  END IF;
END$$;

DO $$
BEGIN
  IF to_regclass('public.facturas_venta') IS NOT NULL THEN
    EXECUTE 'CREATE INDEX IF NOT EXISTS idx_facturas_referencia ON public.facturas_venta(id_factura_referencia)';
  END IF;
END$$;

CREATE OR REPLACE FUNCTION public.crear_asiento_desde_factura(
  p_id_factura integer
)
RETURNS integer AS $$
DECLARE
  v_factura RECORD;
  v_asiento_id integer;
  v_numero_asiento varchar(50);
  v_cuenta_ventas integer;
  v_cuenta_iva integer;
  v_cuenta_clientes integer;
  v_total numeric;
  v_subtotal numeric;
  v_iva numeric;
  v_es_nota_credito boolean := false;
BEGIN
  SELECT * INTO v_factura
  FROM public.facturas_venta
  WHERE id = p_id_factura;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Factura no encontrada: %', p_id_factura;
  END IF;

  v_es_nota_credito := (v_factura.tipo_comprobante LIKE 'Nota de Crédito%');
  v_total := ABS(COALESCE(v_factura.total, 0));
  v_subtotal := ABS(COALESCE(v_factura.subtotal, 0));
  v_iva := ABS(COALESCE(v_factura.iva, 0));

  SELECT id INTO v_cuenta_ventas
  FROM public.plan_cuentas
  WHERE codigo = '4.1.1.01'
  LIMIT 1;

  SELECT id INTO v_cuenta_iva
  FROM public.plan_cuentas
  WHERE codigo = '1.1.2.01'
  LIMIT 1;

  SELECT id INTO v_cuenta_clientes
  FROM public.plan_cuentas
  WHERE codigo = '1.1.1.03'
  LIMIT 1;

  v_numero_asiento := public.generar_numero_asiento();

  INSERT INTO public.asientos_contables (
    numero_asiento,
    fecha,
    concepto,
    tipo_asiento,
    id_origen,
    tipo_origen,
    total_debe,
    total_haber,
    estado
  ) VALUES (
    v_numero_asiento,
    v_factura.fecha_emision,
    v_factura.tipo_comprobante || ' ' || v_factura.numero_factura || ' - ' || v_factura.cliente_nombre,
    'Facturación',
    v_factura.id,
    'factura',
    v_total,
    v_total,
    'Contabilizado'
  ) RETURNING id INTO v_asiento_id;

  IF v_es_nota_credito THEN
    IF v_cuenta_ventas IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_ventas, v_subtotal, 0, 'Reversa ventas (nota crédito)');
    END IF;

    IF v_cuenta_iva IS NOT NULL AND v_iva > 0 THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_iva, v_iva, 0, 'Reversa IVA débito fiscal (nota crédito)');
    END IF;

    IF v_cuenta_clientes IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_clientes, 0, v_total, 'Cliente (nota crédito): ' || v_factura.cliente_nombre);
    END IF;
  ELSE
    IF v_cuenta_clientes IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_clientes, v_total, 0, 'Cliente: ' || v_factura.cliente_nombre);
    END IF;

    IF v_cuenta_ventas IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_ventas, 0, v_subtotal, 'Ventas');
    END IF;

    IF v_cuenta_iva IS NOT NULL AND v_iva > 0 THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_iva, 0, v_iva, 'IVA Débito Fiscal');
    END IF;
  END IF;

  UPDATE public.facturas_venta
  SET id_asiento_contable = v_asiento_id
  WHERE id = p_id_factura;

  RETURN v_asiento_id;
END;
$$ LANGUAGE plpgsql;

COMMIT;


-- =============================================================================
-- SECCIÓN 6 — 2026-04-16_pagos_cobros_asientos_automaticos.sql
-- Requiere: pagos_cobros, cuentas_por_cobrar/pagar, plan_cuentas, generar_numero_asiento, asientos_contables/detalle
-- =============================================================================
BEGIN;

SET LOCAL check_function_bodies TO FALSE;

CREATE OR REPLACE FUNCTION public.crear_asiento_desde_pago_cobro(
  p_id_pago_cobro integer
)
RETURNS integer AS $$
DECLARE
  v_pc RECORD;
  v_cxc RECORD;
  v_cxp RECORD;
  v_asiento_id integer;
  v_numero_asiento varchar(50);
  v_cuenta_caja integer;
  v_cuenta_bancos integer;
  v_cuenta_clientes integer;
  v_cuenta_proveedores integer;
  v_cuenta_tesoreria integer;
  v_monto numeric;
  v_concepto text;
BEGIN
  SELECT * INTO v_pc
  FROM public.pagos_cobros
  WHERE id = p_id_pago_cobro;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pago/Cobro no encontrado: %', p_id_pago_cobro;
  END IF;

  v_monto := ABS(COALESCE(v_pc.monto, 0));
  IF v_monto <= 0 THEN
    RAISE EXCEPTION 'Monto inválido en Pago/Cobro %', p_id_pago_cobro;
  END IF;

  SELECT id INTO v_cuenta_caja FROM public.plan_cuentas WHERE codigo = '1.1.1.01' LIMIT 1;
  SELECT id INTO v_cuenta_bancos FROM public.plan_cuentas WHERE codigo = '1.1.1.02' LIMIT 1;
  SELECT id INTO v_cuenta_clientes FROM public.plan_cuentas WHERE codigo = '1.1.1.03' LIMIT 1;
  SELECT id INTO v_cuenta_proveedores FROM public.plan_cuentas WHERE codigo = '2.1.1.01' LIMIT 1;

  IF COALESCE(v_pc.metodo_pago, '') = 'Efectivo' THEN
    v_cuenta_tesoreria := v_cuenta_caja;
  ELSE
    v_cuenta_tesoreria := v_cuenta_bancos;
  END IF;

  IF v_cuenta_tesoreria IS NULL THEN
    v_cuenta_tesoreria := v_cuenta_caja;
  END IF;

  IF v_pc.tipo = 'Cobro' THEN
    SELECT * INTO v_cxc FROM public.cuentas_por_cobrar WHERE id = v_pc.id_cuenta_por_cobrar;
    v_concepto := 'Cobro ' || COALESCE(v_cxc.cliente_nombre, '') || ' (' || COALESCE(v_pc.metodo_pago, '') || ')';
  ELSE
    SELECT * INTO v_cxp FROM public.cuentas_por_pagar WHERE id = v_pc.id_cuenta_por_pagar;
    v_concepto := 'Pago ' || COALESCE(v_cxp.proveedor_nombre, '') || ' (' || COALESCE(v_pc.metodo_pago, '') || ')';
  END IF;

  v_numero_asiento := public.generar_numero_asiento();

  INSERT INTO public.asientos_contables (
    numero_asiento,
    fecha,
    concepto,
    tipo_asiento,
    id_origen,
    tipo_origen,
    total_debe,
    total_haber,
    estado
  ) VALUES (
    v_numero_asiento,
    v_pc.fecha_pago,
    v_concepto,
    'Tesorería',
    v_pc.id,
    'pago_cobro',
    v_monto,
    v_monto,
    'Contabilizado'
  ) RETURNING id INTO v_asiento_id;

  IF v_pc.tipo = 'Cobro' THEN
    IF v_cuenta_tesoreria IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_tesoreria, v_monto, 0, 'Ingreso por cobro');
    END IF;
    IF v_cuenta_clientes IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_clientes, 0, v_monto, 'Cancelación CxC');
    END IF;
  ELSE
    IF v_cuenta_proveedores IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_proveedores, v_monto, 0, 'Cancelación CxP');
    END IF;
    IF v_cuenta_tesoreria IS NOT NULL THEN
      INSERT INTO public.asientos_detalle (id_asiento, id_cuenta, debe, haber, concepto)
      VALUES (v_asiento_id, v_cuenta_tesoreria, 0, v_monto, 'Egreso por pago');
    END IF;
  END IF;

  RETURN v_asiento_id;
END;
$$ LANGUAGE plpgsql;

COMMIT;


-- =============================================================================
-- Índice opcional: ver 2026-04-25_stock_mov_entrada_unique_index_pedido_articulo.sql
-- =============================================================================