-- Pagos a proveedores (migrado desde Planilla de Pagos a Proveedores.XLS)
BEGIN;

CREATE TABLE IF NOT EXISTS public.pagos_proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha date NOT NULL,
  numero_pago varchar(50) NOT NULL,
  numero_recibo varchar(50) NOT NULL DEFAULT '',
  proveedor_nombre text NOT NULL,
  usuario varchar(80),
  monto numeric(15,2) NOT NULL DEFAULT 0,
  id_proveedor integer REFERENCES public.proveedores(id) ON DELETE SET NULL,
  id_pago_cobro integer REFERENCES public.pagos_cobros(id) ON DELETE SET NULL,
  fecha_desde date,
  fecha_hasta date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(numero_pago, numero_recibo)
);

CREATE INDEX IF NOT EXISTS idx_pagos_proveedores_fecha ON public.pagos_proveedores(fecha DESC);
CREATE INDEX IF NOT EXISTS idx_pagos_proveedores_proveedor ON public.pagos_proveedores(id_proveedor);
CREATE INDEX IF NOT EXISTS idx_pagos_proveedores_nombre ON public.pagos_proveedores(proveedor_nombre);

ALTER TABLE public.pagos_proveedores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pagos_proveedores_all ON public.pagos_proveedores;
CREATE POLICY pagos_proveedores_all ON public.pagos_proveedores FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

INSERT INTO public.pagos_proveedores (fecha, numero_pago, numero_recibo, proveedor_nombre, usuario, monto, fecha_desde, fecha_hasta)
VALUES
  ('2026-03-18', '00000-00010447', '00000-00001928', 'IGENAR ARGENTINA S.A.', 'ROSAALV', 6478512.79, '2026-01-01', '2026-06-19'),
  ('2026-04-17', '00000-00010621', '00000-00001954', 'IGENAR ARGENTINA S.A.', 'ROSAALV', 4274361.82, '2026-01-01', '2026-06-19'),
  ('2026-06-18', '00000-00010774', '00000-00001964', 'IGENAR ARGENTINA S.A.', 'ROSAALV', 4505535.04, '2026-01-01', '2026-06-19')
ON CONFLICT (numero_pago, numero_recibo) DO UPDATE SET
  fecha = EXCLUDED.fecha,
  proveedor_nombre = EXCLUDED.proveedor_nombre,
  usuario = EXCLUDED.usuario,
  monto = EXCLUDED.monto,
  fecha_desde = EXCLUDED.fecha_desde,
  fecha_hasta = EXCLUDED.fecha_hasta,
  updated_at = now();

CREATE OR REPLACE FUNCTION public.vincular_pagos_proveedores()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE v_count integer;
BEGIN
  UPDATE public.pagos_proveedores p
  SET id_proveedor = pr.id, updated_at = now()
  FROM public.proveedores pr
  WHERE p.id_proveedor IS NULL
    AND (
      upper(trim(coalesce(pr.razon_social, ''))) = upper(trim(p.proveedor_nombre))
      OR upper(trim(pr.nombre)) = upper(trim(p.proveedor_nombre))
      OR upper(trim(pr.nombre)) LIKE '%' || upper(trim(split_part(p.proveedor_nombre, ' ', 1))) || '%'
    );
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

SELECT public.vincular_pagos_proveedores();

COMMIT;
