BEGIN;

-- Tipo general de impresión en la OP (complementa líneas detalladas)
ALTER TABLE public.ordenes_trabajo
  ADD COLUMN IF NOT EXISTS tipo_impresion text;

COMMENT ON COLUMN public.ordenes_trabajo.tipo_impresion IS 'Tipo o familia de trabajo de impresión en la OP (ej. lona, vinilo, papel).';

-- Varios ítems con tipo y m² por orden
CREATE TABLE IF NOT EXISTS public.orden_lineas_m2 (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden integer NOT NULL REFERENCES public.ordenes_trabajo(id) ON DELETE CASCADE,
  tipo varchar(200) NOT NULL DEFAULT '',
  metros_cuadrados numeric(12,2) NOT NULL DEFAULT 0 CHECK (metros_cuadrados >= 0),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orden_lineas_m2_orden ON public.orden_lineas_m2(id_orden);

COMMENT ON TABLE public.orden_lineas_m2 IS 'Detalle de m² por ítem/tipo dentro de una OP; la suma suele reflejarse en ordenes_trabajo.metros_cuadrados.';

GRANT SELECT ON public.orden_lineas_m2 TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.orden_lineas_m2 TO authenticated;

COMMIT;
