-- RRHH: postulaciones laborales (formulario público + panel interno)

BEGIN;

CREATE TABLE IF NOT EXISTS public.rrhh_postulaciones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  email text NOT NULL,
  telefono text,
  puesto text NOT NULL,
  categoria_puesto text,
  mensaje text,
  cv_url text NOT NULL,
  cv_nombre text,
  cv_mime text,
  estado text NOT NULL DEFAULT 'nuevo'
    CHECK (estado IN ('nuevo', 'en_revision', 'entrevista', 'aprobado', 'descartado')),
  metadata_ia jsonb NOT NULL DEFAULT '{}'::jsonb,
  score_ia numeric(5, 2),
  notas_rrhh text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  revisado_por integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  revisado_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_rrhh_postulaciones_estado ON public.rrhh_postulaciones(estado);
CREATE INDEX IF NOT EXISTS idx_rrhh_postulaciones_puesto ON public.rrhh_postulaciones(puesto);
CREATE INDEX IF NOT EXISTS idx_rrhh_postulaciones_created ON public.rrhh_postulaciones(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rrhh_postulaciones_email ON public.rrhh_postulaciones(lower(email));

ALTER TABLE public.rrhh_postulaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "rrhh_postulaciones_select" ON public.rrhh_postulaciones;
DROP POLICY IF EXISTS "rrhh_postulaciones_insert" ON public.rrhh_postulaciones;
DROP POLICY IF EXISTS "rrhh_postulaciones_update" ON public.rrhh_postulaciones;

CREATE POLICY "rrhh_postulaciones_select" ON public.rrhh_postulaciones FOR SELECT USING (true);
CREATE POLICY "rrhh_postulaciones_insert" ON public.rrhh_postulaciones FOR INSERT WITH CHECK (true);
CREATE POLICY "rrhh_postulaciones_update" ON public.rrhh_postulaciones FOR UPDATE USING (true) WITH CHECK (true);

GRANT SELECT, INSERT, UPDATE ON public.rrhh_postulaciones TO anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public._rrhh_es_gestor_postulaciones(p_usuario_id integer)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.usuarios u
    WHERE u.id = p_usuario_id
      AND COALESCE(u.activo, true) = true
      AND u.rol IN ('recursos-humanos', 'administracion', 'gerencia')
  );
$$;

CREATE OR REPLACE FUNCTION public.crear_postulacion_cv_public(
  p_nombre text,
  p_email text,
  p_telefono text,
  p_puesto text,
  p_categoria_puesto text,
  p_mensaje text,
  p_cv_url text,
  p_cv_nombre text,
  p_cv_mime text,
  p_honeypot text DEFAULT NULL
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id bigint;
  v_nombre text;
  v_email text;
  v_puesto text;
  v_cv_url text;
  v_recientes integer;
BEGIN
  IF coalesce(trim(p_honeypot), '') <> '' THEN
    RETURN 0;
  END IF;

  v_nombre := trim(p_nombre);
  v_email := lower(trim(p_email));
  v_puesto := trim(p_puesto);
  v_cv_url := trim(p_cv_url);

  IF length(v_nombre) < 2 THEN
    RAISE EXCEPTION 'Nombre inválido';
  END IF;
  IF v_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    RAISE EXCEPTION 'Email inválido';
  END IF;
  IF length(v_puesto) < 2 THEN
    RAISE EXCEPTION 'Puesto requerido';
  END IF;
  IF v_cv_url = '' OR v_cv_url !~* '^https?://' THEN
    RAISE EXCEPTION 'URL de CV inválida';
  END IF;

  SELECT COUNT(*)::integer INTO v_recientes
    FROM public.rrhh_postulaciones p
   WHERE lower(p.email) = v_email
     AND p.created_at > now() - interval '1 hour';

  IF v_recientes >= 5 THEN
    RAISE EXCEPTION 'Demasiados envíos recientes desde este email. Intentá más tarde.';
  END IF;

  INSERT INTO public.rrhh_postulaciones (
    nombre, email, telefono, puesto, categoria_puesto, mensaje,
    cv_url, cv_nombre, cv_mime, estado
  ) VALUES (
    v_nombre, v_email, nullif(trim(p_telefono), ''), v_puesto,
    nullif(trim(p_categoria_puesto), ''), nullif(trim(p_mensaje), ''),
    v_cv_url, nullif(trim(p_cv_nombre), ''), nullif(trim(p_cv_mime), ''), 'nuevo'
  )
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.rrhh_postulacion_set_metadata_ia(
  p_id bigint,
  p_metadata jsonb,
  p_score numeric DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.rrhh_postulaciones
     SET metadata_ia = coalesce(p_metadata, '{}'::jsonb),
         score_ia = p_score,
         updated_at = now()
   WHERE id = p_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.rrhh_postulaciones_listar(
  p_usuario_id integer,
  p_busqueda text DEFAULT NULL,
  p_estado text DEFAULT NULL,
  p_puesto text DEFAULT NULL,
  p_limite integer DEFAULT 300
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_busqueda text;
BEGIN
  IF NOT public._rrhh_es_gestor_postulaciones(p_usuario_id) THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  v_busqueda := nullif(trim(p_busqueda), '');

  RETURN coalesce(
    (
      SELECT jsonb_agg(row_to_json(s)::jsonb ORDER BY s.created_at DESC)
      FROM (
        SELECT
          p.id,
          p.nombre,
          p.email,
          p.telefono,
          p.puesto,
          p.categoria_puesto,
          p.mensaje,
          p.cv_url,
          p.cv_nombre,
          p.cv_mime,
          p.estado,
          p.metadata_ia,
          p.score_ia,
          p.notas_rrhh,
          p.created_at,
          p.updated_at,
          p.revisado_por,
          p.revisado_at
        FROM public.rrhh_postulaciones p
        WHERE (p_estado IS NULL OR p_estado = '' OR p.estado = p_estado)
          AND (p_puesto IS NULL OR p_puesto = '' OR p.puesto = p_puesto)
          AND (
            v_busqueda IS NULL
            OR p.nombre ILIKE '%' || v_busqueda || '%'
            OR p.email ILIKE '%' || v_busqueda || '%'
            OR p.puesto ILIKE '%' || v_busqueda || '%'
            OR coalesce(p.mensaje, '') ILIKE '%' || v_busqueda || '%'
            OR coalesce(p.metadata_ia::text, '') ILIKE '%' || v_busqueda || '%'
          )
        ORDER BY p.created_at DESC
        LIMIT greatest(1, least(coalesce(p_limite, 300), 500))
      ) s
    ),
    '[]'::jsonb
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.rrhh_postulacion_actualizar_estado(
  p_usuario_id integer,
  p_id bigint,
  p_estado text,
  p_notas_rrhh text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.rrhh_postulaciones%ROWTYPE;
BEGIN
  IF NOT public._rrhh_es_gestor_postulaciones(p_usuario_id) THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  IF p_estado NOT IN ('nuevo', 'en_revision', 'entrevista', 'aprobado', 'descartado') THEN
    RAISE EXCEPTION 'Estado inválido';
  END IF;

  UPDATE public.rrhh_postulaciones
     SET estado = p_estado,
         notas_rrhh = coalesce(nullif(trim(p_notas_rrhh), ''), notas_rrhh),
         revisado_por = p_usuario_id,
         revisado_at = now(),
         updated_at = now()
   WHERE id = p_id
   RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Postulación no encontrada';
  END IF;

  RETURN to_jsonb(v_row);
END;
$$;

GRANT EXECUTE ON FUNCTION public.crear_postulacion_cv_public(text, text, text, text, text, text, text, text, text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rrhh_postulacion_set_metadata_ia(bigint, jsonb, numeric) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rrhh_postulaciones_listar(integer, text, text, text, integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rrhh_postulacion_actualizar_estado(integer, bigint, text, text) TO anon, authenticated;

COMMENT ON TABLE public.rrhh_postulaciones IS 'CVs recibidos desde formulario público Trabajá con Nosotros';

COMMIT;
