-- Depósitos y saldos por artículo (BD principal). id_articulo_stock coincide con articulos.id en la base de stock.
-- Movimientos de transferencia: dos filas en stock_movimientos (Salida / Entrada) + columnas opcionales de depósito.

BEGIN;

CREATE TABLE IF NOT EXISTS public.stock_depositos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(120) NOT NULL,
  codigo varchar(40),
  activo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_depositos_codigo_unique UNIQUE (codigo)
);

CREATE INDEX IF NOT EXISTS idx_stock_depositos_activo ON public.stock_depositos(activo);

CREATE TABLE IF NOT EXISTS public.stock_saldo_deposito (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo_stock integer NOT NULL,
  id_deposito integer NOT NULL REFERENCES public.stock_depositos(id) ON DELETE RESTRICT,
  cantidad numeric(12, 3) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stock_saldo_deposito_unique UNIQUE (id_articulo_stock, id_deposito)
);

CREATE INDEX IF NOT EXISTS idx_stock_saldo_deposito_articulo ON public.stock_saldo_deposito(id_articulo_stock);
CREATE INDEX IF NOT EXISTS idx_stock_saldo_deposito_deposito ON public.stock_saldo_deposito(id_deposito);

INSERT INTO public.stock_depositos (nombre, codigo, activo)
VALUES ('Principal', 'PRINCIPAL', true)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS id_deposito_origen integer REFERENCES public.stock_depositos(id) ON DELETE SET NULL;

ALTER TABLE public.stock_movimientos
  ADD COLUMN IF NOT EXISTS id_deposito_destino integer REFERENCES public.stock_depositos(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_stock_movimientos_dep_origen ON public.stock_movimientos(id_deposito_origen);
CREATE INDEX IF NOT EXISTS idx_stock_movimientos_dep_destino ON public.stock_movimientos(id_deposito_destino);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_depositos TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.stock_saldo_deposito TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_depositos_id_seq TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stock_saldo_deposito_id_seq TO anon, authenticated;

ALTER TABLE public.stock_depositos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_saldo_deposito ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stock_depositos all" ON public.stock_depositos;
CREATE POLICY "stock_depositos all" ON public.stock_depositos FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "stock_saldo_deposito all" ON public.stock_saldo_deposito;
CREATE POLICY "stock_saldo_deposito all" ON public.stock_saldo_deposito FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

COMMENT ON TABLE public.stock_depositos IS 'Depósitos / ubicaciones para inventario multi-almacén (referencia por id_articulo_stock en base de stock).';
COMMENT ON TABLE public.stock_saldo_deposito IS 'Cantidad por artículo y depósito. La suma puede alinearse con articulos.stock vía sincronización en app.';

COMMIT;
