-- Intercambio de turno de almuerzo entre dos usuarios con menú del día ya pedido.
-- La solicitud puede hacerse en cualquier hora; al aceptar se intercambian turno_almuerzo en menu_selecciones.

CREATE TABLE IF NOT EXISTS public.menu_intercambios_turno (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_menu integer NOT NULL REFERENCES public.menus_diarios(id) ON DELETE CASCADE,
  id_solicita integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  id_destino integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  estado text NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aceptada', 'rechazada', 'cancelada')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT menu_intercambios_distintos CHECK (id_solicita <> id_destino)
);

CREATE INDEX IF NOT EXISTS idx_menu_intercambios_menu ON public.menu_intercambios_turno(id_menu);
CREATE INDEX IF NOT EXISTS idx_menu_intercambios_solicita ON public.menu_intercambios_turno(id_solicita);
CREATE INDEX IF NOT EXISTS idx_menu_intercambios_destino ON public.menu_intercambios_turno(id_destino);
CREATE INDEX IF NOT EXISTS idx_menu_intercambios_estado ON public.menu_intercambios_turno(estado);

-- Una solicitud pendiente por par (solicita → destino) en un mismo menú
CREATE UNIQUE INDEX IF NOT EXISTS uq_menu_intercambio_pendiente_par
  ON public.menu_intercambios_turno (id_menu, id_solicita, id_destino)
  WHERE (estado = 'pendiente');

COMMENT ON TABLE public.menu_intercambios_turno IS 'Solicitudes de intercambio de turno de almuerzo (menú diario)';

ALTER TABLE public.menu_intercambios_turno ENABLE ROW LEVEL SECURITY;

-- =============================================================================
CREATE OR REPLACE FUNCTION public.solicitar_intercambio_turno_menu(
  p_id_menu integer,
  p_id_solicita integer,
  p_id_destino integer
)
RETURNS public.menu_intercambios_turno
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_menu public.menus_diarios;
  v_fecha_argentina date;
  v_ts_solicita public.menu_selecciones%ROWTYPE;
  v_ts_destino public.menu_selecciones%ROWTYPE;
  v_row public.menu_intercambios_turno%ROWTYPE;
  v_nombre_solicita text;
  v_title text;
  v_desc text;
BEGIN
  IF p_id_solicita IS NULL OR p_id_destino IS NULL OR p_id_menu IS NULL THEN
    RAISE EXCEPTION 'Parámetros inválidos';
  END IF;
  IF p_id_solicita = p_id_destino THEN
    RAISE EXCEPTION 'No podés solicitar intercambio contigo mismo';
  END IF;

  SELECT * INTO v_menu FROM public.menus_diarios WHERE id = p_id_menu;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menú no encontrado';
  END IF;

  v_fecha_argentina := public.get_argentina_date();
  IF v_menu.fecha <> v_fecha_argentina THEN
    RAISE EXCEPTION 'Solo se pueden intercambiar turnos del menú del día actual';
  END IF;

  SELECT * INTO v_ts_solicita
  FROM public.menu_selecciones
  WHERE id_menu = p_id_menu AND id_usuario = p_id_solicita;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Primero debés tener un pedido de menú para solicitar intercambio';
  END IF;

  SELECT * INTO v_ts_destino
  FROM public.menu_selecciones
  WHERE id_menu = p_id_menu AND id_usuario = p_id_destino;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'La otra persona no tiene pedido de menú para hoy';
  END IF;

  IF v_ts_solicita.turno_almuerzo = v_ts_destino.turno_almuerzo THEN
    RAISE EXCEPTION 'Ya están en el mismo turno de almuerzo';
  END IF;

  INSERT INTO public.menu_intercambios_turno (id_menu, id_solicita, id_destino, estado)
  VALUES (p_id_menu, p_id_solicita, p_id_destino, 'pendiente')
  RETURNING * INTO v_row;

  SELECT nombre INTO v_nombre_solicita FROM public.usuarios WHERE id = p_id_solicita;
  v_title := 'Intercambio de turno de almuerzo';
  v_desc := COALESCE(trim(v_nombre_solicita), 'Un compañero') ||
    ' te pidió intercambiar el turno de almuerzo del menú de hoy. Revisá Menú diario para aceptar o rechazar.';

  BEGIN
    INSERT INTO public.user_notifications (user_id, type, title, description, is_read)
    VALUES (p_id_destino, 'info', v_title, v_desc, false);
  EXCEPTION WHEN undefined_table THEN
    NULL;
  WHEN OTHERS THEN
    NULL;
  END;

  RETURN v_row;
END;
$$;

-- =============================================================================
CREATE OR REPLACE FUNCTION public.responder_intercambio_turno_menu(
  p_id_intercambio bigint,
  p_id_usuario integer,
  p_accion text
)
RETURNS public.menu_intercambios_turno
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_row public.menu_intercambios_turno%ROWTYPE;
  v_menu public.menus_diarios;
  v_fecha_argentina date;
  t_sol smallint;
  t_dst smallint;
  v_title text;
  v_desc text;
  v_nombre_destino text;
BEGIN
  IF p_accion IS NULL OR trim(p_accion) = '' THEN
    RAISE EXCEPTION 'Acción inválida';
  END IF;
  p_accion := lower(trim(p_accion));
  IF p_accion NOT IN ('aceptar', 'rechazar', 'cancelar') THEN
    RAISE EXCEPTION 'Acción debe ser aceptar, rechazar o cancelar';
  END IF;

  SELECT * INTO v_row FROM public.menu_intercambios_turno WHERE id = p_id_intercambio FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitud no encontrada';
  END IF;
  IF v_row.estado <> 'pendiente' THEN
    RAISE EXCEPTION 'Esta solicitud ya fue procesada';
  END IF;

  SELECT * INTO v_menu FROM public.menus_diarios WHERE id = v_row.id_menu;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Menú no encontrado';
  END IF;

  v_fecha_argentina := public.get_argentina_date();
  IF v_menu.fecha <> v_fecha_argentina THEN
    RAISE EXCEPTION 'Esta solicitud ya no es válida (no es el día del menú)';
  END IF;

  IF p_accion = 'cancelar' THEN
    IF p_id_usuario <> v_row.id_solicita THEN
      RAISE EXCEPTION 'Solo quien solicitó puede cancelar';
    END IF;
    UPDATE public.menu_intercambios_turno
    SET estado = 'cancelada', updated_at = now()
    WHERE id = p_id_intercambio
    RETURNING * INTO v_row;
    RETURN v_row;
  END IF;

  IF p_accion IN ('aceptar', 'rechazar') THEN
    IF p_id_usuario <> v_row.id_destino THEN
      RAISE EXCEPTION 'Solo quien recibió la solicitud puede aceptar o rechazar';
    END IF;
  END IF;

  IF p_accion = 'rechazar' THEN
    UPDATE public.menu_intercambios_turno
    SET estado = 'rechazada', updated_at = now()
    WHERE id = p_id_intercambio
    RETURNING * INTO v_row;

    BEGIN
      INSERT INTO public.user_notifications (user_id, type, title, description, is_read)
      VALUES (
        v_row.id_solicita,
        'info',
        'Intercambio de turno',
        'Tu solicitud de intercambio de turno de almuerzo fue rechazada.',
        false
      );
    EXCEPTION WHEN undefined_table THEN NULL;
    WHEN OTHERS THEN NULL;
    END;

    RETURN v_row;
  END IF;

  -- aceptar
  SELECT turno_almuerzo INTO t_sol
  FROM public.menu_selecciones
  WHERE id_menu = v_row.id_menu AND id_usuario = v_row.id_solicita;
  SELECT turno_almuerzo INTO t_dst
  FROM public.menu_selecciones
  WHERE id_menu = v_row.id_menu AND id_usuario = v_row.id_destino;

  IF t_sol IS NULL OR t_dst IS NULL THEN
    RAISE EXCEPTION 'Ya no hay selección de menú para uno de los usuarios';
  END IF;

  IF t_sol = t_dst THEN
    UPDATE public.menu_intercambios_turno
    SET estado = 'aceptada', updated_at = now()
    WHERE id = p_id_intercambio
    RETURNING * INTO v_row;
    RETURN v_row;
  END IF;

  -- Intercambio uno a uno: los cupos por turno no cambian (solo se permutan dos personas).

  UPDATE public.menu_selecciones
  SET turno_almuerzo = t_dst, fecha_seleccion = now()
  WHERE id_menu = v_row.id_menu AND id_usuario = v_row.id_solicita;

  UPDATE public.menu_selecciones
  SET turno_almuerzo = t_sol, fecha_seleccion = now()
  WHERE id_menu = v_row.id_menu AND id_usuario = v_row.id_destino;

  UPDATE public.menu_intercambios_turno
  SET estado = 'aceptada', updated_at = now()
  WHERE id = p_id_intercambio
  RETURNING * INTO v_row;

  SELECT nombre INTO v_nombre_destino FROM public.usuarios WHERE id = v_row.id_destino;
  v_title := 'Intercambio de turno confirmado';
  v_desc := COALESCE(trim(v_nombre_destino), 'Tu compañero') ||
    ' aceptó el intercambio. Ya tenés el nuevo turno de almuerzo en el menú del día.';

  BEGIN
    INSERT INTO public.user_notifications (user_id, type, title, description, is_read)
    VALUES (v_row.id_solicita, 'info', v_title, v_desc, false);
  EXCEPTION WHEN undefined_table THEN NULL;
  WHEN OTHERS THEN NULL;
  END;

  RETURN v_row;
END;
$$;

-- =============================================================================
CREATE OR REPLACE FUNCTION public.obtener_intercambios_turno_menu(
  p_id_usuario integer,
  p_id_menu integer DEFAULT NULL
)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN COALESCE(
    (
      SELECT json_agg(row_to_json(q))
      FROM (
        SELECT
          i.id,
          i.id_menu,
          i.id_solicita,
          i.id_destino,
          us.nombre AS nombre_solicita,
          ud.nombre AS nombre_destino,
          i.estado,
          i.created_at,
          i.updated_at
        FROM public.menu_intercambios_turno i
        JOIN public.usuarios us ON us.id = i.id_solicita
        JOIN public.usuarios ud ON ud.id = i.id_destino
        WHERE (p_id_menu IS NULL OR i.id_menu = p_id_menu)
          AND (i.id_solicita = p_id_usuario OR i.id_destino = p_id_usuario)
          AND i.estado = 'pendiente'
        ORDER BY i.created_at DESC
      ) q
    ),
    '[]'::json
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.solicitar_intercambio_turno_menu(integer, integer, integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.responder_intercambio_turno_menu(bigint, integer, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_intercambios_turno_menu(integer, integer) TO anon, authenticated;
