-- Fix etiquetas: asegurar tabla, funciones y permisos para autocomplete y altas desde frontend
BEGIN;

-- 1) Tabla base
CREATE TABLE IF NOT EXISTS public.etiquetas_disponibles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL UNIQUE,
  veces_usada integer NOT NULL DEFAULT 0,
  ultima_uso timestamptz,
  color varchar(7),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_etiquetas_disponibles_veces_usada
ON public.etiquetas_disponibles(veces_usada DESC);

CREATE INDEX IF NOT EXISTS idx_etiquetas_disponibles_ultima_uso
ON public.etiquetas_disponibles(ultima_uso DESC);

-- 2) Helper color (si no existe ya)
CREATE OR REPLACE FUNCTION public.generar_color_aleatorio()
RETURNS varchar(7)
LANGUAGE plpgsql
AS $$
DECLARE
  colores_disponibles varchar(7)[] := ARRAY[
    '#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8',
    '#F7DC6F', '#BB8FCE', '#85C1E2', '#F8B739', '#52BE80',
    '#EC7063', '#5DADE2', '#58D68D', '#F4D03F', '#AF7AC5',
    '#85C1E9', '#F1948A', '#73C6B6', '#F9E79F', '#A569BD',
    '#E74C3C', '#3498DB', '#2ECC71', '#F39C12', '#9B59B6',
    '#1ABC9C', '#34495E', '#E67E22', '#95A5A6', '#16A085'
  ];
BEGIN
  RETURN colores_disponibles[1 + floor(random() * array_length(colores_disponibles, 1))::int];
END;
$$;

-- 3) RPCs (definer para que funcionen incluso con RLS)
CREATE OR REPLACE FUNCTION public.agregar_etiqueta_disponible(p_nombre text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_nombre text := lower(trim(p_nombre));
  v_color varchar(7);
BEGIN
  IF v_nombre IS NULL OR v_nombre = '' THEN
    RETURN;
  END IF;

  v_color := public.generar_color_aleatorio();

  INSERT INTO public.etiquetas_disponibles (nombre, veces_usada, ultima_uso, color)
  VALUES (v_nombre, 1, now(), v_color)
  ON CONFLICT (nombre) DO UPDATE SET
    veces_usada = public.etiquetas_disponibles.veces_usada + 1,
    ultima_uso = now();
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_etiquetas_disponibles()
RETURNS TABLE (
  nombre text,
  veces_usada integer,
  color varchar(7)
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.nombre,
    e.veces_usada,
    COALESCE(e.color, public.generar_color_aleatorio())::varchar(7) as color
  FROM public.etiquetas_disponibles e
  ORDER BY e.veces_usada DESC, e.ultima_uso DESC NULLS LAST
  LIMIT 200;
END;
$$;

CREATE OR REPLACE FUNCTION public.obtener_color_etiqueta(p_nombre text)
RETURNS varchar(7)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_nombre text := lower(trim(p_nombre));
  v_color varchar(7);
BEGIN
  SELECT color INTO v_color
  FROM public.etiquetas_disponibles
  WHERE nombre = v_nombre;

  IF v_color IS NULL OR v_color = '' THEN
    v_color := public.generar_color_aleatorio();
  END IF;

  RETURN v_color;
END;
$$;

-- 4) Permisos
GRANT SELECT, INSERT, UPDATE, DELETE ON public.etiquetas_disponibles TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.etiquetas_disponibles_id_seq TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.agregar_etiqueta_disponible(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_etiquetas_disponibles() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.obtener_color_etiqueta(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.generar_color_aleatorio() TO anon, authenticated;

-- 5) RLS (si se usa)
ALTER TABLE public.etiquetas_disponibles ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'etiquetas_disponibles' AND policyname = 'Allow anon select etiquetas'
  ) THEN
    CREATE POLICY "Allow anon select etiquetas"
    ON public.etiquetas_disponibles
    FOR SELECT
    TO anon
    USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public' AND tablename = 'etiquetas_disponibles' AND policyname = 'Allow anon write etiquetas'
  ) THEN
    CREATE POLICY "Allow anon write etiquetas"
    ON public.etiquetas_disponibles
    FOR ALL
    TO anon
    USING (true)
    WITH CHECK (true);
  END IF;
END $$;

COMMIT;

